### ISSUE TITLE
B站AV号全面升级至BV号之后插件失效

### ISSUE THREAD

**Issue by malow005** [MotooriKashin/Bilibili-Old#1]
如题，AV号全面升级至BV号插件失效了

**Comment by MotooriKashin** [comment]
已在昨晚紧急匹配了bv地址，似乎可以正常使用，其他受牵连的功能正在抢修中……

**Comment by BryanSer** [comment]
考虑一下配合 https://greasyfork.org/zh-CN/scripts/398535-bv2av

**Comment by MotooriKashin** [comment]
@BryanSer 

> 考虑一下配合 https://greasyfork.org/zh-CN/scripts/398535-bv2av

参考https://www.zhihu.com/question/381784377/answer/1099438784的回答，用js从新实现了bvid与aid的互转，即将更新到实现中并默认在bv页开启跳转到av页功能
