### ISSUE TITLE
添加互动弹幕相关功能

### ISSUE THREAD

**Issue by wly5556** [MotooriKashin/Bilibili-Old#102]
https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5/discussions/81183

提了这个需求，我去弄一弄

- 互动弹幕有专门的几个类去管理和渲染，移植过来应该很方便
- 这些投票弹幕如"1""2"······的弹幕池属性pool=3，可以很方便地隐藏掉
- 其实还想加个按钮，可以不投票就看结果

**Comment by wly5556** [comment]
靠，仔细看下去，这玩意从零开始做一个还要更简单，
新播放器的代码很难拿来用
- 需要配合几百kb的css和svg
- 关注点赞收藏这些功能依赖另一个脚本的代码
- 被压缩的变量名和分散的工具函数

![](https://static.saraba1st.com/image/smiley/face2017/117.png)我也没多少空闲的时间了，这个功能还是需要靠 @MotooriKashin 你来做

**Comment by MotooriKashin** [comment]
好的，我试试

**Comment by wly5556** [comment]
放了个4天的假，如果有帮得上忙的地方，我也能出份力![](https://static.saraba1st.com/image/smiley/face2017/077.png)

**Comment by MotooriKashin** [comment]
可以啊，毕竟原生代码你比我熟。

**Comment by wly5556** [comment]
互动弹幕已经做好多少了？还有什么地方没做的，我看着去做一下

**Comment by MotooriKashin** [comment]
可以说是没任何进展吧，开启一个新功能之前我想先把未完成的东西弄个大概吧——所以我还在学C＋＋或者说WinApi

**Comment by wly5556** [comment]
哇winapi可以算是超硬核的那一类api了吧，佩服
关于互动弹幕，我就先去做做基础部分吧

**Comment by MotooriKashin** [comment]
就是Windows提供的API，用来写图形化界面（我是原始人的说_(:з」∠)_）

**Comment by wly5556** [comment]
欸欸这东西已经底层到中文资料都少见了吧，从零绘制出界面总感觉很帅啊

**Comment by MotooriKashin** [comment]
http://winprog.org/tutorial/zh/start_cn.html  
原生界面很简陋的……

**Comment by wly5556** [comment]
看到全大写字幕和下划线头就开始痛了咋办![](https://static.saraba1st.com/image/smiley/face2017/068.png)

**Comment by MotooriKashin** [comment]
的确，不能像js一样类型转化更头疼，一个let/var声明所有才是真的爽。

**Comment by wly5556** [comment]
提交的`commandDm.js`是这次互动弹幕功能的代码，程序入口只有BLOD.test()
运行方法：找个顺手的方式载入`commandDmStyle.css`和`commandDm.js`到av页，控制台BLOD.test()，在视频的大约2分半就会弹出投票界面了
到时候入口大概要放在`getSegDanmaku()`，不过它的被调用的情况比较多，不好处理就先放一边
`commandDmStyle.css`也还没做自动前缀，各种样式全凭喜好，先凑合着看

互动弹幕的话总计有九种，开了个很大的坑啊
command|弹幕指令
------------|------------
#ATTENTION#|视频内嵌引导关注按钮
#ACTORFOLLOW#|？
#MANAGERFOLLOW#|？
#VOTE#|投票
#UP#|带蓝色“UP”标识的弹幕
#RESERVE#|？
#LINK#|关联视频弹幕
#ACTOR#|？
#ACTIVITYCOMBO#|播放器更新日志里提到的春节活动弹幕？

**Comment by MotooriKashin** [comment]
所以弹幕时间轴是要由脚本来解析吗，以在需要的时候显示弹幕？

**Comment by wly5556** [comment]
>所以弹幕时间轴是要由脚本来解析吗，以在需要的时候显示弹幕？

投票弹幕、引导关注这种弹窗确实是要这么做，魔改现有弹幕渲染器感觉会麻烦些
不过#UP#这种类型的，看起来就是在普通弹幕上面加了点特效，在原生弹幕渲染器生成这些弹幕的dom对象的时候，设置特殊的class应该就能达到效果

`commandDm.js`设想在每个av页只运行一次，切P应该不影响，不知道在哪里载入合适？

**Comment by MotooriKashin** [comment]
> `commandDm.js`设想在每个av页只运行一次，切P应该不影响，不知道在哪里载入合适？

一次的话可以放在`rewrite.js`的av页对应处理底部，只要在**重写**页面之后就行，与其他放在那里的av页后续处理也无排序要求。  
引入模块的方法随意，`import()`为了照顾旧浏览器大概还是不行，可以仍用`@resource`声明引入，然后在那里用`Function`运行，或者直接像jQuery那样创建`script`标签？反正请随意。

**Comment by MotooriKashin** [comment]
体验了一下还不错，不过因为我没登录(无痕模式)，所以控制台提示投票失败(我觉得可以改用toast提示)  
另外：是否有不登录获取结果的可能呢？
![2021-04-16_172030](https://user-images.githubusercontent.com/60416767/115003424-5c15f700-9ed8-11eb-9812-b3af6c9ec085.png)

**Comment by wly5556** [comment]
不登录的话服务器给的投票人数是0，好像也没有别的途径获得投票人数了

**Comment by MotooriKashin** [comment]
那大概可以向官方那样判断没有登录就别post，直接弹出那个mini登录窗口  
另外我挂载了个`uid`在`BLOD`上，用if判断一下就知道登录了没有。

**Comment by wly5556** [comment]
这个登录弹窗还真是方便，什么都打包好了
看起来判断登录状态挺关键的，关注三连什么的功能都肯定需要登录

**Comment by byyxx128** [comment]
我就静静看你们俩秀恩爱q(≧▽≦q)
