### ISSUE TITLE
番剧播放页面不显示相关视频

### ISSUE THREAD

**Issue by Hibanaw** [MotooriKashin/Bilibili-Old#103]
![image](https://user-images.githubusercontent.com/61813396/115098506-fa4e9f00-9f62-11eb-80a8-228b1fb7bcca.png)

**Comment by MotooriKashin** [comment]
是的，问题存在很久了，后台返回的番剧推荐数据是空数组，不止播放器右边，右下角“相关视频推荐”也是。  
我看看有没有替换的接口。

**Comment by MotooriKashin** [comment]
已将填充右侧内容：
   1.  由于接口不兼容，占位数据将一闪而过
   2.  番剧封面长宽比不匹配，图像有点形变

**Comment by Hibanaw** [comment]
我把他换成剧集的封面了，可以正常比例显示
![image](https://user-images.githubusercontent.com/61813396/115747136-89c2da80-a3c7-11eb-8627-816f50ac377b.png)
