### ISSUE TITLE
似乎加载不上脚本了？

### ISSUE THREAD

**Issue by WolfgangWu** [MotooriKashin/Bilibili-Old#107]
chrome mac 86.0.4240.198（正式版本） (x86_64)现在打开B站界面似乎加载不上脚本。强制刷新和重装脚本都试过了。

**Comment by MotooriKashin** [comment]
控制台是不是报错“未知模块”？

**Comment by WolfgangWu** [comment]
额今天下午似乎有可以了

**Comment by WolfgangWu** [comment]
我电脑这几天又出问题挂不上脚本了啊
控制台长这样：
![image](https://user-images.githubusercontent.com/69294448/118370623-159ce080-b5db-11eb-98b7-592467d64ca5.png)
![image](https://user-images.githubusercontent.com/69294448/118370636-24839300-b5db-11eb-86db-dd1c1c4665fc.png)

现在是chrome mac 版本 90.0.4430.212（正式版本） (x86_64)

**Comment by MotooriKashin** [comment]
Chrome的话推荐把油猴换成红色的版本，黑色的最新版可能有点问题。

**Comment by MotooriKashin** [comment]
参看 https://github.com/Tampermonkey/tampermonkey/issues/1215  
应该是同一个问题，该问题在4.13版本修复了，但黑色的最新版恰巧的有问题的4.12

**Comment by WolfgangWu** [comment]
好的，谢谢
