### ISSUE TITLE
关于无法手动切换4k视频

### ISSUE THREAD

**Issue by malow005** [MotooriKashin/Bilibili-Old#11]
在开启脚本的情况下无法从1080p手动切换到4k，播放器左下角提示切换失败，关闭脚本后可以手动切换4k。再次打开脚本并刷新后4k设置可保持，可手动切换1080p。

**Comment by MotooriKashin** [comment]
4k番剧如[异常生物见闻录](https://www.bilibili.com/bangumi/play/ss26191/)有没有类似问题

**Comment by malow005** [comment]
番剧切换没有问题
https://www.bilibili.com/video/av925868504
我昨天是在这个视频下测试的，今天再测试问题又消失了，挠头

**Comment by MotooriKashin** [comment]
可能是这两天引入了xhr hook的原因，旧版播放器也能默认获取到4k视频地址了，你前天测试的时候可能没有更新，昨天自动更新了……大概，4k需要大会员，我也没办法调试，也不知道是不是真解决了。

**Comment by byyxx128** [comment]
非大会员，测试了一下，显示切换成功，其实没有成功……右击点“视频统计信息”可以看详情，切4k之后其实是按1080P播放的。4k需要大会员权限，所以只有大会员可能才知道切换后是啥样的了。

**Comment by MotooriKashin** [comment]
greasyfork那边有人测试了，有大会员似乎可以切换成功
