### ISSUE TITLE
消息导航栏样式出错

### ISSUE THREAD

**Issue by Hibanaw** [MotooriKashin/Bilibili-Old#111]
![image](https://user-images.githubusercontent.com/61813396/116673404-edf02a80-a9d5-11eb-82ab-28a80f56b8c9.png)
🤔

**Comment by MotooriKashin** [comment]
额，吐槽一下前端没事老折腾CSS干嘛，把单位从`px`换成`vw`难道是为了证明自己没摸鱼？！

**Comment by Hibanaw** [comment]
![image](https://user-images.githubusercontent.com/61813396/116767398-761c1180-aa62-11eb-91d0-11daa1920276.png)
🤔

**Comment by MotooriKashin** [comment]
红点是疏忽了，容后更新。

**Comment by MotooriKashin** [comment]
现在应该可以了，他真就是把所有`px`换成了`vw`也是闲的可以→_→

**Comment by Hibanaw** [comment]
> 现在应该可以了，他真就是把所有`px`换成了`vw`也是闲的可以→_→

感谢，五一加班辛苦了♥
