### ISSUE TITLE
填充播放器上方消息栏出现动图彩蛋的关键词是怎么回事

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#112]
![image](https://user-images.githubusercontent.com/77530593/116689076-31ed2a80-a9ea-11eb-871d-f30ab0e8b60a.png)

**Comment by MotooriKashin** [comment]
找不到合适的接口，用那个将就一下，毕竟每次刷新都不同，保持新鲜感。  
有合适的接口可以提一下。

**Comment by followmypeach** [comment]
（（（（（（（（（（

**Comment by followmypeach** [comment]
建议主页的广告
![image](https://user-images.githubusercontent.com/77530593/116811222-ad7de180-ab7a-11eb-9e33-ff426b4b2904.png)

**Comment by MotooriKashin** [comment]
> 建议主页的广告
> ![image](https://user-images.githubusercontent.com/77530593/116811222-ad7de180-ab7a-11eb-9e33-ff426b4b2904.png)

这个吃豆人只剩下3个，说明已经去掉广告了。这种不打广告便签伪装成正常内容的广告无法识别。

**Comment by Hibanaw** [comment]
> 找不到合适的接口，用那个将就一下，毕竟每次刷新都不同，保持新鲜感。
> 有合适的接口可以提一下。

https://api.bilibili.com/x/web-interface/search/default

**Comment by followmypeach** [comment]
！
