### ISSUE TITLE
播放多P视频时没有自动切换到下一P

### ISSUE THREAD

**Issue by Hibanaw** [MotooriKashin/Bilibili-Old#114]
![image](https://user-images.githubusercontent.com/61813396/116798941-189dc880-ab27-11eb-9f34-bbeaf2e64924.png)
我印象中旧版播放器应该会在左下角写着“x秒后播放下一P”然后自动跳转🥺

**Comment by MotooriKashin** [comment]
你看看齿轮那里的设置

**Comment by Hibanaw** [comment]
噢，谢谢😺
