### ISSUE TITLE
添加下载视频分辨率选择

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#115]
不知道没有提供flv和mp4的其它分辨率是只因为布局问题还是因为b站没有提供接口。
用旧版移动客户端是可以获取到其它分辨率的文件的。

**Comment by MotooriKashin** [comment]
flv一次只能获取一种画质，为了发送过多请求，脚本默认请求你能获取到的最高画质(如果播放器播放的是flv的话则不请求直接捕获当前播放源)，因为个人以为要下载的话一般默认都选能画质最高的吧。  
mp4目前只能获取到一档画质，一般为1080P，没有其他画质可选（当然硬要说的360P、240P这种清晰度不能看的还是有的）

**Comment by MyBlueHorizon** [comment]
不知道可不可以添加一个向上的选框，允许用户请求别的清晰度

**Comment by MotooriKashin** [comment]
我可以设计成同步当前播放器画质，直接使用播放器画质切换选项。不过这个感觉意义不大，mp4是固定画质的，DASH默认提供所有能获取的画质，只要flv才需要自己选择画质。
