### ISSUE TITLE
一个关于页面自适应的问题

### ISSUE THREAD

**Issue by Hibanaw** [MotooriKashin/Bilibili-Old#117]
现在的页面在浏览器宽度为`1400px`的时候会有显示错误😦
css中自适应的部分有的写的是`min-width`有的是`max-width`
一个是大于等于一个是小于等于，在等于`1400px`的时候就会出现问题
我在wayback machine里看了一下，
17年时自适应用的是js判断网页宽度来改变body的类
反而没有这个问题🤔

**Comment by MotooriKashin** [comment]
等于`1400px`也太极限了，px是个有点玄乎的单位，我觉得就算故意要把浏览器宽度调为正好`1400px`实在有点困难，所以那种问题应该是小概率事件吧。
