### ISSUE TITLE
鼠标手势不起作用

### ISSUE THREAD

**Issue by reserveword** [MotooriKashin/Bilibili-Old#119]
在视频播放页使用鼠标手势时，不会触发对应的手势动作
使用环境：
浏览器：Firefox 88.0
bilibili 旧播放页：4.7.9
鼠标手势插件：Gesturefy 3.1.2

**Comment by MotooriKashin** [comment]
如果鼠标手势指的是一个拓展，那么很抱歉本脚本无法去兼容。

**Comment by reserveword** [comment]
但是这应该是因为脚本的某处覆盖了鼠标手势的检测吧？有没有可能把这部分修改一下让他俩能不冲突呢？
