### ISSUE TITLE
稍后再看打不开

### ISSUE THREAD

**Issue by reserveword** [MotooriKashin/Bilibili-Old#121]
稍后再看没法正常加载，整个网页只有一个底部栏（关于我们、备案什么的）
![图片](https://user-images.githubusercontent.com/12995615/117559107-3209bc00-b0b5-11eb-97f8-e965f1b2a4de.png)
![图片](https://user-images.githubusercontent.com/12995615/117559112-3cc45100-b0b5-11eb-9172-f58ae2c8922f.png)

开F12看会发现报错称jQuery加载失败，但是网络请求里jQuery成功响应了
![图片](https://user-images.githubusercontent.com/12995615/117559128-4fd72100-b0b5-11eb-9850-db10fda2e728.png)
![图片](https://user-images.githubusercontent.com/12995615/117559142-65e4e180-b0b5-11eb-8370-41ce8ed1af82.png)

浏览器版本是Firefox 88
脚本版本是 4.7.9

**Comment by MotooriKashin** [comment]
硬刷新没法解决吗？  
“载入模块”下第二行明确提示了jQuery载入失败，所以是jQuery请求下来了但是运行失败，我不太明白这是什么原因。

**Comment by reserveword** [comment]
刷新过几次，都没法加载。有一次浏览器更新的时候，更新前没法加载，更新完刚打开的时候意外地加载好了，但是关掉再打开就又没法加载了。
我也搞不清楚这是为什么加载失败了，我把jquery的响应手动复制到控制台再运行就好了，不知道有没有人能复现这个问题

**Comment by MotooriKashin** [comment]
你更新一个4.8.0版本试试，我把jQuery提前了

**Comment by reserveword** [comment]
4.8.0还是不起作用，我发现在head和body之间没有jQuery的标签
![图片](https://user-images.githubusercontent.com/12995615/117569465-6488d880-b0f8-11eb-926d-130a646cdfd9.png)

**Comment by MotooriKashin** [comment]
标签不至于消失，也许是在head上面一些。  
另外，突然想到的，把tampermonkey“注入模式”修改一下会不会好一些？比如从“默认”改为“即时”什么的。

**Comment by reserveword** [comment]
标签确实在上面一些
把注入模式改成document-body或者document-end之后确实可以了，但是会先闪一下新版页面再变成旧版页面，可以作为一个临时解决方案吧
