### ISSUE TITLE
有关“稍后再看”内评论区出现显示错误的问题

### ISSUE THREAD

**Issue by Taebost** [MotooriKashin/Bilibili-Old#122]
如题，在“稍后再看”列表里观看视频时会出现显示错误，很多图像会出现错位现象。

**Comment by Taebost** [comment]
我的火狐版本为88.0.1
插件版本为4.7.9
错位效果如下
![图片](https://user-images.githubusercontent.com/64080472/117627216-8347a780-b1aa-11eb-984d-b9bd9cb18e1d.png)

**Comment by MotooriKashin** [comment]
4.8.0版本怎么样？

**Comment by Taebost** [comment]
> 
> 4.8.0版本怎么样？

不行，仍然是这样显示

**Comment by MotooriKashin** [comment]
调一个这个设置试试
![2021-05-10_163449](https://user-images.githubusercontent.com/60416767/117630411-bccde200-b1ad-11eb-8f27-76dd5a38ca46.png)

**Comment by Taebost** [comment]
> 
> 
> 调一个这个设置试试
> ![2021-05-10_163449](https://user-images.githubusercontent.com/60416767/117630411-bccde200-b1ad-11eb-8f27-76dd5a38ca46.png)

注入模式里三个选项都试了一遍，没用

**Comment by MotooriKashin** [comment]
我试了下火狐也偶发了这个问题，该是评论区样式`comment.min.css`丢失。  
参考 #121 也不知道火狐最近更新什么，不是js加载失败，就是css丢失，这些问题暂时没什么头绪
