### ISSUE TITLE
在使用该插件时无法开启CC字幕

### ISSUE THREAD

**Issue by Taebost** [MotooriKashin/Bilibili-Old#123]

**Comment by MotooriKashin** [comment]
需要安装[Bilibili CC字幕工具](https://greasyfork.org/scripts/378513)

**Comment by Taebost** [comment]
![图片](https://user-images.githubusercontent.com/64080472/117632104-7f6a5400-b1af-11eb-99f3-b8813741e3d5.png)
刚刚安装了该插件，却发现无法同时使用。
本插件版本为刚更新的4.8.0
CC字幕工具为0.5.21

**Comment by Taebost** [comment]
![图片](https://user-images.githubusercontent.com/64080472/117632944-2353ff80-b1b0-11eb-8e46-90c3ae4bccd4.png)
单独使用则没有问题

**Comment by zkyhzxf** [comment]
> 需要安装[Bilibili CC字幕工具](https://greasyfork.org/scripts/378513)

+1，测试了下，我这边也不行

**Comment by MotooriKashin** [comment]
都是Firefox吗？感觉本脚本对Firefox支持一直不太行

**Comment by zkyhzxf** [comment]
> 都是Firefox吗？感觉本脚本对Firefox支持一直不太行

不，我是百分浏览器（Chromium内核）

**Comment by Taebost** [comment]
> 
> 
> 都是Firefox吗？感觉本脚本对Firefox支持一直不太行

是的，火狐88.0.1

**Comment by MotooriKashin** [comment]
可以试试chrome或者edge  
浏览器平台的事可能很难处理，我去下个火狐看看

**Comment by zkyhzxf** [comment]
> 可以试试chrome或者edge
> 浏览器平台的事可能很难处理，我去下个火狐看看

edge试了一下，也不行，可能不是浏览器的关系，而是获取不到了？（猜测）

**Comment by Taebost** [comment]
> 
> 
> 可以试试chrome或者edge
> 浏览器平台的事可能很难处理，我去下个火狐看看

![图片](https://user-images.githubusercontent.com/64080472/117637039-01f51280-b1b4-11eb-900e-2e93964cbc05.png)
刚刚试了一下Edge，没问题

**Comment by zkyhzxf** [comment]
> > 可以试试chrome或者edge
> > 浏览器平台的事可能很难处理，我去下个火狐看看
> 
> ![图片](https://user-images.githubusercontent.com/64080472/117637203-2bae3980-b1b4-11eb-8370-092501d7e5ee.png)
> 刚刚试了一下Edge，没问题

![image](https://user-images.githubusercontent.com/35629617/117637798-be4ed880-b1b4-11eb-91cf-450b608bd56d.png)
欸，为什么我这边还是不行呢。。。请问您怎么设置的

**Comment by zkyhzxf** [comment]
> > 可以试试chrome或者edge
> > 浏览器平台的事可能很难处理，我去下个火狐看看
> 
> ![图片](https://user-images.githubusercontent.com/64080472/117637203-2bae3980-b1b4-11eb-8370-092501d7e5ee.png)
> 刚刚试了一下Edge，没问题

算了，大概是我这边网的问题，即使关了脚本还是看不到这个视频的cc字幕，那就不是脚本能解决的问题了

> > 可以试试chrome或者edge
> > 浏览器平台的事可能很难处理，我去下个火狐看看
> 
> ![图片](https://user-images.githubusercontent.com/64080472/117637203-2bae3980-b1b4-11eb-8370-092501d7e5ee.png)
> 刚刚试了一下Edge，没问题

我现在也可以了，没有换浏览器。但是我是先关掉旧播放页脚本，清除缓存，刷出cc字幕，然后打开脚本，就行了。。。也不知道问题出在哪，总之算是解决了吧（

**Comment by zkyhzxf** [comment]
> > 可以试试chrome或者edge
> > 浏览器平台的事可能很难处理，我去下个火狐看看
> 
> ![图片](https://user-images.githubusercontent.com/64080472/117637203-2bae3980-b1b4-11eb-8370-092501d7e5ee.png)
> 刚刚试了一下Edge，没问题

算了，大概是我这边网的问题，即使关了脚本还是看不到这个视频的cc字幕，那就不是脚本能解决的问题了

> > 可以试试chrome或者edge
> > 浏览器平台的事可能很难处理，我去下个火狐看看
> 
> ![图片](https://user-images.githubusercontent.com/64080472/117637203-2bae3980-b1b4-11eb-8370-092501d7e5ee.png)
> 刚刚试了一下Edge，没问题

我现在也可以了，没有换浏览器。但是我是先关掉旧播放页脚本，清除缓存，刷出cc字幕，然后打开脚本，就行了。。。也不知道问题出在哪，总之算是解决了吧（

**Comment by MotooriKashin** [comment]
我试了下火狐或许给那个CC字幕脚本添加上红框中的元数据就可以了。
![无标题](https://user-images.githubusercontent.com/60416767/117641827-34553e80-b1b9-11eb-8407-ce2c6aeb17d5.png)

**Comment by zkyhzxf** [comment]
> // @run-at document-body

加上去试了一下，其他浏览器貌似也是适用的，非常感谢

**Comment by MotooriKashin** [comment]
已尝试移植该功能进模块，只实现了基本功能，不支持本地字幕及字幕转码下载。  
要继续兼容使用[Bilibili CC字幕工具](https://greasyfork.org/scripts/378513)的话请在本脚本设置->播放里关闭相关功能。  

以下是移植缘由
   1. 取消额外安装第三方工具的成本
   2. 修改第三方脚本添加元数据终究不是稳定的办法
   3. 本脚本底层机制决定了无法主动去兼容第三方脚本，也不想因此去向第三方请求兼容。
