### ISSUE TITLE
【Bug Report】旧播放器播放番剧时手动切换下一话会导致弹幕列表乱套

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#124]
## 这个问题好久了，不知道为啥没人反馈……好吧，我亲自来。
直接上例子。比如打开这个——
https://www.bilibili.com/bangumi/play/ep118541
不要全屏，直接这样看。然后鼠标点右边“弹幕列表”和“推荐视频”，来回切换几次。一切正常是不是？那就对了。
然后，单击播放器按钮![image](https://user-images.githubusercontent.com/20079289/118427697-678b5680-b700-11eb-9ea4-17b186efd7b7.png)切换到下一话，然后再用鼠标点右边“弹幕列表”和“推荐视频”，来回切换几次。然后就会这样——
![image](https://user-images.githubusercontent.com/20079289/118427776-943f6e00-b700-11eb-8902-1dc5c5c9cc5a.png)
刷新之后一切正常——
![image](https://user-images.githubusercontent.com/20079289/118427871-c9e45700-b700-11eb-8701-d0ad61477786.png)
但是如果再切换下一话又不行了……

**Comment by MotooriKashin** [comment]
该是我替换推荐视频时出了点问题，不过还真是没人发现，感谢反馈！

**Comment by byyxx128** [comment]
亲测好用，感谢~
