### ISSUE TITLE
"载入本地弹幕"有时候载入不全

### ISSUE THREAD

**Issue by Akari-R** [MotooriKashin/Bilibili-Old#125]
如下图，2500+条弹幕只载入了200+条
![Snipaste_2021-05-19_11-07-32](https://user-images.githubusercontent.com/75869519/118750808-c254b780-b892-11eb-9a5d-14379944bee1.png)
![Snipaste_2021-05-19_11-07-17](https://user-images.githubusercontent.com/75869519/118750814-c680d500-b892-11eb-989b-b0dd117c69e4.png)
这些载入不全的弹幕文件都有一个共性：拖拽到Chrome里报错"PCDATA invalid Char value 28"
![Snipaste_2021-05-19_11-07-46](https://user-images.githubusercontent.com/75869519/118750985-237c8b00-b893-11eb-9ebd-1869137a3348.png)
（原视频：av2991-这不是BAD apple）

**Comment by MotooriKashin** [comment]
这个问题应该是json转xml时出现了xml文档不支持的字符造成的  
定位于该视频第208条弹幕那个`\u001c`  
![2021-05-19_200101](https://user-images.githubusercontent.com/60416767/118811367-8136c480-b8df-11eb-9c06-cef1632353f4.png)
保存到本地文件中变成了文档分隔符  
![2021-05-19_200209](https://user-images.githubusercontent.com/60416767/118811507-af1c0900-b8df-11eb-9ae6-669a22eb1682.png)
对比一下旧版接口直接获取到的xml文档并没有那个字符的  
![2021-05-19_200344](https://user-images.githubusercontent.com/60416767/118811615-ca871400-b8df-11eb-8cac-9ac158208415.png)
但弹幕作者输入该字符应该是由意义的，参考控制台显示  
![2021-05-19_202156](https://user-images.githubusercontent.com/60416767/118811806-01f5c080-b8e0-11eb-97dd-268f32eb4b1b.png)

这个问题你怎么看 @wly5556 ？  
我这边实在不知道该如何识别这些“非法字符”，所以有在考虑以后下载弹幕是不是直接保存json而不转化为xml，当然“本地弹幕”功能在支持解析json同时依然会保留对于xml的支持。

**Comment by wly5556** [comment]
惊了，为什么会出现文件分隔符啊
本身显示不出来，旧接口也没有这个字符，大概不是弹幕作者发送出来的。不知道从后端到protobuf.js哪里出bug了，突然出现文件分隔符怎么看都不正常
现在先把文件分隔符替换掉了，希望之后不会再冒出别的特殊字符
保存到json，要在代码里改动的地方好像还不少，我觉得有最通用的xml格式就够了←_←

**Comment by MotooriKashin** [comment]
我也是百度了一下才发现xml不支持的字符挺多的，但愿不要出现其他“非法字符”吧。
