### ISSUE TITLE
建议修改点赞图标margin来对齐

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [MotooriKashin/Bilibili-Old#127]
- 这是默认的

![QQ截图20210521182558](https://user-images.githubusercontent.com/45261195/119123377-11047c00-ba62-11eb-93ff-d2bc74f967b1.jpg)

------

- 这是修改过后的

![QQ截图20210521182526](https://user-images.githubusercontent.com/45261195/119123431-1f529800-ba62-11eb-85e6-a0242cb88e5f.jpg)

**Comment by MotooriKashin** [comment]
已修改
