### ISSUE TITLE
关于旧版嵌入式播放器的问题

### ISSUE THREAD

**Issue by Minteea** [MotooriKashin/Bilibili-Old#129]
旧版嵌入式播放器接口没了（真不知道b站那些做前端的是怎么想的），脚本换成了[远古播放器](https://www.bilibili.com/blackboard/activity-ancient-player.html)

![Bilibili-Old-Issue02](https://user-images.githubusercontent.com/83207760/119221219-db729800-bb20-11eb-87c1-d74728a27e60.png)

感觉远古播放器没有旧版播放器美观，我想的是能否用旧版嵌入式播放器代码重写[新版嵌入式播放器页面](https://www.bilibili.com/blackboard/newplayer.html)来实现旧版播放器的样式

**Comment by MotooriKashin** [comment]
可以，我之前就是这么想的，不过后来忘记了。

**Comment by MotooriKashin** [comment]
已重写嵌入式播放器页面
