### ISSUE TITLE
建议将设置存储到 Tampermonkey 本地存储而非浏览器缓存

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#13]
如题，目前设置应该是存储到了浏览器缓存，这会导致每次清理缓存之后设置就恢复默认了……这不太好，建议存储到 Tampermonkey 的本地存储，因为我用的其他一些脚本就是这样做的，好处就是，不受浏览器缓存影响。
![image](https://user-images.githubusercontent.com/20079289/84285637-4923ef00-ab70-11ea-9885-635b6a38e06a.png)

**Comment by MotooriKashin** [comment]
`localStorage`不知道是不是称之为本地储存更合适，缓存应该是另一种机制，浏览器提供的清理入口一般是和`cookie`绑定的，实在没有专门清理的必要，**单独清理缓存不会导致`localStorage`丢失吧**。(我也亲自测试了一下，至少chrome里清理缓存不会清除`localStorage`，清理`cookie`才会)
使用`localStorage`的优势是不必专门去适应脚本管理器提供的存储api，我不知道几个管理器`Tampermonkey`、`Greasemonkey`等对于这种api是否有区别，以及本身就支持用户脚本而不需要脚本管理器的浏览器如`Qupzilla`等又是否提供这样的存储api，如果没有一个普适的标准，兼容起来也是有点问题的(虽然也没想着去兼容就是了)。`localStorage`作为HTML5的标准，本身就是提供给站点永久储存少量数据用的，大部分浏览器肯定都是支持的，而且**真的没有主动清理的必要**，里面数据量也不大(都是纯文本字符串，撑死2M)。
引用维基百科的解释，`localStorage`其实就是改进版的`cookie`，不该主动去清理导致每次访问都要重新登录，这与HTML5这项功能的设计理念也是冲突的。看了下带某清理广告功能的拓展，默认也只清理缓存而忽略`cookie`和`localStorage`
![2020-06-11_075250](https://user-images.githubusercontent.com/60416767/84330010-cc693300-abb8-11ea-8619-dd07c7ea53b0.png)

**Comment by byyxx128** [comment]
其实我之所以敢提这个建议，是因为我看到了这句话——
![image](https://user-images.githubusercontent.com/20079289/84339175-6ee0e080-abd0-11ea-8a65-49bb1f9ba822.png)
所以我就以为老大只需要考虑Tampermonkey的兼容性就行……如果要考虑其他的，那就不好说了。不过有一点：老大的这个脚本在Greasemonkey中无法正常使用，所以不用考虑Greasemonkey的兼容性了……Qupzilla也停更很久了，而且没什么人用吧……其他的，Violentmonkey和AdGuard都可以，没有问题。至于localStorage的问题，我好像几年前看过，不过强迫癌晚期并不看好这玩意……而且我的确会清理cookies……

所以有可能的话，还是建议能存储到脚本管理器中，反正也没打算考虑兼容性的问题，而且常用的几款都是兼容的。

**Comment by MotooriKashin** [comment]
已更改储存方式，所有自定义设置需要重新设置

**Comment by byyxx128** [comment]
已更新，确认可用。Perfect. 感谢！( •̀ ω •́ )✧
