### ISSUE TITLE
关于首页的资讯区

### ISSUE THREAD

**Issue by hsqbl** [MotooriKashin/Bilibili-Old#130]
“最新投稿”没有数据
![资讯区无数据](https://user-images.githubusercontent.com/84609642/119228326-11c20e80-bb45-11eb-899e-9a0d31233f4c.png)
个人的想法是用热点的最新投稿
https://api.bilibili.com/x/web-interface/newlist?rid=203&type=0&pn=1&ps=20&jsonp=jsonp&callback=jsonCallback_bili_80012624615749922
修复

**Comment by hsqbl** [comment]
另外，首页的资讯区的图标用的应该是以前的广告区的吧
因为22举的牌子里的“AD”就是“广告”的意思，所以自己改了两个图标
一种是22举的牌子里的字改成“News”
![biliNews1](https://user-images.githubusercontent.com/84609642/119228504-d70ca600-bb45-11eb-8b40-14012b3ab5f0.png)
一种是直接把新版资讯区的图标放到22举的牌子里
![biliNews2](https://user-images.githubusercontent.com/84609642/119228480-c4926c80-bb45-11eb-9208-6e11ac021c4a.png)

**Comment by MotooriKashin** [comment]
已添加“最新投稿”及咨询区图标，非常感谢。
