### ISSUE TITLE
在开启脚本后部分弹幕无法显示

### ISSUE THREAD

**Issue by Taebost** [MotooriKashin/Bilibili-Old#131]
如题，在开启脚本后部分弹幕会无法显示，如下为不开启脚本时：
![OFF](https://user-images.githubusercontent.com/64080472/119254566-923a4b00-bbe9-11eb-9c9f-8250d30d6343.PNG)
开启脚本时：
![ON](https://user-images.githubusercontent.com/64080472/119254569-99615900-bbe9-11eb-99f2-ed6d7834c3f4.PNG)
其中“金发的孩子真可怜”、“捡垃圾bb草生”两条未显示
部分其他视频的吞弹幕现象更严重

**Comment by MotooriKashin** [comment]
可以更新一下版本，应该已经修复了。  
如图，该视频已是10条弹幕，当然不登录时还是8条  
![2021-05-23_181613](https://user-images.githubusercontent.com/60416767/119256406-3379cf00-bbf3-11eb-889d-4ca5cea5b680.png)
