### ISSUE TITLE
关于"弹幕下载"和"全弹幕装填"的一点建议

### ISSUE THREAD

**Issue by Akari-R** [MotooriKashin/Bilibili-Old#132]
关于弹幕下载：可以添加手动输入avid和cid下载新版弹幕的功能吗？
（有一些已失效的视频无法进入该视频的播放页下载弹幕，但一般能通过查cid历史或者根据相邻几个视频找到该视频的cid，但旧版弹幕api获取的弹幕不全）

关于全弹幕装填：
目前脚本"全弹幕装填"功能使用了[这一接口](https://api.bilibili.com/x/v2/dm/history/index?type=1&oid=xxxxx&month=xxxx-xx)，目前很多视频通过这个接口只能到2017年左右（但能通过历史弹幕api获取到更早的弹幕）
另外可以添加手动输入avid和cid下载全弹幕的功能吗？（理由同上）

**Comment by Akari-R** [comment]
顺便附biliplus的"全弹幕下载器"
[moepus.powered.full-danmaku.txt](https://github.com/MotooriKashin/Bilibili-Old/files/6527959/moepus.powered.full-danmaku.txt)

**Comment by MotooriKashin** [comment]
弹幕下载：
   1. 脚本设置面板提供了“载入其他视频弹幕”的功能，支持输入视频链接和aid/bvid/cid等数据，成功载入后推送到下载面板的便是对应的弹幕，设置面板也会临时提供下载提示右键另存为即可。
   2. 设置里开启失效视频，脚本会尝试借助第三方缓存数据重建失效视频播放页面，这时播放器左下角应该有“载入弹幕”按钮，点击载入也可下载弹幕。也可以同样进设置面板“载入其他视频弹幕”输入当前失效视频链接。

全弹幕下载：请参考方式二重建播放页面后，设置面板里应该有对应功能。

**Comment by MotooriKashin** [comment]
全弹幕下载功能就是使用的历史弹幕API

**Comment by Akari-R** [comment]
> 全弹幕下载功能就是使用的历史弹幕API

我表述得不够好，全弹幕下载先通过[这个api](https://api.bilibili.com/x/v2/dm/history/index?type=1&oid=xxxxx&month=xxxx-xx)查找有弹幕的日期，但是[这个api](https://api.bilibili.com/x/v2/dm/history/index?type=1&oid=xxxxx&month=xxxx-xx)很多视频只能查到17年左右，但是[历史弹幕API](https://api.bilibili.com/x/v2/dm/web/history/seg.so?type=1&oid=xxxxx&date=xxxx-xx-xx)可以获取到更早的弹幕

**Comment by MotooriKashin** [comment]
> 我表述得不够好，全弹幕下载先通过[这个api](https://api.bilibili.com/x/v2/dm/history/index?type=1&oid=xxxxx&month=xxxx-xx)查找有弹幕的日期，但是[这个api](https://api.bilibili.com/x/v2/dm/history/index?type=1&oid=xxxxx&month=xxxx-xx)很多视频只能查到17年左右，但是[历史弹幕API](https://api.bilibili.com/x/v2/dm/web/history/seg.so?type=1&oid=xxxxx&date=xxxx-xx-xx)可以获取到更早的弹幕

“只能查到17年左右”能举个av号作为例子我去排查一下吗？我一般都是用的远古视频做测试，并没有出现这个问题，比如“三集定律”起源的这个失效视频“魔法少女小圆 03”。  
![2021-05-24_110442](https://user-images.githubusercontent.com/60416767/119291056-628a5200-bc80-11eb-8d07-984fa09af52f.png)

**Comment by Akari-R** [comment]
> > 我表述得不够好，全弹幕下载先通过[这个api](https://api.bilibili.com/x/v2/dm/history/index?type=1&oid=xxxxx&month=xxxx-xx)查找有弹幕的日期，但是[这个api](https://api.bilibili.com/x/v2/dm/history/index?type=1&oid=xxxxx&month=xxxx-xx)很多视频只能查到17年左右，但是[历史弹幕API](https://api.bilibili.com/x/v2/dm/web/history/seg.so?type=1&oid=xxxxx&date=xxxx-xx-xx)可以获取到更早的弹幕
> 
> “只能查到17年左右”能举个av号作为例子我去排查一下吗？我一般都是用的远古视频做测试，并没有出现这个问题，比如“三集定律”起源的这个失效视频“魔法少女小圆 03”。
> ![2021-05-24_110442](https://user-images.githubusercontent.com/60416767/119291056-628a5200-bc80-11eb-8d07-984fa09af52f.png)

一些比较早的视频会有这种情况，比如av106,av39444等视频

**Comment by MotooriKashin** [comment]
的确，2017年8月之前按月份就查不到有弹幕的日期了

**Comment by MotooriKashin** [comment]
> 顺便附biliplus的"全弹幕下载器"
> [moepus.powered.full-danmaku.txt](https://github.com/MotooriKashin/Bilibili-Old/files/6527959/moepus.powered.full-danmaku.txt)

biliplus 使用的是旧版接口而且已经停止维护了
