### ISSUE TITLE
播放长视频切p有时会页面崩溃

### ISSUE THREAD

**Issue by Hibanaw** [MotooriKashin/Bilibili-Old#133]
遇到两次了好像

**Comment by MotooriKashin** [comment]
页面崩溃是指失去响应吗？从来没遇到过。

**Comment by Hibanaw** [comment]
> 页面崩溃是指失去响应吗？从来没遇到过。

是在看了一个三个多小时的视频之后
弹出了chrome自带的崩溃界面
![image](https://user-images.githubusercontent.com/61813396/119361098-dd358a80-bcdd-11eb-9ed2-d4204b34cc25.png)
类似这样
内存占用没什么大变化
也有可能是播放器本身的bug

**Comment by Hibanaw** [comment]
> > 页面崩溃是指失去响应吗？从来没遇到过。
> 
> 是在看了一个三个多小时的视频之后

这周末我继续补[那个实况](https://www.bilibili.com/video/BV1Wf4y1s7gy)的时候看看还有没有类似的情况

**Comment by MotooriKashin** [comment]
> 是在看了一个三个多小时的视频之后

哇，这要复现并排查难度有点大啊。
总之，期待后续跟进

**Comment by Hibanaw** [comment]
> 成功复现
> 错误代码`STATUS_ACCESS_VIOLATION`

好像不用几个小时那么长，三十分钟左右也会有这种情况
