### ISSUE TITLE
插件功能似乎影响到了直播画质切换

### ISSUE THREAD

**Issue by hzyluffy** [MotooriKashin/Bilibili-Old#134]
开启插件之后，选择切换画质会一直显示加载中，然后失败，禁用插件之后就能正常切换画质

**Comment by hzyluffy** [comment]
补充一下，不禁用插件的话连直播弹幕也发不出去了

**Comment by hzyluffy** [comment]
再次确认了一下，禁用了其他所有的插件和外置扩展程序，依旧存在画质切换的问题。版本也是上greasyfork更新过了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月26日(星期三) 下午5:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MotooriKashin/Bilibili-Old] 插件功能似乎影响到了直播画质切换 (#134)





 有更新版本吗？画质切换似乎已修复了

**Comment by hzyluffy** [comment]
另外直播间还存在无法发送弹幕的bug，和上面一样确认了不是其他插件影响的缘故




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月26日(星期三) 下午5:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MotooriKashin/Bilibili-Old] 插件功能似乎影响到了直播画质切换 (#134)





 有更新版本吗？画质切换似乎已修复了

**Comment by MotooriKashin** [comment]
抱歉，已经修改好了，可是昨天似乎推送失败，现在已经推送好了，你再更新试试。

**Comment by hzyluffy** [comment]
已经修复好了，辛苦了，十分感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月26日(星期三) 下午5:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MotooriKashin/Bilibili-Old] 插件功能似乎影响到了直播画质切换 (#134)





 抱歉，已经修改好了，可是昨天似乎推送失败，现在已经推送好了，你再更新试试。
 
 
   
&mdash;
