### ISSUE TITLE
增加个人空间动态翻页功能

### ISSUE THREAD

**Issue by Sodapopoo** [MotooriKashin/Bilibili-Old#135]
如题，b站个人空间动态、动态首页和评论一样是下拉式，各种up主动态堆在一块，加载太多了电脑都会卡得动不了，根本拉不了太远，有没有可能增加一个动态翻页功能呢？

**Comment by MotooriKashin** [comment]
如果是指某条动态点进去的【评论】翻页的话应该已经一并处理过了。  
如果是指将【动态】做成翻页式的话那就无能为力了，B站没提供相关接口也就无法做到。翻页意味着能够直接跳转到第n页，显然这是办不到的，不然我也想翻到最后一页看看第一条动态是什么。

**Comment by Sodapopoo** [comment]
直接跳转到第n页的功能是不可能做到的吗？
那么，如果每次只跳转一页的功能呢？
限制每页的加载动态数量，用箭头每次只跳转上一页和下一页，然后再标注页数
即使不能直接跳转到第n页也无所谓，毕竟这样的话动态网页就能不卡顿从而拉到很远了

**Comment by MotooriKashin** [comment]
我会去看看也评论区调用是否有共通之处，有大概可以做，否则只能放弃了。因为那等于要由脚本重新实现整个动态脚本的所有细节，还是饶了我吧。  
我回复评论翻页是直接用旧版评论脚本覆盖掉新版，旧版是B站原有的实现，这样轻松的事才适合这个脚本。

**Comment by MotooriKashin** [comment]
测试了一下，和评论区实现机制无共通之处，要整个重新实现原生脚本的代码工程量实在太大，抱歉哈，做不了。
