### ISSUE TITLE
无法保存设置

### ISSUE THREAD

**Issue by Lehmaning** [MotooriKashin/Bilibili-Old#136]
![firefox_5SmJ20jc0B](https://user-images.githubusercontent.com/60032845/119979273-4aeafa80-bfed-11eb-8ec4-27ce99c7fadb.png)
在刷新页面以后设置面板会自动变成默认的设置。
浏览器版本 Firefox 88.0.1，脚本版本 v4.8.7。

**Comment by MotooriKashin** [comment]
单看控制台信息并没有异常，而且脚本最近也没有实质性的更新，莫非是火狐升级引发的？  
今天暂时无法测试，你可以先试试在非重写页面，比如个人空间能不能复现。

**Comment by Lehmaning** [comment]
@MotooriKashin 试了下，个人空间里保存成功了，但在视频播放页里更改的设置还是没法保存。

**Comment by MotooriKashin** [comment]
那就好

**Comment by MotooriKashin** [comment]
测试同样的版本Firefox也没问题，难道只是个例？

**Comment by Lehmaning** [comment]
@MotooriKashin 今天一刷新整个脚本都失效了，变成了新版页面。。也有可能是插件的问题

**Comment by MotooriKashin** [comment]
是最新版吗？

**Comment by Lehmaning** [comment]
> 是最新版吗？
是，现在是5.0.2版本。

**Comment by MotooriKashin** [comment]
看一下控制台报错

**Comment by Lehmaning** [comment]
> 看一下控制台报错

![firefox_CnI319jeSl](https://user-images.githubusercontent.com/60032845/120312534-6d418880-c30b-11eb-97e8-6f531c0d2fbc.png)

**Comment by MotooriKashin** [comment]
原来如此，稍后修复

**Comment by Lehmaning** [comment]
行，能用了，不过重写页面还是没法保存设置、

**Comment by MotooriKashin** [comment]
请问你用的脚本管理器是，我试过Firefox 88 + Tampermonkey没出现问题

**Comment by Lehmaning** [comment]
Violentmonkey

**Comment by MotooriKashin** [comment]
这其实是一个已知问题
> 其实主要是`document.write()`方法的影响：将导致其他以`run-at document-start`注入的其他脚本异常。
>    - GM_setValue()方法失效，无法保存数据到脚本管理器
>    - addEventListener、document.onclick等回调失效

参看 https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5/discussions/6875 或 https://code.google.com/p/chromium/issues/detail?id=253388 查看更多信息。  
这个问题暂时无法解决。  
但在Tampermonkey中只导致其他脚本保存设置(GM_setValue())失效，本脚本是不会失效的。我不知道Violentmonkey是如何处理该问题的。  
本脚本重写页面只能使用document.write()方法，所以只有3个建议
   1. 只在非重写页面（比如个人空间、直播等）调整设置
   2. 换用Tampermonkey
   3. 向Violentmonkey提issue

**Comment by Lehmaning** [comment]
好吧，辛苦了。
