### ISSUE TITLE
旧版播放器bas弹幕全屏不会等比缩放

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#138]
旧版播放器
https://user-images.githubusercontent.com/77530593/120093880-ae8d3900-c14f-11eb-93da-881c5dadc86d.mp4

新版播放器
https://user-images.githubusercontent.com/77530593/120093897-c49af980-c14f-11eb-8d78-adc3c4f266c7.mp4

望修复（）

**Comment by followmypeach** [comment]
另一个问题：
旧版播放器：![image](https://user-images.githubusercontent.com/77530593/120095000-0a5ac080-c156-11eb-9e1e-e0f4184d80d8.png)
新版播放器：![image](https://user-images.githubusercontent.com/77530593/120095015-26f6f880-c156-11eb-8dbd-b0b0067b83c6.png)

测试地址https://www.bilibili.com/video/av671353527/?p=1

**Comment by followmypeach** [comment]
所以，，啥时候修复，，

**Comment by MotooriKashin** [comment]
弹幕相关的我不太清楚，可能要周末？

**Comment by followmypeach** [comment]
呐，修復沒有啊

**Comment by followmypeach** [comment]
@wly5556 儘快

**Comment by wly5556** [comment]
修了，你现在再试试......

说个题外的，让我尽快我也快不了啊
主要是我本身能用来维护脚本的时间很少，而且修了bug，又不是b站前端有工资拿，所以对修复速度的期待值降到最低就好。添加新功能的计划会一直搁置也说不定![](https://static.saraba1st.com/image/smiley/face2017/037.png)

对于bas、互动弹幕这类的功能，直接使用新播放器肯定能得到更好更稳定的体验

**Comment by MotooriKashin** [comment]
> 修了，你现在再试试......
> 
> 说个题外的，让我尽快我也快不了啊
> 主要是我本身能用来维护脚本的时间很少，而且修了bug，又不是b站前端有工资拿，所以对修复速度的期待值降到最低就好。添加新功能的计划会一直搁置也说不定![](https://camo.githubusercontent.com/c8e3884279d2a39f13e0648330d958b8c161b27165dbdae9c0f0dfbffa5fbe94/68747470733a2f2f7374617469632e7361726162613173742e636f6d2f696d6167652f736d696c65792f66616365323031372f3033372e706e67)
> 
> 对于bas、互动弹幕这类的功能，直接使用新播放器肯定能得到更好更稳定的体验

辛苦了。  
弹幕方面果然还是得看你，换我的话只能治标不治本地由脚本来头痛医头脚痛医脚。

**Comment by followmypeach** [comment]
> 修了，你现在再试试......
> 

然并卵啊！
最新版本了还是那样的移位
况且还有点卡（）

**Comment by followmypeach** [comment]
![image](https://user-images.githubusercontent.com/77530593/121125854-d2403580-c859-11eb-8f46-9b6514e70bba.png)

**Comment by MotooriKashin** [comment]
的确是修复了  
![2021-06-08_130629](https://user-images.githubusercontent.com/60416767/121126226-6ca07900-c85a-11eb-8104-8b5b0503ecdc.png)
