### ISSUE TITLE
撞车视频无法正常显示

### ISSUE THREAD

**Issue by Hibanaw** [MotooriKashin/Bilibili-Old#139]
![image](https://user-images.githubusercontent.com/61813396/120889030-e7388100-c62d-11eb-9393-627544b94c2c.png)

![image](https://user-images.githubusercontent.com/61813396/120889026-de47af80-c62d-11eb-82e9-54646c8245b0.png)

**Comment by MotooriKashin** [comment]
感谢反馈，已添加主动跳转。
