### ISSUE TITLE
建议互动视频保留使用新版播放器（或加个选项）

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#14]
由于旧版播放器天生的原因，是不可能支持互动视频的。所以，有没有可能，对于互动视频的页面，保留使用新版播放器，然后其他页面继续使用旧版播放器。理论上应该是能够检测页面是否是互动视频。

**Comment by MotooriKashin** [comment]
在普通av页面已经主动忽略了互动视频，难道有部分视频忽略失效了，请提供相应的av(BV)号以便修复

**Comment by byyxx128** [comment]
好像每个视频都这样，不是特定的某一个，比如这个吧——
https://www.bilibili.com/video/av75997777
点开之后，会看到新版播放器加载出来——
![image](https://user-images.githubusercontent.com/20079289/84338824-b024c080-abcf-11ea-8603-1f8083c86058.png)
然后弹出来“你发现了一个互动视频”——
![image](https://user-images.githubusercontent.com/20079289/84338846-bc108280-abcf-11ea-9040-a3f8773dfe38.png)
点击“我知道了”之后就空白了——
![image](https://user-images.githubusercontent.com/20079289/84338867-ca5e9e80-abcf-11ea-926a-1524ec164080.png)

**Comment by MotooriKashin** [comment]
这个可以确定是bug，马上修复

**Comment by byyxx128** [comment]
已更新，暂时可行。Perfect. 感谢！( •̀ ω •́ )✧
