### ISSUE TITLE
多人合作稿件只能看见up主

### ISSUE THREAD

**Issue by Hibanaw** [MotooriKashin/Bilibili-Old#141]
![image](https://user-images.githubusercontent.com/61813396/121336932-91761880-c94e-11eb-8d26-30bb374b0ada.png)
![image](https://user-images.githubusercontent.com/61813396/121336975-9c30ad80-c94e-11eb-94e1-da748b5f7c90.png)

**Comment by MotooriKashin** [comment]
脚本设置里应该有相关功能

**Comment by Hibanaw** [comment]
> 脚本设置里应该有相关功能

找到了，谢谢
