### ISSUE TITLE
首页分区菜单“资讯”处不显示数字

### ISSUE THREAD

**Issue by Hibanaw** [MotooriKashin/Bilibili-Old#143]
![image](https://user-images.githubusercontent.com/61813396/121908251-64b36e00-cd5f-11eb-8737-e0f8e8645571.png)
![image](https://user-images.githubusercontent.com/61813396/121908190-549b8e80-cd5f-11eb-9737-8ac6386c3f54.png)

**Comment by MotooriKashin** [comment]
不是不显示数字，而是数字为0

**Comment by Hibanaw** [comment]
> 不是不显示数字，而是数字为0

新版主页有的
https://api.bilibili.com/x/web-interface/online
data.region_count[202]

**Comment by MotooriKashin** [comment]
那个0是原广告区的，我一直觉得那个数字超过一定量都是99+这种概数实在没有修改的必要。

**Comment by Hibanaw** [comment]
> 那个0是原广告区的，我一直觉得那个数字超过一定量都是99+这种概数实在没有修改的必要。

资讯区似乎内容比较少，大部分时间都不是999+

**Comment by MotooriKashin** [comment]
哈哈，测试时是`666`
