### ISSUE TITLE
重新兼容pakku.js

### ISSUE THREAD

**Issue by wly5556** [MotooriKashin/Bilibili-Old#146]
>https://github.com/xmcp/pakku.js/commit/7d9371ffd9f18f606c73b3d051e69f904f2d31e6
>- stop disabling web worker (close #179)

之前是依据是否禁用worker来判断pakku.js的，现在pakku.js不再这么做了。要重新兼容一下
>https://github.com/xmcp/pakku.js/issues/180

**Comment by wly5556** [comment]
pakku.js在v10.1的[更新](https://github.com/xmcp/pakku.js/commit/26ea8ed76d4a1e8aab0b37c43c44ffe6fecfdb10)中移除了对旧播放器的支持
具体测试了一下，**过滤弹幕**功能不受影响，主要的变化是弹幕密度图不能在旧播放器中使用了
![R01%D~DUPB~13`BR1{MY )Q](https://user-images.githubusercontent.com/61644753/125180491-461f8600-e1ea-11eb-8057-85074ec51c2b.png)

**Comment by MotooriKashin** [comment]
对比两幅波形图似乎不大对得上？有意思。
