### ISSUE TITLE
无法跳转到旧版收藏列表

### ISSUE THREAD

**Issue by Minteea** [MotooriKashin/Bilibili-Old#147]
![2021-06-20 (5)](https://user-images.githubusercontent.com/83207760/122678923-46e08000-d21b-11eb-9529-4c0700de8cb6.png)
如图，进入收藏播放列表后出现的仍是新版收藏播放页面
（已勾选设置中的「收藏」选项，且多次刷新（包括Shift+F5）后仍不起作用，使用Edge和Firefox均为同样的情况）

- - -

另外，我建议可以用稍后再看页面框架「重写」新版收藏播放页面，而不是「跳转」到普通av页再用稍后再看页面模拟，跳转的问题有点多，比如不能自动播放列表中下一个视频。

**Comment by MotooriKashin** [comment]
已修复。  
跳转的问题无论“顺序播放”、“随机播放”还是“逆序播放”测试都没有问题
