### ISSUE TITLE
部分视频没有相关视频推荐？

### ISSUE THREAD

**Issue by Hibanaw** [MotooriKashin/Bilibili-Old#148]
https://www.bilibili.com/video/av248681005
![image](https://user-images.githubusercontent.com/61813396/122781258-347d4980-d2e2-11eb-9366-53356fc3ed55.png)
![image](https://user-images.githubusercontent.com/61813396/122781292-3cd58480-d2e2-11eb-8835-6796f46d02ad.png)

**Comment by MotooriKashin** [comment]
太新的视频没有，变旧了就会有的，大概？几天后？  
新版给的大概类似于“看过该视频的还喜欢”？
