### ISSUE TITLE
“稍后再看”标题栏错位

### ISSUE THREAD

**Issue by redapple0204** [MotooriKashin/Bilibili-Old#15]
RT，就像这样

![image](https://user-images.githubusercontent.com/16254644/85694117-6d9fcf80-b709-11ea-93af-9e96fa8faf7a.png)

**Comment by MotooriKashin** [comment]
好像是下载视频按钮，马上修复。
话说那个下载视频功能蛮鸡肋的，真的有人启用？

**Comment by byyxx128** [comment]
哈哈，当然有人启用呀！虽然我没看懂怎么用，点击后只是弹出个对话框，对话框也不能复制……🤔

**Comment by MotooriKashin** [comment]
什么对话框？“拉取视频地址失败”？可不可以截图看看？

**Comment by byyxx128** [comment]
不是，就是点击那个下载按钮弹出的对话框，里面是解析的地址。我测试了下，在 Firefox 中我可以复制这个地址，在 Chrome 中无法复制……不过那个地址测试是有效的。所以老大看看是不是需要改善一下展现方式。

![](https://user-images.githubusercontent.com/20079289/85933199-02bbe780-b907-11ea-8075-7b650e2c3c97.png)
![](https://user-images.githubusercontent.com/20079289/85933206-1c5d2f00-b907-11ea-9653-1c3824ae1ddf.png)

当然还有个一劳永逸的方式：就是我给 Chromium 发个 Feature Request，直接让对话框的内容可以复制。等我好消息～😏

**Comment by MotooriKashin** [comment]
奇怪了，点击那个对话框应该是直接调用下载才对，如下图
![1](https://user-images.githubusercontent.com/60416767/85933399-297b1d80-b909-11ea-8e19-809a94c7e2ce.gif)
是浏览器版本的原因还是应该我安装了idm的原因？
那个对话框是alert警告框吗？
应该是我调用的下载方式有问题，发个 Feature Request应该就不必了，我去看看别人是怎么调用下载功能的

**Comment by MotooriKashin** [comment]
查了下文档似乎是因为`download`属性有同源安全策略，视频地址不是`www.bilibili.com`开头的，不同源所以没有触发下载。
又看了下别人的实现，大都用的是`blob`链接的方式，可这种方式浏览器下载可以，无法调用idm。
可能这就是很多脚本只是显示链接而不直接下载的原因吧

**Comment by redapple0204** [comment]
> 什么对话框

emmm 并没有什么对话框啊

**Comment by MotooriKashin** [comment]
报好意思，没什么，出了bug有人借这里反馈(那人删了评论)
