### ISSUE TITLE
—

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#151]
新版用了这么久还是不习惯😂

**Comment by MotooriKashin** [comment]
直播间我始终不愿意去动它，原因有三：
   - 直播间牵连了太多与金钱挂钩的功能，而且更迭速度太快，没精力也不想去维护。
   - 特殊的直播间我没发现可靠的判定方法，不过这一点有心应该能解决。
   - 可能是个人用得少吧，对于直播间也没有那么不习惯，除了那“*黄色”的粉丝牌子！
