### ISSUE TITLE
按下键盘上的暂停键时无法正常暂停

### ISSUE THREAD

**Issue by h5mcbox** [MotooriKashin/Bilibili-Old#154]
按下暂停键后视频暂停但弹幕还在滚(播放器显示没停)
见图:
![image](https://user-images.githubusercontent.com/33593244/126932325-a9ce31ca-2e2c-4fe2-a22f-46990b623620.png)

**Comment by wly5556** [comment]
刚提交的5.1.4版本，给旧播放器加了多媒体快捷键的事件处理程序，应该能用键盘控制播放了
刚才测试的时候发现，后台开着网易云的话，这个快捷键就只会控制网易云的播放器，chrome是一点反应没有，对我来说用着就不太顺手了......不知道你的感受如何

**Comment by h5mcbox** [comment]
但是在[08c3d44](https://github.com/MotooriKashin/Bilibili-Old/commit/08c3d4478d9c32cc3ef80b6e2b6669f15f9ed0ed)和[82af894](https://github.com/MotooriKashin/Bilibili-Old/commit/82af8948764cee23bd6cfe17c6bc958b0eeb4d4c)这两次Commit后番剧页又出现了以上问题

**Comment by wly5556** [comment]
之前的代码是对着av页写的，怕在其他页面上面会报错，所以暂时不在av页之外的地方运行它
我去完善一下代码，把番剧页的问题解决

**Comment by h5mcbox** [comment]
![bug-plus](https://user-images.githubusercontent.com/33593244/128271747-df1a281d-ecff-4d7d-864c-a6d911accad3.png)
依然有问题

**Comment by h5mcbox** [comment]
升级5.17后问题依旧(av页和番剧页都是这样)
已尝试Ctrl-Shift-R硬刷
Tampermonkey:v4.13
Chrome:v92.0.4515.107
Windows 11:22000.71
使用的插件:SwitchyOmega[自动切换],pakku.js[v10.1.1]

**Comment by wly5556** [comment]
控制台有什么报错吗？可以的话发个控制台截图

**Comment by h5mcbox** [comment]
![image](https://user-images.githubusercontent.com/33593244/128285804-48e9226a-589e-4e03-b192-a4589f1e368c.png)

**Comment by wly5556** [comment]
我这里加上pakku之后没能重现问题，看控制台也没有异常
或许真是跟哪个脚本冲突了，要不试着只打开旧播放页脚本，看看有没有问题
