### ISSUE TITLE
canvas高级弹幕渲染问题

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#156]
如题
测试地址https://www.bilibili.com/video/av287126651?p=2

**Comment by followmypeach** [comment]
用了canvas看，比css3，但是有个问题
canvas：
![image](https://user-images.githubusercontent.com/77530593/127441014-ab4ed019-cd85-4cc2-9f9a-a45adde106e0.png)

css3：
![image](https://user-images.githubusercontent.com/77530593/127441071-c3b2e3a7-49df-4222-a0e1-e617c44b8418.png)

**Comment by followmypeach** [comment]
canvas:
![image](https://user-images.githubusercontent.com/77530593/127447499-56ee923c-04f1-4128-ae5d-ab5f816e5b64.png)

css3
![image](https://user-images.githubusercontent.com/77530593/127447568-a17d366a-318d-4859-808b-7a5afef3d7da.png)

**Comment by wly5556** [comment]
”比新版还卡“大概是因为reset.js里面的ParameterTrim.aitem()比较花时间
在性能工具里面看，每次节点插入事件，aitem()用掉了2~2.3ms，其余的处理程序一共0.2~0.4ms
注释掉aitem()之后，感觉帧率跟新版相差不大了，@MotooriKashin 这个地方有没有优化的可能？👀

图里面两行字错位，跟canvas本身的限制有关。弹幕作者在竖轴y和横轴z上把弹幕分别旋转180°去做出倒影效果，css3支持3d变换，显示正常，canvas就只有2d变换，不能处理y轴上的旋转，就不能正确显示了

**Comment by MotooriKashin** [comment]
那先暂时注释掉吧

**Comment by MotooriKashin** [comment]
改用`MutationObserver`不知道有没有用，好像说是异步处理。

**Comment by wly5556** [comment]
是异步了，直到播放器的渲染函数结束后才开始处理，不过一帧里面插入的dom元素太多，aitem()重复执行了好多遍，整个节点插入事件耗时比帧渲染时间还长
要不给aitem()整一个最小执行时间间隔，应该就能避免这样的情况了

![%$}~BNL2X3@3 MF~OQVX1OL](https://user-images.githubusercontent.com/61644753/127671778-8a2d1b2e-add1-4d97-9a95-696d7bbf98b2.png)
![7Z5}UWKQE@ {J(EY ~VV2YA](https://user-images.githubusercontent.com/61644753/127671784-7b17bb86-138f-4056-bb91-e30ee0d9de14.png)

**Comment by MotooriKashin** [comment]
我在想监听节点是不是个好办法，不知道那些广告过滤拓展或脚本是怎么做的，我去研究研究。

**Comment by followmypeach** [comment]
> 图里面两行字错位，跟canvas本身的限制有关。弹幕作者在竖轴y和横轴z上把弹幕分别旋转180°去做出倒影效果，css3支持3d变换，显示正常，canvas就只有2d变换，不能处理y轴上的旋转，就不能正确显示了

![image](https://user-images.githubusercontent.com/77530593/127728231-ec519029-93dc-44d1-99d7-cdf28a435085.png)

**Comment by followmypeach** [comment]
![image](https://user-images.githubusercontent.com/77530593/127728238-adcc8cd5-9f2e-4682-8d7b-a01e9be2b646.png)

**Comment by followmypeach** [comment]
![image](https://user-images.githubusercontent.com/77530593/127728257-05044be0-3963-4a3a-b0bc-89291608974e.png)

**Comment by followmypeach** [comment]
上面的话都是一个程序员说的

**Comment by followmypeach** [comment]
https://www.jianshu.com/p/e3ebe08dddad
这个教程可以用canvas绘制3d图形

**Comment by followmypeach** [comment]
![image](https://user-images.githubusercontent.com/77530593/127728666-58bb4cbb-29e4-4719-9810-75817db0e7f6.png)

**Comment by followmypeach** [comment]
https://www.jianshu.com/p/7025d40673e5
canvas 2D api 3D 视觉

**Comment by MotooriKashin** [comment]
调整了一下：
   1. 页面`window.onload`事件时进行一次全局a标签处理
   2. 节点插入时仅检查插入节点是否包含a标签并只处理那部分
 
这样感觉像弹幕绘制这种不会包含a标签的插入应该影响不大了吧？

**Comment by followmypeach** [comment]
@wly5556 出来挨打（bushi

**Comment by MotooriKashin** [comment]
这个视频是新版播放器完全不支持吗？我还想看看新版播放器的canvas效果

**Comment by wly5556** [comment]
.....？没搞哪里有问题
前面说的”canvas就只有2d变换“，别误解成“canvas做不出3d效果”这个意思啊
canvas2d api没有3d变换，于是大神们自行写代码处理坐标投影，做出来3d效果，canvas api作为2d画布的角色没变，不能说它支持3d绘制吧
canvas2d api简单好用，非常适合以它作为基础去讲解3d变换的概念，但是实际情况下，做3d效果直接用包装好的webgl库，省心省力，不会想到拿canvas2d来干这活的....

>这个视频是新版播放器完全不支持吗？我还想看看新版播放器的canvas效果

"这里没有哦"是个bas弹幕，弹幕作者画了一个黑色大矩形，刚好新旧版播放器布局不同，在新版播放器里它会把其他的高级弹幕挡住，大概是坑没填完的作者故意这么做的👀，手动删掉div.bilibili-player-video-bas-danmaku就行
不过新版播放器菜单里已经不提供canvas模式的选项了，虽然有关代码还没删

**Comment by MotooriKashin** [comment]
> 新版播放器菜单里已经不提供canvas模式的选项了，虽然有关代码还没删
>
所以官方自己都放弃了canvas模式的样子，还是说没精力去维护呢？感觉用两种引擎实现相同的效果在这种高级弹幕里还是工程量太大了，而且听闻`Canvas`效率不及`CSS3`的样子，被抛弃也正常。

**Comment by followmypeach** [comment]
旧版：
![image](https://user-images.githubusercontent.com/77530593/127769792-72ad86ba-d3cf-422f-9765-9410a316ffad.png)
![image](https://user-images.githubusercontent.com/77530593/127769809-d4ae7c23-03a2-4495-ac6e-129c0408f380.png)

新版：
![image](https://user-images.githubusercontent.com/77530593/127769832-7223e140-50eb-41ac-ac43-ff1744b7ce70.png)
![image](https://user-images.githubusercontent.com/77530593/127769841-e59d7517-8ead-4ef3-a81a-c0237f62c586.png)

**Comment by followmypeach** [comment]
补上
![image](https://user-images.githubusercontent.com/77530593/127769859-016d98eb-dc2b-4aab-9e39-5fa4c6105f24.png)
