### ISSUE TITLE
bas弹幕渲染范围的一些建议

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#159]
bas渲染范围别留和视频一样的黑边，有些弹幕PV是上层是纯弹幕，下层是弹幕录屏的，开和不开效果差不多，难以分清，在新版至少可以看黑边判别，但在旧版 弹幕和视频的黑边宽度都是相同的，无法直观判别。
便求BAS弹幕的渲染范围增大（去除黑边）
测试地址在↓

**Comment by followmypeach** [comment]
https://www.bilibili.com/video/av589602473/?p=1

**Comment by MotooriKashin** [comment]
不是很懂你的需求，“所见即所得”不是最好吗？要什么要区分开？

**Comment by followmypeach** [comment]
好家伙 我用哔哩哔哩旧版（bilibili.com）播放器调整插件时 同时启动“自动隐藏播放器控制栏”和“手动指定播放器大小”这俩选项时打开宽屏 会出现bas弹幕无法完全盖住视频的现象
https://www.bilibili.com/video/av589602473/?p=3

**Comment by MotooriKashin** [comment]
那应该是那个插件的问题，猜测是调整了播放器大小没有跟着调整弹幕显示范围？

**Comment by followmypeach** [comment]
那你可以做个检测插件然后调整弹幕显示范围的代码伐..

**Comment by MotooriKashin** [comment]
为什么要求此脚本去改进彼插件的功能呢，应该给对应作者提issue吧？

**Comment by followmypeach** [comment]
作者已经无了。
