### ISSUE TITLE
关于点赞按钮

### ISSUE THREAD

**Issue by meiruitesi** [MotooriKashin/Bilibili-Old#160]
想问一下点赞按钮能不能直接做到框架里，每次加载视频时先有硬币和收藏再有点赞总觉得有点违和
![Snipaste_2021-08-04_08-40-40](https://user-images.githubusercontent.com/84609642/128103991-ca293cb5-695d-410a-8d18-5e25144f39bc.png)

另外一键三连真不打算实现一下吗。。。。。。。。

**Comment by MotooriKashin** [comment]
违和是有的，包括鼠标焦点和点击的效果，包括“一键三连”也是。功能本身并不难做，难做的是动效反馈，毕竟不是原生的功能。  
我不是很擅长这些设计，包括脚本设置面板也是做得不大满意。

**Comment by hsqbl** [comment]
> 违和是有的，包括鼠标焦点和点击的效果，包括“一键三连”也是。功能本身并不难做，难做的是动效反馈，毕竟不是原生的功能。 我不是很擅长这些设计，包括脚本设置面板也是做得不大满意。

所以三个按钮不能同时出现吗。。。。。。。

**Comment by meiruitesi** [comment]
想问一下，让三个按钮同时出现真得实现不了吗，每次加载较慢的时候总想先赞后看。。。。。。。

**Comment by MotooriKashin** [comment]
已经添加需求

**Comment by meiruitesi** [comment]
感谢
