### ISSUE TITLE
启用插件之后无法正常显示b站主界面

### ISSUE THREAD

**Issue by hzyluffy** [MotooriKashin/Bilibili-Old#161]
更新了最新版本的插件，也试过重装，依旧无法显示主界面
![QQ图片20210804173804](https://user-images.githubusercontent.com/79327265/128159035-00a1bfdc-d002-4db6-9807-3c241b635577.png)

**Comment by MotooriKashin** [comment]
能提供下控制台报错信息吗？

**Comment by hzyluffy** [comment]
Uncaught TypeError: toStringTag is not a function!
&nbsp; &nbsp; at t.exports (1.home.4eadf4209b1762230047120e0a9945a9f3b56fd1.js:7)
&nbsp; &nbsp; at t.exports (1.home.4eadf4209b1762230047120e0a9945a9f3b56fd1.js:7)
&nbsp; &nbsp; at Object.<anonymous&gt; (1.international-home.07a66f65bde63e8b105d9fdea075c18b11d64d6c.js:25)
&nbsp; &nbsp; at o (home.4eadf4209b1762230047120e0a9945a9f3b56fd1.js:1)
&nbsp; &nbsp; at e (home.4eadf4209b1762230047120e0a9945a9f3b56fd1.js:1)
&nbsp; &nbsp; at home.4eadf4209b1762230047120e0a9945a9f3b56fd1.js:1
&nbsp; &nbsp; at home.4eadf4209b1762230047120e0a9945a9f3b56fd1.js:1
www.bilibili.com/:1 Uncaught (in promise) e
sentry-5.7.1.min.js:2 Uncaught TypeError: Cannot set property 'innerHTML' of null
&nbsp; &nbsp; at Function.onload (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=%25E7%25A6%2581%25E7%2594%25A8B%25E7%25AB%2599%25E9%25A6%2596%25E9%25A1%25B5%25E9%25A6%2596%25E6%25A0%258F%25E4%25B8%25AA%25E6%2580%25A7%25E6%258E%25A8%25E8%258D%2590.user.js&amp;id=75f2a564-f7ed-4768-922e-2106c1fc8e66:31)
&nbsp; &nbsp; at <anonymous&gt;:4:80
&nbsp; &nbsp; at eval (eval at exec_fn (www.bilibili.com/:2), <anonymous&gt;:28:360)
&nbsp; &nbsp; at <anonymous&gt;:4:80
&nbsp; &nbsp; at i (eval at exec_fn (www.bilibili.com/:2), <anonymous&gt;:5:165)
&nbsp; &nbsp; at eval (eval at exec_fn (www.bilibili.com/:2), <anonymous&gt;:5:292)
&nbsp; &nbsp; at <anonymous&gt;:13:99
&nbsp; &nbsp; at HTMLDocument.v (<anonymous&gt;:13:118)
&nbsp; &nbsp; at HTMLDocument.sentryWrapped (sentry-5.7.1.min.js:2)


是这一部分吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月4日(星期三) 下午5:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MotooriKashin/Bilibili-Old] 启用插件之后无法正常显示b站主界面 (#161)





 
能提供下控制台报错信息吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hzyluffy** [comment]
Uncaught TypeError: Cannot read property 'filter' of undefined
&nbsp; &nbsp; at eval (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=B%25E7%25AB%2599%25E7%2595%25AA%25E5%2589%25A7%25E8%25A7%25A3%25E9%2594%2581.user.js&amp;id=5c22c22a-0ee3-4825-b9a6-4d3ed8836b71:30)
&nbsp; &nbsp; at eval (eval at exec_fn (www.bilibili.com/:2), <anonymous&gt;:24:190)
&nbsp; &nbsp; at <anonymous&gt;:13:99
&nbsp; &nbsp; at HTMLDocument.v (<anonymous&gt;:13:118)
&nbsp; &nbsp; at HTMLDocument.sentryWrapped (sentry-5.7.1.min.js:2)
1.home.4eadf4209b1762230047120e0a9945a9f3b56fd1.js:7 Uncaught TypeError: toStringTag is not a function!
&nbsp; &nbsp; at t.exports (1.home.4eadf4209b1762230047120e0a9945a9f3b56fd1.js:7)
&nbsp; &nbsp; at t.exports (1.home.4eadf4209b1762230047120e0a9945a9f3b56fd1.js:7)
&nbsp; &nbsp; at Object.<anonymous&gt; (1.international-home.07a66f65bde63e8b105d9fdea075c18b11d64d6c.js:25)
&nbsp; &nbsp; at o (home.4eadf4209b1762230047120e0a9945a9f3b56fd1.js:1)
&nbsp; &nbsp; at e (home.4eadf4209b1762230047120e0a9945a9f3b56fd1.js:1)
&nbsp; &nbsp; at home.4eadf4209b1762230047120e0a9945a9f3b56fd1.js:1
&nbsp; &nbsp; at home.4eadf4209b1762230047120e0a9945a9f3b56fd1.js:1
www.bilibili.com/:1 Uncaught (in promise) e
sentry-5.7.1.min.js:2 Uncaught TypeError: Cannot set property 'innerHTML' of null
&nbsp; &nbsp; at Function.onload (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=%25E7%25A6%2581%25E7%2594%25A8B%25E7%25AB%2599%25E9%25A6%2596%25E9%25A1%25B5%25E9%25A6%2596%25E6%25A0%258F%25E4%25B8%25AA%25E6%2580%25A7%25E6%258E%25A8%25E8%258D%2590.user.js&amp;id=75f2a564-f7ed-4768-922e-2106c1fc8e66:31)
&nbsp; &nbsp; at <anonymous&gt;:4:80
&nbsp; &nbsp; at eval (eval at exec_fn (www.bilibili.com/:2), <anonymous&gt;:28:360)
&nbsp; &nbsp; at <anonymous&gt;:4:80
&nbsp; &nbsp; at i (eval at exec_fn (www.bilibili.com/:2), <anonymous&gt;:5:165)
&nbsp; &nbsp; at eval (eval at exec_fn (www.bilibili.com/:2), <anonymous&gt;:5:292)
&nbsp; &nbsp; at <anonymous&gt;:13:99
&nbsp; &nbsp; at HTMLDocument.v (<anonymous&gt;:13:118)
&nbsp; &nbsp; at HTMLDocument.sentryWrapped (sentry-5.7.1.min.js:2)



是这一部分吗




------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月4日(星期三) 下午5:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MotooriKashin/Bilibili-Old] 启用插件之后无法正常显示b站主界面 (#161)





 
能提供下控制台报错信息吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MotooriKashin** [comment]
直接截图吧，这样看不到一条本脚本相关信息。。。  
而且看起来你同时启用了很多脚本，可以关闭其他的试试。

**Comment by hzyluffy** [comment]
关闭了其他的脚本，我不清楚是不是这一部分




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月4日(星期三) 晚上6:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MotooriKashin/Bilibili-Old] 启用插件之后无法正常显示b站主界面 (#161)





 
直接截图吧，这样看不到一条本脚本相关信息。。。
 而且看起来你同时启用了很多脚本，可以关闭其他的试试。
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hzyluffy** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月4日(星期三) 晚上7:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MotooriKashin/Bilibili-Old] 启用插件之后无法正常显示b站主界面 (#161)





 还是截个控制台图给我看一下吧
 
 
   
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by followmypeach** [comment]
?

**Comment by hzyluffy** [comment]
> 还是截个控制台图给我看一下吧

![QQ图片20210805212510](https://user-images.githubusercontent.com/79327265/128357413-7135d9ae-d680-41fe-a1ba-1aacfa21b1d9.png)
之前上传的格式可能有些问题，我重新截了一下。如果造成了困扰很抱歉，我不是很懂这方面

**Comment by MotooriKashin** [comment]
看脚本的调试信息被新版页面的`sentry`脚本代理了，应该是脚本注入慢了，在TamperMonkey里将注入模式改为“即时”试试。

**Comment by hzyluffy** [comment]
> 看脚本的调试信息被新版页面的`sentry`脚本代理了，应该是脚本注入慢了，在TamperMonkey里将注入模式改为“即时”试试。

改成即时之后问题依然存在

**Comment by MotooriKashin** [comment]
我能想到的最后的办法：
TamperMonkey会给每个脚本一个序号（在TamperMonkey脚本列表每个脚本的最前面），请让这个序号最小试试。有证据表明那个序号代表着脚本注入顺序，序号越小注入优先级越高。  
而那个序号也是脚本的安装顺序，所以可以试试第一个安装本脚本。（可以使用TamperMonkey的导出功能备份一下其他脚本）

**Comment by hzyluffy** [comment]
> 我能想到的最后的办法： TamperMonkey会给每个脚本一个序号（在TamperMonkey脚本列表每个脚本的最前面），请让这个序号最小试试。有证据表明那个序号代表着脚本注入顺序，序号越小注入优先级越高。 而那个序号也是脚本的安装顺序，所以可以试试第一个安装本脚本。（可以使用TamperMonkey的导出功能备份一下其他脚本）

依旧无效，但谢谢大佬耐心的帮助，我接下来试一下重新安装浏览器之类的方法吧，这几天打扰你了

**Comment by hzyluffy** [comment]
> 我能想到的最后的办法： TamperMonkey会给每个脚本一个序号（在TamperMonkey脚本列表每个脚本的最前面），请让这个序号最小试试。有证据表明那个序号代表着脚本注入顺序，序号越小注入优先级越高。 而那个序号也是脚本的安装顺序，所以可以试试第一个安装本脚本。（可以使用TamperMonkey的导出功能备份一下其他脚本）
![QQ图片20210806145507](https://user-images.githubusercontent.com/79327265/128469192-617d00b3-d6a7-4a9c-a495-8b075d251000.png)
补一张图，我把序号调到了最小，同时也开启了即时，也尝试过了重置浏览器，看其他Bug反馈safari浏览器没有问题，难道说是chrome的问题
