### ISSUE TITLE
关于动图彩蛋

### ISSUE THREAD

**Issue by meiruitesi** [MotooriKashin/Bilibili-Old#162]
关于哆啦A梦的动图彩蛋失效了
![Snipaste_2021-08-06_14-15-46](https://user-images.githubusercontent.com/84609642/128465126-bbbde328-3b5a-45ae-8f26-75693fa61743.png)
![Snipaste_2021-08-06_14-16-34](https://user-images.githubusercontent.com/84609642/128465131-5e9df029-91b3-4aa4-bffa-a8b204efc661.png)
个人建议将彩蛋的链接全部统一鼠标提示文字的搜索结果

**Comment by MotooriKashin** [comment]
失效的很多，毕竟是失去维护的东西。统一不现实，毕竟有也有未失效的，我觉得它存在的意思不是内容，而是动图本身。
