### ISSUE TITLE
关于首页头图

### ISSUE THREAD

**Issue by meiruitesi** [MotooriKashin/Bilibili-Old#163]
像黄绿合战这种会动的真的不打算弄一下吗。。。。。。
哪怕弄成静态的也行。。。。。。
![Snipaste_2021-08-06_14-22-07](https://user-images.githubusercontent.com/84609642/128465812-d73cc93b-c54e-4938-8789-ad1d65fb0afa.png)
![Snipaste_2021-08-06_14-23-24](https://user-images.githubusercontent.com/84609642/128465821-a577e05d-6e5b-4431-a5ce-4030eeb04f6c.png)
新版的头图是黄绿合战，但旧版的仍然是“河南加油”

**Comment by hsqbl** [comment]
刚才看了下审查元素，那个黄绿合战的头图是个循环播放的视频
[yellowVSgreen7th.zip](https://github.com/MotooriKashin/Bilibili-Old/files/6943516/yellowVSgreen7th.zip)
（原版是webm，GitHub的评论不支持上传webm，打成zip包）
放在blob里
![Snipaste_2021-08-06_14-35-04](https://user-images.githubusercontent.com/84609642/128466819-62fce3a8-893e-4480-ae68-9359dc753921.png)

**Comment by hsqbl** [comment]
目前的个人建议是黄绿合战的这段时间先直接把黄绿合战的头图直接做到脚本里，等黄绿合战结束后再更新脚本换回原来的头图接口。。。。。。

**Comment by MotooriKashin** [comment]
大概跟 #120 一个要求，有在尝试实现整个功能，专门内置一个banner是不会的

**Comment by MotooriKashin** [comment]
ts分支已移植动态banner  
监听banner节点载入用的是hook jQuery的jsonp，但是有个问题，对于jsonp返回值，暂时还找不到异步修改的方式，而banner图必须通过异步Ajax获取。  
目前的办法是异步获取然后存储到本地，这样比的就是两个ajax谁跑得快了，如果旧版banner再新版之前返回，那么修复用到就是本地原有的缓存，这样就会出现分区对不上的情况（比如可能明明是番剧区，显示的却是国创区的banner）

另外，动态banner的雪花等特效并没有移植过来。
