### ISSUE TITLE
视频页下的迷你播放器顶部宽度宽过视频宽度

### ISSUE THREAD

**Issue by Sonic853** [MotooriKashin/Bilibili-Old#164]
![Snipaste_2021-08-10_14-40-30](https://user-images.githubusercontent.com/8389962/128820666-f4d9ee4f-1927-413d-abc9-b39586970d47.png)

**Comment by MotooriKashin** [comment]
不会啊，是不是其他脚本干扰？  
或者提供个av号

**Comment by Sonic853** [comment]
> 不会啊，是不是其他脚本干扰？ 或者提供个av号

是我的问题。

（挺奇怪，刚刚使用全新的浏览器只安装这一个脚本倒是没问题，在自己主用的浏览器只启用这一个脚本就会这样，可能是缓存没跟上？
