### ISSUE TITLE
关于视频评论区页数

### ISSUE THREAD

**Issue by meiruitesi** [MotooriKashin/Bilibili-Old#168]
看图，注意楼层号和页码
![image](https://user-images.githubusercontent.com/84609642/130075854-f09930d2-16d7-46bd-958c-d90604dda748.png)
![image](https://user-images.githubusercontent.com/84609642/130075923-cfc6ce69-eec8-47b0-8b80-ce2dbc3e5ab1.png)

**Comment by h5mcbox** [comment]
这是已知问题,见README
![issue1](https://user-images.githubusercontent.com/33593244/130080851-6582931b-d6cb-460b-aaee-4cc8761c9c07.png)
