### ISSUE TITLE
网页显示不全

### ISSUE THREAD

**Issue by MC-dusk** [MotooriKashin/Bilibili-Old#17]
之前一直在用这个脚本，很好用，今天用发现播放器、右侧栏、评论区……都没了，网页处于“伪加载完毕”状态。最近b站播放器改版，不知道是不是和这个有关。

火狐79.0，暴力猴v2.12.7，脚本更新最新3.2.7

**Comment by MotooriKashin** [comment]
最近很多脚本都出现类似问题，肯定是与B站播放器改版有关，但我使用chrome+Tampermonkey好像没有问题，也没有其他人反馈说出现类似情况，待我下载火狐去检查一下。

**Comment by MotooriKashin** [comment]
似乎不是B站改版的原因，而是几天前更新的firefox79的原因，不知道火狐更新了些什么，反正很莫名其妙，在开启控制台(f12)的情况下是可以正常加载的，否则就只显示版头。
控制台也没找到任何报错信息，根本无从查起，暂时建议使用firefox79之前的版本，或者换用chrome，个人只使用chrome，对于firefox的兼容其实一直没做处理

**Comment by MC-dusk** [comment]
好的，我使用新版edge 84.0.522.52使用无问题，油猴4.10.6111，确实是火狐的问题，谢谢。
