### ISSUE TITLE
关于视频页的给UP主充电的按钮

### ISSUE THREAD

**Issue by meiruitesi** [MotooriKashin/Bilibili-Old#170]
看了一下，个人空间的充电对话框实际上是个单独的页面
例如我要给灰太狼办公室（uid31832612）充电，
![image](https://user-images.githubusercontent.com/84609642/130230450-7ddfbe7b-3c83-4de9-baa7-a54fa366f7c3.png)
那么我将使用的充电对话框
![image](https://user-images.githubusercontent.com/84609642/130230499-375dc3bb-0932-45fa-b696-53de79c4886b.png)
的链接为
https://www.bilibili.com/v/pay/charge?upmid=31832612&upurl=%2F%2Fspace.bilibili.com%2F31832612&upname=%E7%81%B0%E5%A4%AA%E7%8B%BC%E5%8A%9E%E5%85%AC%E5%AE%A4&upavatar=http%3A%2F%2Fi2.hdslb.com%2Fbfs%2Fface%2F09730be918be0e59d72e2557444b4da09e276370.jpg&oid=31832612&otype=up&from=zone
![image](https://user-images.githubusercontent.com/84609642/130230553-5cfca2f5-aee5-46ee-81e2-df94a3999132.png)
看样子这个对话框链接的格式应该是
https://www.bilibili.com/v/pay/charge?upmid=（要充电的UP主的uid）&upurl=（要充电的UP主的个人主页的链接）&upname=（要充电的UP主的名字）&upavatar=（要充电的UP主的头像）&oid=（要充电的UP主的uid）&otype=up&from=zone
所以视频页的那个给UP主充电的按钮
![image](https://user-images.githubusercontent.com/84609642/130230901-72961ffe-b260-4730-a740-d592f0d864c2.png)
应该是可以修复的

**Comment by meiruitesi** [comment]
另外参数里的斜杠貌似要全部换成%2F

**Comment by MotooriKashin** [comment]
这种涉及金钱的东西我不会去碰的……

**Comment by meiruitesi** [comment]
> 这种涉及金钱的东西我不会去碰的……

啊这......
试了一下，这个对话框要改成给别人充电的话五个参数貌似都要改，否则直接“充电失败”......
应该不会有什么问题吧......

**Comment by MotooriKashin** [comment]
问题很大……  
本来是想直接屏蔽掉那个按钮的，鉴于本脚本的初衷是尽量还原旧版页面加上那个按钮必然失败才留下的。
