### ISSUE TITLE
专栏无法选中内容

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#171]
如题

**Comment by MotooriKashin** [comment]
B站专栏原本好像就是防复制的

**Comment by MyBlueHorizon** [comment]
尝试了一下，关闭脚本复制是正常的，但不知道是不是新版没有加载完全的问题（网络环境所限，新版b站经常加载缓慢）

**Comment by MotooriKashin** [comment]
新版专栏没有限制，限制的只是旧版

**Comment by MyBlueHorizon** [comment]
感谢回复，不知道能不能修改下这个限制，毕竟如果要用右键选择搜索的功能有一些不方便

**Comment by MotooriKashin** [comment]
这种我都是用专用的拓展处理的，如[Absolute Enable Right Click & Copy](https://chrome.google.com/webstore/detail/jdocbkpgdakpekjlhemmfcncgdjeiika)   
通杀所有网站，需要时点一下，无需刷新。所以专门针对某个页面进行处理对我而言有点多余了，不过既然有需求有时间我会添加一下。
