### ISSUE TITLE
评分弹幕支持搞快点

### ISSUE THREAD

**Issue by meiruitesi** [MotooriKashin/Bilibili-Old#172]
![image](https://user-images.githubusercontent.com/84609642/131104878-ef6623f2-bbbf-4e20-a883-02ffbbeeaa9d.png)
https://www.bilibili.com/video/av419992106

**Comment by wly5556** [comment]
15天前已经提交了相关改动，但是由于油猴的机制，可能要晚一些才能实际收到更新😥
如果有其他相关建议欢迎反馈
