### ISSUE TITLE
使用TypeScript重构源码

### ISSUE THREAD

**Issue by MotooriKashin** [MotooriKashin/Bilibili-Old#174]
遥记上一次将项目模块化的重构已经近一年，曾经希冀的通过模块化来实现更新和维护上的便利却并不尽如人意，问题有三：
   1. 独创的模块体系并不为代码编译器所完美支持，无法提供合适的代码提示与检查，代码分布在不同模块中反而提高了语法出错的概率。
   2. 模块更新时需要手动记录commit到脚本主体中，既繁杂又不便于进一步细化。
   3. `@resource`存储方案会拖累脚本注入速度，对于以重写页面为核心功能的本脚本而言是致命的。

于是花了一些时间对于项目进行了二次重构，目前已基本重构完整，可前往[ts分支](https://github.com/MotooriKashin/Bilibili-Old/tree/ts)体验。  
借着引入TypeScript以完美贴合VSCode编辑器的需求时，本项目的模块化方案也进行了大改：
### TypeScript
源代码基本上使用ts语言进行了重构并完善了声明文件，现在可以完美使用VSCode提供的代码校验功能，减少语法错误。当然代价就是ts的学习成本，不过那大概就是强类型的js会js学习起来应该不难？  
反正对于我不熟悉的代码就一路any？！  
当然托管的原生脚本如video.js就没办法重构了，饶了我吧！

### 弃用`@resource`
不论如何，注入速度严重关系到重写页面的效果。新的模块方案使用GM_setValue存储模块数据以规避这个问题，剩下的唯一问题是脚本第一次运行时需要主动下载模块数据，不然就只是一个没有任何功能的空壳。不过这点初始化的操作应该不是太大问题，大概……

### 核心对象改重命名为了API
私以为核心对象应该有个醒目的名字让开发者一看就知道这个对象的用途。  

### 不污染顶层对象window
原来模块之间交流数据是通过window.BLOD，终究还是稍微污染了window，现在的API已经和其他对象变成了“全局变量”一样的存在，可以像使用window一样使用，但并不放在window下，解决了顶层对象污染问题。黑科技？

### 自动加载模块依赖
之前如果用到了模块提供的函数等工具，必须检查一下模块有没有加载运行，现在不必了，脚本将自动检测并载入对应的模块，可以安心地敲代码了。  
前提是由记录对象与函数的对应关系在apply.json里

### 主动的模块依赖支持
载入模块时可以主动提供一些数据给被加载的模块，这些数据在该模块中可以像API等对象一样使用，把模块当成同步函数使用？其实是模块本身实现就是特殊的函数。

### 自动记录模块修改信息
之前修改模块后还需要手动记录commit信息，模块一旦多了简直不堪重负，所以一直不敢完全细化。现在把这些事件交给自动化脚本，更新维护更便捷。

### 本地模块更新支持
`@resource`一大缺点就是更新维护极不方便，必须推送到远程仓库再下载模块，或者使用麻烦的代理工具。当然`@resource`支持file协议，但拖累注入速度的问题还是并没有缓解。换用GM_setValue后，可以直接选择本地文件进行更新了，调试难度直线下降。  
其实重构时每个模块都是这样安装调试后才上线的。

### ESNext
“兼容”一直是前端永远的痛，所以放飞自我，尽管真香吧。要用就用最新的ES特性，怎么舒服怎么来，不想再背沉重的兼容包袱了！  
坚持用旧版的B站页面却抛弃旧的浏览器是怎么回事？  
我不管，B站是旧版的好，浏览器还是新的香，二者不是一个范畴的。  
正经项目上没办法只能各种兼容，用户脚本是私下的爱好不想再束手束脚了 →_→

### 当然还有一些功能尚未重构完成
首先是下载功能，这个准备和设置界面一样重绘，并打算专注于ef2下载，所以大概需要亿点时间？主打下载功能的脚本太多了，我做这个功能大概只是方便自己。  
然后是本地弹幕、全弹幕装填等弹幕相关……额，这个已经重构完成了只是忘了添加调用方式，稍后奉上。  
还精简了一些功能？部分功能太小众了一时懒得重构，有需要再说吧。

还有 @wly5556 贡献的部分，因为代码风格差异太大，怕出错我就一路any了π_π

**Comment by wly5556** [comment]
用TS的话我这要边学边改代码了，全部可能弄完可能要一段时间π_π
试着用了下ts版，好像动态评论区的样式有问题？
另外旧版主页的头图接口是不是失效了，现在一直停留在“武汉加油”

**Comment by MotooriKashin** [comment]
一些功能的确没有重构完成，正在一点一点修复。  
旧版banner可能的确失效了，也有这方面的issue，是时候把新版那套移植一下了。  

ts个人觉得就是就是添加了类型的js，不过代码提示和语义检查是真的方便，我已经真香了。

**Comment by wly5556** [comment]
编译出来好多新文件，这是哪里没弄对？
话说编译目标真的要设置那么高吗，记得还是有人在用着旧一些的浏览器的

**Comment by MotooriKashin** [comment]
哦，我忘了把.gitignore文件推送了，不过也没关系，提交就是了，应该都是.d.ts声明文件。  
编译目标方面，暂时就那样吧，毕竟还不是正式版。

**Comment by MotooriKashin** [comment]
编译目标已设置为ES2018，是`async/await`那个版本。

**Comment by MotooriKashin** [comment]
已经基本重构完成了，过两天应该就可以推送了。不过“互动弹幕”部分我没测试，感觉一路any应该不会有问题？  
至于兼容性方面，编译目标涉设置为ES2018，像`?.`之类的新语法可以自动转化，而`replaceAll`之类的新特性还是不能用。查阅相关资料，应该就是分别对应`Transpile`和`Polyfill`，后者ts编译器是不提供的。

所以……看来为了兼容性还是得妥协一点，毕竟为了一些新特性额外引入Polyfill没必要，也不想使用打包工具。

**Comment by wly5556** [comment]
升级到ts版本的时候，会自动从旧版迁移设置项吗？感觉这个功能很关键，到时候能无缝切到新版本最好了👀
刚才升级的时候还弹出这个错误![](https://user-images.githubusercontent.com/61644753/135751340-c7540725-c816-4b71-b890-cdcb8e4a7a37.png)
顶栏头像的修改动画在重写页面上面不会生效，是不是要去到像av.ts的write()这种地方添加一行``API.addCss(API.getModule("avatarAnimation.css"));``
还有“从其他视频载入弹幕”这个功能，好像不能识别``/?p=n``的链接，只会载入第1p的弹幕？
另外设置按钮是不是有点太明显了，每打开一个页面都会弹出来一下，还是喜欢原来靠边那个，当然这个纯粹是个人喜好啦
火狐好像初次启动下载资源的时候比chrome慢很多，而且页面会卡住，如果初始化的时候有个地方能看到载入进度就好了（改成下载完所有模块之后再一次性``GM.setValue``会不会好一点）
当然这些都是个人想法，随便看看就好![](https://static.saraba1st.com/image/smiley/face2017/044.png)

**Comment by MotooriKashin** [comment]
1. 是该做一下设置项迁移工作
2. setting.js那个错误已经修复了，应该是CDN还没更新。
3. 顶栏头像的修改动画，待测。
4. 从其他视频载入弹幕，待测。
5. 设置按钮，可以考虑设置成仅初次显示，不过可能有人会第一次没注意后来就再也注意不到？或者添加一个设置项让用户自己隐藏，还是说还原原来的贴边版本作为可选样式？
6. 火狐我还真没测试，难道真是GM.setValue的问题？

其他问题还是等上线后等其他人反馈吧，测试肯定测试不全面。

**Comment by MotooriKashin** [comment]
旧版设置迁移不好做，因为结构差异太大，只能当全新安装了个脚本了。  
加载进度方面，可以做，但我个人不想在脚本本体中添加太多实际功能，以减少后续更新维护中可能涉及的对于脚本本体的修改。如果要做类似的功能，应该在专门的模块中提供。然后与初始化的矛盾在于，未初始化前是没有加载任何模块的状态，所以初始化还是就这样干脆利落吧，毕竟只需要初始化一次，不显示进度也不会太过突兀。个人在chrome 94中测试，3秒中之内即可初始化完成，当然这涉及网络延迟因素。

**Comment by MotooriKashin** [comment]
what？！
> Script sync failed - Codecontains errors: Uncaught SyntaxError: Unexpected token '<' at undefined:43:28.
>
GreasyFork不支持CDATA的吗→_→

**Comment by yingziwu** [comment]
> 所以还是有必要另寻模块存储方案，`GM.setValue`不行，`@resource`文件过多也不行……难道真要使用打包工具将所有模块打包进一个文件？ 可本脚本的模块系统是独创的，市面上并不存在能完美兼容的打包工具，因为无法分析模块间的联系，难道要自己写打包工具？
> 回想本脚本模块化的初衷是为了方便维护，而维护维护的是源代码，是TypeScript文件，至于最终编译出的脚本，似乎并不要求可读性？！所以将所有模块文件一起编译到一个文件里从结果而言是可行的，问题在于没有现行的打包工具，将如何把上百个文件嵌入最终的js文件中呢？仔细考虑了一下只有一个难点：
> 如何让模块代码以字符串的形式存在？
> 没错，字符串，要的就是脚本运行时不将模块代码解释为JavaScript代码，模块解析运行的事由脚本主体运行后自行接管。

关于脚本模块化说一点自己的看法。
本人脚本 [novel-downloader](https://github.com/yingziwu/novel-downloader) 为了方便维护也进行了模块化。
具体模块化方案是通过 `import` 语句 + webpack 打包来实现。

对于 [rules](https://github.com/yingziwu/novel-downloader/tree/master/src/rules) 目录下，每次只需要载入当前网站，不需要全部加载的众多网站规则，则是在 [router/download.ts](https://github.com/yingziwu/novel-downloader/blob/master/src/router/download.ts) 文件中基于网站host进行选择然后通过 [import()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports) 语句动态加载。

webpack 在编译时将相应的 `await import()` 编译成 `await Promise.resolve().then(() => __webpack_require__())` [形式](https://github.com/yingziwu/novel-downloader/blob/ce670dd6328c3a86f33d85401d94560d342ad5f3/bundle-greasyfork.user.js#L4919)。
最终的效果是：虽然 `bundle.user.js` 文件中带有所有网站的规则，但运行时只运行当前网站规则，更具体而言，只在调用 `getRule()` 函数之后才加载当前网站规则。

将 `tsconfig.json` 文件中 [module](https://www.typescriptlang.org/tsconfig#module) 设置由 `CommonJS` 改为 `ES2020`，更是可以将所有异步模块分割至独立的文件中，真正地按需加载，但由于要发布为单文件油猴脚本，并不能使用。

**Comment by MotooriKashin** [comment]
感谢！
我在这里写这些其实是当做开发笔记之类的东西，没想到真的会有人看，受宠若惊，受宠若惊。
作为我学习js的初衷及试验台，本项目其实已经进行了多次的重构，从当初的不到200行的小文件，到如今上百个模块的“大”工程，我需要记录一下这些变迁的思路，以便自己日后如果还要优化重构的话，能够立即回忆起来龙去脉。而且目前的方案似乎还不够完美——比如没有彻底解决原生脚本的托管问题。
感谢你分享的模块化经验！下面我谈谈对其中一些点的看法：
首先es6提供import特性其实是我第一个考虑的模块化方案，但import运行的模块是运行在独立的模块中的上下文环境中，这种状况下模块无法使用脚本管理器提供的高级API。webpack打包或许可以解决这个问题，尤其是她提供的eval模式。但这些打包工具也有自己的问题，首当其冲就是会将代码压缩，这是违反了Greasyfork的用户脚本规则的，作为要发布在该平台上的用户脚本，我还是想尽量不触犯相关规则。
然后其实我目前的解决方案，基本上是借鉴的webpack并稍加改进：
  1. 用Function构造函数替代eval作为模块的加载方案，避免安全问题。
  2. 使用模板字符串作为模块存档方案，原汁原味保留模块所有细节，不进行任何压缩(代价就是打包的文件比较大，只是以本脚本目前的规模，这个还不是问题。) 
  3. 使用resourceurl标记模块，方便调试(在chrome devtool中)。  
其中Function构造函数是我觉得最适合本项目模块加载方案，在解决了eval不安全隐患的前提下还能够自定义添加独立上下文环境中的顶层变量，用来传递GM高级函数简直再好不过。而且不像原生import特性，要么只能全局静态加载模块，没有“规则”；要么只能使用import()方法异步地动态加载，对于“库”等需要同步先行加载的模块不友好(当然仅就本脚本而言，因为本脚本有些功能必须运行在页面脚本之前，必须争分夺秒，异步来加载模块是不可以接受的)。

——但由于要发布单文件的油猴脚本，并不能使用。

***@***.***，考虑过GM_setValue，目前看来还是模板字符串最合适。把所有模块打包进一个文件，有点类似于压缩文件的“固实压缩”？webpack的eval模式也是类似的方法，只是她是真的“压缩”了，而我只想要打包，不想要压缩，类比于压缩相关的概念，就是我只想要.tar不想.gz！
如果webpack等打包工具能够提供不压缩的方案就好了，而且不仅不要压缩，模块内部的代码最好连碰都不要碰。

**Comment by yingziwu** [comment]
> 首先es6提供import特性其实是我第一个考虑的模块化方案，但import运行的模块是运行在独立的模块中的上下文环境中，这种状况下模块无法使用脚本管理器提供的高级API。

这个问题我是通过将 GM API 封装成函数来解决的。
[lib/GM.ts](https://github.com/yingziwu/novel-downloader/blob/master/src/lib/GM.ts) 对几个使用到的 GM API 进行了一个简单的封装，同时做了一点 Greasemonkey 的兼容。
[lib/http.ts](https://github.com/yingziwu/novel-downloader/blob/master/src/lib/http.ts) 则是对 `_GM_xmlhttpRequest` API 进了一进一步的封装，将其 Promise 化，让使用体验上类似于 [fetch](https://developer.mozilla.org/en-US/docs/Web/API/fetch) API 。

> webpack打包或许可以解决这个问题，尤其是她提供的eval模式。但这些打包工具也有自己的问题，首当其冲就是会将代码压缩，这是违反了Greasyfork的用户脚本规则的，作为要发布在该平台上的用户脚本，我还是想尽量不触犯相关规则。

webpack 的代码压缩是可以手动禁止的，文档[参见](https://webpack.js.org/configuration/optimization/#optimizationminimize)。
压缩版 webpack [配置文件](https://github.com/yingziwu/novel-downloader/blob/master/webpack.config.js)，禁用压缩版 webpack 所做的[改动](https://github.com/yingziwu/novel-downloader/blob/master/webpack-greasyfork.config.js)。

另外，刚刚注意到即使开启压缩，压缩后的代码中也保留了 GM API 的名称，而不是换名为 a, b, c 这种局部变量，这也是压缩之后脚本还能正常工作的基础，虽然不知道为什么，也许和 GM.d.ts 声明有关。
因为之前一直都是直接关闭压缩功能，只是在最近几个版本才打包出一个压缩版本，在此之前都没有想过这个问题。

![image](https://user-images.githubusercontent.com/22741471/142990179-bdfdadbd-8402-4bc4-a76a-14d4441986d0.png)

**Comment by yingziwu** [comment]
刚刚学习了一下 bilibili-old 的模块系统，模块首次载入时通过调用 Function 将源码构造成函数，同时传入 API、GM 等全局对象，真是非常地巧妙。

**Comment by MotooriKashin** [comment]
webpack 可以禁止压缩
看来是我想当然了，以后或许可以再用webpack重构一下。

压缩后的代码中也保留了 GM API 的名称
以declare声明的话，就类似于window、document等全局变量，自然不会被替换。

另外，对于用户脚本，Function构造函数还有一个优点不得不提，那就是模块可以脱离脚本管理器的沙盒，可以直接使用顶层对象window，而不需要再使用unsafeWindow，避免一些莫名其妙的问题。

**Comment by yingziwu** [comment]
>对于用户脚本，Function构造函数还有一个优点不得不提，那就是模块可以脱离脚本管理器的沙盒，可以直接使用顶层对象window

这个特点我也发现了，不过这一点给我带来了一些困扰，比如说 Vue3 在油猴脚本中无法正常工作。
为了解决这个问题，还专门 hook Function 函数。

**Comment by MotooriKashin** [comment]
Vue3 在油猴脚本中无法正常工作

不应该吧，一般来说页面顶层对象window肯定比沙盒中的那个好用吧，无法工作实在难以理解。难道是因为脚本主体本身在沙盒中，而vue需要用到沙盒中的脚本提供的数据？(从页面上下文肯定无法访问沙盒的，这也是沙盒存在的意义)
像我是遇到了沙盒中提供的异步函数clearTimeout有时无法正确清除定时器的问题，所以更喜欢所有模块全部脱离沙盒回到页面上下文中。而且我很不喜欢使用unsafeWindow，很容易导致上下文环境出错，尤其是在“基于搜索引擎编程”的时候。
***@***.***元数据的方式引入的vue3吧？

**Comment by MotooriKashin** [comment]
***@***.***引入的vue，这样vue就运行在沙盒中了，与页面上下文交流数据存在问题也就可以理解了。
***@***.******@***.******@***.***。
***@***.*** + Function构造函数，让该库回到页面上下文中，这样确保不会因为上下文环境出现一些稀奇古怪的问题。

***@***.***残废的原因，我觉得还是那个万恶的unsafeWindow！那个东西根本就不该存在，沙盒自身的window对于用户脚本而言根本毫无意义，从来都不可能用到，我们会用window时肯定是想访问页面上下文的，为什么要绕道unsafeWindow这种东西？！
而且观察TamperMonkey注入的用户脚本在devtool中表现出来的样式，分明就是类似于Function构造函数的函数体的存在(这包括后面的话只是个人的猜想，我没有分析过具体的实现原理)，用户脚本本来就是运行在页面上下文中的，只是被强行塞进去了个unsafeWindow！

**Comment by MotooriKashin** [comment]
额，怎么这么多星星？难道是触发了屏蔽词？
