### ISSUE TITLE
视频无法播放

### ISSUE THREAD

**Issue by abgai** [MotooriKashin/Bilibili-Old#175]
最新版本，今天突然视频无法加载，关掉插件可以正常播放
![UC1T3~SR3(R@FI(DVSEDO~A](https://user-images.githubusercontent.com/91419003/134809176-9dda22b2-038c-4f59-ab12-5ad400625311.png)
![)GQDDBZ8)`8XPAN(31QL3$S](https://user-images.githubusercontent.com/91419003/134809177-c14838fe-0e59-4d3a-b999-5cd17df7bfa9.png)

**Comment by MotooriKashin** [comment]
看起来是CDN问题，这种带着端口号前缀是xy开头的好像经常无法解析DNS地址，这种网络问题是暂时的，只能靠时间去解决了。  
另外，我不知道新版播放器是怎么处理这种错误的，可能是换了备用源？（可以在新版播放器上右键查看播放信息验证一下CDN）

**Comment by abgai** [comment]
确实是网络问题，今天又好了
