### ISSUE TITLE
投稿简介区只能识别第一个BV号，后面的通通成了文本

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#176]
这个问题其实也存在挺久了，不过可能没太被注意，比如这样——
![image](https://user-images.githubusercontent.com/20079289/135400503-00ec4376-e6fc-483c-9263-1c077d28f6b7.png)
没仔细观察的话可能都看不出端倪。
![image](https://user-images.githubusercontent.com/20079289/135400657-2100cda2-d5d7-48c1-94d7-30622c55137d.png)
可以用此链接测试：https://www.bilibili.com/video/av249361307

这个我估计可能和现在b站页面加载机制有关。目前页面是只加载可见区域，然后往下拉的时候再继续加载，所以**评论区有时候也会这样，就是发的内链或BV号没有被识别**。只是很奇怪的是，为什么没有识别之后，就都成了纯文本，连超链接都掉了呢……值得研究一下。

**Comment by byyxx128** [comment]
好像有点不太对劲，现在整个简介区成了纯文本了？
![image](https://user-images.githubusercontent.com/20079289/135703839-3361b4f1-4a6e-420c-ad64-330984dd7841.png)
没改之前还能识别一个BV号的来着……😂
不知道是不是我姿势不对。

**Comment by MotooriKashin** [comment]
额⊙∀⊙！变量名写错了！  
果然习惯了ts，写js时没有语义检查就是容易出错……  
可以试试切换到ts分支的版本，js的稍后修复。

**Comment by byyxx128** [comment]
哈哈哈哈，这可能就是微软大力发展ts的原因之一吧，估计那群人写js写得太恼火了hhh

亲测有效，fixed.

不过转向ts的确是对的，ts的优点太多太多了。
