### ISSUE TITLE
评论区刷新页面后，可能导致不显示“av”字样

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#178]
先放上测试网址，待我详细说这是个啥情况——
https://www.bilibili.com/video/av627103190

先决条件：**默认开启了脚本“禁用评论链接转标题”功能**——
![image](https://user-images.githubusercontent.com/20079289/135739912-3a45bdb8-601f-47c2-b249-09573d6105b8.png)

首先，初次载入页面的时候，受可见区域影响，评论区一般并没有加载。然后，往下拉的时候，评论区才会加载出来——
![image](https://user-images.githubusercontent.com/20079289/135739951-4711df59-e94e-42fb-ae08-7c8c1b87082c.png)
此时一切正常。
然后，屏幕停留在当前界面，就是显示评论区的界面，然后直接刷新网页，就会成这个样子——
![image](https://user-images.githubusercontent.com/20079289/135739974-02ecdc65-1a3d-4fbc-b0c9-73786e1b813a.png)
屡试不爽，不知道为什么会这样。
如果把页面向上拉，不显示评论区，再刷新一次页面，然后往下拉加载评论区的话，一切又正常了。

这问题可能不注意的还真发现不了……

**Comment by MotooriKashin** [comment]
已在ts分支中修复

**Comment by byyxx128** [comment]
这么说的话我越来越期待ts版本了。
