### ISSUE TITLE
嵌入式播放器互动弹幕初始化出错

### ISSUE THREAD

**Issue by MotooriKashin** [MotooriKashin/Bilibili-Old#179]
在诺贝尔2021专题页面 https://www.bilibili.com/blackboard/Nobel2021.html 中出现如下错误
![2021-10-04_110416](https://user-images.githubusercontent.com/60416767/135787330-d65741df-6ad7-4869-94f0-f1c401032aa2.png)

我猜测是因为目前互动弹幕功能只适配了av页，所以`init`被忽略，之后`load`便出现未定义错误。  

我不太懂代码之间的逻辑，所以只将入口函数调整为了async，以免干扰正常弹幕载入。  

没时间的话这个问题先挂起吧，反正av页之外有互动弹幕(其实本质就是嵌入了个av页)的少。

**Comment by wly5556** [comment]
现在这几个视频好像又没有互动组件了，或者是我打开方式不对吧
错误原因应该就是你说的那样，现在改成异步之后不影响弹幕载入了，那就先保持现在这个状态吧

**Comment by MotooriKashin** [comment]
的确，那个页面是修改后的，我当时提issue时还没开奖，现在最初的视频已不见了。

**Comment by MotooriKashin** [comment]
一个月后又在一个新专题页面出现类似情况，这次应该不会再换掉视频了。  
https://www.bilibili.com/blackboard/activity-wuqiannian.html  
![2021-11-18_171225](https://user-images.githubusercontent.com/60416767/142386379-4d5b46e3-125a-4421-a4d2-fc0fb26b4750.png)

**Comment by MotooriKashin** [comment]
拜年祭2022的几个视频都开始报错了  
![image](https://user-images.githubusercontent.com/60416767/151653171-36ebfadf-e78c-45c9-bc13-197e47b1dd83.png)  
这个功能是不是要从bilibiliPlayer.js中暴露接口比较好？API对象现在不公开，可以暴露到window后者player对象下。

**Comment by wly5556** [comment]
拖了这么久太抱歉了
载入互动弹幕那块的代码没写好，当时是只想要在av页上运行，用了__INITIAL_STATE__.videoData来判定。结果在嵌入式播放器上面没通过判定时，没有终止载入，就报错了。现在把这个判定取消了。
看了下，拜年祭那个互动弹幕是“直播预约”按钮，还没有在脚本里做出来，目前就只能在控制台打印一条警告了``debug.warn("未被支持的互动弹幕类型：" + cdm.command);``
另外我测试的时候发现，一般的嵌入播放器（[拜年祭活动页]）(https://www.bilibili.com/blackboard/bnj2022.html)，切了p，创建了新的播放器实例后，旧的实例的html元素就被清理干净了，而在脚本更新后用shadow dom处理的[拜年祭视频页](https://www.bilibili.com/festival/2022bnj)，切p后，互动弹幕的容器div没有像其他时候一样成为null，而是引用着已经不存在于页面中的那个div，所以互动弹幕还是不能正常加载。这个问题会不会与拜年祭页面特殊的重写方式有关？

>这个功能是不是要从bilibiliPlayer.js中暴露接口比较好？API对象现在不公开，可以暴露到window后者player对象下。

是要暴露哪部分呢？时间隔得有点久了，大概回想了一下，互动弹幕大部分处理都是commandDm.js做的，应该没有修改bilibiliPlayer.js的代码

**Comment by MotooriKashin** [comment]
> 拖了这么久太抱歉了😥
>
这有什么好抱歉的，反而不好意思的是我。  
>
> 另外我测试的时候发现，一般的嵌入播放器（拜年祭活动页），切了p，创建了新的播放器实例后，旧的实例的html元素就被清理干净了，互动弹幕运行正常，而在脚本更新后用shadow dom处理的拜年祭视频页，切p后，互动弹幕的容器div没有像其他时候一样成为null，而是引用着已经不存在于页面中的那个div，所以互动弹幕还是不能正常加载。这个问题会不会与拜年祭页面特殊的重写方式有关？
>
改用player.destory销毁了一下再创建新播放器实例，不知道有没有效果。  
> 
> 是要暴露哪部分呢？时间隔得有点久了，大概回想了一下，互动弹幕大部分处理都是commandDm.js做的，应该没有修改bilibiliPlayer.js的代码
> 
我是看你用\_\_INITIAL_STATE\_\_来获取一些数据，这个显然只针对av页，所以提个建议要获取数据是不是直接从bilibiliPlayer.js中暴露接口来获取比较方便，我在“反查弹幕发送者”功能中就是这么做的。不过你好像找到了别的办法。

**Comment by MotooriKashin** [comment]
添加了player.destory有效果吗？不行我去找找你之前说的“简洁的切P方式”——虽然忘记了我为什么弃用了，可能是Bilibiliplayer用着顺手？！

**Comment by wly5556** [comment]
改好了，之前的推断错了，这个问题跟重写方式完全没有关联，是我一开始写commandDm.js的时候没想清楚，在普通av页里切p应该也会发生，当时没有找到一个多p的互动弹幕视频，就没有测试到这种情况。blackboard/bnj2022的“切p”是直接改变iframe src，运行的是新的command.js实例，没有出问题，festival/2022bnj的里，你写的切p方法应该是和av页的切p方法一样``player.destory(); new BilibiliPlayer``，旧的``div#bilibiliPlayer``被remove()，于是引用的``div.bilibili-player-video-popup``就不属于页面中了。加了个条件处理这个情况。

> 切p后，互动弹幕的容器div没有像其他时候一样成为null

改正一下前面说的话，自动变为null是不可能发生的。父元素被remove()后，子元素对应的变量继续引用到不在页面中的这个元素才是应该发生的事情
