### ISSUE TITLE
一些在使用过程中发现的问题

### ISSUE THREAD

**Issue by sddddd213** [MotooriKashin/Bilibili-Old#181]
首先是播放，好像更新到6.0.0后并且关闭“启用新版弹幕”好像就不兼容pakku（开启时兼容pakku的）的同时使用了？（开启时兼容pakku的）这个在未更新之前是支持的。
其次，如果开启“启用新版弹幕”，并且视频源本身支持分段，好像【弹幕】和【播放】中的一些功能就失灵了？比如【弹幕】下的“添加互动弹幕”好像不管开启与否都是直接开启的，无法关闭窗口，只能等待弹窗时间到了自动消失。【播放】下的分段进度条开启与否都毫无意义。
上述两个情况都可在https://www.bilibili.com/video/av717911514/视频中验证。
最后在未升级之前，点赞功能属于时灵时不灵，但是更新之后好像就属于不灵了，所有视频都点赞不了。
以上问题测试平台：Microsoft Edge版本 94.0.992.38 (官方内部版本) (64 位)。
谢谢

**Comment by MotooriKashin** [comment]
感谢反馈！
有些东西不合并到主分支无法测试，带来的困扰请多担待。

ps：退回旧版大概是不可能了，应该旧版也要下载模块数量，而模块已经合并完成了。如果一开始就没升级，那就没问题。不过反馈的问题会尽快修复的，尽请放心。

**Comment by MotooriKashin** [comment]
pakku之外的问题已经修复，pakku部分代码可能需要另一位合作者 @wly5556 的帮助，不过对方最近没时间，可能需要留待之外修复了。

您可以在脚本设置“模块”中立即检查更新，不过由于CDN有24小时左右的延迟，可能无法立即获取到更新信息，可以明天再试。如果可以直连Github(raw.githubusercontent.com)的话，可将“更新源”调整为“Github”，直连源没有延迟。

**Comment by sddddd213** [comment]
> pakku之外的问题已经修复，pakku部分代码可能需要另一位合作者 @wly5556 的帮助，不过对方最近没时间，可能需要留待之外修复了。
> 
> 您可以在脚本设置“模块”中立即检查更新，不过由于CDN有24小时左右的延迟，可能无法立即获取到更新信息，可以明天再试。如果可以直连Github(raw.githubusercontent.com)的话，可将“更新源”调整为“Github”，直连源没有延迟。

现已更新，点赞功能已回归正常，添加交互弹幕功能也已回归正常。真的很好！
谢谢您的回复和更新。
