### ISSUE TITLE
10.08使用时，突然发现的bug

### ISSUE THREAD

**Issue by sddddd213** [MotooriKashin/Bilibili-Old#183]
[https://p.inari.site/home/a/211008/wWLg-QQ截图20211008000625.png](url)不能刷新出弹幕了，
同时搜索栏也出现了上一个issue中的问题。
测试平台依旧是：Microsoft Edge 版本 94.0.992.38 (官方内部版本) (64 位)。

**Comment by sddddd213** [comment]
今天继续更新已发现的bug，还是右上角弹窗。
当该视频出现弹窗后，在视频区域右键，发现视频好像不存在了。就是还能播放，但是没有弹幕，右键弹窗的是整个页面的右键，即刷新，另存为之类的那些，正常视频中的视频比例，播放速度等等是没有的。
该情况在现在的和以前的视频中都有出现，但是也只是一部分视频中有出现，不是所有的视频都会出现。
弹窗出现相当不稳定。

**Comment by MotooriKashin** [comment]
问题硬币已修复了
