### ISSUE TITLE
ㅤ

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#186]
ㅤ

**Comment by MotooriKashin** [comment]
下载菜单是异步添加到右键菜单上去的，要等同步任务执行完才会轮到异步，所以有一点延迟是正常的，而不是因为要先解析下载源的原因。选择异步是基于性能方面的考虑，毕竟播放器本身已有很大的资源消耗，不该在同步任务中实时去检测右键菜单。  
边缘检测就算存在也是播放器内部的逻辑，外部无权干涉，异步再检测一遍也不是不可以，但肯定也存在延迟，检测后移动就不优雅了。况且好像也不存在什么边缘检测，上面的其他项也一样会落到外面去。

**Comment by byyxx128** [comment]
啊要是做不了就算了……边缘检测还是有的，但是我不知道是什么机制。菜单会落在视频画面外面，但始终会在显示器的可见区域内，比如这样——
![image](https://user-images.githubusercontent.com/20079289/136702389-295fac0a-0655-4ce0-af3c-39b52f7c180f.png)
当然要是没法弄就算了……反正能用就行。
