### ISSUE TITLE
简介部分的BV号无法变蓝

### ISSUE THREAD

**Issue by redapple0204** [MotooriKashin/Bilibili-Old#19]
RT，如图所示
![image](https://user-images.githubusercontent.com/16254644/89534326-50414380-d827-11ea-827a-d512d29c47f7.png)
新版无此问题
![image](https://user-images.githubusercontent.com/16254644/89534477-97c7cf80-d827-11ea-9111-3e3690462b48.png)

**Comment by MotooriKashin** [comment]
这个问题曾经处理过，后来重构脚本时把属性抄错了。感谢反馈，将在下个版本中修复。
