### ISSUE TITLE
弹幕.xml：我/n呢

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#194]
我把av41401的弹幕文件下载到mukioplayer观看，完美错位
然后我打开xml文件：
![image](https://user-images.githubusercontent.com/77530593/139520432-100dc6a5-1c7d-4a3b-97a5-74bc675265d6.png)
？？？？？？？？我换行符呢😂

**Comment by MotooriKashin** [comment]
我这里测试下载没有问题
![2021-10-30_175732](https://user-images.githubusercontent.com/60416767/139528474-68fcd83c-2be3-4da4-a573-c503149982db.png)

**Comment by followmypeach** [comment]
经观察 json有换行符。
![image](https://user-images.githubusercontent.com/77530593/139563003-8395e30a-910e-4390-956e-a34e57627e0e.png)
在此脚本下载的xml没有。（你的截图）
![image](https://user-images.githubusercontent.com/60416767/139528474-68fcd83c-2be3-4da4-a573-c503149982db.png)
在bilibilijj下载的xml有换行符
![image](https://user-images.githubusercontent.com/77530593/139563059-8ea189cf-bc68-455f-820b-c46af58281f9.png)

**Comment by MotooriKashin** [comment]
我的截图里没有是因为Windows不显示`\n`换行符，用16进制编辑器还是看得到的
![2021-10-31_100505](https://user-images.githubusercontent.com/60416767/139563793-3707a0d6-4a56-48a3-ac60-e250963b835c.png)
可以看到，所有换行符都得到了保留。对比你提供的jijidown的截图，那只是将所有换行符都替换成了`/n`——正斜杠！  
用正斜杠`/n`替换反斜杠`\n`这难道是什么特殊做法？按理来说反斜杠才表示换行。
