### ISSUE TITLE
新版bnagumi不支持港澳台

### ISSUE THREAD

**Issue by CaptBK13** [MotooriKashin/Bilibili-Old#195]
打开重写bnagumi的话是正常的，但有时候弹幕又太多，就想要新版的弹幕云屏蔽，但是用关了重写bangumi的话就播放港澳台失败了，这是bug么还是就是这样（谢谢dalao的插件

**Comment by MotooriKashin** [comment]
本脚本核心就是重写回旧版页面，很多功能也是围绕旧版页面设计的，所以关闭相关页面的重写解除区域限制失效是必然的。  
本脚本不会专门为新版播放器实现任何功能，否则就喧宾夺主，不如单独另写一个脚本。单独的脚本的话不妨另外安装“解除区域限制”那个脚本，那才是专业的。  
至于弹幕太多，旧版播放器设置里有弹幕密度调节选项，勉强可作为替代。智能云屏蔽功能暂时没有移植到旧版播放器里的计划，抱歉。

**Comment by CaptBK13** [comment]
谢谢解答，确实可以用弹幕密度，解决了

> 本脚本核心就是重写回旧版页面，很多功能也是围绕旧版页面设计的，所以关闭相关页面的重写解除区域限制失效是必然的。本脚本不会专门为新版播放器实现任何功能，否则就喧宾夺主，不如单独另写一个脚本。单独的脚本的话不妨另外安装"解除区域限制"那个脚本，那才是专业的。至于弹幕太多，旧版播放器设置里有弹幕密度调节选项，勉强可作为替代。智能云屏蔽功能暂时没有移植到旧版播放器里的计划，抱歉。
