### ISSUE TITLE
评论区不能展示UP主、大会员等特殊身份

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#196]
盲猜可能和用了旧版评论有关。不过有可能的话，能不能把相关功能也移植过来呢？
https://www.bilibili.com/video/av251399701
![image](https://user-images.githubusercontent.com/20079289/141036588-d0b3cef6-8236-4cac-a174-21a0035a2325.png)
![image](https://user-images.githubusercontent.com/20079289/141036663-f8b3ee58-e492-4e4b-b309-9b42cda7a7ae.png)

哎对，直播间评论区也不显示，不知道是不是用了一样的组件

**Comment by byyxx128** [comment]
补一下，旧版的小闪电和账号级别标志比新版清楚……建议保留，只把大会员和UP以及账号身份移植过来即可，图标还继续用旧版就行。

**Comment by byyxx128** [comment]
补一下，旧版的小闪电和账号级别标志比新版清楚……建议保留，只把大会员和UP以及账号身份移植过来即可，图标还继续用旧版就行。

附：目前找到的旧版图标——
https://s1.hdslb.com/bfs/static/jinkela/videoplay/asserts/user-auth.png
https://s1.hdslb.com/bfs/static/jinkela/space/assets/level.png

新版图标很多是用 svg 绘制的，反正我觉得颜色不醒目……

**Comment by byyxx128** [comment]
补一下，旧版的小闪电和账号级别标志比新版清楚……建议保留，只把大会员和UP以及账号身份移植过来即可，图标还继续用旧版就行。

附：目前找到的旧版图标——
https://s1.hdslb.com/bfs/static/jinkela/videoplay/asserts/user-auth.png
https://s1.hdslb.com/bfs/static/jinkela/space/assets/level.png

P.S. 哔哩哔哩竟然有九级？这是曾经有过，还是未来会有……

新版图标很多是用 svg 绘制的，反正我觉得颜色不醒目……

**Comment by MotooriKashin** [comment]
九级一直都有，只是作为彩蛋存在，实际上遵循学园都市标准，七级以上的从来没有过，将来应该也不会有。

**Comment by byyxx128** [comment]
大佬你怎么什么时候都在……你是住在GitHub了嘛？😂

**Comment by MotooriKashin** [comment]
我有订阅邮件

**Comment by byyxx128** [comment]
不对不对，你应该说“是的，我就是住在GitHub了，我在GitHub买了别墅”，这就好玩儿了。

**Comment by byyxx128** [comment]
效率够快的。
不过还漏了一个：评论区回复中UP主的身份
如果是UP主直接发评论，这个是正常显示的。
但是，如果是UP主回复其他人的评论，这个就没有展示——
![image](https://user-images.githubusercontent.com/20079289/141223819-5cc8f959-8195-4994-aa45-209dbae8a40d.png)
![image](https://user-images.githubusercontent.com/20079289/141223917-77f5b969-9a16-42cc-8ff2-293d8f03c7d3.png)
而且这个评论区的回复中也有小闪电标志，这个看能不能也移植过来。
![image](https://user-images.githubusercontent.com/20079289/141224202-c2bd07ee-2789-4653-a600-4eb079937c83.png)
![image](https://user-images.githubusercontent.com/20079289/141224236-a66bb435-d889-4690-9cc9-bcd49ca181e3.png)

测试网址：https://www.bilibili.com/video/av588874215

另外，捎带吹毛求疵一下，看能不能再调整一下——

1. “年度大会员”这几个字周围没有空隙，显得太挤
![image](https://user-images.githubusercontent.com/20079289/141222052-7623a89e-0ac5-4864-b75c-6a0206eaea1b.png)
![image](https://user-images.githubusercontent.com/20079289/141222080-bf862440-b334-466d-91df-da5bd33fc1cf.png)
字号不用改了，咱这个比新版原版的合适。就是粉红色背景稍微有点边框更好看一点。
2. 认证信息上面挨得太近
![image](https://user-images.githubusercontent.com/20079289/141222310-d9fad94e-e6cb-41f2-bfbd-d4cdb3ded4ef.png)
![image](https://user-images.githubusercontent.com/20079289/141222245-eabed8a8-7c0c-4559-9f1c-7e11dbb70322.png)
稍微上面有点空隙，也别太大，稍微有一点就好看了。新版原版的空隙就有点过大了。

就这两点，有时间的时候稍微给调一下就行，不是什么大问题。总之已经很好了。

**Comment by MotooriKashin** [comment]
已添加修改，效果图：
![2021-11-11_113450](https://user-images.githubusercontent.com/60416767/141233032-22a9ed8f-cbc8-41d0-b0b1-6d190f52e47e.png)

**Comment by byyxx128** [comment]
爱死你了
