### ISSUE TITLE
[Bilibili 翻页评论区] 评论区用户的 `UP` 和粉丝勋章标识移至等级后方

### ISSUE THREAD

**Issue by Geeyun-JY3** [MotooriKashin/Bilibili-Old#197]
既然已经将新版评论区的楼中楼认证标志、身份标志和新版个人信息弹窗移植了过来，建议也和新版评论区一样将用户的 `UP` 和粉丝勋章标识移至等级后方。
新版评论区样式：
![image](https://user-images.githubusercontent.com/49396421/142616193-e269a5fc-92dc-4004-af6b-96754744ad4f.png)
![image](https://user-images.githubusercontent.com/49396421/142616322-aecc0b01-27d4-486f-b6b4-e53a63e18192.png)

现在脚本的样式为标志在前，且用户名和标志之间没有间距：
![image](https://user-images.githubusercontent.com/49396421/142616394-4c427111-f88f-4f98-b68d-04c521198396.png)
![image](https://user-images.githubusercontent.com/49396421/142616531-209939f2-4e22-4ef8-9f3a-957ef24eabbe.png)

**Comment by MotooriKashin** [comment]
样式我还是想保留旧版的样式，没有间距的问题或许是新版残留的影响，会想办法加以修复。
——最近一段时间摸不到电脑，维护时间可能会稍后。


 

-------- 原始邮件 --------
发件人：Geeyun-JY3 ***@***.***>
时间：2021年11月19日 19:37
收件人：MotooriKashin/Bilibili-Old ***@***.***>
抄送：Subscribed ***@***.***>
主题：[MotooriKashin/Bilibili-Old] 评论区用户的 `UP` 和粉丝勋章标识移至等级后方 (Issue #197)

**Comment by Geeyun-JY3** [comment]
如果是想保留旧版样式的话，那就建议让这两标识的大小和旧版一样。现在是新版的大小，需要调大些。
