### ISSUE TITLE
评论区链接转换又出错了，这次是av号不行了（上次是BV）

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#198]
# 老大好像最近拿不到电脑？不着急，啥时候有空啥时候修就行。
***
未启用脚本——
![image](https://user-images.githubusercontent.com/20079289/143799547-0bc75144-a5b2-48bd-8260-4a459807b4a8.png)
启用脚本后——
![image](https://user-images.githubusercontent.com/20079289/143799580-40df05c0-2f11-4d80-94a2-fded88042e17.png)
测试网址——
https://www.bilibili.com/video/av84946131

另外，刷新网页时候，可能明显看到先出现纯文本的BV，然后又转为超链接av，但是原本是av超链接的，就成了大写AV纯文本……这很奇怪——
![动画](https://user-images.githubusercontent.com/20079289/143800485-e63d2c48-7bdc-4f11-80d3-6766bf3a0dc1.gif)
主要疑问点：为什么会先显示BV纯文本，然后才转成av超链接，这个过程为何会有明显卡顿？

**Comment by MotooriKashin** [comment]
转化是在视频载入完成时触发的，而不是显示出来立刻触发，这是为了性能考虑，我并不想所有问题都监控页面节点载入情况。

大写AV这是原生脚本所没有考虑的情况，已添加处理。

**Comment by byyxx128** [comment]
亲测有效
