### ISSUE TITLE
去掉链接无用参数功能会导致非超链接的误伤

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#199]
咱们脚本有个处女座和强迫癌的专属功能，就是去除链接后面的无用参数，比如`?spm_id_from`之类的。
不过，这个功能可能在判断逻辑上存在欠缺，导致会误伤非网页超链接的链接。

比如这里——
https://app.bilibili.com
上述网页打开后，有个大按钮——
![image](https://user-images.githubusercontent.com/20079289/143801248-4c13f8f1-73a3-47d6-86dc-4bffff1f350f.png)
这个按钮指向的链接本来应该是——
`ms-appinstaller:?source=https://dl.hdslb.com/mobile/appinstaller/bilibili_win.appinstaller`
结果，在脚本的处理下，就变成了——
`ms-appinstaller:`
这就很奇怪了，因为这个只是应用的专门协议，非HTTP或HTTPS超文本传输协议，按理说不应该处理才对……可能是脚本本身没加入这个判断逻辑，导致出现了这个情况。望老大看到后进行修正。
***
## 老大没电脑不要紧，不着急，我就是想起来就赶紧开 issue 了，免得一会儿我忘了……

**Comment by MotooriKashin** [comment]
这种属于自定义协议，由于我还在用win8，所以没注意，感谢反馈！
已忽略对于自定义协议的处理。

**Comment by MotooriKashin** [comment]
> bilibili 追踪参数过滤好像有一点遗漏，具体可以参见这个 [PR](https://github.com/AdguardTeam/AdguardFilters/pull/99685/files)

的确，目前的参数都是我自己整理出来的，应该足够应对网页端大部分情况，我看了下那个参考，直接把`from`去掉会有不妥，印象中在直播页面与付费相关的某些链接这个`from`参数是必要的，其余大部分`share`类的参数应该没问题，我会添加试试。

**Comment by byyxx128** [comment]
自定义协议亲测已排除。鉴于有关于移除无用参数的新 PR，暂不关闭，留着以观后效。

**Comment by byyxx128** [comment]
亲测可用，感谢大佬补充的参数
