### ISSUE TITLE
首页顶栏模糊背景消失

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [MotooriKashin/Bilibili-Old#2]
### 如题，这样文字会因为背景很花变得看不清楚

启用脚本后
![1](https://user-images.githubusercontent.com/45261195/77388010-ed946180-6dc9-11ea-91eb-4af7b7440e30.jpg)

原版旧顶栏
![2](https://user-images.githubusercontent.com/45261195/77388012-eff6bb80-6dc9-11ea-96bb-453fc9f1af7f.jpg)

**Comment by MotooriKashin** [comment]
其实故意为之的(任性!)，因为看新版顶栏是完全透明，所以画蛇添足地处理了一下透明效果。但可能不是每个人都需要，正在尝试实现交互界面，让每个人自己选择每项功能的开关，可能需要些时间但不会太久。
目前临时的办法是搜索关键词`heahblur`，把第一个`heahblur`后面的`1`改为`0`，保存即可。

**Comment by Aira-Sakuranomiya** [comment]
ok 感谢作者！！
太爱这个脚本了

**Comment by MotooriKashin** [comment]
@Aira-Sakuranomiya 2.7.0版本已经引入设置界面，应该可以主动关闭了
