### ISSUE TITLE
使用收藏夹的“播放全部”功能无法获取全部视频

### ISSUE THREAD

**Issue by redapple0204** [MotooriKashin/Bilibili-Old#20]
RT，例如[一个收藏夹](https://www.bilibili.com/medialist/play/ml221330720)有999个视频，只能获取其中216个（也就是只有216个视频被添加到了播放列表中）

![image](https://user-images.githubusercontent.com/16254644/89615038-4156a180-d8b8-11ea-9c00-492995a5edbd.png)
如图，点击“播放全部之后”获取的视频并不全
![image](https://user-images.githubusercontent.com/16254644/89615090-68ad6e80-d8b8-11ea-898b-d66f4a33618c.png)

**Comment by redapple0204** [comment]
PS:能获取的视频个数是不定的，但就是获取不完。上述收藏夹刷新后又能获取410个视频了。

**Comment by redapple0204** [comment]
另外还有一个问题，获取的列表顺序似乎是错乱的

**Comment by MotooriKashin** [comment]
999个视频？？？能提供这样的收藏号给我测试一下吗？我没碰见过那么多的收藏所以没发现这种问题。顺序的问题我试下换个接口吧。


来自 魅族 16th

**Comment by redapple0204** [comment]
> 999个视频？？？能提供这样的收藏号给我测试一下吗？我没碰见过那么多的收藏所以没发现这种问题。顺序的问题我试下换个接口吧。 来自 魅族 16th

好的，这是测试链接：https://www.bilibili.com/medialist/play/ml221330720

**Comment by MotooriKashin** [comment]
感谢，已优化了视频获取，现在能获取除失效视频外所有的视频，但是有个问题，像这种900多个视频一起放到列表里将导致视频载入及切换速度变得非常慢，应该是稍后再看列表承受能力问题，印象中稍后再看列表上限就是100。
新版采取的是一次获取20个视频的方式构造列表，滚动到底部再20个一批加载，这是稍后再看列表办不到的。

**Comment by redapple0204** [comment]
@MotooriKashin 感谢！
