### ISSUE TITLE
页面改版

### ISSUE THREAD

**Issue by sddddd213** [MotooriKashin/Bilibili-Old#200]
![image](https://user-images.githubusercontent.com/38841494/144394853-dc3ab7d0-15a4-4c86-8ecc-115c51d99ab0.png)
该页面中除了国创区还是原来的
![image](https://user-images.githubusercontent.com/38841494/144395025-1875aa2a-7c5f-481a-b703-40bda477b9ca.png)
其余的页面都已变成
![image](https://user-images.githubusercontent.com/38841494/144395130-90598e6b-863d-4b6d-816c-e7461b93e7a6.png)
番剧和部分几个区变成了
![image](https://user-images.githubusercontent.com/38841494/144395384-6ad15dab-3b8c-4201-bbe9-b19762c110ec.png)

能处理修复吗？谢谢

测试平台依旧Microsoft Edge
版本 96.0.1054.34 (官方内部版本) (64 位)
![image](https://user-images.githubusercontent.com/38841494/144395716-cfdd146e-47d3-4ff4-8733-b82fb4efed3c.png)

**Comment by MotooriKashin** [comment]
灰度测试吗？我这里还是旧的。
![image](https://user-images.githubusercontent.com/60416767/144400366-420b55f6-0128-47c1-8ce8-c583bceb6b97.png)

**Comment by sddddd213** [comment]
> 灰度测试吗？我这里还是旧的。 ![image](https://user-images.githubusercontent.com/60416767/144400366-420b55f6-0128-47c1-8ce8-c583bceb6b97.png)

其他页面是恢复了，但是番剧页面好像是恢复不了，只要不点击其下的其他分区就无法回到旧版页面，点击旧版页面里的全部也会直接变成![image](https://user-images.githubusercontent.com/38841494/144395384-6ad15dab-3b8c-4201-bbe9-b19762c110ec.png)

**Comment by MotooriKashin** [comment]
番剧区也一样
![image](https://user-images.githubusercontent.com/60416767/144521679-67b6c687-341a-442b-a66a-e89ac6822a02.png)

**Comment by sddddd213** [comment]
> 番剧区也一样 ![image](https://user-images.githubusercontent.com/60416767/144521679-67b6c687-341a-442b-a66a-e89ac6822a02.png)

请问插件是6.1.5版本吗？

**Comment by MotooriKashin** [comment]
目前尝试通过cookies的方式强制切换为旧版番剧分区主页，不知道有没有效果？

**Comment by sddddd213** [comment]
> 目前尝试通过cookies的方式强制切换为旧版番剧分区主页，不知道有没有效果？

如何更新到有这个功能的版本呢？

**Comment by MotooriKashin** [comment]
直接检查脚本更新就可以吧，GreasyFork我看也更新了。

**Comment by sddddd213** [comment]
> 直接检查脚本更新就可以吧，GreasyFork我看也更新了。

更新了没恢复，删除脚本后重新安装也没恢复。是我脚本删除的不彻底的原因吗？如何彻底删除脚本？

**Comment by MotooriKashin** [comment]
那看来没效果，稍后启用重写版本


来自 16th

**Comment by MotooriKashin** [comment]
已推送重写版本，但没自动启用，请更新脚本后自行在设置 -> 重写 -> 番剧分区处启用。  

“编辑推荐”栏因为无相关接口暂时留空

**Comment by sddddd213** [comment]
> 已推送重写版本，但没自动启用，请更新脚本后自行在设置 -> 重写 -> 番剧分区处启用。
> 
> “编辑推荐”栏因为无相关接口暂时留空

目前已解决，解决方式，通过删除bili相关的所有cookie，已成功恢复。
