### ISSUE TITLE
Bilibili 翻页评论区脚本：视频详情页和动态页面评论区文本框错位

### ISSUE THREAD

**Issue by tianyun1114** [MotooriKashin/Bilibili-Old#201]
https://greasyfork.org/zh-CN/scripts/403348-bilibili-%E7%BF%BB%E9%A1%B5%E8%AF%84%E8%AE%BA%E5%8C%BA/discussions/107714

**Comment by MotooriKashin** [comment]
已使用新版打包方式重构了该脚本，更新了hook方式，最大限度阻止原生样式干扰，应该能够解决问题。

**该脚本现在完全使用与[主脚本](https://greasyfork.org/scripts/394296)相同的hook方式，未避免产生冲突，再次强调最好不要同时安装。**

**Comment by tianyun1114** [comment]
不好意思，视频页和动态页修复了，但专栏内容页还是错位的
