### ISSUE TITLE
jsdelivr被墙导致插件失效

### ISSUE THREAD

**Issue by StackExplode** [MotooriKashin/Bilibili-Old#203]
打开播放页无法载入播放器，一片白，一按F12发现`https://cdn.jsdelivr.net/gh/MotooriKashin/Bilibili-Old/JavaScript/video.min.js`和`https://cdn.jsdelivr.net/gh/MotooriKashin/Bilibili-Old/JavaScript/comment.min.js`都加载失败了，一开梯子立马好了。我用手机4G网也试过了访问不了jsdelivr。麻烦作者测一下是不是被墙了还是间歇性抽风，如果被墙还请改一下CDN罢，如果是我的网络环境问题，那我自裁。

**Comment by sequencelight** [comment]
我这边的网络也不行，应该是群体性的

**Comment by sequencelight** [comment]
我目前的使用方法是加载的时候开一下梯子，后面关掉，不清缓存就行。

**Comment by MotooriKashin** [comment]
应该不是被墙，只是节点停电，参考——https://github.com/jsdelivr/jsdelivr/issues/18348

等到晚上再看吧，稍后添加一个设置开关，提供关闭原生脚本托管的功能（开启该功能将导致部分功能不可用）。

**Comment by MotooriKashin** [comment]
CDN已恢复，可以继续启用原生脚本托管了

**Comment by luminous030** [comment]
> CDN已恢复，可以继续启用原生脚本托管了

这会儿测试还是不行, https://cdn.jsdelivr.net/gh/MotooriKashin/Bilibili-Old/dist/video.min.js net::ERR CERT_ COMMON NAME_ INVALID

**Comment by luminous030** [comment]
> > > CDN已恢复，可以继续启用原生脚本托管了
> > 
> > 
> > 这会儿测试还是不行, https://cdn.jsdelivr.net/gh/MotooriKashin/Bilibili-Old/dist/video.min.js net::ERR CERT_ COMMON NAME_ INVALID
> 
> 可以试试刷新DNS缓存
> 
> ```
> ipconfig /flushdns
> ```
> 
> 然后ping一下cdn.jsdelivr.net-> `ping cdn.jsdelivr.net`，应该都是切换到Fastly了。

感谢回复, 目前用起来一切正常.
