### ISSUE TITLE
评论区无法显示

### ISSUE THREAD

**Issue by xijunji-jie** [MotooriKashin/Bilibili-Old#204]
![2021-12-20](https://user-images.githubusercontent.com/81166596/146735852-e5425c6e-e25c-4a9c-837e-724e9ca0bedd.png)

**Comment by xijunji-jie** [comment]
-

**Comment by MotooriKashin** [comment]
应该和 #203 是同一个原因，升级版本并关闭“托管原生脚本”可临时缓解

**Comment by MotooriKashin** [comment]
CDN已恢复，问题是否还在？
