### ISSUE TITLE
加载在线弹幕不能解析avid和cid

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#206]
如题（
要解析的av:122646,cid:208382

**Comment by MotooriKashin** [comment]
如图，你提供的aid与cid并不对应，导致B站返回弹幕数据出错。  
你可以直接在输入框输入`av122646`而不需要带上cid，脚本会自动获取正确的cid。  
如果是分p的视频，以第二p为例，那就世界输入`av122646?p=2`，或者直接复制地址栏的完整url，`https://www.bilibili.com/...`。  
cid最好不要自己输入，你输入了脚本就认定你输入的是对的，一旦出错肯定获取不到弹幕。
![image](https://user-images.githubusercontent.com/60416767/147866705-d763a57f-80ba-43c9-88fd-c399b09a3e97.png)
