### ISSUE TITLE
[bug]载入本地视频的奇怪bug

### ISSUE THREAD

**Issue by ciriue** [MotooriKashin/Bilibili-Old#207]
本地视频会被载入到版头里
![image](https://user-images.githubusercontent.com/84818059/149035260-a118f5a0-18fc-471c-8f7a-64c705044e7a.png)

![image](https://user-images.githubusercontent.com/84818059/149035172-7cf5647c-913e-4a1f-bd89-ed2179c85734.png)

如图

系统环境win10 20H2 19042.1415
chrome版本 97.0.4692.71

100%复现

**Comment by MotooriKashin** [comment]
实现这个功能时想当然了，以为一个页面只会出现一个视频节点。  
已修复，感谢反馈！

**Comment by ciriue** [comment]
> 实现这个功能时想当然了，以为一个页面只会出现一个视频节点。 已修复，感谢反馈！

大佬辛苦了
