### ISSUE TITLE
和 Bilibili Evolved 一起运行的时候会有一些冲突

### ISSUE THREAD

**Issue by MSGOOHPA** [MotooriKashin/Bilibili-Old#208]
Bilibili-Old 和 Bilibili Evolved 一起运行的时候，Bilibili Evolved 会无法保存配置和保存插件，即刷新后就恢复成原来的配置了，关闭 Bilibili-Old 后就可以正常保存了，这个问题可能是由于 Bilibili-Old 的工作方式而导致的，可能不能解决，但还是希望作者看看能不能修好

**Comment by MotooriKashin** [comment]
参考兼容性文档，这种问题无法由本脚本去主动兼容。解决办法有二：
1. 在非重写页面（如个人空间）中，或者临时禁用本脚本后进行。
2. 对方去掉run at document-start元数据。
