### ISSUE TITLE
能否添加个播放速率控制界面

### ISSUE THREAD

**Issue by AndyStrom** [MotooriKashin/Bilibili-Old#209]
新版会有这个功能，用这个来练歌还是挺好用的

**Comment by MotooriKashin** [comment]
播放器速率在右键吧？

**Comment by AndyStrom** [comment]
[https://i.bmp.ovh/imgs/2022/01/e989f9a591580d14.png](url)
旧版播放器没有的
[https://i.bmp.ovh/imgs/2022/01/5b381980bef4d510.png](url)
新版则是这样

**Comment by MotooriKashin** [comment]
你看看控制台console是不是有什么报错，正常邮件是这个样子的
![image](https://user-images.githubusercontent.com/60416767/150236382-95768a6b-b9a3-443b-b9f2-c58748489f89.png)
