### ISSUE TITLE
显示楼中楼的楼层

### ISSUE THREAD

**Issue by Geeyun-JY3** [MotooriKashin/Bilibili-Old#21]
个人一直在用 [修复B站评论区楼层](https://greasyfork.org/scripts/403348) 独立脚本。
希望能显示楼中楼的楼层（这个以前网页版能不能看到我也记不太清楚了🤦‍♂️）

**Comment by MotooriKashin** [comment]
我也不太清楚，参考Android Google play版，感觉当时应该楼中楼也会显示楼层。  
我会试试看，只是楼中楼显然比一维的楼层实现起来困难。

**Comment by Geeyun-JY3** [comment]
那抛开还原旧版页面，显示楼中楼的楼层有实现的可能性吗

**Comment by MotooriKashin** [comment]
应该没问题，就是定位楼中楼element有点麻烦，我会想办法的

**Comment by MotooriKashin** [comment]
楼中楼分两种状态，折叠显示3条热评，展开按时间先后排序10个一页。  
前者直接绑定在顶层评论上获取不难，后者目前的接口获取不到3页及以后的数据，干脆直接根据页码算出楼层号，只要没删楼中楼，这个页码就是准确的。  
不够完美，先将就着用，如果以后有办法获取原生的数据再说。附截图一张
![2020-08-08_210355](https://user-images.githubusercontent.com/60416767/89711114-c88c3e00-d9ba-11ea-8f4b-f74338a453df.png)

**Comment by Geeyun-JY3** [comment]
> 后者目前的接口获取不到3页及以后的数据，干脆直接根据页码算出楼层号，只要没删楼中楼，这个页码就是准确的。

我觉得如果获取不到就暂时先别显示了，楼中楼被删还是挺常见的，准确性更重要些

**Comment by MotooriKashin** [comment]
那只能用笨办法实现了，把该页及之前的所有页面都获取一遍，如果楼层号过大，显示出楼层号就会很缓慢。  
实测55页的楼中楼获取到数据需要3s左右，具体看网络延迟决定，好在一般点开楼中楼的机会也少，而且大部分楼中楼页数也不会太多。
 
原因是楼中楼相比于顶层，获取对应页面的数据需要当页第一条回复的楼层号，然而如果连当页数据都获取不到又凭什么获取到当页第一条评论的楼层？解决办法只有从第一页开始获取，因为第一页回复是不需要第一条回复的楼层号作为参照物的，获取到了第一页就可以在最后一条回复的楼层号上+1，作为第二页第一条回复的楼层号(如果+1评论恰好被删，也没有任何影响，参照值会自动顺延)，以此类推，直到获取到指定页数的回复数据。

**Comment by Geeyun-JY3** [comment]
> 那只能用笨办法实现了，把该页及之前的所有页面都获取一遍，如果楼层号过大，显示出楼层号就会很缓慢。
> 实测55页的楼中楼获取到数据需要3s左右，具体看网络延迟决定，好在一般点开楼中楼的机会也少，而且大部分楼中楼页数也不会太多。
> 
> 原因是楼中楼相比于顶层，获取对应页面的数据需要当页第一条回复的楼层号，然而如果连当页数据都获取不到又凭什么获取到当页第一条评论的楼层？解决办法只有从第一页开始获取，因为第一页回复是不需要第一条回复的楼层号作为参照物的，获取到了第一页就可以在最后一条回复的楼层号上+1，作为第二页第一条回复的楼层号(如果+1评论恰好被删，也没有任何影响，参照值会自动顺延)，以此类推，直到获取到指定页数的回复数据。

抱歉没怎么看懂这段话😅。那现在是有办法准确获取所有楼中楼的楼层，但加载起来会比较慢吗？

**Comment by MotooriKashin** [comment]
已经更新了，可以试试看


来自 魅族 16th

**Comment by Geeyun-JY3** [comment]
在何同学这个 [视频](https://www.bilibili.com/video/av626524324) 试了试（置顶有一万多层，一千多页），第一次展开后翻了几页都没问题，拿旧版 Android 客户端测试前几页都没错，不过直接跳到尾页再回去楼中楼的楼层就消失了，之后再去看其他视频中展开后的楼中楼也失效了🤦‍♂️，可能是我在何同学这个视频测试的问题。
总之能做到这个效果我觉得已经相当 OK 了。万分感谢。

**Comment by MotooriKashin** [comment]
那可能是请求过多触发了B站风控被临时封端口了，那种成百上千页的楼中楼还是最好不要试了。
要不我还是在脚本中控制一下页数吧，50我认为是比较稳妥的页数。


来自 魅族 16th

-------- 原始邮件 --------
发件人：Geeyun-JY3 <notifications@github.com>
时间：2020年8月9日 12:30
收件人：MotooriKashin/Bilibili-Old <Bilibili-Old@noreply.github.com>
抄送：MotooriKashin <lianmengkexin@gmail.com>,Comment <comment@noreply.github.com>
主题：Re: [MotooriKashin/Bilibili-Old] 显示楼中楼的楼层 (#21)

**Comment by Geeyun-JY3** [comment]
> 那可能是请求过多触发了B站风控被临时封端口了

十分抱歉，是我滥用了🤦‍♂️。
> 要不我还是在脚本中控制一下页数吧，50我认为是比较稳妥的页数。

同意。要不做成按需请求，请求满 50 页后才再请求加载的需要的 50 页？
建议在 README 中也说明一下吧。

**Comment by MotooriKashin** [comment]
改进了下获取方法，现在能获取任意页数楼中楼层号，不再受页数限制。  
唯一的问题是：当楼中楼该页的第一条评论是回复(@)别人时，那页的楼层无法获取。暂时只能这样，哪有那么巧刚好第一条评论是回复？——其实还真有！甚至是连续好几页都是回复的情况！  
暂时没有更好的接口了，一页一页获取容易触发风控也不要用了，毕竟是被B站抛弃了的功能，也许有一天干脆连接口也封了……
