### ISSUE TITLE
“热门视频排行榜”中的月排行错误

### ISSUE THREAD

**Issue by redapple0204** [MotooriKashin/Bilibili-Old#210]
当在热门视频中切换成“月排行”，出来的排行是2020年的视频
![image](https://user-images.githubusercontent.com/16254644/150663456-dfe8a83c-becd-4e1d-8916-32a184f8ad32.png)
![image](https://user-images.githubusercontent.com/16254644/150663467-5ab2ee87-1021-49ae-ad33-7bfaf7ae69c9.png)

**Comment by MotooriKashin** [comment]
接口失效，无法修复，已添加样式禁用相关鼠标事件。
