### ISSUE TITLE
播放器切换画质失败卡死

### ISSUE THREAD

**Issue by MotooriKashin** [MotooriKashin/Bilibili-Old#212]
本月24日B站网页端开启支持av1编码视频流，似乎会导致旧版播放器切换画质功能异常卡死。

另外，下载功能中av1格式暂缺1080P+(大会员)以上格式参数  
![image](https://user-images.githubusercontent.com/60416767/151652441-005285e1-1f9f-47f7-aefc-c750d21435a1.png)  
希望可以提供相关链接参考，
如，下面100026：av1格式1080P
>
> https://upos-sz-mirrorcoso1.bilivideo.com/upgcxcode/66/22/493482266/493482266-1-100026.m4s?...`
>

**Comment by MotooriKashin** [comment]
不行。。。调试了半天实在不知道卡在哪里，还是说我硬件的问题。  
@wly5556 有空的话帮忙看看，调试bilibiliPlayer.js还是你比较厉害。路过大神也请伸伸援手，不能切换画质这个问题实在有点严重了，必须得想办法解决。  

![image](https://user-images.githubusercontent.com/60416767/151682077-9950da0c-4d2d-4fea-873b-ec644e1812e8.png)
另外，我看了下chrome原生就支持av1，这样的话处理好了，以后旧版播放器支持hdr以上画质也不是梦了吧。

**Comment by wly5556** [comment]
我这里已经有1080p以上的下载按钮了，是已经处理好了吗
![LX4N}R9HOJU~UTPDX(`$16Y](https://user-images.githubusercontent.com/61644753/151684928-44275c9b-b63c-44b8-96bc-e69daafe9c52.png)
4k：
>https://xy218x85x123x3xy.mcdn.bilivideo.cn:4483/upgcxcode/20/66/496616620/496616620-1-100029.m4s

1080P+：
>https://xy110x85x55x83xy.mcdn.bilivideo.cn:4483/upgcxcode/20/66/496616620/496616620-1-100027.m4s

切换画质卡死是视频画面卡死，还是切换画质按钮卡死？

**Comment by MotooriKashin** [comment]
按钮卡死

**Comment by MotooriKashin** [comment]
目前是直接读取的画质信息，网页端接口会直接提供。但下载面板的数据可能来自APP、电视端等接口，那些只能从这五六位编号中读取画质。

**Comment by MotooriKashin** [comment]
补充：按钮卡死，等于切换不了画质，视频在播放的时候会继续播放，未播放就直接点不开，只能通过player.seek恢复播放。

**Comment by MotooriKashin** [comment]
> 我这里已经有1080p以上的下载按钮了，是已经处理好了吗 ![LX4N}R9HOJU~UTPDX(`$16Y](https://user-images.githubusercontent.com/61644753/151684928-44275c9b-b63c-44b8-96bc-e69daafe9c52.png) 4k：
> 
> > https://xy218x85x123x3xy.mcdn.bilivideo.cn:4483/upgcxcode/20/66/496616620/496616620-1-100029.m4s
> 
> 1080p 60fps:
> 
> > https://xy218x85x123x5xy.mcdn.bilivideo.cn:4483/upgcxcode/42/20/494072042/494072042-1-100028.m4s
> 
> 1080P+：
> 
> > https://xy110x85x55x83xy.mcdn.bilivideo.cn:4483/upgcxcode/20/66/496616620/496616620-1-100027.m4s
> 

感谢，那就只差杜比视界和8K清晰度了，这个得看缘分了，这两个清晰度的视频上热门的应该太罕见了。

**Comment by wly5556** [comment]
杜比好像是hevc编码的吧，我看你之前已经标注好了``30126: "Dolby"``
8k av1，他们的工程师说是“[指日可待](https://t.bilibili.com/619202956877939745)”的状态，不知道现在实装没有

**Comment by wly5556** [comment]
另外hevc 30106好像对应的是1080p 60，download.ts里标成了1080P+
```
30106: '1080P+',
30102: '1080P+',
```

**Comment by MotooriKashin** [comment]
> 杜比好像是hevc编码的吧，我看你之前已经标注好了`30126: "Dolby"` 8k av1，他们的工程师说是“[指日可待](https://t.bilibili.com/619202956877939745)”的状态，不知道现在实装没有

杜比难道只能用hevc编码？这个我还真没了解过。
> 另外hevc 30106好像对应的是1080p 60，download.ts里标成了1080P+

的确是疏忽了，已修正。

**Comment by wly5556** [comment]
> 按钮卡死，等于切换不了画质，视频在播放的时候会继续播放，未播放就直接点不开，只能通过player.seek恢复播放。

反复切换画质试了一会，点击切换画质后，到成功切换画质之前，画质切换按钮确实是不能操作，应该是原本就这么设计了，有时网络慢的话按钮像卡住了一样，但是我还没有触发完全卡死的情况，不知道是我的操作有哪里不同

看playurl里面，h264对应``codecid=7``
然后video.js里面用这段代码把其他的编码格式都过滤掉了，应该不会影响到视频的正常播放才对

```javascript
t.Period.AdaptationSet[0].Representation = e.video.filter(function (e) {
    return 7 === e.codecid
})
```

_(hevc codecid = 12; av1 codecid = 13;)_
![Q}IBE8D2)P7}38E8_8Q Z(W](https://user-images.githubusercontent.com/61644753/151689522-2d88419e-3f2a-477b-901c-35daff3272fb.png)

**Comment by MotooriKashin** [comment]
不只是画质按钮无法操作，如果切换画质时视频没有播放，切换后根本无法播放，network里也根本看不到有请求新流

**Comment by MotooriKashin** [comment]
我测试用的时排行榜上的[?](https://www.bilibili.com/video/av253420838)

**Comment by wly5556** [comment]
确实在这个视频上出现了一样的问题，我也试着找找原因

**Comment by wly5556** [comment]
我试着重新描述一下这个问题
触发条件：播放器缓冲到视频末尾后，切换画质

- 与视频时长无关，那个排行榜上的”?“视频因为时长短所以容易发现这个问题。其实在那些一小时长的视频，跳到最后十秒，等待缓冲完毕，切画质，也会发生这个情况

- **与播放器新旧版本无关**，新播放器如此操作也能大概率触发，无法切换到新画质，不同的是： 1.新播放器对于短的视频默认只缓冲20秒的内容，旧播放器是一律缓冲80秒，所以新播放器更难遇上这个bug  2.新播放器会**在一段时间后提示”切换失败“**，不至于卡住；旧播放器在点击新画质到切换成功前，设计上就会一直保持“播放状态中可以点击暂停，但暂停后不能通过再次点击恢复播放”、“暂停后仍能够通过拖动进度条恢复播放”、“画质切换按钮不可用” 的状态，这时如果遇上这种无法进入新画质的bug，就等于卡死了

我试着强行限制旧播放器的缓冲时长到20秒（和这个commit修改同一个地方 b9127f62fe3c32540c6480f58e30d6c2669f6854），这时候旧播放器播放那种短视频时，只要没有缓冲到底，切画质就没出问题，所以这个问题应该能确定跟**缓冲到视频末尾**有关，至于它的产生原因我就没能力去找出来了

**Comment by wly5556** [comment]
另外大概了解了一下，上个月国内的jsdelivr挂掉，恢复访问之后，已经没有国内的节点了，国内的请求都转发到了境外的cdn。所以现在全新安装旧播放页脚本，访问视频页，由于浏览器没有缓存，去cdn载入托管的脚本要等几秒钟以上，期间就会像[这个反馈](https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5/discussions/117231)一样白屏。
或许应该考虑别的托管方式？

**Comment by MotooriKashin** [comment]
辛苦了，过年好啊！
这样的问题真亏你能调试出来，不是av1格式的问题就好，是我随便挑了个提供av1的视频就中奖了。。。
jsdelivr出问题那天我看了下全国的ping数据，应该不至于延迟那么高吧。额，不过国内的网络情形的确太复杂。只是我是实在找不到替代方案了，那天我还去试了下码云，该说不愧是国内的服务，外链都要求登录，根本当不了CDN。这方面jsdelivr应该是独家了。另辟蹊径找永久存储方案的话，现在前端的各种标准都只提供异步服务，这种脚本依赖应该等不了异步返回吧。找到的一个同步工具是serviceworker，但服务脚本要托管在B站顶级域名下，显然也是用不了的。
不知道你有没有什么解决办法推荐？
***@***.***，另外chrome开始强制推行manifest V3，用户脚本尤其是同步API前途未卜啊。

**Comment by MotooriKashin** [comment]
三个原生脚本现在都使用 `@resource`方案存储到Tampermonkey提供的储存功能中了，这样只需要安装时访问一次jsdelivr，不会再每次打开视频都请求一次了。

新方案暂时没有编译，需要自行编译——测试几天再发布。[→测试脚本文件](https://github.com/MotooriKashin/Bilibili-Old/files/7978510/main.user.zip)

**Comment by wly5556** [comment]
惊了，这么快就有新方案
简单测试了下，只发现了播单页的重写不正常，其他地方都挺好的
```javascript
Uncaught (in promise) TypeError: Cannot read properties of null (reading '1')
    at e.exports (eval at set (EmbedPlayer.js:1:1), <anonymous>:28105:60)
    at playlist.7d294586b1b77cce5918121205cf42a71034e85d.js:1:101801
    at c (1.playlist.7d294586b1b77cce5918121205cf42a71034e85d.js:86:29354)
    at Generator._invoke (1.playlist.7d294586b1b77cce5918121205cf42a71034e85d.js:86:29107)
    at Generator.next (1.playlist.7d294586b1b77cce5918121205cf42a71034e85d.js:86:29717)
    at n (1.playlist.7d294586b1b77cce5918121205cf42a71034e85d.js:13:9501)
    at s (1.playlist.7d294586b1b77cce5918121205cf42a71034e85d.js:13:9712)
```

**Comment by MotooriKashin** [comment]
播放好像是后台不返回数据吧？

**Comment by wly5556** [comment]
我弄混了，应该说是medialist页面有点问题

**Comment by MotooriKashin** [comment]
的确，原来medialist页面也有类似video.min.js的东西存在，我还以为只有旧版页面才有，所以直接hook了EmbedPlayer，导致旧版播放器脚本直接被新版页面拉起了，参数，节点都不对，不报错才怪！  
看了下播放器初始化参数
>
> playlistType=3&playlistId=182603655&auxiliary=1&playlistOid=NaN&playlistOtype=NaN&autoplay=true&show_bv=1&tid=0&desc=true&sort_field=1
>

居然连aid，cid都没有！

**Comment by MotooriKashin** [comment]
已禁用在非重写页面对于`EmbedPlayer`的hook。

原本是想不管页面是否重写都hook一下video.min.js的，没想到新版页面没完全抛弃`EmbedPlayer`。video.min.js作为写在HTML里的脚本，hook起来不如bilibiliPlayer.min.js这种后续插入的脚本方便。
