### ISSUE TITLE
无法恢复最新界面

### ISSUE THREAD

**Issue by NullPtrSaMa** [MotooriKashin/Bilibili-Old#213]
我用了插件以下载视频，但在我发现老界面视频无法加载、速度慢后想要恢复最新界面
但是我禁用了插件、TamperMonkey后，B站还是老界面
删除缓存也没有
视频也看不了
有办法吗？

**Comment by MotooriKashin** [comment]
虽然不知道为什么禁用TamperMonkey无效。
脚本还在运行的话，页面加载完右下角会有一个活动的齿轮，点进去会跳转出设置界面，把“重写”里面的所有选项关闭试试。


来自 16th

**Comment by MotooriKashin** [comment]
新年快乐
