### ISSUE TITLE
重构B站原生脚本video.min.js

### ISSUE THREAD

**Issue by MotooriKashin** [MotooriKashin/Bilibili-Old#214]
`video.min.js`和`bilibiliPlayer.min.js`，这两个原生的旧版播放器脚本可能由于历史原因代码重合颇多。为了修复和增强一些播放器功能，本项目不得不修改她们并托管到GitHub，可每每涉及这方面的修改总是得修改两份，这种压缩混淆过的代码修改一份已是头疼，何况两份！而在免费公共CDN`jsdelivr`丢失国内ISP执照后，所有CDN都必须绕道国外节点，造成这两个脚本加载缓慢。  
所以我想是该做些什么了。  
首先，两个脚本之间的关系发现其实`bilibiliPlayer.min.js`才是播放器脚本的核心，`video.min.js`充其量只不过时一个启动内核的外壳而已，很多页面其实没有`video.min.js`，但必须有`bilibiliPlayer.min.js`。想个办法干掉`video.min.js`应该不难。
进一步分析如下：
![image](https://user-images.githubusercontent.com/60416767/152126555-351ce0a3-663e-4182-99a6-e3cb386ea020.png)  
脚本之间传递数据通过window暴露的两个接口`EmbedPlayer`和`bilibiliPlayer`函数，并没有其他直接关联。既然通过window变量那hook起来也简单，有之前hook评论区脚本的经验在，就算她是直接写在HTML文档里的行内脚本应也不难。

**Comment by MotooriKashin** [comment]
已重写video.min.js，基本页面测试正常，页面载入好像都快了不少。  
*——依旧未编译成脚本，需要自行编译测试。*

**Comment by wly5556** [comment]
太厉害了，从来没想过video.min.js可以被去掉！

发现不能切p，报了这个错误
```javascript
Uncaught TypeError: window.GrayManager.reload is not a function
    at a.changeVideo (video.b1b7706abd590dd295794f540f7669a5d8d978b3.js:1:119725)
    at click (video.b1b7706abd590dd295794f540f7669a5d8d978b3.js:1:170078)
    at e (vendor.b1b7706abd590dd295794f540f7669a5d8d978b3.js:6:17656)
    at HTMLAnchorElement.t._withTask.t._withTask (vendor.b1b7706abd590dd295794f540f7669a5d8d978b3.js:6:17045)
```

**Comment by wly5556** [comment]
看起来video.min.js是dash播放器的核心，看右键统计信息，不使用它的播放器载入的是flv流

**Comment by MotooriKashin** [comment]
也有dash流，冰菓是flv，国王排名是dash。

**Comment by MotooriKashin** [comment]
GrayManager我没移植完，里面的东西太多了，且部分绑定了播放器实例，完全移植需要点工夫。

**Comment by wly5556** [comment]
我这里干掉video.js之后，包括国王排名，点开的所有视频都是显示用的flvplayer。但是bilibiliPlayer.js和video.js里dash.js的部分又几乎一模一样....

**Comment by MotooriKashin** [comment]
那难道是GrayManager的问题？把上个commit修改的那行注释掉试试，我测试时还没覆盖它。

**Comment by MotooriKashin** [comment]
dash与否我记得只根后台返回值有关，移植解除区域限制时我试过请求flv流返回dash流一样不会没问题。
而播放流加载出问题时，重连请求的是flv，所以大概率是GrayManager没移植完导致载入dash出错，重连时改申请flv了。

**Comment by MotooriKashin** [comment]
昨天只是猜测，今天测试后发现是默认请求流的问题，video.min.js会默认添加`dashSymbol=true`乃至代为请求视频流，我也就默认加上了，如此，只要移植好GrayManager应该就可以直接抛弃video.min.js了。

**Comment by MotooriKashin** [comment]
已移植`GrayManager.reload`，切P功能应该回复正常了。

**Comment by MotooriKashin** [comment]
其他似乎都是`video.min.js`内部自调用，而不是向外部暴露的接口，移植也是浪费资源，以后如果发现还有外部接口再移植吧。
