### ISSUE TITLE
是否有可能作为 Bilibili Evolved 的插件？

### ISSUE THREAD

**Issue by alex3236** [MotooriKashin/Bilibili-Old#215]
是否有可能将旧播放页作为 [Bilibili Evolved](https://github.com/the1812/Bilibili-Evolved) 的一个插件，实现功能整合？

**Comment by MotooriKashin** [comment]
要说可能那当然有可能，只是代价有点高，本项目如今代码量已经太庞大，要修改为[Bilibili Evolved](https://github.com/the1812/Bilibili-Evolved)的插件或者组件得完全重写，时间和精力成本太高。如果有人愿意这么做，那也欢迎之至，并且愿意提供力所能及的帮助。  
不过本项目底层实现至今仍有问题，这导致了本脚本与其他脚本或扩展不兼容，并且至今没有什么好的解决办法。这可能也是你提出这个issue的原因——与[Bilibili Evolved](https://github.com/the1812/Bilibili-Evolved)的兼容问题。不过说实话，底层问题不解决，就算移植为的[Bilibili Evolved](https://github.com/the1812/Bilibili-Evolved)的插件或者组件也只会导致[Bilibili Evolved](https://github.com/the1812/Bilibili-Evolved)与其他脚本或扩展产生兼容问题，甚至包括插件或者组件之间，其他插件或者组件可能也要主动去兼容“本插件或组件”，那样就有喧宾夺主之嫌了，还不如像现在一样当一个独立脚本。
缓解与[Bilibili Evolved](https://github.com/the1812/Bilibili-Evolved)的兼容问题，目前只能将就将[Bilibili Evolved](https://github.com/the1812/Bilibili-Evolved)的元数据`run-at`修改为`document-start`之外的选项，当然[Bilibili Evolved](https://github.com/the1812/Bilibili-Evolved)的部分功能可能依赖run-at document-start`，这就没办法了。
