### ISSUE TITLE
现在新版番剧页也是有点赞功能的

### ISSUE THREAD

**Issue by meiruitesi** [MotooriKashin/Bilibili-Old#216]
![image](https://user-images.githubusercontent.com/84609642/152371619-1120e7d9-497a-4d73-99e5-6414f5aa3389.png)
求添加到旧版番剧页里
![image](https://user-images.githubusercontent.com/84609642/152371443-69ed8070-50ee-4906-9c21-982eda55c2f9.png)
![image](https://user-images.githubusercontent.com/84609642/152371485-40e7bb47-8f92-47ee-b365-2d12491218a3.png)

**Comment by MotooriKashin** [comment]
已移植bangumi点赞支持，bangumi里点赞数据只针对当前ep，所以不像新版页面算的系列点赞数据。
