### ISSUE TITLE
关键更新：改进页面重构方法

### ISSUE THREAD

**Issue by MotooriKashin** [MotooriKashin/Bilibili-Old#217]
有上次尝试弃用`video.min.js`的经验，对于页面初始化逻辑尤其是旧版播放器初始化逻辑有了更深的理解，我想是时候抛弃2年多来广受诟病的`document.write`方法，用更精细化更合理的方法来重构(由重写更名为重构)旧版页面了 。

### `document.write`方法的作用  
1. 用旧版页面HTML文件刷新当前页面DOM树。
2. 立即阻止当前页面DOM树中所有资源的解析或运行，这很重要，否则来自新版页面的脚本运行后会在页面中大肆破坏！
3. 刷新DOM的机制与解析浏览器解析html文件的机制相同，相比其他修改的DOM的方法优势巨大。

### `document.write`方法的副作用
`document`对象引用被新DOM树覆盖，但在此之前很多脚本，尤其是来自chrome扩展的`content.js`已建立对原始`document`对象的引用，DOM树的更新并不会通知传递引用。这些`content.js`引用的还是那个已经停止解析的`document`对象，并由此引发一些列兼容问题，IDM下载悬浮窗的消息就是最明显的。此外所有添加给原始`document`对象事件回调页全部失灵——原始DOM树已停止解析还回调个屁！这甚至影响到了脚本自身，使得在 `document.write`方法执行前脚本页不敢添加任何事件监听。

### 新的重构方案
1. 使用`window.stop`立即停止原始DOM树解析，实现2。**但这也有个副作用此处按下不表。**
2. 使用`Node.replaceWith`方法替换head节点。
3. 赋值`document.body`为新body节点，`document.body`居然是可写的你敢信！

head+body的替换相当于实现了1，而且由于没有动到html标签，也就是`document`对象没有被覆盖，成功回避了`document.write`方法的副作用。但新方法有个问题：script节点不会执行！重写过后的页面将一片空白！  
万幸除了`document.write`方法外，还有一种方法可以执行script标签，那就是使用`document.createElement`方法重建script节点然后通过`Node.appendChild`等方法添加进DOM树。  
然而这样就万事大吉了吗？把上述方法重现一边你会发现页面虽然重构完成了，但只重构了一点点，打开console控制台你会发现一大片来自添加的script节点的报错！稍微排查一下发现都是变量引用出错？  
回顾上述过程，很明显，还缺的实现3，浏览器加载解析DOM树时碰到script标签(一般)会停下来加载对应的脚本文件并执行，`document.write`方法很完美了重现了这一机制，但`Node.appendChild`等方法不会，不会等到前一个script节点已加载执行完再执行下一个，一堆script节点同时添加上去遇到相互依赖的地方不报错才怪。所以重建script节点还需优化一下，等待前一个脚本已执行完再添加进下一个脚本进DOM树，这需要作者很清楚脚本之间的依赖先后关系，这正是重写`video.min.js`后才有的契机。

这便是脚本即将发布新的关键更新信息，详细内容如下：
1. 取消使用`document.write`，更精细化地重构页面，提高脚本兼容性。
2. 更新模块模板，增强VSCode提示功能。
3. 推出开发者模式，开发调时基本不再需要重新安装脚本。

本次更新还优化了模块机制，推出了开发者模式，详见后续开发者文档更新。

最后问题来到了`window.stop`的副作用，那就是如果执行得太早，早于浏览器加载完`favicon.ico`，那么完蛋了这个标签页将丢失`favicon.ico`。这一副作用说大也不大，只是让人很不爽！  
那脚本不能等到`favicon.ico`加载完再stop吗？理论上可以，但事实上做不到，首先作为Tampermonkey脚本，脚本的注入时机是取决于Tampermonkey的，而这一时期很抱歉并不是固定的，否则这就不再是“如果”这种概率性的副作用。其次本脚本作为重构页面的脚本，拦截新版页面的速度自然是越快越好，重构前新版页面若一闪而过也是让人不爽的，而脚本如果判断一下`favicon.ico`是否加载完再执行`window.stop`，肯定会加剧一闪而过的现象，因为判断方法只能异步等待，异步回调的时间是不确定的，但肯定够body节点执行一大截，那是非但页面一闪而过，一些写在body标签里的script标签很可能就从此起飞了——脚本一旦执行是没有任何办法制止的，它们若想再重构后的页面中大肆破坏或者再全局环境中倒垃圾就无法阻止了。最后也是最重要的一点，新版很多页面并没有提供`favicon.ico`的link节点，所以根本无法判断浏览器到底加载完了`favicon.ico`没有→_→

**Comment by MotooriKashin** [comment]
medialist页面构思新模拟方案重新实现中。。。

**Comment by wly5556** [comment]
这个真的太厉害了！这个工作量辛苦你了！！
另外现在是还没有完全把脚本的各种功能迁移到新架构的版本吗？好像顶栏又恢复成远古版本了👀

**Comment by MotooriKashin** [comment]
远古顶栏有什么问题吗？我感觉直接在上面修复比整个替换要好，替换那瞬间的跳跃感不太好。

**Comment by wly5556** [comment]
这个是av页的顶栏
![L9Q1`BI_9$~~E% QXYR$L4G](https://user-images.githubusercontent.com/61644753/153704667-faaabba9-7746-4633-ba5e-6c7a5f5b50c3.png)

这个是首页的顶栏
![NHJ_H2)5Q9U}%X @_YYW`2I](https://user-images.githubusercontent.com/61644753/153704672-8410ca87-c8fb-4bfb-a5c9-545cd7660daf.png)

（我不清楚顶栏修复的细节啦，可能没描述清楚问题）

**Comment by MotooriKashin** [comment]
区别的确挺大的，但只要没有失效的链接应该没关系吧。之前替换掉是因为“消息”子页面失效了，现在用新方法修复了。

**Comment by wly5556** [comment]
功能上也不太对劲吧
BML BW 还是2021年的东西，那个”画友“页面里的内容自从2018年就没更新了，顶栏头像的动画也很难受

**Comment by MotooriKashin** [comment]
也是，那还是替换回来吧。

**Comment by wly5556** [comment]
辛苦了，实在感谢！🎉🎉
