### ISSUE TITLE
Firefox 80 兼容性问题

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#22]
系统Ubuntu 20.04
浏览器是软件源里的版本
视频播放和弹幕完全正常

**Comment by MyBlueHorizon** [comment]
测试了一下，加载出播放器之后控制台反而报错，没有加载出来只有警告
这里有时候打开控制台也是无法加载

**Comment by MyBlueHorizon** [comment]
另外，发现有时加载出来了播放器没有弹幕，右键菜单不正常

**Comment by MotooriKashin** [comment]
那也就是没有加载完全  
这总时灵时不灵的问题实在没有头绪  
只能说不建议使用Firefox 79

**Comment by MyBlueHorizon** [comment]
您那边还是开启控制台就一切正常吗

**Comment by MotooriKashin** [comment]
现在不行了

**Comment by MyBlueHorizon** [comment]
多次测试 Firefox 80 加载正常

**Comment by MyBlueHorizon** [comment]
补充 av页正常，ep页依然无法正常加载播放器

**Comment by MotooriKashin** [comment]
我这边还是一样的

**Comment by MyBlueHorizon** [comment]
一个猜测，是否是因为加载时机的问题导致加载失败。

**Comment by MotooriKashin** [comment]
> 一个猜测，是否是因为加载时机的问题导致加载失败。

感觉不是，以av页为例：
![2020-11-08_200800](https://user-images.githubusercontent.com/60416767/98464528-7c8da700-21fe-11eb-8fe4-f5e899d55b18.jpg)
红框框出来的分别是av页的三部分，可以形象地称之为头、身、尾，头和尾都能正常生成，只有身完全没动静，而页面绝大部分包括播放器都在身里。如果是时机问题，那么应该三部分都完全没反应，不应该只有身没反应。 
比较一下三部分的异同，只能归结于身上多了一串`data-server-rendered="true"`，百度了一下与vue相关，就没什么进展了。  
这种不报错的差异化问题，真真不知道从何下手。

**Comment by MyBlueHorizon** [comment]
刚才偶然发现在Firefox83可以正常加载，但仍然需要继续测试确认。

**Comment by MotooriKashin** [comment]
好像是的，不知道是Firefox更新版本还是脚本重构了的原因
