### ISSUE TITLE
打开播放页无法载入播放器

### ISSUE THREAD

**Issue by sequencelight** [MotooriKashin/Bilibili-Old#222]
播放器区域全白，已刷新dns缓存无用，全局也无法载入。

**Comment by MotooriKashin** [comment]
受CDN问题影响，脚本已改进原生脚本托管方法并托送，你可以更新试试。

**Comment by sequencelight** [comment]
已更新，无限自动刷新。。

**Comment by sequencelight** [comment]
并且无痕模式仍然无法载入，复现率100%（

**Comment by MotooriKashin** [comment]
不会每打开一个页面都要强制刷新吧？

**Comment by sequencelight** [comment]
> 不会每打开一个页面都要强制刷新吧？

已清除缓存，所有视频页面打开后都会强制刷新，刷新次数随机且不少于2次

**Comment by sequencelight** [comment]
刚刚发现强制刷新是插件冲突，抱歉打扰。。
正常打开会与video speed controller冲突，但是无痕模式下无冲突。这是一个小bug，麻烦看一下，其他的问题均已解决。
冲突插件为bilibili merged flv+mp4+ass+enhance，已禁用

**Comment by MotooriKashin** [comment]
本次更新改善了与其他脚本的兼容性，所以其他脚本会在重写页面正常生效，但对方可能并未适配旧版页面，这种问题只能由对方去兼容。
