### ISSUE TITLE
播放器加载不出来了是什么情况

### ISSUE THREAD

**Issue by WolfgangWu** [MotooriKashin/Bilibili-Old#223]
![image](https://user-images.githubusercontent.com/69294448/153495759-22876d54-cf25-430a-af04-67ac284e0d82.png)

如题，整个页面中只有播放器加载不出来，持续好几天了

**Comment by MotooriKashin** [comment]
更新最新版试试。

**Comment by WolfgangWu** [comment]
解决了，谢谢

**Comment by WolfgangWu** [comment]
![image](https://user-images.githubusercontent.com/69294448/153712123-e17a277e-c1dc-4693-b4b4-4dd7a0c68775.png)
动态页的CSS掉了？

**Comment by MotooriKashin** [comment]
火狐？

**Comment by WolfgangWu** [comment]
> 火狐？

97.0.4692.99 (Official Build) (arm64)

**Comment by MotooriKashin** [comment]
好的
