### ISSUE TITLE
建议加一个使用其他视频编码（如 hevc 或 av1 编码）源播放的功能

### ISSUE THREAD

**Issue by MSGOOHPA** [MotooriKashin/Bilibili-Old#224]
以为现在有一些浏览器支持 hevc 和 av1 编码的解码，所以我想能不能加入这个功能，而且 8k 视频也就只有 hevc 和 av1 的源了

**Comment by MotooriKashin** [comment]
我一直想移植，hevc姑且不论，chrome肯定是支持av1的，只是这好像超出了我目前的能力，不知道 @wly5556 有没有时间，或者求助路过的高手。

**Comment by MSGOOHPA** [comment]
直接用获取到的别的编码的视频源来替换本来的h264视频源可行吗？

**Comment by wly5556** [comment]
新播放器的hevc方案是wasm软解+canvas渲染，这套方案要移植到旧播放器应该比较麻烦（没有去看代码，猜的🙏🏻）
av1的话应该可以做，之前也找到了[入手点](https://github.com/MotooriKashin/Bilibili-Old/issues/212#issuecomment-1025085728)

**Comment by MSGOOHPA** [comment]
> 新播放器的hevc方案是wasm软解+canvas渲染，这套方案要移植到旧播放器应该比较麻烦（没有去看代码，猜的🙏🏻）
> av1的话应该可以做，之前也找到了[入手点](https://github.com/MotooriKashin/Bilibili-Old/issues/212#issuecomment-1025085728)

那 Safari 和 老 Edge 的 hevc 应该是直接调用系统解码器吧，新 Edge 装了微软商店里的 hevc 解码器之后也能硬解来着

**Comment by wly5556** [comment]
这个确实，解码交给浏览器，剩下要改代码的话无非多个选择，我去试着弄一下

**Comment by MotooriKashin** [comment]
> 新播放器的hevc方案是wasm软解+canvas渲染，这套方案要移植到旧播放器应该比较麻烦（没有去看代码，猜的🙏🏻） av1的话应该可以做，之前也找到了[入手点](https://github.com/MotooriKashin/Bilibili-Old/issues/212#issuecomment-1025085728)

新版增加了开发版脚本，使用chrome的话调试会方便不少，免去每次修改后*去浏览器中重新安装*的步骤，B站原生脚本也是更是tsc编译都省了，直接刷新页面就行，你可以看看[开发者文档](https://github.com/MotooriKashin/Bilibili-Old/wiki/%E5%BC%80%E5%8F%91%E8%80%85%E6%96%87%E6%A1%A3)

**Comment by MotooriKashin** [comment]
![image](https://user-images.githubusercontent.com/60416767/153741058-550a280a-d661-44c9-86e0-6e6864b20693.png)
太强了 @wly5556 ！

**Comment by wly5556** [comment]
7.0.3版本提供了切换hevc、av1源的选项，可以更新到这个版本看看效果
![ZFWUZ{TK7866XFEWK 2Q7YX](https://user-images.githubusercontent.com/61644753/153755696-9e793a5a-a141-4de9-83ab-a57f99d71973.png)
