### ISSUE TITLE
7.0.1 版本中部分设置项目手动关闭后自动打开

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#226]
截至八小时前发布的 7.0.1 版本，目前发现，某些设置项目无法被保存。

具体比如重构中的`av/BV`、`主页`——
![image](https://user-images.githubusercontent.com/20079289/153561838-f281813d-bbe7-4e6b-9da9-3f60806aac3c.png)
以及样式中的`统一换回旧版顶栏`——
![image](https://user-images.githubusercontent.com/20079289/153561870-2fdfa00c-c236-43a4-bb12-aca88227fea8.png)

这几个设置项目，在手动关闭后，刷新页面后会恢复为勾选状态。以`主页`开关为例，这个选项是改写主页的。如果关闭，将会呈现b站当前的最新主页。然后，安装脚本后，首次打开b站主页，是新版，再刷新一次，变为旧版。然后到设置中关掉这个开关，再刷新，页面会呈现为新版，但再去设置中一看，这个开关自动打开了……于是，再刷新页面，又变回旧版……
（至于为什么我要关这些开关，这个不是重点……）

精力和需求有限，没有对所有选项进行测试，目前发现了上述这几个选项存在手动关闭后自动打开的情况。但是关闭后似乎可以保存一次状态，否则不会出现关闭后刷新主页会呈现新版主页的情况了。

烦请老大抽空瞅瞅什么情况。（观察到上次 [commit](https://github.com/MotooriKashin/Bilibili-Old/commit/e9380e4041955b28621ffb0a55292755f78e587a) 是一小时前，不知道老大是否依然在疯狂敲键盘中……）

**Comment by MotooriKashin** [comment]
感谢反馈，每一次大改动总是难免各种各样的bug。
