### ISSUE TITLE
Bilibili 旧播放页 TypeError: parrent is null

### ISSUE THREAD

**Issue by Taebost** [MotooriKashin/Bilibili-Old#227]
![图片](https://user-images.githubusercontent.com/64080472/153572058-d337dcbe-79b9-4d88-83cb-4b6afbe3f578.png)
火狐浏览器，在最近的一次更新后就成这样了。
所有功能全部失效，同时评论无法正常显示。
![图片](https://user-images.githubusercontent.com/64080472/153572360-07b4fcd2-b08e-4053-a35b-0d6d947789c0.png)

**Comment by MotooriKashin** [comment]
应该是只有评论区异常吧？

**Comment by Taebost** [comment]
不止。经测试，部分界面能除了评论区外可以正常加载，如图
![图片](https://user-images.githubusercontent.com/64080472/153594077-fc705fb7-e044-4839-af86-018946997bf0.png)

但出现头图所示的“TypeError: parrent is null”错误后，该脚本除了设置按钮内置内容以外的所有功能均无效（存疑，但是常用的如界面改写、反查、右键下载等确实无效），同时评论区无法正常加载，如图
![图片](https://user-images.githubusercontent.com/64080472/153594166-b8b611f5-08e3-43ba-b603-1deaa53549f3.png)

顺便一提该BUG的出现界面不局限于视频，还可能是空间主页。

**Comment by MotooriKashin** [comment]
“TypeError: parrent is null”错误已尝试修复，但没更新版本号，评论区问题也调整了一个样式表位置，我这边测试基本不再重现。

**Comment by Taebost** [comment]
辛苦了。
不过据我刚才测试，在动态界面打开评论区还是会有错位现象出现
![图片](https://user-images.githubusercontent.com/64080472/153692029-3956dd5a-bdfd-46aa-bd70-2cd4055583fe.png)
不过也确实不是什么很影响使用的大问题就是了

**Comment by MotooriKashin** [comment]
这个问题也已修复，将在稍晚时正式编译并推送。

**Comment by MotooriKashin** [comment]
已正式推送
