### ISSUE TITLE
【功能异常】还原评论中的超链接

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#228]
截止到19小时前的最新版本，无论是否开启`还原评论中的超链接`这一项，都未发现任何效果。
![image](https://user-images.githubusercontent.com/20079289/153702877-1c746473-ca81-4c59-9075-c3bfe4e35b57.png)

等下，怎么一分钟前有个新版本？我测试一下……

该死的CDN还没更新……啊，先装个历史版本……

不行，这个问题依然存在。请老大测试定位下吧。

**Comment by MotooriKashin** [comment]
已经找回来了

**Comment by byyxx128** [comment]
Perfect.
