### ISSUE TITLE
没有发现B站播放器

### ISSUE THREAD

**Issue by sddddd213** [MotooriKashin/Bilibili-Old#229]
作者你好，我又来麻烦你了（呜呜呜

问题描述：我浏览器同时安装了【pakku】和本脚本，以前可以在就就播放页面上实习弹幕过滤的功能，但是从昨天（好像）开始，点击任何一个视频【pakku】插件都表示未发现B站播放器，并且标签页上也不显示B站logo，
![image](https://user-images.githubusercontent.com/38841494/153704984-758335b4-5850-4318-b03d-0ce6d36eb369.png)
但当我在本页面关闭脚本并刷新之后，【pakku】正常工作，然后我再次开启脚本并刷新之后，【pakku】正常工作，标签页的logo也正常显示
![image](https://user-images.githubusercontent.com/38841494/153705500-b20404c6-a1e6-4ac1-9491-50e8c36b41bb.png)
请问这个是BUG吧？能处理吗？谢谢

其次是我的分区模块又出现bug了
![image](https://user-images.githubusercontent.com/38841494/153705583-31f1dbe8-e889-4755-8fa3-09567848d769.png)
这里面除了番剧区点击打开是就旧放页以外，其余全都是新播放页，
![image](https://user-images.githubusercontent.com/38841494/153705631-95b01581-7b59-4269-b522-513f7b35ebdb.png)
![image](https://user-images.githubusercontent.com/38841494/153705637-444cd878-1ea4-4483-98ac-e89db5de3b97.png)
这个又该怎么处理？之前是通过清理cookie解决，现在该方法失效。

Ps：同时在这里给你拜个晚年，新年快乐。

测试平台：Microsoft Edge 版本 97.0.1072.62 (官方内部版本) (64 位)，旧播放页脚本 版本 7.0.1，
![image](https://user-images.githubusercontent.com/38841494/153705782-14861c00-226c-4eb9-bfda-3745dd764c74.png)
![image](https://user-images.githubusercontent.com/38841494/153705824-0d194775-b10f-4b68-957f-aaef21afda25.png)

**Comment by wly5556** [comment]
感谢反馈，我这里的情况和你一样
开发者工具显示，在旧播放器脚本7.0.0以上的版本中，pakku.js的xhr_hook.js没有运行，直接导致了这个问题。
这种情况会不会跟这次采用的新重构方式有关？这部分还得请教@MotooriKashin 
![3T9MGE 4T6LE0FYV}J${A9O](https://user-images.githubusercontent.com/61644753/153706112-bb900d75-239d-4f65-95bd-20df33e9e253.png)![GBCC_GJQ0JIE%{ 6BE2NS5](https://user-images.githubusercontent.com/61644753/153706115-f9c2bf06-a3a6-46db-834b-c7176b876ad4.png)
（左边是6.2.6版本对应的截图，右边是最新版）

**Comment by MotooriKashin** [comment]
pakku不是早就不能用了吗？ #181

**Comment by wly5556** [comment]
记得之前为了兼容pakku专门commit了几次，应该还是能用的（#181 里也提到了，无法兼容的是关闭“使用proto弹幕”之后，记得是因为pakku那时删去了worker hook）

**Comment by sddddd213** [comment]
> 

当时不清楚，但是后来是可以同时在旧播放页上使用pakku的，也就是从昨天开始才不能使用的。并且在问题中也提出一些可以使用的情况。
现在的问题是，不能在点击视频的时候pakku自动运行，会显示没有发现B站播放器，只有通过上述的方法才可以在就播放页中启动pakku，这样会很麻烦。

**Comment by MotooriKashin** [comment]
按理说这次重构提高了与扩展的兼容性，不该出现这种问题啊，pakku在注入内容脚本之前是不是要判定什么条件。

新重写方法问题就是中断了正常的加载事件循环，window.onload，document.readyState等事件不再触发（脚本会代为发布部分，可能是少发布了哪个？）

**Comment by sddddd213** [comment]
> 

估计是这样，另一位答着表示，在开发者工具中显示，就6.2.6和7.0.0两个版本中【pakku】相关脚本运行情况有不同。

**Comment by MotooriKashin** [comment]
"content_scripts": [ { "matches": ["*://*.bilibili.com/*"], "js": ["assets/script_injector.js"], "run_at": "document_end", "all_frames": true } ]

莫非是run_at document_end根本不触发？

**Comment by byyxx128** [comment]
>另一位答着表示

首先错别字，应该是“答者”。

另外，前面回复你的那个人可不是普通的“答者”，他是作者的好X友。🤔

**Comment by MotooriKashin** [comment]
已尝试兼容性改动，谁测试一下可以兼容pakku了不？
[测试文件.zip](https://github.com/MotooriKashin/Bilibili-Old/files/8053259/main.user.zip)

**Comment by sddddd213** [comment]
怎么使用？

**Comment by MotooriKashin** [comment]
解压，安装
![image](https://user-images.githubusercontent.com/60416767/153709780-3e567588-6bbc-4bff-ade0-4f73ccb3075a.png)

**Comment by sddddd213** [comment]
目前就问题中所描述的问题已在测试文件中得到解决。

但是这个点赞的效果，颜色变化不明显，建议改回原来的“由空白变粉红”的设置。

**Comment by MotooriKashin** [comment]
那好，虽然新版脚本残留对页面进行破坏的可能性加剧了，遇到这种问题就硬刷新解决吧。

**Comment by sddddd213** [comment]
> 那好，虽然新版脚本残留对页面进行破坏的可能性加剧了，遇到这种问题就硬刷新解决吧。

”刷新解决“的意思是指，没法处理吗？

还有比较好奇【破坏性】是指什么？指脚本重构页面（js和css）的程度吗？

**Comment by MotooriKashin** [comment]
重新页面是在新版页面的基础上进行的，新版页面下的脚本还在运行，如果不加阻止，它们会在全局环境下创建各种污染变量，会对重写后的页面进行破坏，导致各种奇怪的问题。 而那些脚本一旦运行，根本不可能让它们停下来，只能一开始就禁止解析，不让运行。之前使用的`document.open`方法也好，这两天尝试的`window.stop`方法也罢，都是在它们运行前就强行停止解析的。我原以为后者对浏览器扩展的兼容性更好，毕竟IDM下载浮动条都回来了，却没测试过pakku这种`run-at document-end`的情况。

**Comment by sddddd213** [comment]
> 重新页面是在新版页面的基础上进行的，新版页面下的脚本还在运行，如果不加阻止，它们会在全局环境下创建各种污染变量，会对重写后的页面进行破坏，导致各种奇怪的问题。 而那些脚本一旦运行，根本不可能让它们停下来，只能一开始就禁止解析，不让运行。之前使用的`document.open`方法也好，这两天尝试的`window.stop`方法也罢，都是在它们运行前就强行停止解析的。我原以为后者对浏览器扩展的兼容性更好，毕竟IDM下载浮动条都回来了，却没测试过pakku这种`run-at document-end`的情况。

懂了，谢谢解答。更新什么时候收到呢？

**Comment by MotooriKashin** [comment]
更新已经推送了，只不过没加版本号，而且你方才从本地安装脚本已经禁用了更新，还是去greasyfork更新一下好。

**Comment by MotooriKashin** [comment]
测试发现页面出问题的频率有点高了，尤其在专栏和medialist页面。于是进行了调整，新增了一个设置项“重构模式选择”，默认还是阻止DOM的解析，像你这种需求切可以忍受“刷新”页面解决问题的可以选择“兼容”模式。

该更新定于今晚推送。
