### ISSUE TITLE
下载文件扩展名不符

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#231]
浏览器：Firefox 97
问题：下载视频和音频，均为mp4格式，且文件名相同，虽然另存为改一下名字就行，但是还是希望脚本可以赋予正确的文件扩展名。

**Comment by MotooriKashin** [comment]
浏览器自带下载吗？自带下载由于同源策略是无法修改文件名的。

**Comment by MyBlueHorizon** [comment]
是的...我记得以前b站给的格式对的，还以为是脚本问题...
另外拦截视频既然打开了，能否直接在播放页明显处添加呼出下载按钮
