### ISSUE TITLE
看不了视频

### ISSUE THREAD

**Issue by 3arrow** [MotooriKashin/Bilibili-Old#232]

**Comment by MotooriKashin** [comment]
抱歉，能不能详细描述一下你的问题，提供一点控制台信息什么的。

**Comment by 3arrow** [comment]
这儿




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MotooriKashin/Bilibili-Old"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月13日(星期天) 中午1:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MotooriKashin/Bilibili-Old] 看不了视频 (Issue #232)





 抱歉，能不能详细描述一下你的问题，提供一点控制台信息什么的。
 
 
   
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MotooriKashin** [comment]
额，Github不支持以右键附件的形式评论。
