### ISSUE TITLE
关于赛事看点标记的建议

### ISSUE THREAD

**Issue by DyGriin** [MotooriKashin/Bilibili-Old#233]
赛事看点标记会遮挡视频，目前做成类似新版进度条的自动隐藏机制体验不太好，看看能否做下改善。
比如说做成类似播放器音量清晰度弹出卡片的机制，鼠标进入进度条区域时弹出标记，离开进度条和绿框区域时隐藏
![image](https://user-images.githubusercontent.com/98444140/153747309-84e65382-f338-4003-aef0-957738ce047d.png)

另外一些不带图标的赛事看点会显示异常，比如[av839942758?p=2](https://www.bilibili.com/video/av839942758?p=2)

**Comment by wly5556** [comment]
感谢建议！自动隐藏的机制就按照你说的改
对于不带图标的赛事看点，目前想到的办法是用一个金色的圆点作为标志，像这样看起来怎么样？
![@BR(2UQK0C@8% NMEP($UKP](https://user-images.githubusercontent.com/61644753/153755997-bca75313-2ee1-4ffd-b231-016f22adf3d0.png)

**Comment by DyGriin** [comment]
其实只要不显示成裂图就行。要说的话感觉在此基础上把图形底部弄尖一点会比较好

**Comment by wly5556** [comment]
提交了改动后的版本，可以去更新看看效果

![3NGV~G3P@4 OC`C{5I)LI%7](https://user-images.githubusercontent.com/61644753/153867925-8434e57f-0809-4a52-b8ca-ad9a6175b6f2.png)
