### ISSUE TITLE
Bilibili-Evolved 冲突：刷出大量问题请求并卡死

### ISSUE THREAD

**Issue by cqjjjzr** [MotooriKashin/Bilibili-Old#234]
# 版本与环境

- Windows 10 Version 21H1 (Build 19043.1526)
- Chrome 98.0.4758.82
- TamperMonkey 4.14
- Bilibili-Old 7.0.3
- Bilibili-Evolved v2.1.3-2-g13300f13b

# 设置

## Bilibili-Old

设置项中全部关闭，问题仍存在。

## Bilibili-Evolved

（根据我的有限观察），仅在 Bilibili-Evolved 处打开「下载视频」功能时出现这个问题。

# 问题

问题在更新到 Bilibili-Evolved 2 后出现，现象为在同时启用插件时，在任意插件页打开 Bilibili-Evolved 的「功能」面板时，Bilibili-Evolved 产生大量错误请求：

![image](https://user-images.githubusercontent.com/6622592/153755986-ecb68f80-f9a1-4918-a2c8-5aeedbaee8d2.png)

下面为两种请求的 Call Stack

![image](https://user-images.githubusercontent.com/6622592/153757003-71c2f3e0-6b6b-404f-826a-46b25f7d04a9.png)

![image](https://user-images.githubusercontent.com/6622592/153757023-47fad2a3-3280-461d-a022-d2e6d64b8a29.png)

同时页面卡死。重启 Chrome 后发现 IP 被 bilibili 临时封禁（上述两 API 返回 412 错误）。

# 临时解决方案

关闭 Bilibili-Evolved 的下载视频功能。

# 分析

目前我这边没有两个插件的开发环境，没有办法做很深入的分析，可能和 B-E 注册的一个自定义事件 `videoChanged` 有关。考虑到关闭 Bilibili-Old 所有功能后问题仍存在，可能问题出在 Bilibili-Old 始终启用的一部分功能中（即不可通过设置关闭的功能）。

**Comment by MotooriKashin** [comment]
稍微分析了一下，因为本脚本默认启用了xhrhook，所以所有的ajax请求都会经过本脚本。确切的说只hook了`XMLHttpRequest.open`，只是在open时本脚本会检查一下url，然后原封不动返还给了原生`XMLHttpRequest`，本脚本甚至没有碰过`XMLHttpRequest.send`，理论上来所有请求来这一趟根本不会产生任何问题，事实上也确实如此，页面中所有请求都没有发生类似问题。
所以问题可能出在B-E那边，我也没有B-E的开发环境，她那些混淆过的代码我也实在无从下手，只不过我觉得即使一个请求如果失败了（我不知道是不是失败了，因为B-E没有任何提示就立刻重新请求了），也不该无限制地死循环请求下去，至少得有个度吧，这点可能需要去B-E那里提issue吧。

**Comment by cqjjjzr** [comment]
是否可能是 Bilibili-Old 对页面上所做的某种修改造成了“循环修改”呢（如改了某 DOM 节点触发事件 B-E 的监听器，监听器做的修改又触发了 B-O 的事件）？但看调用栈也没有无限递归的迹象。同时因为关了播放页 refactor 后问题依旧，可能是某个无法在设置中关闭的功能造成的，这一定程序上可以缩小范围。

我先去那边开个 Issue

**Comment by MotooriKashin** [comment]
> 是否可能是 Bilibili-Old 对页面上所做的某种修改造成了“循环修改”呢

关闭了所有功能后脚本不会对页面做任何修改，处理依旧添加一个设置入口。被脚本所有运行的功能都可以在source面板找到。
![image](https://user-images.githubusercontent.com/60416767/153787880-04d2ee6e-dd2c-4435-b355-ce2040c2a658.png)

**Comment by cqjjjzr** [comment]
考虑到 the1812/Bilibili-Evolved/3005 中的讨论，是否是 `src/include/EmbedPlayer.ts` 里修改了 `window.cid` 导致？

**Comment by MotooriKashin** [comment]
的确有可能，如果B-E监听了cid的话，我吃完饭测试一下。

**Comment by MotooriKashin** [comment]
已提交兼容性更改，编译发布可能会在今天晚些时候等其他提交一起发布，感谢反馈！
