### ISSUE TITLE
观看一些高画质（大会员画质）视频时无法缓冲

### ISSUE THREAD

**Issue by MSGOOHPA** [MotooriKashin/Bilibili-Old#235]
看观看一些高画质（大会员画质）的视频时，缓冲一点点就不缓冲了，然后视频就卡在那了，还提示降画质试试，此时打开bilibili播放器的详细信息会发现 Network 不更新了。这个问题似乎存在很长时间了，不管是 avc、hevc 还是 av1 编码的视频，只要是高画质（大会员画质）视频，就都有这个问题，我把别的脚本还有广告拦截插件关了还是一样。

系统：Windows 11 专业工作站版 22543.1000
浏览器：Microsoft Edge 98.0.1108.50
![屏幕截图 2022-02-13 220055](https://user-images.githubusercontent.com/40914017/153757251-a8d07506-2a82-43e1-b080-3d530caa99d5.png)
![屏幕截图 2022-02-13 220006](https://user-images.githubusercontent.com/40914017/153757269-b941e2b4-60f0-49f7-86fd-dc4e287cef3e.png)

**Comment by MotooriKashin** [comment]
这个莫非是上次调整4k缓存大小导致的问题？ @wly5556   
缩短了缓存时间但播放器并不知道缩短了，以为后面还有缓存——我猜的。

**Comment by MSGOOHPA** [comment]
> 这个莫非是上次调整4k缓存大小导致的问题？ @wly5556   
> 缩短了缓存时间但播放器并不知道缩短了，以为后面还有缓存——我猜的。

缓冲进度条缓冲了一段之后突然往回缩了一点，然后播放到这里的时候就卡了

**Comment by wly5556** [comment]
刚更新的版本里面解决了旧播放器播放高画质视频的一个bug，但是我不太确定这个改动是否能解决你遇上的问题，如果有改善就最好了

**Comment by MSGOOHPA** [comment]
> 刚更新的版本里面解决了旧播放器播放高画质视频的一个bug，但是我不太确定这个改动是否能解决你遇上的问题，如果有改善就最好了

我试了一下，缓冲这块的问题已经解决啦，不过还有个播放上的问题，我先去提一个新 Issues ？
