### ISSUE TITLE
播放页视频无法播放

### ISSUE THREAD

**Issue by Kongchenglige** [MotooriKashin/Bilibili-Old#236]
情况如图所示，有时候会变成这样，较少情况下会正常运行，已多次尝试硬刷新
![image](https://user-images.githubusercontent.com/35166074/153918311-310ea19d-957f-4269-bbd7-239e05537e15.png)
控制台
![image](https://user-images.githubusercontent.com/35166074/153918630-91f061cf-fe48-4d8a-b28a-32cdbdfe8b6a.png)
版本信息:
Tampermonkey v4.14
Chrome 98.0.4758.82(64bit)
插件版本 7.0.3

**Comment by MotooriKashin** [comment]
7.0.4版本在设置-通用-页面重构模式中提供了"极端"模式可供选择，该模式回归了经典的重写方案，效果最好，只是又回到了那个与部分脚本和浏览器扩展不兼容的时代，你可以测试一下。

**Comment by Kongchenglige** [comment]
经测试，似乎是扩展程序Night Eye (ID:alncdjedloppbablonallfbkeiknmkdi)导致的无法加载，关闭后在各模式下均正常加载

**Comment by MotooriKashin** [comment]
看来各种扩展对于旧版页面支持都不太好，提高了与她们的兼容性反而出现了一大堆问题・_・
