### ISSUE TITLE
默认模式无法加载视频，兼容和极端模式可以

### ISSUE THREAD

**Issue by StackExplode** [MotooriKashin/Bilibili-Old#237]
如下图：`https://static.hdslb.com/player/js/dash.mediaplayer.min.js` 报404
其他插件都关了也没用。。。
![QQ拼音截图未命名](https://user-images.githubusercontent.com/19866685/153998600-307ace70-7403-47dc-8238-cca00729dc89.png)
![image](https://user-images.githubusercontent.com/19866685/153998681-f901b3e2-1b7d-4c20-b5e7-2a087434bb98.png)

**Comment by MotooriKashin** [comment]
这个问题从来没见过，而且所请求的脚本也是见所未见，看起来是前面一系列报错才导致后面的请求……  
也是奇怪默认模式不过比兼容模式多了个`window.stop`，理论上来说应该避免了很多问题才是，与该问题联系不起来，会不会是特例问题？既然其他模式能用就暂时用其他模式吧，看看会不会有其他线索。

**Comment by StackExplode** [comment]
我又仔细测试了一下，是另一个反广告插件的锅，之前控制变量测试时忘记关了。。。

**Comment by StackExplode** [comment]
我又发现新的问题了，载入本地文件功能还是报错：
![image](https://user-images.githubusercontent.com/19866685/154030932-25279225-f2af-4195-a7ea-84bf1d05cc4b.png)

**Comment by MotooriKashin** [comment]
> 我又发现新的问题了，载入本地文件功能还是报错： ![image](https://user-images.githubusercontent.com/19866685/154030932-25279225-f2af-4195-a7ea-84bf1d05cc4b.png)

感谢反馈，已修复。

**Comment by StackExplode** [comment]
感谢您及时的修复。:beer:
