### ISSUE TITLE
最近一次更新后，新页面的弹幕字体总会被重置为黑体

### ISSUE THREAD

**Issue by Reisen-U** [MotooriKashin/Bilibili-Old#24]

**Comment by MotooriKashin** [comment]
未能复现你说的问题，能不能提供一下操作过程？  
已试过av-->av、av-->bangumi、关闭旧版页面刷新、关闭脚本刷新、关闭浏览器刷新，都没有出现问题  
如果有报错的话还请提供一下报错数据

ps：播放器设置数据脚本的确有动，就是在页面载入时判断该数据是否被新版播放器刷写过，因为新版播放器的设置数据不完全兼容旧版播放器。如果没被新版播放器动过，那么脚本只会进行备份而不会做任何修改。

**Comment by Reisen-U** [comment]
没有错误报告
  不加载任何插件和脚本的情况下打开一个视频，更改弹幕字体，刷新页面后弹幕字体仍然是刚改的字体
  只开启旧播放页脚本，打开视频，更改弹幕字体，刷新页面后弹幕字体被恢复为默认值
===============================
在我写下这些之后，又新装了chrome试了试，问题没了.怪。
我使用的是Microsoft Edge Dev 86.0.608.2

**Comment by Reisen-U** [comment]
===============================
没有错误报告
不加载任何插件和脚本的情况下打开一个视频，更改弹幕字体，刷新页面后弹幕字体仍然是刚改的字体
只开启旧播放页脚本，打开视频，更改弹幕字体，刷新页面后弹幕字体被恢复为默认值
在我写下这些之后，又新装了chrome试了试，问题没了.怪。
我使用的是Microsoft Edge Dev 86.0.608.2

**Comment by MotooriKashin** [comment]
这。最新版没有改过播放器设置，所以之前的版本真的没问题吗？或不会是浏览器自动更新导致某些功能失效了？  
目前怀疑是`GM_setValue`命令出了问题，烦请再测试一下：
   + 修改播放器设置中的“自动换P”是否也会被重置为默认
   + 修复本脚本中任意设置选项是否也会被重置为默认

**Comment by MotooriKashin** [comment]
刚测试了一下最新版的Microsoft Edge Dev也无法复现你说的问题（管理器tampermonkey
![2020-08-25_185036](https://user-images.githubusercontent.com/60416767/91165930-23849b80-e704-11ea-860e-510da45bb1eb.png)
）

**Comment by Reisen-U** [comment]
我重置了脚本的默认设置已经好了orz

**Comment by Reisen-U** [comment]
不过的确是这个版本更新后出现的，既然已经好了就不管了orz

**Comment by MotooriKashin** [comment]
这还真是怪事。。。不管没事就好


来自 魅族 16th
