### ISSUE TITLE
首页头图在文档宽度大于 1895px 时有缝隙

### ISSUE THREAD

**Issue by Hibanaw** [MotooriKashin/Bilibili-Old#241]
![图片](https://user-images.githubusercontent.com/61813396/154446513-03245a72-400b-4516-924a-6713558e7fdb.png)

**Comment by MotooriKashin** [comment]
设置里切换一下重构模式还会复现吗，我用最新版Firefox测试好像没发现类似问题。

**Comment by Hibanaw** [comment]
极端模式，在隐私窗口中可复现？
![图片](https://user-images.githubusercontent.com/61813396/154459282-b5bf6923-54e5-4544-b124-3b5b1c80ad16.png)
这里 width 为什么是1895？

**Comment by MotooriKashin** [comment]
不太清楚，我现在没法调试。你可以切换到source标签，左侧bilibili-old/do/banner.js里有源码，copy自B站header.js，印象中就是视频的宽度？

**Comment by MotooriKashin** [comment]
> 还有一个问题就是为什么这个 banner 有三个 layer？

这个动图就是个三层的动画，所以有三层。
![image](https://user-images.githubusercontent.com/60416767/154625461-dd55f638-2d6c-4eca-b37e-e92abd65b527.png)

意思时在chrome中无法复现？
```
   const video = document.createElement('video');
   video.muted = true;
   // video.autoplay = true
   video.loop = true;
   video.src = url;
   video.playsInline = true;
   video.style.objectFit = 'cover'; // 元素尺寸大于视频实际尺寸时放大
   this.resources[index] = video;

   // 视频需要添加到dom树才能获取宽高
   video.width = 0
   video.height = 0
   document.body.appendChild(video)
```
看了下源码及注释，这个`video.style.objectFit = 'cover'`应该有无视视频实际尺寸的作用，难道只在chrome下有效？

**Comment by Hibanaw** [comment]
chrome 下也有这个问题的，之前没有尝试



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MotooriKashin/Bilibili-Old"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月18日(星期五) 中午1:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MotooriKashin/Bilibili-Old] 首页头图在firefox下有缝隙 (Issue #241)





  
还有一个问题就是为什么这个 banner 有三个 layer？
  
这个动图就是个三层的动画，所以有三层。
 
 
意思时在chrome中无法复现？
    const video = document.createElement('video');    video.muted = true;    // video.autoplay = true    video.loop = true;    video.src = url;    video.playsInline = true;    video.style.objectFit = 'cover'; // 元素尺寸大于视频实际尺寸时放大    this.resources[index] = video;    // 视频需要添加到dom树才能获取宽高    video.width = 0    video.height = 0    document.body.appendChild(video)  
看了下源码及注释，这个video.style.objectFit = 'cover'应该有无视视频实际尺寸的作用，难道只在chrome下有效？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hibanaw** [comment]
![图片](https://user-images.githubusercontent.com/61813396/154628847-ca66d144-8187-4442-8941-1ea092dab617.png)

**Comment by Hibanaw** [comment]
> 这个动图就是个三层的动画，所以有三层。

这是原版首页
![图片](https://user-images.githubusercontent.com/61813396/154631594-4a6487ea-c4ba-4152-8d21-bdd6baa6fde8.png)
离谱了，这里 width 为什么是 2006？？

**Comment by Hibanaw** [comment]
> 这是原版首页 ![图片](https://user-images.githubusercontent.com/61813396/154631594-4a6487ea-c4ba-4152-8d21-bdd6baa6fde8.png) 离谱了，这里 width 为什么是 2006？？

可能是想做一个动态banner出现时候的放大效果？🤔

**Comment by Hibanaw** [comment]
一个很玄学的事情，现在第一次加载的时候是正常的，但是过一段时间回来就又会有缝隙？
可以稳定复现，但我还没搞懂触发条件
![图片](https://user-images.githubusercontent.com/61813396/154964388-9beb77d6-de3f-4b3e-b4e6-c50866de612d.png)
过了一会
![图片](https://user-images.githubusercontent.com/61813396/154964990-a202443f-5a9d-43b1-84ab-ba2e69fdbdf5.png)

**Comment by MotooriKashin** [comment]
已将视频缩放比固定，暂时应该不会有问题了，大概在今晚推送。
