### ISSUE TITLE
使用此脚本最新版后“哔哩哔哩旧版（bilibili.com）播放器调整”脚本寄了

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#242]
![image](https://user-images.githubusercontent.com/77530593/154481442-705216d5-d3d9-4fd8-b0cc-411581796ec1.png)
（别问我为什么我还有这脚本）
![image](https://user-images.githubusercontent.com/77530593/154481586-23b02f45-80a5-4295-a4d8-8cf0d7ebca28.png)

**Comment by followmypeach** [comment]
还发现一个问题 就是播放器右端的俩按钮消失了

**Comment by followmypeach** [comment]
顺便问下 有恢复播放器旧版通知顶栏的选项么？

**Comment by MotooriKashin** [comment]
> 使用此脚本最新版后“哔哩哔哩旧版（bilibili.com）播放器调整”脚本寄了

为什么我还有这……这脚本是做什么的？设置里将重构模式调整为“极端”基本就是旧版的实现了，你看看有没有效果。

> 还发现一个问题 就是播放器右端的俩按钮消失了

那两个按钮本身也没什么意义了，精简播放器相关代码时直接去掉了，应该没什么影响吧？

> 顺便问下 有恢复播放器旧版通知顶栏的选项么？

播放器通知一直找不到什么完美的替代品，所以临时禁用了，的确不太好看，直接改回来吧。

**Comment by MotooriKashin** [comment]
> [哔哩哔哩旧版（bilibili.com）播放器调整.zip](https://github.com/MotooriKashin/Bilibili-Old/files/8095657/bilibili.com.zip) 请你试试 我语言组织能力不是很行

调试了一下，原来这脚本是根据那两个按钮定位的，需要我找回来吗？

**Comment by Hibanaw** [comment]
> 播放器通知一直找不到什么完美的替代品，所以临时禁用了，的确不太好看，直接改回来吧。

请问可以使用热门搜索吗
https://api.bilibili.com/x/web-interface/search/default

**Comment by MotooriKashin** [comment]
> 
> 请问可以使用热门搜索吗  https://api.bilibili.com/x/web-interface/search/default

已替换为新番推荐，是否需要提供一个选项以允许换为热搜？

**Comment by Hibanaw** [comment]
> > 请问可以使用热门搜索吗  https://api.bilibili.com/x/web-interface/search/default
> 
> 已替换为新番推荐，是否需要提供一个选项以允许换为热搜？

其实不空着就好啦都可以

**Comment by followmypeach** [comment]
> > [哔哩哔哩旧版（bilibili.com）播放器调整.zip](https://github.com/MotooriKashin/Bilibili-Old/files/8095657/bilibili.com.zip) 请你试试 我语言组织能力不是很行
> 
> 调试了一下，原来这脚本是根据那两个按钮定位的，需要我找回来吗？

我觉得你可以把反馈按钮导向你的github上的issues

**Comment by MotooriKashin** [comment]
> 我觉得你可以把反馈按钮导向你的github上的issues

旧版该是什么样，还是原样保留吧。

**Comment by meiruitesi** [comment]
> > 请问可以使用热门搜索吗  https://api.bilibili.com/x/web-interface/search/default
> 
> 已替换为新番推荐，是否需要提供一个选项以允许换为热搜？

建议直接把顶部通知这个原有的设置换成接口选择（）
![QQ截图20220220181419](https://user-images.githubusercontent.com/84609642/154837942-f6317698-5da2-42b6-860b-839079a4eb19.png)

**Comment by MotooriKashin** [comment]
> 建议直接把顶部通知这个原有的设置换成接口选择（）

旧版页面原有的东西其实我不大乐意修改覆盖，都是回忆啊，还是想尽可能保留页面原有的样子。接口的话还是做在设置界面吧，不过为那个齿轮添加一个点击事件直达对应的设置项却是可以。

**Comment by Hibanaw** [comment]
> 旧版页面原有的东西其实我不大乐意修改覆盖，都是回忆啊，还是想尽可能保留页面原有的样子。接口的话还是做在设置界面吧，不过为那个齿轮添加一个点击事件直达对应的设置项却是可以。

不改文字，但“系统通知”对应搜索推荐，“新番通知”对应新番，“新闻”对应首页热门（或者其他顺序）呢

**Comment by meiruitesi** [comment]
> > 旧版页面原有的东西其实我不大乐意修改覆盖，都是回忆啊，还是想尽可能保留页面原有的样子。接口的话还是做在设置界面吧，不过为那个齿轮添加一个点击事件直达对应的设置项却是可以。
> 
> 不改文字，但“系统通知”对应搜索推荐，“新番通知”对应新番，“新闻”对应首页热门（或者其他顺序）呢

也行（）
