### ISSUE TITLE
播放器彻底寄了

### ISSUE THREAD

**Issue by 4li77l3n00b** [MotooriKashin/Bilibili-Old#245]
![截屏2022-02-19 上午12 25 04](https://user-images.githubusercontent.com/31160627/154722303-6f70bb7e-7e31-4314-93ca-7b5ec36a9b90.png)
完全加载不出来
以下为全部的报错
![截屏2022-02-19 上午12 27 36](https://user-images.githubusercontent.com/31160627/154723344-c99bb686-f5cb-4180-bc80-e78e787b7514.png)
![截屏2022-02-19 上午12 28 25](https://user-images.githubusercontent.com/31160627/154723343-18fac90e-cf24-4482-92b2-336f42e69697.png)
![截屏2022-02-19 上午12 28 51](https://user-images.githubusercontent.com/31160627/154723345-95ccc935-9fe6-42d7-9128-2a2b0046b537.png)
![截屏2022-02-19 上午12 29 28](https://user-images.githubusercontent.com/31160627/154723352-9ca0842d-5142-4c13-885a-717cdcf825d7.png)
![截屏2022-02-19 上午12 29 45](https://user-images.githubusercontent.com/31160627/154723365-c0a6278b-f9ec-45cd-aea0-09839e7016a9.png)
![截屏2022-02-19 上午12 30 00](https://user-images.githubusercontent.com/31160627/154723381-82ee5bc4-5916-4d9c-b0cd-52bafee69518.png)

**Comment by MotooriKashin** [comment]
这种情况应该是resource资源下载失败（jsdelivr），可以在设置里关闭“原生脚本托管”试试。

**Comment by 3arrow** [comment]
> 这种情况应该是resource资源下载失败（jsdelivr），可以在设置里关闭“原生脚本托管”试试。

哪里

**Comment by Hibanaw** [comment]
歪个楼，这是 Linux 吗，请问下你有管理过 Chromium 系的字体吗？Chromium 的 sans-serif 中文字体默认是 simsun 让我很难办...

**Comment by MotooriKashin** [comment]
没用过linux👀

**Comment by 4li77l3n00b** [comment]
蒽，现在又有了，大概是连接问题
