### ISSUE TITLE
视频子分区显示了主分区的名称

### ISSUE THREAD

**Issue by DyGriin** [MotooriKashin/Bilibili-Old#246]
一些分区视频的子分区显示成了主分区(图来自[#188](https://github.com/MotooriKashin/Bilibili-Old/issues/188))，像动画和鬼畜大区下面的原生脚本有定义的子分区都有这个问题(如动画-手办区就正常)
![image](https://user-images.githubusercontent.com/61813396/154689981-9ce6555f-2222-4a10-9456-0a4e0cbdfa6c.png)
脚本还没完全加载的时候一度是显示正确分区的
![image](https://user-images.githubusercontent.com/98444140/154804050-a5f68f93-f967-40ba-921c-258e3c91042f.png)
下断点发现`API.tid`在`video.b1b7706abd590dd295794f540f7669a5d8d978b3.js`加载之后变成了大区的id，然后触发分区修正导致出错。但具体的位置尝试在js里面加断点和给`API.tid`加set hook都跟不到。
加载前：
![image](https://user-images.githubusercontent.com/98444140/154802488-e76b3b41-e2e6-4c34-a314-b48f104ae658.png)
加载后：
![image](https://user-images.githubusercontent.com/98444140/154802500-abc6223f-435d-4843-a99b-bb3055ce74cc.png)

奇怪的是，把代码`API.tid`变量换成别的名字(比如`ttid`)，编脚本再运行又变正常了。这边试了chrome和基于chromium的浏览器都有这个问题。

**Comment by MotooriKashin** [comment]
调整了`API`上属性获取优先级，并且不再主动代为写入全局变量，以避免获取到window下的错误tid
