### ISSUE TITLE
在有合集的 av 页面也使用播单播放器？

### ISSUE THREAD

**Issue by Hibanaw** [MotooriKashin/Bilibili-Old#247]
![图片](https://user-images.githubusercontent.com/61813396/154827014-50bbe6c8-4c4d-4458-9ce1-0104d7825275.png)

**Comment by MotooriKashin** [comment]
好提议！

**Comment by DyGriin** [comment]
最近研究代码刚好也尝试做了一下合集的显示。不过当时想到的是类似分P一样的标签，后面考虑播放器连播的时候才发现直接往播放器里面传playlist会比较简单。
不过单纯显示成播单的话，播单的标签大小对于一些比较大的合集可能不是那么友好，而且换P是自动播放的。
另外还要考虑的是换P之后视频页的刷新，包括脚本里面的点赞、合作列表和分区修正功能。

我这边做的放在这个[仓库](https://github.com/DyGriin/Bilibili-Old/tree/seasontest)。目前做了分P标签方式显示（如图）和换P及浏览器前进/后退时的页面刷新，主要剩下播放器相关的修改还没做。如果可以的话我这边pr过来继续开发。
![image](https://user-images.githubusercontent.com/98444140/154836088-abd3f9d1-a371-42cf-8b3d-2ba79199cad3.png)

另外像[av332784259](https://www.bilibili.com/video/av332784259)里面分章节的合集不知道有没有什么比较好的显示方式。
![image](https://user-images.githubusercontent.com/98444140/154836213-3baf19f4-06a9-4087-8bff-569280b33619.png)

**Comment by MotooriKashin** [comment]
> 后面考虑播放器连播的时候才发现直接往播放器里面传playlist会比较简单。

我也觉得基于playlist比较简单，且不是简单地传递playlist到播放器里，而是项[medialist](https://www.bilibili.com/medialist/play/1868902080?aid=978659748&cid=497459110)一样基于playlist完全重构，切p、页面更新完全由原生脚本自己负责。(详见medialist.ts)  

> 我这边做的放在这个[仓库](https://github.com/DyGriin/Bilibili-Old/tree/seasontest)。目前做了分P标签方式显示（如图）和换P及浏览器前进/后退时的页面刷新，主要剩下播放器相关的修改还没做。如果可以的话我这边pr过来继续开发。

没什么毛病，除了播放按钮旁边那个切p按钮（包括自动切p）不知道怎么实现（可能要修改bilibiliplayer.js？），总之欢迎pr！

> 另外像[av332784259](https://www.bilibili.com/video/av332784259)里面分章节的合集不知道有没有什么比较好的显示方式。

没有，除非在旧版页面完全重写一个这种列表，或者参考拜年祭页面直接炸掉新版播放器换旧版嵌入式播放器进去，不过那就不像旧版页面了。

**Comment by DyGriin** [comment]
> 我也觉得基于playlist比较简单，且不是简单地传递playlist到播放器里，而是像[medialist](https://www.bilibili.com/medialist/play/1868902080?from=space&business=space&sort_field=pubtime)一样基于playlist完全重构，切p、页面更新完全由原生脚本自己负责。(详见medialist.ts)

看了一下确实各方面都会简化(用av.html的话可能还要想办法换掉播放器的创建参数)，不过url会不可避免多出一段类似`?aid=000&cid=000`这样的内容。

下一P按钮的话比较简单的方式是给播放器创建参数传个playlist；或者把播放器获取分P信息的请求给hook掉。
不管哪种方式基本都免不了要改`bilibiliPlayer.js`，比如播单里面的列表链接要换成合集的链接，并且保留推荐视频显示等等。

**Comment by MotooriKashin** [comment]
> 不过url会不可避免多出一段类似`?aid=000&cid=000`这样的内容。

那个切p后延时改回去就行，原始url备份在`API.path`，`history.replaceState`可以无任何毒副作用修改url，我留着`?aid=000&cid=000`只是方便观察切p，现在看来却不利于刷新。

**Comment by DyGriin** [comment]
> 那个切p后延时改回去就行，原始url备份在`API.path`，`history.replaceState`可以无任何毒副作用修改url

还要考虑原生脚本如何处理浏览器前进/后退的情况，如果是直接通过url判断aid和cid的话（像av页分P的popstate就是通过url中的`p=`获取P号的）可能会变得比较麻烦

**Comment by MotooriKashin** [comment]
我倒是没想过把播单切P记录到浏览器历史记录里，那看来还得保留aid,cid，不过这也没什么关系吧，又不是垃圾参数，就跟普通av页保留p参数一样，合集页面保留aid,cid合情合理顺理成章。

**Comment by DyGriin** [comment]
下一P按钮的这边已经做好了，昨天看`medialist.ts`的时候突然有了想法。之前一直不知道到有xhr/jsonp hook这么个东西。

`bilibiliPlayer.js`对分P视频的下一P按钮和播放器换P是通过API请求结果判断的。
判断下一P有无是`/x/player.so?aid=&cid=`；把response里面`has_next`标签的内容改成1就可以把按钮显示出来了
![image](https://user-images.githubusercontent.com/98444140/154904131-cd4284fd-1a12-4422-8271-2fe04cd1dc52.png)

换P获取分P列表的API是不怎么常用的`/x/player/pagelist`；返回的列表里面是没有`aid`字段的(可以执行`window.player.getPlaylist()`手动获取)。
然后利用这一点，在hook中伪造分P列表并添加`aid`字段；然后把`bilibiliPlayer.js`里面换P的相关代码改成有aid字段切新的aid，没有就用当前aid（分P的默认处理）。做完发现甚至不怎么需要改`bilibiliPlayer.js`。

**Comment by MotooriKashin** [comment]
`xhr/jsonp hook`是在支持新版弹幕时添加的，跟随需求增加改版多次，未在开发者文档中说明，**值得注意的是可选第四个参数，可能需要指定为false，如果这个请求会切p后还会请求的话，因为默认只hook一次。**
