### ISSUE TITLE
弹幕帧率低，可以看出卡顿

### ISSUE THREAD

**Issue by Hibanaw** [MotooriKashin/Bilibili-Old#249]
弹幕帧率低，可以看出卡顿，在全屏模式尤为明显
原版（新版）播放器一切正常

**Comment by MotooriKashin** [comment]
额，我这渣配置看两者都有点卡顿，新版尤为明显。

**Comment by wly5556** [comment]
有没有能稳定看出差异的测试视频呢？新、旧播放器的弹幕渲染应该是同一套方法，在css的层面上相差不大。或许新版加了什么神秘优化？

**Comment by Hibanaw** [comment]
环境是 firefox 97
比如 https://www.bilibili.com/video/av46900196
或者更明显的是https://www.bilibili.com/video/av810872
都不限制同屏密度，不透明度100%
旧版播放器弹幕层会卡死，但新版播放器只有轻微的卡顿

**Comment by Hibanaw** [comment]
![图片](https://user-images.githubusercontent.com/61813396/155740231-7f22e03f-bd33-4ea3-8232-03fc463751ef.png)
旧版播放器弹幕渲染不使用硬件加速？
