### ISSUE TITLE
评论区消失

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#25]
如题
浏览器版本 Firefox 80

**Comment by MotooriKashin** [comment]
这和 #22 其实是同一个问题，评论区包含在主体框架中，主题框架异常评论区自然不会安然

**Comment by MyBlueHorizon** [comment]
这个就有点…有的页面是播放器正常 有的是评论区正常…

**Comment by MotooriKashin** [comment]
av页不再隐藏播放器后，播放器是必然能加载出来的，评论等其他部分随缘
