### ISSUE TITLE
点赞按钮可以改一下吗

### ISSUE THREAD

**Issue by meiruitesi** [MotooriKashin/Bilibili-Old#251]
![image](https://user-images.githubusercontent.com/84609642/154882194-20655f64-a0c8-4a04-a3ad-a86f7f050acb.png)
未激活状态个人觉得还是以前的粉色轮廓比较协调
而且点击后的图标的左侧有一点没有与点击前对齐
![image](https://user-images.githubusercontent.com/84609642/154882240-ee71d5e7-d4bf-424c-ac0b-dcd16b299ed9.png)

**Comment by meiruitesi** [comment]
有一说一，线条的粗细能不能和硬币和收藏一致，现在这样总感觉有点违和。。。。
![image](https://user-images.githubusercontent.com/84609642/154902309-0c1540a9-7a24-411a-84a5-5853039f0271.png)

**Comment by MotooriKashin** [comment]
目前使用的是“文字”+阴影实现的（copy的新版），稍微调整了一下，粗细实在没办法，其实最好还是使用svg，可惜新版不用。

**Comment by meiruitesi** [comment]
> 目前使用的是“文字”+阴影实现的（copy的新版），稍微调整了一下，粗细实在没办法，其实最好还是使用svg，可惜新版不用。

那就用svg吧（）

**Comment by MotooriKashin** [comment]
图片不好储存，现在jsdelivr cdn部分地区又访问不畅，有svg推荐吗，我找不到合适素材？

**Comment by meiruitesi** [comment]
[https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5/discussions/87629](url)
（这个“花生乔贝利”就是我（））

**Comment by MotooriKashin** [comment]
已修改为svg形式

**Comment by MotooriKashin** [comment]
其实还想像其他两个图标一样添加鼠标焦点的互动动画效果及一(xia)键(ci)三(yi)连(ding)，可惜css不拿手，欢迎有兴趣的pr！
