### ISSUE TITLE
评论区楼层消失，可以改回来吗？

### ISSUE THREAD

**Issue by sddddd213** [MotooriKashin/Bilibili-Old#253]
![image](https://user-images.githubusercontent.com/38841494/154931492-41a4e355-afe7-4ae2-8f92-2722def37f1b.png)
如图所示。
现在只有在评论的回复中可以看到，单个用户的评论楼层不显示。

**Comment by sddddd213** [comment]
啊/(ㄒoㄒ)/~~，陈睿你坏事做尽🙁

**Comment by vsouild** [comment]
乐(｡･∀･)ﾉﾞ
https://www.bilibili.com/read/cv10636844

**Comment by MyBlueHorizon** [comment]
所以是旧版评论接口出问题了吗，最近旧版手机端也加载不出评论了？

**Comment by MotooriKashin** [comment]
应该是，参考[B吧讨论](https://tieba.baidu.com/p/7729721954)
