### ISSUE TITLE
nav-menu 分区计数失效？

### ISSUE THREAD

**Issue by Hibanaw** [MotooriKashin/Bilibili-Old#255]
![图片](https://user-images.githubusercontent.com/61813396/155561412-240eea14-0da7-481a-96e8-c3ea13ea52c6.png)

**Comment by MotooriKashin** [comment]
还在啊
![image](https://user-images.githubusercontent.com/60416767/155635227-fa5b8d0e-4a5a-44db-9d0b-6c76b43381b9.png)

**Comment by Hibanaw** [comment]
emmmm，我这里现在也可以了
再出现问题的时候我再 reopen 吧
