### ISSUE TITLE
播放器 卒（火狐）

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#256]
![图片](https://user-images.githubusercontent.com/77530593/155685314-63df9916-abf1-46aa-a2ff-545bb0e8ceb9.png)
使用版本：最新版

**Comment by MotooriKashin** [comment]
就没有任何报错信息吗？

**Comment by followmypeach** [comment]
![图片](https://user-images.githubusercontent.com/77530593/155731339-7706c306-8df9-401a-9a1c-c534828dca31.png)
![图片](https://user-images.githubusercontent.com/77530593/155731305-f1401aed-a964-4765-b0d2-2b45007f3244.png)

**Comment by MotooriKashin** [comment]
未找到有效信息，可能也需要清除缓存+卸载脚本重新安装
