### ISSUE TITLE
播放（高画质）视频时有时候会卡一下

### ISSUE THREAD

**Issue by MSGOOHPA** [MotooriKashin/Bilibili-Old#257]
我之前提了一个 [视频缓冲这块的 Issues](https://github.com/MotooriKashin/Bilibili-Old/issues/235)，现在这个 bug 已经修好啦。
不过随之而来的还有一个 bug，就是在播放（高画质）视频时，有时候视频会卡一下，<strike>我猜测可能是切换 Dash 分片时导致的问题，因为卡顿时视频已经缓冲好了，网络正常，解码这块应该没有把 GPU 硬解单元占满。</strike>这个视频没有分片，我把 hevc 的源下载下来播放也没有出现这个问题。
![Screenshot 2022-02-25 221338](https://user-images.githubusercontent.com/40914017/155729814-12f33b6f-4eea-42fc-a9c1-93bb0fb8980b.png)
![Screenshot 2022-02-25 221045](https://user-images.githubusercontent.com/40914017/155729700-f3a428c2-4bff-4819-bfeb-a523005b1f98.png)
卡顿是在大约 2:35 处左右发生的，也就是截图中 GPU 解码单元负载波动较大的那块。
https://www.bilibili.com/video/av290253551
![Screenshot 2022-02-25 212721_2](https://user-images.githubusercontent.com/40914017/155732462-19e282ef-58c4-46aa-af96-45dacc01289f.png)
![Screenshot 2022-02-25 220235](https://user-images.githubusercontent.com/40914017/155728685-39e22345-3408-4cb1-b06e-0f96e8f4280b.png)
![Screenshot 2022-02-25 220340](https://user-images.githubusercontent.com/40914017/155728651-8a3617e8-fede-476b-b3d3-eef5bc19aad9.png)

**Comment by wly5556** [comment]
如果是解码的瓶颈，视频统计信息的“Dropped Frames”一栏应该会增加，可以去检查下
（上个issue被解决了太好了😋，不过接下来这几个月我可能不太有时间去调试脚本，现在就先找出更多关于这个“卡一下”问题的细节吧。提供多一些信息也方便更多人参与讨论）

**Comment by MSGOOHPA** [comment]
> 如果是解码的瓶颈，视频统计信息的“Dropped Frames”一栏应该会增加，可以去检查下 （上个issue被解决了太好了😋，不过接下来这几个月我可能不太有时间去调试脚本，现在就先找出更多关于这个“卡一下”问题的细节吧。提供多一些信息也方便更多人参与讨论）

我觉得不太可能是解码瓶颈，不过我还是去试着找一下这个问题的细节吧。

> 不过接下来这几个月我可能不太有时间去调试脚本

话说您这是要备战高考了？如果是的话，祝您考上心仪的大学💪

**Comment by wly5556** [comment]
谢谢！！😇
