### ISSUE TITLE
热门评论无法显示楼中楼，找不到设置按钮

### ISSUE THREAD

**Issue by miss1ng** [MotooriKashin/Bilibili-Old#263]
![20220305150006](https://user-images.githubusercontent.com/18642603/156872471-0be79852-3e0a-489f-8d60-c474e1859ba2.jpg)
修改过一次设置按钮的位置后按钮丢失，重装脚本也无法找回设置按钮
系统：Windows 11 Pro 21H2 22000.493
浏览器：Microsoft Edge 99.0.1150.30

**Comment by MotooriKashin** [comment]
重装也没有按钮似乎不太可能，只是重装前要先卸载？卸载后脚本管理器还有个“❌”标签，必须点就去彻底删除。然后再重新安装脚本。
脚本设置模式还有一种贴边隐藏模式，你可能是点了那个导致没有找不到入口图标。
另外图示的评论类型也是开起了很久以前的评论样式，重装之后会恢复正常的。

**Comment by byyxx128** [comment]
Tampermonkey 现在删除脚本不是彻底删除，比如自己手动确认才行。很多新用户可能不知道这个事——
![image](https://user-images.githubusercontent.com/20079289/156908955-22090986-9fe4-499d-9b22-008fdf793cd7.png)
![image](https://user-images.githubusercontent.com/20079289/156908931-c477d26e-5377-42d2-bb43-14f82780e51d.png)

**Comment by miss1ng** [comment]
> 

重装tampermonkey后找回了设置按钮。
旧版评论样式能否支持显示楼中楼回复呢？

**Comment by miss1ng** [comment]
> 重装也没有按钮似乎不太可能，只是重装前要先卸载？卸载后脚本管理器还有个“❌”标签，必须点就去彻底删除。然后再重新安装脚本。 脚本设置模式还有一种贴边隐藏模式，你可能是点了那个导致没有找不到入口图标。 另外图示的评论类型也是开起了很久以前的评论样式，重装之后会恢复正常的。

重装tampermonkey后找回了设置按钮
旧版评论样式能否支持显示楼中楼回复呢？

**Comment by hmjz100** [comment]
点击一下以上为热门评论，查看更多中的“查看更多”即可显示楼中楼。
