### ISSUE TITLE
对分区主页的重构

### ISSUE THREAD

**Issue by DyGriin** [MotooriKashin/Bilibili-Old#268]
最近发现B站这波新版主页改动把分区主页也改了，顶栏和内容都变了，脚本顶栏替换也会失效。 (如https://www.bilibili.com/v/game/)
这个新版主页目前说是在内测中。估计后面还会有别的页面会被改掉。
![image](https://user-images.githubusercontent.com/98444140/158611591-697b4f57-6266-40de-a5b2-369e16ce3053.png)

**Comment by MotooriKashin** [comment]
看起来会是一个大工程（除非它们基础框架基本一样

**Comment by MotooriKashin** [comment]
分区本身变化不大，用不到重构，直接替换了顶栏

**Comment by DyGriin** [comment]
呃，这个新版分区似乎还有一定概率刷不出来。header-v3这个版本我在另一个浏览器刷出来了，的确只变了顶栏。截图提到的版本是这样的：
![image](https://user-images.githubusercontent.com/98444140/158730821-df34c8c7-ae2d-43f2-afb9-38895fa81e30.png)

**Comment by MotooriKashin** [comment]
呃，没见过，B站这是在干什么？为什么同时测试好几个版本！

**Comment by MotooriKashin** [comment]
添加了一个设置项强制修改cookie返回旧版分区主页，重构的事留待后续。
