### ISSUE TITLE
首页资讯区图标丢失

### ISSUE THREAD

**Issue by meiruitesi** [MotooriKashin/Bilibili-Old#269]
![image](https://user-images.githubusercontent.com/84609642/158744555-54a96e6d-a04e-4202-9c50-c95ac707ce12.png)
![image](https://user-images.githubusercontent.com/84609642/158744583-93507dd3-29d3-4735-ad30-1d20ba6e90b4.png)

**Comment by meiruitesi** [comment]
附
![biliNews1](https://user-images.githubusercontent.com/84609642/158744732-9ee2537a-7d59-4035-a567-89ab52c4b2f2.png)

**Comment by meiruitesi** [comment]
简单在审查元素替换了下
![image](https://user-images.githubusercontent.com/84609642/158745165-65d0a44d-d56f-4d36-9cb2-7daa1a7e89b7.png)
建议转成svg以避免图标周围出现残影（）

**Comment by MotooriKashin** [comment]
由于jsdelivr CDN丢失国内isp，放在仓库中可能不再是好方案，有下列替代吗？
1. 首选来自B站官方静态资源站的链接，避免访问问题。
2. svg等可以打包进脚本的纯文本格式图片。
3. 其他国内免费CDN推荐。

**Comment by meiruitesi** [comment]
> 由于jsdelivr CDN丢失国内isp，放在仓库中可能不再是好方案，有下列替代吗？
> 
> 3. 其他国内免费CDN推荐。

这个应该可以参考[隔壁](https://greasyfork.org/zh-CN/scripts/412245-github-%E5%A2%9E%E5%BC%BA-%E9%AB%98%E9%80%9F%E4%B8%8B%E8%BD%BD)（）

**Comment by MotooriKashin** [comment]
使用dataurl替代了，反正图片不大
