### ISSUE TITLE
在2K及以上版本的屏幕顶栏横幅适配有问题

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [MotooriKashin/Bilibili-Old#27]
![QQ截图20200912222844](https://user-images.githubusercontent.com/45261195/92997661-6ab5bd80-f547-11ea-8f43-4508c24ba965.jpg)
关闭脚本后没有这个问题

**Comment by MotooriKashin** [comment]
看来旧版顶栏一直就没有考虑过高分辨率问题，已参考新版顶栏修正了下样式，不知道效果如何  
没有4K显示器，2K也是把手机当显示器调试的(ಡωಡ)hiahiahia～

话说我才发现推送消息打了个错别字！

**Comment by Aira-Sakuranomiya** [comment]
哇 太强了wwww
光速修复

**Comment by MotooriKashin** [comment]
照抄两行CSS还是挺简单的  
感谢反馈！

**Comment by Aira-Sakuranomiya** [comment]
啊对了，我发现在各个分区的顶栏那里还没改(。・ω・。)

**Comment by MotooriKashin** [comment]
举个例子？

**Comment by Aira-Sakuranomiya** [comment]
https://www.bilibili.com/v/kichiku/

**Comment by MotooriKashin** [comment]
不应该啊，我只添加了两行样式，没有特定给主页，主页生效的话其他页面也会生效的，如你举的下图例子
![2020-09-14_154324](https://user-images.githubusercontent.com/60416767/93058656-3dc9ed80-f6a2-11ea-9cda-42a1eb2c4eba.png)

**Comment by MotooriKashin** [comment]
你可以打开控制台，选中同一个element（节点），看看右边style（样式）里有没有那两行

**Comment by Aira-Sakuranomiya** [comment]
啊搞定了，是我TamperMonkey设置有问题=-=

**Comment by MotooriKashin** [comment]
那就好

**Comment by Aira-Sakuranomiya** [comment]
我之前设置的注入模式是即时，现在改成了标准

**Comment by MotooriKashin** [comment]
没测试过那个选项，难道“即时”不会运行？

**Comment by Aira-Sakuranomiya** [comment]
会运行，但是不知道为什么那两条样式没弄进去

**Comment by Aira-Sakuranomiya** [comment]
还有就是有一个建议呀，旧版播放器能不能改成16:9的比例，现在大多数视频都是16:9的

**Comment by MotooriKashin** [comment]
已优化了下样式的注入方式，应该可以解决“即时”注入的问题，需要的话你可以改回去试试  
播放器样式方面，由于旧版播放器和弹幕列表是一个整体，强行要求播放区域16:9其他部分就会变形，而且有些这个脚本的用户（包括我自己）就是喜欢原汁原味旧版的感觉。  
强迫症的话就启用宽屏模式吧，旧版播放器设计好的模式正好是16:9（正常改为16:9的话宽屏也难两全）

**Comment by Aira-Sakuranomiya** [comment]
ok，超棒~
