### ISSUE TITLE
[Bug]账号有会员，但开启脚本导致会员视频无法播放

### ISSUE THREAD

**Issue by wongzeon** [MotooriKashin/Bilibili-Old#270]
**问题详情**
1. 看会员专属的视频的时候，会显示视频无法播放，关闭插件后正常。

2. 浏览器标签的显示标题会变成网址，而非页面的title内容。

**复现步骤**
1. 开启插件播放该页视频 https://www.bilibili.com/bangumi/play/ep213944

**相关截图**
![截图](https://pic.rmb.bdstatic.com/bjh/fa7f10e9c6b39d2bd2d6f55c8104a5dd.png)

![截图2](https://pic.rmb.bdstatic.com/bjh/7ec3cb6eec3dbf052744b7895e01acf2.png)

![截图3](https://pic.rmb.bdstatic.com/bjh/f9877edc02ad0f04cd8c8566e725b403.png)

**运行环境**
 - 操作系统：Windows11 企业版 22000.556
 - 浏览器：MS Edge 99.0.1150.46
 - 脚本管理器：Tampermonkey 4.16.6156
 - 脚本版本：7.1.8

**Comment by MotooriKashin** [comment]
已修复，请更新试试

**Comment by wongzeon** [comment]
解决了，目前没有问题
