### ISSUE TITLE
[Bug]搜索页面还是新版界面

### ISSUE THREAD

**Issue by redapple0204** [MotooriKashin/Bilibili-Old#271]
RT，
![image](https://user-images.githubusercontent.com/16254644/159124458-5f10cd33-dfaf-4a20-a1ee-458369aeac99.png)
console报错如下
![image](https://user-images.githubusercontent.com/16254644/159124471-47d4590c-ab7a-4a9e-90dc-f554effec711.png)

**Comment by MotooriKashin** [comment]
搜索我记得不是默认开启的

**Comment by redapple0204** [comment]
@MotooriKashin oh 还真是，之前的版本好像是默认开启的都没注意到改了默认设置
打扰了~

**Comment by MotooriKashin** [comment]
没事，搜索因为还在AB测试中，所以并没有默认启用
