### ISSUE TITLE
渲染带有/n或\n的普通弹幕（非字幕弹幕）不正常

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#273]
![image](https://user-images.githubusercontent.com/77530593/160229078-0f18f026-98d0-4f39-b88a-8b40ab7f25a5.png)
弹幕文件：
![image](https://user-images.githubusercontent.com/77530593/160229091-de611ad8-9101-4c27-b773-d14ea7a123fe.png)

求修复

**Comment by followmypeach** [comment]
补充：测试视频https://www.bilibili.com/video/av83088
在老版播放器测试正常
![image](https://user-images.githubusercontent.com/77530593/160229153-c7cb24ce-31bd-45da-a29d-ace5381dcdb4.png)

**Comment by MotooriKashin** [comment]
可能是我没get到，你难道是指换行符不该换行？  
还有，这是上古播放器是怎么调出来的？

**Comment by MotooriKashin** [comment]
看了剧情我有点懂你的意思了，这可能需要另一位作者来处理，而且可能需要好久。
我也会试试看，不敢保证一定能修好。我觉得你那个应该是flash播放器，B站原生HTML5播放器应该从未支持过此类弹幕。

**Comment by followmypeach** [comment]
> 还有，这是上古播放器是怎么调出来的？

用的弹幕塚（DMF_Local）和魔改的SWF

**Comment by followmypeach** [comment]
> 还有，这是上古播放器是怎么调出来的？
通过弹幕塚(DMF_Local)（没GIthub链接别问了）
下载链接：https://pan.baidu.com/s/11sSXrV-8Wm-rUySH_nEJlw?pwd=07fe 
提取码：07fe

**Comment by followmypeach** [comment]
> 看了剧情我有点懂你的意思了，这可能需要另一位作者来处理，而且可能需要好久。 我也会试试看，不敢保证一定能修好。我觉得你那个应该是flash播放器，B站原生HTML5播放器应该从未支持过此类弹幕。

呸 是离线弹幕测试工具

**Comment by MotooriKashin** [comment]
收回前言，问题是字幕弹幕标记丢失或者没有打上，已尝试修复。

**Comment by followmypeach** [comment]
不是所有带换行符的普通弹幕都是字幕弹幕啊！
把换行符的普通弹幕打上标记后无法在旧版播放器正确屏蔽
（修复个换行符没必要打标记把）

**Comment by followmypeach** [comment]
说真的代码弹幕也没必要打字幕弹幕标记......

**Comment by MotooriKashin** [comment]
的确，已进行修改，允许普权弹幕换行并不再标记为字幕弹幕。
