### ISSUE TITLE
[Bug]区域解除限制功能无法使用

### ISSUE THREAD

**Issue by Kongchenglige** [MotooriKashin/Bilibili-Old#275]
**问题详情**
插件的区域解除限制功能无法使用

**复现步骤**
1. 尝试打开ep369678
2. 提示尝试解除区域限制并报"此视频无法播放，请反馈以添加此类错误信息 （错误信息cid：9947622）"

**相关截图**
![image](https://user-images.githubusercontent.com/35166074/161296655-5ab400aa-e9f6-40e2-959f-4acfbb8208b6.png)

**运行环境**
 - 操作系统：Windows10 professional 21H1
 - 浏览器：Google Chrome 99.0.4844.84
 - 脚本管理器：Tampermonkey 4.14.6125

**补充内容**
此内容似乎是泰区内容，然而却并未被解析至泰区

**Comment by MotooriKashin** [comment]
解除限制功能的泰区部分已年久失修，因为一直缺少泰区代理服务器来测试。  
对于泰区视频还是建议使用其他更为专业的脚本。

**Comment by Kongchenglige** [comment]
您是否可以考虑使用 [BiliRoaming](https://github.com/yujincheng08/BiliRoaming) 提供的代理服务器进行测试？

**Comment by MotooriKashin** [comment]
> 遇到了rebuildPlayerurl.ts的283行报错TypeError: ogv.data.video_info.stream_list.forEach(...) is not a function 的情况

大概是返回的json数据已经改变了，不再是数组了——的确是很久没有维护了，有变动很正常

**Comment by MotooriKashin** [comment]
`rebuildPlayerurl.ts`的作用是将代理接口返回的`playurl`转化为播放器支持的`playurl`格式，即网页端`playurl`接口返回的数据格式。  

另外当时代码写得有点糟糕，请多担待！

**Comment by MotooriKashin** [comment]
> 您是否可以考虑使用 [BiliRoaming](https://github.com/yujincheng08/BiliRoaming) 提供的代理服务器进行测试

其实最近有尝试过，但好像那些公开接口返回的`playurl`有点问题，缺少`duration`(时长)数据，重构出来的`playurl`无法播放，所以就没有说深究。  
另外还抓包到网页端接口
```
    https://api.biliintl.com/intl/gateway/ogv/m/v2/view?ep_id=378226&s_locale=en_US&season_id=36690
    https://api.biliintl.com/intl/gateway/m/ogv/v2/playurl?device=wap&ep_id=378226&platform=html5&qn=16&s_locale=en_US&season_id=36690&tf=0&type=0
    https://api.bilibili.tv/intl/gateway/web/playurl?aid=2009284891&buvid=dd20a8b4-1a4f-436a-be0a-5fb803bae56440320infoc&device=wap&platform=web&qn=64&s_locale=en_US&tf=0&type=0
    https://api.bilibili.tv/intl/gateway/web/playurl?buvid=dd20a8b4-1a4f-436a-be0a-5fb803bae56440320infoc&device=wap&ep_id=10225348&platform=web&qn=64&s_locale=en_US&tf=0&type=0
```
这些数据比APP端好用多了，至少不用重构`sidx`，可惜所有代理服务器都是当时根据APP端接口设计的，不会转发这些url，所以我更想要泰区的ssr/v2ray什么的，直接基于网页端接口重构代码。
