### ISSUE TITLE
添加弹幕云屏蔽&硬核会员弹幕池功能

### ISSUE THREAD

**Issue by wly5556** [MotooriKashin/Bilibili-Old#276]
最近b站新推出了“**硬核会员弹幕模式**”，号称 “_在网页端和移动端播放器开启模式后，各位实验室成员将在视频中被优先展示来自于和你一样通过试炼答题的硬核会员同伴们发布的弹幕内容_” ，就很好奇它到底是什么样的😋。

于是想要在旧播放器里试试把这个功能做进来，同时把很久之前有人[提过](https://greasyfork.org/zh-CN/scripts/394296/discussions/94894)的弹幕云屏蔽的需求一起做了，目前完成得差不多了，还有一点问题没解决、需要再测试，开个issue记录一下

>效果如图，为了方便操作，入口放在播放器右侧 弹幕屏蔽 一栏
![{ 81P9 41Q}QO)TPZ JEU)3](https://user-images.githubusercontent.com/61644753/161378432-7606a683-1947-4679-a41d-801aa52f7466.png)

**Comment by MotooriKashin** [comment]
哇！好久不见！辛苦了！

**Comment by MotooriKashin** [comment]
硬核会员在评论区我直接以lv7显示，我觉得B站也是这个意思，只是碍于学园都市的限制只能采取这种折衷的法子。——好吧~_~，我就是懒……

**Comment by wly5556** [comment]
### 关于“硬核会员弹幕”
翻找新播放器的代码可以发现，这类弹幕在云屏蔽系统中的权重值(danmakuElem.weight)是11，在原本的最高级上加了一级，于是只需要屏蔽掉11级以下的弹幕就能达到效果

![2HMQCFXGRO6MU PN{VNPG(C](https://user-images.githubusercontent.com/61644753/161378925-10a2aa41-a565-46fd-9f2e-a152681e2c62.png)
_(新播放器判断一条弹幕是否被屏蔽的代码，在代码文件中搜索seniorMode基本可以找到所有跟“硬核会员弹幕”有关的代码)_

关键是我的账号还没达到6级😥，不能直接去测试，上面的想法还只能算是猜测。虽然把弹幕云屏蔽功能实现之后，与[这个视频](https://www.bilibili.com/video/av640368880)比对屏蔽11级以下弹幕的效果，基本可以确认没搞错，但是如果有达到lv6+的人能直接去对比一下就好了......但是这又要先把新版本发出来，希望不会闹乌龙吧🤣

### 关于播放器设置项
这次试着把屏蔽等级用播放器本身的设置系统来[保存](https://github.com/MotooriKashin/Bilibili-Old/commit/a6b5dc73c60cbb4716d70e6e078f24bdd20ab4ab#diff-f43f1672c5ca28b7f265f6c95035d6bcfdd662132f22de4edf552d8d7a15ac36R17683)，保存在``block.ai_level``这一项里，后面调试新版播放器的时候才发现，它那边也能读取到我在旧播放器设置的``ai_level``，还好新播放器的屏蔽等级保存到``ailevel``，没有相互影响到。播放器设置的存储方式是本地储存+云同步吗？旧播放页里的播放器设置也是脚本在代为维护？现在这样给它新增一项会导致什么隐含的问题吗？有点迷惑了。记得好像@MotooriKashin 有处理过播放器设置有关的代码，先把这些问题发在这了，求解答！

### 随便记点什么
这次试着把屏蔽等级的设置项放在了播放器内部，实际做起来发现要修改bilibiliPlayer.js的地方挺多

- [这里](https://github.com/MotooriKashin/Bilibili-Old/commit/a6b5dc73c60cbb4716d70e6e078f24bdd20ab4ab#diff-f43f1672c5ca28b7f265f6c95035d6bcfdd662132f22de4edf552d8d7a15ac36R4460)是播放器的默认设置，添加了新的一项ai_level
- bilibiliPlayer.js在[这里](https://github.com/MotooriKashin/Bilibili-Old/commit/a6b5dc73c60cbb4716d70e6e078f24bdd20ab4ab#diff-f43f1672c5ca28b7f265f6c95035d6bcfdd662132f22de4edf552d8d7a15ac36R5550)往页面写入了一大堆播放器主界面要用的css
- c.c（有时候是this.c）这个变量很方便，到处都能通过它的引用得到弹幕数据\播放器各种dom组件\播放器UI库
- c.C.ah是滑动条组件，简单易用

**Comment by wly5556** [comment]
忘记说了，其实不少权重为11的弹幕，反查出来的发送者是lv5，这个是最迷惑的地方，还得进一步测试啊....

>哇！好久不见！辛苦了！

感觉时间过得好快啊😙

> 硬核会员在评论区我直接以lv7显示，我觉得B站也是这个意思，只是碍于学园都市的限制只能采取这种折衷的法子。——好吧~_~，我就是懒……

紫色的lv7比lv6⚡酷炫太多了😎

**Comment by MotooriKashin** [comment]
> 如果有达到lv6+的人能直接去对比一下就好了

这个我可以测试，不才已经是硬核会员了。

> 播放器设置的存储方式是本地储存+云同步吗？

应该是本地ls保存，云端没有记录。

> 旧播放页里的播放器设置也是脚本在代为维护？

维护谈不上，只是新旧播放器公用一个键保存播放器设置，但下属项目值已有差异，有些会导致旧版播放器出错。脚本只是备份了一下设置，然后在设置被新版播放器改动后还原一下。你添加的项不在检测范围内，所以应该没有问题。

**Comment by wly5556** [comment]
太感谢了！

发现历史弹幕的弹幕云屏蔽不正常，需要解决下

另外实时弹幕也挂了，服务器端口又换了，这个可能要到明天才有时间去修

**Comment by wly5556** [comment]
历史弹幕本身没有权重数据，新版播放器：那就来一个随机数作为它的权重吧！！
![7(V88YES CL}JAD`5(( )5K](https://user-images.githubusercontent.com/61644753/161382017-0bb13651-d409-491f-a7ef-5218c39c081d.png)
真的是好智能的智能云屏蔽啊🤣

**Comment by MotooriKashin** [comment]
亏我还以为她真的用了什么AI算法，不会在云端也是随机一下解决吧🤣

**Comment by MotooriKashin** [comment]
啊，我这边甚至直接报错，根本无法测试
![image](https://user-images.githubusercontent.com/60416767/161407130-296cd8a7-cc0b-4881-8f37-0e5b233d43c5.png)
![image](https://user-images.githubusercontent.com/60416767/161407135-f0cafdbb-e209-4ecb-a23c-c91949f46efa.png)
播放器屏蔽选项卡也不正常
![image](https://user-images.githubusercontent.com/60416767/161407155-e548783e-195d-4df8-8e52-954274215e69.png)

**Comment by wly5556** [comment]
我这没遇到这个报错，c.list.weight是在21633行创建的，应该不会是未定义啊
```javascript
c.list.weight = new Array(100).fill(0);
for (var e = +new Date, k = [], h = void 0, q = 0, m = b.danmakuArray.length; q < m; q++) {
    h = b.danmakuArray[q], h.gb = b.danmakuArray[q]["class"], k[k.length] = h;
    c.list.weight[h.weight] += 1;
}
for(let i = 10; i >= 0; i--) {
    c.list.weight[i] += c.list.weight[i + 1];
}
```

**Comment by MotooriKashin** [comment]
现在好像没问题了，不过这个要怎么测试，我试了一下一个基本上都是都是发的弹幕的视频，也基本上都被屏蔽了。也的确发现了一些小于lv6的弹幕反而幸存（反查有碰撞的可能信，所以不一定可靠）

**Comment by MotooriKashin** [comment]
我这边一直是这样，只有偶尔不报错。测得的确有lv5幸存，可能是哈希碰撞的锅？反查发送者真不一定可靠。  
另外我发现以前我发的很多弹幕也都被屏蔽了，难道要新发的弹幕才算硬核？

**Comment by MotooriKashin** [comment]
测试发现选择“屏蔽设定”面板刷新的话，播放器刷新出来会保持该设定，直接加载“屏蔽设定”面板，这是`weight`并没有初始化。一般第一次加载视频肯定不会首先展示该选项所以不会报错。

**Comment by wly5556** [comment]
>不过这个要怎么测试

用新版播放器打开硬核模式的屏蔽效果跟旧版相互对比一下就行

>测试发现选择“屏蔽设定”面板刷新的话，播放器刷新出来会保持该设定，直接加载“屏蔽设定”面板，这是weight并没有初始化。一般第一次加载视频肯定不会首先展示该选项所以不会报错。

🤯我一直开着自动切换到弹幕列表，怪不得没遇上这个问题

**Comment by MotooriKashin** [comment]
测试了多个视频屏蔽效果是一样的，应该没问题。不过我真怀疑这个硬核弹幕肯定不只是剩下lv7人发的弹幕，可能目前才刚公测，怕人太少弹幕太少？
另外强烈怀疑这个所谓的智能云屏蔽真的只是随机数，我看了某个只由一个人发弹幕作为歌词的视频，被屏蔽得惨不忍睹🤣

**Comment by MotooriKashin** [comment]
建议对于【字幕弹幕】等高级弹幕作例外处理，干脆全部置为11，不然就像[小圆](https://www.bilibili.com/video/av75432)这个视频一样直接团灭了！虽然那个人也还是lv5就是了。
![image](https://user-images.githubusercontent.com/60416767/161410065-8911bdb4-6973-47fe-8c61-bea22ba75caa.png)

**Comment by wly5556** [comment]
>不过我真怀疑这个硬核弹幕肯定不只是剩下lv7人发的弹幕，可能目前才刚公测，怕人太少弹幕太少？

感觉他们确实会这么做啊 哈哈

>另外强烈怀疑这个所谓的智能云屏蔽真的只是随机数，我看了某个只由一个人发弹幕作为歌词的视频，被屏蔽得惨不忍睹🤣

所以我一直没有去用这类功能，要么看到所有弹幕，要么整个关掉弹幕😋

>【字幕弹幕】等高级弹幕作例外处理，干脆全部置为11

确实应该这么做

**Comment by wly5556** [comment]
>另外实时弹幕也挂了，服务器端口又换了

端口从7823换成了7826，用上了protobuf来序列化消息。但是新的地址居然不会下发实时弹幕，只是空虚地每20秒发心跳包跟服务器一问一答。明明是有相关代码在那里的，不会是要准备砍掉实时弹幕了吧.....
![{GC$XN8A7HFV5W25GB(R}MQ](https://user-images.githubusercontent.com/61644753/161415465-21de4b9f-c3f0-4fdd-8d06-9e59200f0606.png)
_建立ws连接后的上发的第一个数据包，有跟实时弹幕有关的内容_

**Comment by MotooriKashin** [comment]
> 但是新的地址居然不会下发实时弹幕

所以是修不了了吗？实时弹幕还真没注意，我一般只看过时的视频（等弹幕大军到了再看

**Comment by wly5556** [comment]
>所以是修不了了吗？实时弹幕还真没注意，我一般只看过时的视频（等弹幕大军到了再看

如果不是服务器暂时抽风，确实修不了...我一直挺喜欢视频刚发布的时候就点进去，边看视频，边看着弹幕数不断增长，现在又得等弹幕多起来再去看了

**Comment by miss1ng** [comment]
根据B站官方的说法，硬核会员弹幕模式将“优先展示同为硬核会员发送的弹幕内容”，并不是屏蔽掉所有非硬核会员的弹幕

**Comment by MotooriKashin** [comment]
> 优先展示同为硬核会员发送的弹幕内容

Soga，居然是阅读理解问题，我想当然了

**Comment by wly5556** [comment]
🤯🤯🤯原来是这样
