### ISSUE TITLE
[Feature Requset]希望把评论区里面的楼层数显示回来

### ISSUE THREAD

**Issue by Jerry19970311** [MotooriKashin/Bilibili-Old#278]
**存在问题**
我记得这个脚本最初时候是有这个功能的，但是好像是今年年初以后就没有了，不知道是怎么回事。

**目标愿景**
希望评论区和评论里面的楼中楼重新显示楼层数。

**参考建议**

**补充内容**

**Comment by MotooriKashin** [comment]
接口被禁，已经移除相关功能。

**Comment by alex3236** [comment]
https://github.com/MotooriKashin/Bilibili-Old/commit/23526752a582f8735b3c7a82cbc84a34a0eff480 这里提到的修复是什么？
