### ISSUE TITLE
[Bug]从历史记录点进视频会造成重复播放

### ISSUE THREAD

**Issue by Jerry19970311** [MotooriKashin/Bilibili-Old#279]
**问题详情**
有的时候从历史记录点进视频，视频尚未点击播放，就会出现视频里的声音，且无法关闭，如果点击播放，则会显示双重的声音。
PS：
①个人怀疑这个问题是因为新版播放器并没有真正消失，只是被旧版播放器掩盖住了，而新版播放器默认是自动播放的。但是我特意关闭脚本，去更改新版浏览器的设置以后，仍会时常出现这个问题。
②并非每次从历史记录点进视频都会遇到这个问题，希望你们测试的时候耐心多做几遍，辛苦了。

**复现步骤**

**相关截图**
已经录制视频，由于此处无法上传视频，且视频中可能含有一些隐私，如果能提供邮箱的话，我会把视频发到邮箱里的。

**运行环境**
 - 操作系统：Windows 10 家庭中文版19044.1586
 - 浏览器：Google Chrome 99.0.4844.74
 - 脚本管理器：Tampermonkey 4.14.6125

**补充内容**
其他补充内容。

**Comment by MotooriKashin** [comment]
设置-通用-重构模式选择“极端”试试

**Comment by Jerry19970311** [comment]
> 设置-通用-重构模式选择“极端”试试

好的，我先试试，如果半个月内没啥问题，那应该就是没问题了。谢谢啦。
