### ISSUE TITLE
[Bug]进度条无法使用

### ISSUE THREAD

**Issue by Levin-7** [MotooriKashin/Bilibili-Old#280]
**问题详情**
进度条跟随鼠标移动而无法使用

**复现步骤**
暂时不知道，还在尝试

**相关截图**

https://user-images.githubusercontent.com/101990094/162743180-6f09e23f-6aa8-4980-a330-c5682cbd8a8f.mp4
(压缩大小，糊了点)

**运行环境**
 - 操作系统：Windows 10 Profession Build 19044.1586
 - 浏览器：Google Chrome 100.0.4896.75
 - 脚本管理器：Tampermonkey 4.16
**补充内容**
其他补充内容。

**Comment by MotooriKashin** [comment]
无法复现暂时无法测试，你可以在碰到类似问题时打开控制台看看报错情况并截图

**Comment by Levin-7** [comment]
OK

**Comment by Levin-7** [comment]
试出来了
播放的这个
https://www.bilibili.com/video/av18142899
控制台如下图
![微信截图_20220420132744](https://user-images.githubusercontent.com/101990094/164156981-29e58487-92f3-4f20-8eb2-09c09604c231.png)

顺带补充一下，音量条也崩了

**Comment by MotooriKashin** [comment]
未能复现。  
不过看控制台打印信息，你应该安装了其他脚本，会不会是脚本之间冲突了，可以尝试临时关闭其他脚本看看。

**Comment by Levin-7** [comment]
解决了
和另一个下载脚本冲突了
不过好像又出新bug了
我确定一下，一会单独发吧
