### ISSUE TITLE
评论楼层在特定情况的出现

### ISSUE THREAD

**Issue by sddddd213** [MotooriKashin/Bilibili-Old#282]
先上图
![InkedQQ图片20220417230733_LI](https://user-images.githubusercontent.com/38841494/163720940-a5a98a1f-9dbc-4106-8b76-95fee93d5e4e.jpg)

脚本版本为7.2.7、并未开启【原生托管】、页面重构模式为【极端】，符合以上情况后，点开任意一条有多人回复的评论即可看见楼层，包括主楼和楼中楼的层数都有体现。
这是否说明楼层接口其实并未屏蔽？是否可以在该情况下把楼层调整到整个评论区，而不是单个评论楼。

**Comment by MotooriKashin** [comment]
如你所见，有朋友提供了相关接口，所以抢救了一下。展开楼中楼自动获取主楼，没有楼中楼的可点击右边“三点”。  
新接口匹配请看不佳，不支持楼中楼翻页，请多担待！  
为避免再次招致和谐，并未在更新记录中明说，也不会调整为被动触发，想知道某楼层号，请主动获取。  
本issue将被关闭并改名，更多建议请前往对应的commit记录评论。
