### ISSUE TITLE
[Bug] 兼容新版pakku

### ISSUE THREAD

**Issue by nzd7xW5** [MotooriKashin/Bilibili-Old#283]
**问题详情**
现在开了脚本之后，有的视频只能加载出一个视频前6分钟的弹幕，后面的弹幕全都不显示了

**复现步骤**
比如说这个视频 https://www.bilibili.com/video/av383347325/ 开了脚本就只能加载出前6分钟

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/69294448/163905867-eea0fd4d-f11d-490b-bd89-4f128dddff0c.png">
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/69294448/163905915-11bb810d-f0ce-4e12-b715-218541cceb79.png">

这个视频也是只有前6分钟的弹幕 https://www.bilibili.com/video/av425870228/
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/69294448/163906189-64cae70d-f6a4-4bce-97d9-d831441720fe.png">

但有的其他的视频就没有这个bug，比如https://www.bilibili.com/video/av938263130 不知道哪些视频才能稳定复现这个bug

**运行环境**
 - 操作系统：Mac
 - 浏览器：Google Chrome 100.0.4896.75 (Official Build) (arm64)
 - 脚本管理器：Tampermonkey 4.16

**补充内容**
其他补充内容。

**Comment by MotooriKashin** [comment]
我这边是没这种问题，从来没有，MAC我也没法测试，只能先凭直觉处理排查一下：  
猜想可能是hook模块载入过迟，未能hook到旧版弹幕接口，已更新版本提前了相关模块运行，你可以测试一下，如果还是不能解决，请提供控制台截图，看看能不能提供更有效的信息。

**Comment by nzd7xW5** [comment]
还是不行。控制台截图：
<img width="790" alt="image" src="https://user-images.githubusercontent.com/69294448/163917539-6986c7f4-3587-4cd9-8daa-0518cc11457f.png">
<img width="790" alt="image" src="https://user-images.githubusercontent.com/69294448/163917559-434309c3-953e-4417-9dd6-b70449a85aad.png">

**Comment by MotooriKashin** [comment]
pakku? 有没有可能是pakku的问题，看起来是她hook了弹幕请求，却只处理了第一包，也就是前六分钟的弹幕。

**Comment by nzd7xW5** [comment]
还真是pakku，禁用了就没问题了。而且禁用了之后，加载出了所有的弹幕，再启用pakku，也能够继续加载出所有弹幕，控制台如下：
<img width="791" alt="image" src="https://user-images.githubusercontent.com/69294448/163920451-d4863c8e-252e-47b0-b3eb-2a8461897535.png">
<img width="790" alt="image" src="https://user-images.githubusercontent.com/69294448/163920490-8e3aa7a0-e467-44a8-a5b9-de2b1f16d3d6.png">


不过老哥能在兼容的重构模式里再试着兼容一下pakku吗？最近pakku在兼容模式里也不能完全工作了。pakku在按下ctrl键之后所有弹幕会变黄，这时候用鼠标移动到弹幕上就可以反查发送者，这个功能最近在这个脚本下用不了了。不过合并弹幕的主要功能倒还是在运行。

**Comment by MotooriKashin** [comment]
反查弹幕发送者功能本脚本也有实现（设置-弹幕-反查弹幕发送者），开启后你可以在弹幕列表或者视频弹幕上右键查询。

**Comment by nzd7xW5** [comment]
哦哦这边也支持了啊，好的

不过老哥能再试着看看pakku截断弹幕到底是啥问题吗🥲

**Comment by MotooriKashin** [comment]
去pakku仓库看了一下，前两天提交了十多个修改并推送了新版本，调试起来成本有点高，我也不熟悉浏览器拓展的开发，所以可能无法回答这个问题。  
就个人观点，能捕获第一包弹幕，那就说明至少至少pakku的弹幕接口hook代码是正常运行的，也就是这方面的兼容性大概率没问题。也许问题并不出在兼容性，而是pakku最新提交有什么bug（信口胡诌，姑妄言之，姑妄听之）。或者还得请教一下对pakku同样有研究的另一个作者 @wly5556 ，不过可能未必有时间。

**Comment by wly5556** [comment]
pakku以前的版本，是hook到首个弹幕分段的请求之后，直接获取视频所有弹幕分段，相应处理所有弹幕之后一次性返回给播放器，同时利用hook直接把随后的其他分段的请求忽略掉。
这两天的新版本pakku（没猜错的话）应该是改成配合新播放器原本的懒加载逻辑，hook到一个弹幕分段包就处理一个

**Comment by wly5556** [comment]
手滑了！！🙇🙇字没打完就发出去了

之前兼容pakku的代码是直接对着pakku旧版本的载入逻辑写的，脚本发现pakku在运行之后，不会主动去请求除了首个弹幕分包之外的弹幕，到了新版本pakku这里就变得不能载入6分钟之后的弹幕了

不过现在我没办法去看pakku的代码，上面说的只算是猜测。不管怎样脚本兼容pakku的相关代码肯定要跟着改了，只是我要到周六才有时间去弄

**Comment by MotooriKashin** [comment]
> 脚本发现pakku在运行之后，不会主动去请求除了首个弹幕分包之外的弹幕

原来如此，问题还是在我们这，收回前言——我没用过pakku，所以真不了解。不过如果是懒加载的话，岂不是不做任何兼容处理就等于是兼容了？毕竟都是使用xhr请求弹幕包，新版播放器发的和本脚本发的似乎没什么区别？（我这更是猜测，还是得辛苦你了！）

**Comment by xmcp** [comment]
TLDR:
- 在上周之前（<=10.1.1）的版本中，`segment_index=1` 的请求会返回全部弹幕，`segment_index=2` 及之后的请求返回空
- 在最新（10.1.2 和 10.2）的版本中，改回了与原版B站播放器一致的分块模式（即原来在哪个 segment_index 的弹幕就在哪个 segment_index 里）

虽然不知道你们这边是怎么实现的，改成获取所有 segment 并把结果拼起来应该不会有问题。

**Comment by xmcp** [comment]
另外 10.1.2 还更改了 xhr_hook 的加载时机（之前是在 `document-end` 加载，改成了在 `document-start` 加载）。虽然不知道会不会导致冲突总之说一下

**Comment by MotooriKashin** [comment]
感谢作者亲自解答💕  
测试了一下去掉兼容代码就没问题了，`document-start`加载更好，不仅没有冲突还避免了冲突。

**Comment by nzd7xW5** [comment]
哦对既然原作者大佬也出现了，还想请问下能不能多修一个pakku的兼容性问题
pakku有个功能是会在进度表上面显示出弹幕的热力图的，而且可以预览在某一时间看到的弹幕
<img width="885" alt="image" src="https://user-images.githubusercontent.com/69294448/164776740-542e934a-c346-4292-b6e7-77c08fd20f60.png">
<img width="876" alt="image" src="https://user-images.githubusercontent.com/69294448/164776850-0882cafa-6a59-4937-a662-705624bf99c3.png">
这个功能在这边的某一次更新之后就不可用了。作者看这个能重新兼容一下吗？

另外就是还请兼容一下pakku按下ctrl或者alt之后显示弹幕详情的功能呗。pakku在这块显示的不仅是弹幕发送者，还会显示这条弹幕都是从哪些弹幕合并来的、字号具体放大了多少倍，等等
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/69294448/164777402-6f5fe2d6-9b13-494d-b29d-43c3a03493eb.png">


再另外请求一个关于兼容性的问题。就这一个chrome插件，https://github.com/igrigorik/videospeed，https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk，一直都是只要识别到html4的视频播放器，就可以生效。但是在开了咱们这个脚本之后，就识别不出旧B站播放器了。

**Comment by nzd7xW5** [comment]
另外自上次更新之后咱们这个脚本是又更改了和pakku相关的代码吗？现在只要开着pakku，这边就完全加载不出弹幕了：
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/69294448/164778913-f44dc00f-dc55-4b2a-9106-3512fb18bf0c.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/69294448/164778949-43734bd7-75c1-4c17-8199-0e71fd3970d0.png">
控制台：
<img width="791" alt="image" src="https://user-images.githubusercontent.com/69294448/164779058-a0b9a84d-4298-4ce5-8cd4-c6d915938dc3.png">
<img width="791" alt="image" src="https://user-images.githubusercontent.com/69294448/164779102-57149daa-031c-4c79-a53b-37e48e32c3ea.png">

**Comment by wly5556** [comment]
没想到插件作者能亲自来解答，太惊喜了🤯！！

>另外自上次更新之后咱们这个脚本是又更改了和pakku相关的代码吗？现在只要开着pakku，这边就完全加载不出弹幕了：

这个跟pakku v10.2.1更新有关，xhr_hook.js的这里貌似有点小问题，可能是忘了把``push(this.onreadystatechange)``改成``push(this.onload)``了
![@VDYJ~JG9@M%K9LZX8(W6LU](https://user-images.githubusercontent.com/61644753/164864344-f09f8cee-c28b-4782-9012-9ef4cdcf77ef.png)

另外脚本设置页面的说明文字也可以改了，现在是默认模式也能用pakku了，极端模式则无法使用

**Comment by MotooriKashin** [comment]
> 再另外请求一个关于兼容性的问题。就这一个chrome插件，https://github.com/igrigorik/videospeed ，https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk ，一直都是只要识别到html4的视频播放器就可以生效。但是在开了咱们这个脚本之后，就识别不出旧B站播放器了。

试试调整重构模式，极端模式与大部分浏览器扩展不兼容，`document-start`模式注入的`content.js`失效。

**Comment by xmcp** [comment]
> 这个跟pakku v10.2.1更新有关，xhr_hook.js的这里貌似有点小问题

是我智障了，pakku v10.2.2已修复bug

**Comment by nzd7xW5** [comment]
> 没想到插件作者能亲自来解答，太惊喜了🤯！！
> 
> > 另外自上次更新之后咱们这个脚本是又更改了和pakku相关的代码吗？现在只要开着pakku，这边就完全加载不出弹幕了：
> 
> 这个跟pakku v10.2.1更新有关，xhr_hook.js的这里貌似有点小问题，可能是忘了把`push(this.onreadystatechange)`改成`push(this.onload)`了 ![@VDYJ~JG9@M%K9LZX8(W6LU](https://user-images.githubusercontent.com/61644753/164864344-f09f8cee-c28b-4782-9012-9ef4cdcf77ef.png)
> 
> 另外脚本设置页面的说明文字也可以改了，现在是默认模式也能用pakku了，极端模式则无法使用

好的 谢谢

另外就是关于pakku的热力图和弹幕成分分析的兼容，作者大佬觉得能做吗？倒也不是想催🥲就是想问下这是个日后有时间就能改的小问题，还是涉及脚本大改的wontfix

**Comment by xmcp** [comment]
看了下问题主要有两个方面。

- 一个是使用bilibili-old之后播放器页面的document_end一直不触发。pakku的播放器增强功能因为需要在document.body里操作，所以[是在document_end时生效的](https://github.com/xmcp/pakku.js/blob/b1076b69cb/pakkujs/core/background.js#L140)，所以没有工作。暂时不知道是什么情况。
- 另一个是pakku的热力图功能之前去除了旧版播放器的支持（因为旧版播放器本来也不被官方使用了，代码里dead code太多不方便维护）。

如果确实有需要的话，第二点pakku这边可以重新恢复支持，但是第一点可能涉及bilibili-old，还没搞懂具体是怎么回事。建议开个新的issue讨论这个事，因为跟本issue无关。

**Comment by MotooriKashin** [comment]
> 使用bilibili-old之后播放器页面的document_end一直不触发

这一点可以调整重构模式为兼容解决
![image](https://user-images.githubusercontent.com/60416767/164889718-14f34481-cada-46f7-a5e5-f4bae4af66dc.png)

**Comment by xmcp** [comment]
pakku v10.2.3已恢复对旧版播放器的支持，看上去跟bilibili-old用起来没什么问题

**Comment by nzd7xW5** [comment]
太感谢了！🤙

**Comment by nzd7xW5** [comment]
@xmcp @wly5556 @MotooriKashin 大佬们能再帮忙看一下这个有关pakku和bilibili-old的兼容性的小问题吗？

**存在问题**
打开pakku的播放器增强功能之后，鼠标漂浮在进度条上的时候不能预览鼠标所在位所对应的视频时间，只能在拖拽的时候看到播放器右侧所显示的视频时间：
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/69294448/168234794-e0223555-4016-42b0-8c93-eb9608c3e9b8.png">

这是不开pakku的情况
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/69294448/168234595-3b8414c0-7635-4a7b-be11-57d6e235def6.png">

开了pakku之后，在特殊的一些位置，可以看到这个显示视频时间的盒子不会被挤掉：
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/69294448/168234897-c04fb416-5dd6-48db-938a-7d65f0b9fec3.png">
但大多时候这个小盒子都是看不到的

**目标愿景**
能不能兼容一下这个，让这个小盒子持续显示呢

**参考建议**
这个盒子的位置应该是不用变的，现在这个盒子就是放在视频预览图的最下方吧，是不太影响使用的。开了pakku之后继续把盒子放在这个位置应该也不会有什么影响。不知道这个小兼容问题对于pakku和bilibili-old来说哪边修起来更容易。

**Comment by xmcp** [comment]
我测试的时候没有问题，不知道是不是最近bilibili-old又改了啥

**Comment by MotooriKashin** [comment]
这边应该也没有动过界面相关的东西，难道是窗口分辨率导致的问题？
