### ISSUE TITLE
[Feature Requset]改进弹幕分包获取方式

### ISSUE THREAD

**Issue by MotooriKashin** [MotooriKashin/Bilibili-Old#284]
**存在问题**
由 #283 想到的，脚本一直以来都是一次性获取所有弹幕(`Promise.all`等待)，对于时长过长或者弹幕量过多的视频(如电影)而言，先期加载弹幕的时间可能会太久影响体验。

**目标愿景**
不再`Promise.all`等待并发返回所有弹幕，返回一个装填一个，而且一包出错也不会导致整体奔溃。

**参考建议**
实时弹幕的接口或许可以一用，`export`暴露一个接口什么的，也可以兼顾未托管原生脚本时的情况。

**补充内容**
并非急需，没时间可以留待以后。

**Comment by wly5556** [comment]
😳其实我觉得目前的弹幕数据量还不至于去按需加载
用4G网去载入08奥运开幕式的11万条弹幕（应该算是比较极端的例子了）花了快4秒，我还是能接受这个耗时的，用有线网还能更快
改成另一种模式的话代码相对复杂了，体验提升可能不会太明显，总感觉投入回报率有点低（个人看法啦）
目前要改进错误处理的话可以把promise.all改成allSettled，就不至于一个错误打断加载了。（另外脚本封装的xhr有办法在回调里获取到http状态码吗，被b站暂时拒绝访问api的那种状况就能更清晰地报错了）
提高等待体验也可以直接在界面上显示载入弹幕包的进度，把目前默认显示的“当前视频弹幕为空”换掉，效果也会不错吧

**Comment by MotooriKashin** [comment]
> 脚本封装的xhr有办法在回调里获取到http状态码吗，被b站暂时拒绝访问api的那种状况就能更清晰地报错了

xhr出错reject传递的是事件对象，可通过` currentTarget`获取原`XMLHttpRequest`对象，`status`就在上面。使用传统`Promise`链应该获取的到，`await`的话可能需要配合`try catch`（xhr这种意外性大的异步操作，本来就应该`try catch`，只是我大多时候懒😊）
```
{
    isTrusted: true,
    bubbles: false,
    cancelBubble: false,
    cancelable: false,
    composed: false,
    currentTarget: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, …},
    defaultPrevented: false,
    eventPhase: 0,
    lengthComputable: false,
    loaded: 0,
    path: [],
    returnValue: true,
    srcElement: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, …},
    target: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, …},
    timeStamp: 6011.199999999255,
    total: 0,
    type: "error",
}
```

**Comment by MotooriKashin** [comment]
> 脚本封装的xhr有办法在回调里获取到http状态码吗，被b站暂时拒绝访问api的那种状况就能更清晰地报错了

xhr出错reject传递的是事件对象，可通过` currentTarget`获取原`XMLHttpRequest`对象，`status`就在上面。使用传统`Promise`链应该获取的到，`await`的话可能需要配合`try catch`（xhr这种意外性大的异步操作，本来就应该`try catch`，只是我大多时候懒😊）
```
{
    isTrusted: true,
    bubbles: false,
    cancelBubble: false,
    cancelable: false,
    composed: false,
    currentTarget: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, …},
    defaultPrevented: false,
    eventPhase: 0,
    lengthComputable: false,
    loaded: 0,
    path: [],
    returnValue: true,
    srcElement: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, …},
    target: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, …},
    timeStamp: 6011.199999999255,
    total: 0,
    type: "error"
}
```
