### ISSUE TITLE
[Feature Requset] 关于动态页的重构

### ISSUE THREAD

**Issue by cqjjjzr** [MotooriKashin/Bilibili-Old#285]
这两天B站把动态页整个重构了，大量 `class` 改变导致我用的 Amazing Bilibili 等 UserCSS 失效。该 UserCSS 作者已经弃坑，因此不可能对新版动态页做适配。

目前用户空间里的动态子页面还没变。请问有无可能把以前的动态页覆盖回来？如果没有这种打算，请问您有无关于获取旧的页面源代码、CSS 以供参考修改 UserCSS 的建议呢？

**Comment by MotooriKashin** [comment]
[Wayback Machine](https://archive.org/web/)大概有源代码存档。

动态页，可能是我很少用吧，没看出跟以前有什么区别，又或者是我还没被灰度到？有需求的话当然可以加入重构，不过众所周知本脚本重构过的页面兼容性不佳，包括很多“夜间模式”之类的脚本就不灵，`UserCSS`可能也会有兼容问题。所以你有心去接手UserCSS维护可能是更合适的做法。  
额，提醒一下[Wayback Machine](https://archive.org/web/)需要科学上网，毕竟无差别的存档难免记录了些敏感内容。

**Comment by cqjjjzr** [comment]
本次重构在外观上似乎并没有引入太多变动，主要是在代码方面。您可以看一下动态条目卡片对应的 CSS Class 是不是都变成了 `bili-dyn-xxx` 的形式...

“夜间模式”脚本不灵可能是因为重构后的页面用的 CSS 类名等属于旧系统的，但这些脚本针对的是新系统。Amazing Bilibili 大多数代码还是针对旧页面，因此和 Bilibili-Old 搭配是比较合适的。

关于 Amazing Bilibili 的 UserCSS，我也只是做了一些小修小补（如搜索页面等）。但考虑到本次动态重构只是修改了下层代码，可能确实修补 UserCSS 要稳妥一些（因为这样的非外观变动实际上不需要 Bilibili-Old 做重构）。
