### ISSUE TITLE
[Bug]动态页不支持av号跳转

### ISSUE THREAD

**Issue by Taebost** [MotooriKashin/Bilibili-Old#286]
**问题详情**
简洁清晰的问题描述。
如题，动态页的超链接仅以文本状态显示，但视频内的并未受影响。
**复现步骤**
1. '用Chrome打开动态页面'

**相关截图**
![image](https://user-images.githubusercontent.com/64080472/164162527-2fd2ea28-c6a8-48f1-963f-f066f936f672.png)
![image](https://user-images.githubusercontent.com/64080472/164162626-d42249f0-10c8-4301-b317-250b75309feb.png)

**运行环境**
 - 操作系统：Windows7旗舰版
 - 浏览器：Google Chrome 100.0.4896.127
 - 脚本管理器：Tampermonkey 4.16

**补充内容**
其他补充内容。

**Comment by MotooriKashin** [comment]
脚本并不负责相关处理，关闭本脚本也是一样的。  
这种问题我觉得更应该反馈给B站，应该是新版动态设计时遗漏了，应该有人提醒。
