### ISSUE TITLE
[Feature Requset] 二级评论的楼层显示问题

### ISSUE THREAD

**Issue by nzd7xW5** [MotooriKashin/Bilibili-Old#287]
关于二级评论，现在不点“展开所有（二级）评论”，是不会显示楼层的
<img width="496" alt="image" src="https://user-images.githubusercontent.com/69294448/164887799-7f10d563-ca79-4a16-81f7-70892f42555b.png">
点了之后会显示楼层
<img width="483" alt="image" src="https://user-images.githubusercontent.com/69294448/164887814-0608e3c5-2536-4196-9fad-7855a1a45d9b.png">

能改成不点击展开所有评论的时候，就把精选（二级）评论的楼层给显示出来吗？有的时候点展开评论就是想看精选评论的上下文，如果在展开前就显示楼层的话就比较好找

不知道这是个技术难题 还是单纯怕默认显示楼层会被叔叔盯上

**Comment by MotooriKashin** [comment]
你可以点击评论右边的三点作为替代

> 不知道这是个技术难题 还是单纯怕默认显示楼层会被叔叔盯上

后者
