### ISSUE TITLE
[Bug]标签页上bilibili图标无法显示

### ISSUE THREAD

**Issue by redapple0204** [MotooriKashin/Bilibili-Old#288]
**问题详情**
![image](https://user-images.githubusercontent.com/16254644/165087738-40bcec1c-4dd5-48fb-be90-a537eea39f58.png)
如图，按理来说标签页不应该是地球，而应该是bilibili图标，ctrl+shift+R无效。

**复现步骤**
打开bilibili播放页面，主页不会有这个问题

**运行环境**
 - 操作系统：Windows10 LTSC 1809
 - 浏览器：Google Chrome 100.0.4896.127
 - 脚本管理器：Tampermonkey 4.16

**Comment by MotooriKashin** [comment]
试试调整重构模式
