### ISSUE TITLE
[Bug] “稍后再看——播放全部”时 Tag CSS 丢失

### ISSUE THREAD

**Issue by Eden7Ba23** [MotooriKashin/Bilibili-Old#290]
**问题详情**
“稍后再看——播放全部”中播放器下方 Tag CSS 丢失

**复现步骤**
1. '在账号登录态选择右上角“稍后再看——播放全部”'
2. '滑动页面展示 Tag '

**相关截图**
![圖片](https://user-images.githubusercontent.com/50616202/166103002-2de4a4c6-b806-43ff-939a-607b738543c1.png)

**运行环境**
 - 操作系统：ArchLinux 
 - 浏览器：Firefox 99.0-1 - archlinux 1.0
 - 脚本管理器：Tampermonkey v4.16.6160

**补充内容**
[null]

**Comment by MotooriKashin** [comment]
Windows+chrome暂时未能复现问题＞﹏＜
