### ISSUE TITLE
[Bug] 嵌入式播放器布局异常

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#291]
**问题详情**
在第三方网站嵌入的播放器布局异常。

**复现步骤**
1. 打开 https://www.mcbbs.net/thread-1321419-1-1.html 。
2. 发现嵌入式播放器布局异常。

**相关截图**
![图片](https://user-images.githubusercontent.com/20754543/166341048-41b48d89-3422-46c9-a135-f987a47d5051.png)

**运行环境**
 - 操作系统：Windows 10 Professional 10.0.19044.1645
 - 浏览器：Mozilla Firefox 99.0.1
 - 脚本管理器：Tampermonkey 4.11.6120

**补充内容**
无。

**Comment by MotooriKashin** [comment]
旧版播放器右侧控制面板是固定大小的，父页面给的长宽不够便成了这样，可以点击宽屏模式隐藏掉——默认进入就是这样的。
