### ISSUE TITLE
[Feature Requset] 和pakku的兼容问题：鼠标漂在进度条上的时候能不能显示一下漂浮位对应的视频时间

### ISSUE THREAD

**Issue by nzd7xW5** [MotooriKashin/Bilibili-Old#294]
**存在问题**
打开pakku的播放器增强功能之后，鼠标漂浮在进度条上的时候不能预览鼠标所在位所对应的视频时间，只能在拖拽的时候看到播放器右侧所显示的视频时间：
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/69294448/168234794-e0223555-4016-42b0-8c93-eb9608c3e9b8.png">

这是不开pakku的情况
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/69294448/168234595-3b8414c0-7635-4a7b-be11-57d6e235def6.png">

开了pakku之后，在特殊的一些位置，可以看到这个显示视频时间的盒子不会被挤掉：
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/69294448/168234897-c04fb416-5dd6-48db-938a-7d65f0b9fec3.png">
但大多时候这个小盒子都是看不到的

**目标愿景**
能不能兼容一下这个，让这个小盒子持续显示呢

**参考建议**
这个盒子的位置应该是不用变的，现在这个盒子就是放在视频预览图的最下方吧，是不太影响使用的。开了pakku之后继续把盒子放在这个位置应该也不会有什么影响

**Comment by MotooriKashin** [comment]
这应该是pakku的适配的问题吧，个人瞎猜可能涉及鼠标穿透、冒泡阻止或者节点位置调整什么的，导致进度条节点未能正确捕获到鼠标焦点事件。

**Comment by nzd7xW5** [comment]
@MotooriKashin 那麻烦能reopen一下 issue#283吗，我觉得干脆直接把这个问题搬到那个issue下面去问吧
