### ISSUE TITLE
[Bug] 弹幕无法加载

### ISSUE THREAD

**Issue by reserveword** [MotooriKashin/Bilibili-Old#295]
**问题详情**
1. 右上角报错“danmaku.js [Object object]”，并且（在线）弹幕全部无法加载
2. 翻看控制台可以找到报错对应的信息
```
[18:58:07] danmaku.js 
Object { code: 304, xhr: XMLHttpRequest }
    ​code: 304
    ​xhr: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: true, … }
    ​​mozAnon: false
    ​​mozSystem: false
    ​​onabort: function ()
    ​​onerror: function ()
    ​​onload: function onload()
    ​​onloadend: null
    ​​onloadstart: null
    ​​onprogress: null
    ​​onreadystatechange: null
    ​​ontimeout: function ()
    ​​readyState: 4
    ​​response: ArrayBuffer { byteLength: 0 }
    ​​responseType: "arraybuffer"
    ​​responseURL: "https://api.bilibili.com/x/v2/dm/web/seg.so?type=1&oid=2484233&pid=1633522&segment_index=5"
    ​​status: 304
    ​​statusText: "Not Modified"
    ​​timeout: 0
    ​​upload: XMLHttpRequestUpload { onloadstart: null, onprogress: null, onabort: null, … }
    ​​withCredentials: true
    ​​<prototype>: XMLHttpRequestPrototype { open: open(rest), setRequestHeader: setRequestHeader(), send: send(), … }
    ​<prototype>: Object { … }
debug.js:14:59
```
4. 翻看网络请求记录可以找到如下请求记录：
![image](https://user-images.githubusercontent.com/12995615/168274341-122151fd-b5d5-45e1-8791-67b6a98cf9c5.png)
5. 即使使用F12开发者工具网络请求页面的禁用缓存选项，并刷新页面，也仍然会出现304响应

**复现步骤**
1. 看着看着就时好时坏，有时候刷新几次能收到一次弹幕，有时候一直刷新都收不到

**相关截图**
![image](https://user-images.githubusercontent.com/12995615/168274630-464a38e5-3f20-4c2b-94a3-788898fae10d.png)
![image](https://user-images.githubusercontent.com/12995615/168274692-b746e242-5135-4522-90c3-04de51c7ee56.png)
![image](https://user-images.githubusercontent.com/12995615/168274341-122151fd-b5d5-45e1-8791-67b6a98cf9c5.png)

**运行环境**
 - 操作系统：Windows10
 - 浏览器：Firefox 100
 - 脚本管理器：Tampermonkey 4.17.6161

**补充内容**
其他补充内容。

**Comment by MotooriKashin** [comment]
https://github.com/MotooriKashin/Bilibili-Old/blob/5f841f4abf60899cbed41c98da23237e02d7f54f/src/include/danmaku.ts#L101

我记得ajax是不会缓存的啊，应该是这行代码的问题。

**Comment by reserveword** [comment]
我即使把请求复制为curl命令到终端执行，返回的也是304结果，这个现象应该也是有问题的吧？

**Comment by MotooriKashin** [comment]
if ((status >= 200 && status < 300) || status === 304)

一般是这样子

**Comment by reserveword** [comment]
> 
> 看起来是弹幕分段的下标溢出了？可以帮忙看一下新版播放器有没有请求第五个seg.so？是这样的话可能计算弹幕分段数的代码要改了
> 

新版播放器好像会在播放到对应位置的时候才请求对应的分段，我看起来好像确实最多只有segment_index=4

然后，能不能写成即使只有部分请求成功也能加载收到的部分弹幕呢？这样即使有些请求失败了也不会一点弹幕都没有

**Comment by wly5556** [comment]
> if ((status >= 200 && status < 300) || status === 304)
一般是这样子

受教了🙇

”部分成功”时的处理逻辑之前有做，现在发现代码有个地方写错了，就没有按期运作🙇🙇
已经去改了，最迟明天下午把新版本脚本发出来

**Comment by MotooriKashin** [comment]
已推送 @wly5556 的修改，我这边测试没问题了。

**Comment by wly5556** [comment]
请求超出范围的弹幕片段的原因是旧播放器把番剧视频结尾那个展示”番剧承包榜“的时段直接算到视频时长里了，新播放器没有
感觉可以直接把这个环节去掉，现在自动切p要等15+5秒，体验不太舒适
