### ISSUE TITLE
无法使用了[Bug]

### ISSUE THREAD

**Issue by 3arrow** [MotooriKashin/Bilibili-Old#296]
fans/follow:1 
        
       [Report Only] Refused to load the stylesheet 'https://at.alicdn.com/t/font_438759_d66lkuno6c9.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline' *.hdslb.com static.geetest.com". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

fans/follow:1 
        
       [Report Only] Refused to load the font 'https://at.alicdn.com/t/font_438759_d66lkuno6c9.woff2?t=1636699893382' because it violates the following Content Security Policy directive: "default-src 'self' data: *.bilibili.com *.hdslb.com". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

fans/follow:1 
        
       [Report Only] Refused to load the font 'https://at.alicdn.com/t/font_438759_d66lkuno6c9.woff?t=1636699893382' because it violates the following Content Security Policy directive: "default-src 'self' data: *.bilibili.com *.hdslb.com". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

fans/follow:1 
        
       [Report Only] Refused to load the font 'https://at.alicdn.com/t/font_438759_d66lkuno6c9.ttf?t=1636699893382' because it violates the following Content Security Policy directive: "default-src 'self' data: *.bilibili.com *.hdslb.com". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

space.62463b842fcc1c3da3a9d7fdb7aeff7003c94f70.js:1                      //         \\         //          \\       //    ##DDDDDDDDDDDDDDDDDDDDDD##    ## DDDDDDDDDDDDDDDDDDDD ##   ________   ___   ___        ___   ________   ___   ___        ___    ## hh                hh ##   |\   __  \ |\  \ |\  \      |\  \ |\   __  \ |\  \ |\  \      |\  \    ## hh    //    \\    hh ##   \ \  \|\ /_\ \  \\ \  \     \ \  \\ \  \|\ /_\ \  \\ \  \     \ \  \    ## hh   //      \\   hh ##    \ \   __  \\ \  \\ \  \     \ \  \\ \   __  \\ \  \\ \  \     \ \  \    ## hh                hh ##     \ \  \|\  \\ \  \\ \  \____ \ \  \\ \  \|\  \\ \  \\ \  \____ \ \  \    ## hh      wwww      hh ##      \ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\    ## hh                hh ##       \|_______| \|__| \|_______| \|__| \|_______| \|__| \|_______| \|__|    ## MMMMMMMMMMMMMMMMMMMM ##    ##MMMMMMMMMMMMMMMMMMMMMM##                             Release 2.43.0. Powered by jinkela-core 2.8.10.         \/            \/
s1.hdslb.com/bfs/seed/log/report/log-reporter.js:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
sentry-5.2.1.min.js:2 
        
       log-reporter.js加载失败，放弃上报
(匿名) @ sentry-5.2.1.min.js:2
5.space.62463b842fcc1c3da3a9d7fdb7aeff7003c94f70.js:1 
        
       Uncaught TypeError: r.reportCustomData is not a function
    at mr (5.space.62463b842fcc1c3da3a9d7fdb7aeff7003c94f70.js:1:1048533)
    at 5.space.62463b842fcc1c3da3a9d7fdb7aeff7003c94f70.js:1:1049671
    at HTMLDivElement.__i18r__callback (5.space.62463b842fcc1c3da3a9d7fdb7aeff7003c94f70.js:1:1049688)
    at 5.space.62463b842fcc1c3da3a9d7fdb7aeff7003c94f70.js:1:1049104
    at Array.forEach (<anonymous>)
    at IntersectionObserver.gr (5.space.62463b842fcc1c3da3a9d7fdb7aeff7003c94f70.js:1:1048997)
dynamic:1 
        
       [Report Only] Refused to load the stylesheet 'https://at.alicdn.com/t/font_438759_d66lkuno6c9.css' because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline' *.hdslb.com static.geetest.com". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

DevTools 无法加载源映射： 无法加载https://s1.hdslb.com/bfs/static/jinkela/space/css/space.4.62463b842fcc1c3da3a9d7fdb7aeff7003c94f70.css.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载源映射： 无法加载https://s1.hdslb.com/bfs/static/jinkela/space/css/space.5.62463b842fcc1c3da3a9d7fdb7aeff7003c94f70.css.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载源映射： 无法加载https://s1.hdslb.com/bfs/static/jinkela/space/css/space.8.62463b842fcc1c3da3a9d7fdb7aeff7003c94f70.css.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载源映射： 无法加载https://s1.hdslb.com/bfs/static/jinkela/space/css/space.23.62463b842fcc1c3da3a9d7fdb7aeff7003c94f70.css.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载源映射： 无法加载https://s1.hdslb.com/bfs/static/jinkela/space/css/space.2.62463b842fcc1c3da3a9d7fdb7aeff7003c94f70.css.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools 无法加载源映射： 无法加载https://s1.hdslb.com/bfs/static/jinkela/space/css/space.9.62463b842fcc1c3da3a9d7fdb7aeff7003c94f70.css.map 的内容:HTTP 错误: 状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE
VM232:16 
        
       @resource: can't load @resource 'protobuf.js' from URL 'https://cdn.jsdelivr.net/npm/protobufjs@6.10.1/dist/protobuf.min.js': timed out
getText @ VM232:16
eval @ webSocket.js:6
importModule @ main.js:42
eval @ protoDm.js:5
importModule @ main.js:42
eval @ vector.js:55
importModule @ main.js:42
eval @ main.js:63
(匿名) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:18452
tms_36e58523_b7e4_4825_b541_0c247a32e35b$ @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:18453
it @ VM193:14
(匿名) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:1
(匿名) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:1
window.__p__2802756.8495202707 @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:18455
it @ VM193:14
set @ VM193:3
(匿名) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:1
eval @ VM158 common.js:2
(匿名) @ VM159 content.js:127
(匿名) @ VM159 content.js:108
it @ VM193:14
D.<computed>.I.<computed> @ VM193:4
it @ VM193:14
y @ VM193:6
send @ VM193:7
V @ VM193:3
(匿名) @ VM193:4
E_u @ VM193:4
(匿名) @ VM232:64
create @ VM232:65
l @ VM232:6
n @ VM232:5
run @ VM232:6
(匿名) @ VM232:67
it @ VM193:14
t @ VM193:15
(匿名) @ VM232:67
(匿名) @ VM232:67
TM_back @ VM232:68
window.__c__19537282.71857254 @ VM232:68
it @ VM193:14
set @ VM193:3
(匿名) @ VM232:1
eval @ VM158 common.js:2
(匿名) @ VM159 content.js:134
E @ VM159 content.js:134
(匿名) @ VM159 content.js:128
Show 17 more frames
VM259:16 
        
       @resource: can't load @resource 'protobuf.js' from URL 'https://cdn.jsdelivr.net/npm/protobufjs@6.10.1/dist/protobuf.min.js': timed out
getText @ VM259:16
eval @ webSocket.js:6
importModule @ main.js:42
eval @ protoDm.js:5
importModule @ main.js:42
eval @ vector.js:55
importModule @ main.js:42
eval @ main.js:63
(匿名) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:18452
tms_36e58523_b7e4_4825_b541_0c247a32e35b$ @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:18453
it @ VM214:14
(匿名) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:1
(匿名) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:1
window.__p__2382936.214465044 @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:18455
it @ VM214:14
set @ VM214:3
(匿名) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:1
eval @ VM158 common.js:2
(匿名) @ VM159 content.js:127
(匿名) @ VM159 content.js:108
it @ VM214:14
D.<computed>.I.<computed> @ VM214:4
it @ VM214:14
y @ VM214:6
send @ VM214:7
V @ VM214:3
(匿名) @ VM214:4
E_u @ VM214:4
(匿名) @ VM259:64
create @ VM259:65
l @ VM259:6
n @ VM259:5
run @ VM259:6
(匿名) @ VM259:67
it @ VM214:14
t @ VM214:15
(匿名) @ VM259:67
(匿名) @ VM259:67
TM_back @ VM259:68
window.__c__18242093.313604128 @ VM259:68
it @ VM214:14
set @ VM214:3
(匿名) @ VM259:1
eval @ VM158 common.js:2
(匿名) @ VM159 content.js:134
E @ VM159 content.js:134
(匿名) @ VM159 content.js:128
Show 17 more frames
webSocket.js:7 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Root')
    at eval (webSocket.js:7:34)
    at Proxy.importModule (main.js:42:79)
    at eval (protoDm.js:5:9)
    at Proxy.importModule (main.js:42:79)
    at eval (vector.js:55:31)
    at Proxy.importModule (main.js:42:79)
    at eval (main.js:63:9)
    at userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:18452:54
    at Proxy.tms_36e58523_b7e4_4825_b541_0c247a32e35b$ (userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:18453:3)
    at it (<anonymous>:14:1074)
    at userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:1:125
    at userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:1:692
    at Object.window.__p__2802756.8495202707 (userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:18455:6)
    at it (<anonymous>:14:1074)
    at set (<anonymous>:3:400)
    at userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:1:35
    at it (<anonymous>:14:1074)
    at D.<computed>.I.<computed> (<anonymous>:4:485)
    at it (<anonymous>:14:1074)
    at y (<anonymous>:6:39)
    at Object.send (<anonymous>:7:128)
    at V (<anonymous>:3:307)
    at <anonymous>:4:275
    at E_u (<anonymous>:4:330)
    at <anonymous>:64:44
    at Object.create (<anonymous>:65:178)
    at l (<anonymous>:6:96)
    at n (<anonymous>:5:325)
    at Object.run (<anonymous>:6:188)
    at <anonymous>:67:49
    at it (<anonymous>:14:1074)
    at t (<anonymous>:15:364)
    at <anonymous>:67:30
    at <anonymous>:67:59
    at TM_back (<anonymous>:68:3)
    at Object.window.__c__19537282.71857254 (<anonymous>:68:10)
    at it (<anonymous>:14:1074)
    at set (<anonymous>:3:400)
    at <anonymous>:1:34
eval @ webSocket.js:7
importModule @ main.js:42
eval @ protoDm.js:5
importModule @ main.js:42
eval @ vector.js:55
importModule @ main.js:42
eval @ main.js:63
(匿名) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:18452
tms_36e58523_b7e4_4825_b541_0c247a32e35b$ @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:18453
it @ VM193:14
(匿名) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:1
(匿名) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:1
window.__p__2802756.8495202707 @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:18455
it @ VM193:14
set @ VM193:3
(匿名) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:1
it @ VM193:14
D.<computed>.I.<computed> @ VM193:4
it @ VM193:14
y @ VM193:6
send @ VM193:7
V @ VM193:3
(匿名) @ VM193:4
E_u @ VM193:4
(匿名) @ VM232:64
create @ VM232:65
l @ VM232:6
n @ VM232:5
run @ VM232:6
(匿名) @ VM232:67
it @ VM193:14
t @ VM193:15
(匿名) @ VM232:67
(匿名) @ VM232:67
TM_back @ VM232:68
window.__c__19537282.71857254 @ VM232:68
it @ VM193:14
set @ VM193:3
(匿名) @ VM232:1
Show 9 more frames
webSocket.js:7 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Root')
    at eval (webSocket.js:7:34)
    at Proxy.importModule (main.js:42:79)
    at eval (protoDm.js:5:9)
    at Proxy.importModule (main.js:42:79)
    at eval (vector.js:55:31)
    at Proxy.importModule (main.js:42:79)
    at eval (main.js:63:9)
    at userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:18452:54
    at Proxy.tms_36e58523_b7e4_4825_b541_0c247a32e35b$ (userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:18453:3)
    at it (<anonymous>:14:1074)
eval @ webSocket.js:7
importModule @ main.js:42
eval @ protoDm.js:5
importModule @ main.js:42
eval @ vector.js:55
importModule @ main.js:42
eval @ main.js:63
(匿名) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:18452
tms_36e58523_b7e4_4825_b541_0c247a32e35b$ @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:18453
it @ VM214:14
(匿名) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:1
(匿名) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:1
window.__p__2382936.214465044 @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:18455
it @ VM214:14
set @ VM214:3
(匿名) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=36e58523-b7e4-4825-b541-0c247a32e35b:1
it @ VM214:14
D.<computed>.I.<computed> @ VM214:4
it @ VM214:14
y @ VM214:6
send @ VM214:7
V @ VM214:3
(匿名) @ VM214:4
E_u @ VM214:4
(匿名) @ VM259:64
create @ VM259:65
l @ VM259:6
n @ VM259:5
run @ VM259:6
(匿名) @ VM259:67
it @ VM214:14
t @ VM214:15
(匿名) @ VM259:67
(匿名) @ VM259:67
TM_back @ VM259:68
window.__c__18242093.313604128 @ VM259:68
it @ VM214:14
set @ VM214:3
(匿名) @ VM259:1
Show 9 more frames

**Comment by MotooriKashin** [comment]
cdn问题，资源更新失败，请临时关闭“新版弹幕”功能。  

自从jsdelivr离开大陆后，这类问题时有发生。不知道国内的静态资源CDN有谁提供protobuf.js资源，本来想替换一下，可找来找去找不到，难道是protobuf.js太小众了？
