### ISSUE TITLE
[Bug]就在刚才（45分钟前），b站的网页端又无法显示评论了

### ISSUE THREAD

**Issue by monkeywoora** [MotooriKashin/Bilibili-Old#299]
**问题详情**
就在刚才（45分钟前），b站的网页端又无法显示评论了。

**相关截图**
[https://imgtu.com/i/ObQzlD](url)
**运行环境**
 - 操作系统：Windows 10 家庭中文版 19043.1706
 - 浏览器：Google Chrome 101.0.4951.67
 - 脚本管理器：Tampermonkey 4.16.1

**补充内容**
是不是Cherry把旧的评论区API接口彻底和谐了的缘故呢？

**Comment by MotooriKashin** [comment]
更新到最新版了吗？是不是CDN问题？

ps:截图可以不用保存为文件直接粘贴进输入框，更不用使用图床

**Comment by monkeywoora** [comment]
不好意思，是我表达有问题：我说的是那个“Bilibili 翻页评论区”那个油猴脚本的问题……
