### ISSUE TITLE
能否实现在旧版播放页点赞

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [MotooriKashin/Bilibili-Old#3]
如题，旧版播放器什么都好就是不知道应该在哪里给视频点赞

**Comment by MotooriKashin** [comment]
从不点赞的某人表示都快忘了还有这个功能，会尝试着添加看看

**Comment by MotooriKashin** [comment]
@Aira-Sakuranomiya 已初步添加了点赞功能，只在av(BV)页，并且默认不开启，可自行在设置里打开
因为番剧页不会有此功能，而稍后再看本身投币功能就有bug
添加一项功能就占用了一定位置，点赞功能并不是为旧版页面原生设计，可能会导致网页分辨率低时布局移位，一行不够显示又多出来一行，影响网页美观，所以默认不开启这个功能。
当然当网页分辨率足够(一般只要不主动缩小窗口来说都够)是不会有问题的
功能设计得有点简陋，除了图标会变色以外没有其他反馈，不会有新版那种长达几秒的动画特效，也没有实现旧版收藏/投币那种蹦跶效果，请多担待！

另外，又由于旧版页面原生并没有点赞功能，所以B站也没提供合适的图标(或者我没找到？)，妥协地使用了追番的图标，正好点赞(大拇指)与追番(爱心)不会出现在同一界面，所以大概不会冲撞吧。
