### ISSUE TITLE
[Bug]昨天看错了，是“Bilibili翻页评论区 ”那个脚本

### ISSUE THREAD

**Issue by monkeywoora** [MotooriKashin/Bilibili-Old#300]
问题详情
就在昨天，b站的网页端又无法显示评论了。

相关截图
[https://imgtu.com/i/ObQzlD](https://github.com/MotooriKashin/Bilibili-Old/issues/url)
运行环境

操作系统：Windows 10 家庭中文版 19043.1706
浏览器：Google Chrome 101.0.4951.67
脚本管理器：Tampermonkey 4.16.1
脚本版本： 1.0.1
补充内容
是不是Cherry把旧的评论区API接口彻底和谐了的缘故呢？

**Comment by MotooriKashin** [comment]
姑且也把CDN域名换为fastly，那个脚本太久没更新，可能会过一段时间重构一下。其他相关问题不一一回复了。
