### ISSUE TITLE
[Bug] 更新了最新的脚本但还是不能加载弹幕

### ISSUE THREAD

**Issue by nzd7xW5** [MotooriKashin/Bilibili-Old#304]
**问题详情**
打开视频时，网页会短暂显示“视频去哪了呢？”然后又跳转回正常的视频页，但此时无法加载弹幕列表

**复现步骤**
1. 视频地址 https://www.bilibili.com/video/av341787877?from=search
2. 浏览器 Chrome Version 101.0.4951.64 (Official Build) (arm64)
3. 系统 mac OS 12.2.1 (21D62)

**相关截图**
网页短暂显示“视频去哪了呢？”
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/69294448/169901780-f7b1406d-93c6-4586-99ca-92e7dcc69750.png">
之后会重新加载正常的视频页，但是获取不到弹幕
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/69294448/169901914-1911de3b-e3d9-4113-b673-81b1cf096bd5.png">
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/69294448/169901923-0b9e3d46-0599-492f-b3e6-3fff5530c9c4.png">

**补充内容**
脚本版本：
// ==UserScript==
// @name         Bilibili 旧播放页
// @namespace    MotooriKashin
// @version      8.0.2

**Comment by MotooriKashin** [comment]
是不是可以关闭pakku测试一下，看控制台日志pakku成功hook到了弹幕，之后就没动静了

**Comment by nzd7xW5** [comment]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/69294448/169916747-9acb5f39-aefe-4088-a08d-94b19a8755fd.png">
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/69294448/169916760-f17bfad9-91e2-4dbf-84ba-be4f0d8f2ac0.png">
关掉了也一样

**Comment by MotooriKashin** [comment]
> <img alt="image" width="1552" src="https://user-images.githubusercontent.com/69294448/169916747-9acb5f39-aefe-4088-a08d-94b19a8755fd.png">
> 
> <img alt="image" width="1552" src="https://user-images.githubusercontent.com/69294448/169916760-f17bfad9-91e2-4dbf-84ba-be4f0d8f2ac0.png">
> 
> 关掉了也一样

你这两张截图中似乎并没有关闭pakku啊

**Comment by nzd7xW5** [comment]
但是你看右上角，pakku已经调成休眠状态了啊，难道需要卸载吗？那看来是pakku的问题？

**Comment by nzd7xW5** [comment]
额还真是卸载了pakku就好了 emmm 又是什么离谱的兼容问题

**Comment by MotooriKashin** [comment]
> 但是你看右上角，pakku已经调成休眠状态了啊，难道需要卸载吗？那看来是pakku的问题？

拓展程序应该有禁用选项吧，像这样
![image](https://user-images.githubusercontent.com/60416767/169919851-84cba204-1c07-4d3e-86c4-411cd70b2438.png)

你这两张图中，pakku虽然休眠却还是hook了xhr请求，无法判断原因在哪

**Comment by nzd7xW5** [comment]
有什么办法可以把我们的整个对话拷贝到issues/283去吗🥲

**Comment by MotooriKashin** [comment]
现在脚本再加载弹幕时会实时显示进度，像这样：
![image](https://user-images.githubusercontent.com/60416767/169920334-5e0721c9-3a06-40fc-8834-a3ab74c0861b.png)

而你那图中就没有，就好像根本没有发送弹幕请求似的

**Comment by nzd7xW5** [comment]
好吧，卸载pakku之后弹幕是能加载了，但是界面还是会有闪一下“视频不见了”再重新加载原视频的问题

**Comment by nzd7xW5** [comment]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/69294448/169920555-b1d62a79-0777-472d-b8d4-587d4d0769bd.png">
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/69294448/169920566-1e064d85-7a0b-4f02-b7b9-58e386fac3c7.png">

**Comment by MotooriKashin** [comment]
> 好吧，卸载pakku之后弹幕是能加载了，但是界面还是会有闪一下“视频不见了”再重新加载原视频的问题

这是正常的，因为为了加快页面重构速度，现在是先重构再请求页面数据，重构时没有视频数据，页面就会询问“视频去哪了”

**Comment by nzd7xW5** [comment]
明白了，把重写换成重定向之后就可以和pakku继续兼容了，完全没有问题了

虽然pakku被禁用之后仍然生效这一点还是挺奇怪的

**Comment by MotooriKashin** [comment]
> 明白了，把重写换成重定向之后就可以和pakku继续兼容了，完全没有问题了
> 
> 虽然pakku被禁用之后仍然生效这一点还是挺奇怪的

原来还是重写方法的问题，【重定向】模式本来就是为兼容性提供的备选方案，能有效就太好了。
