### ISSUE TITLE
[Bug] 脚本未适配 s/video 页面

### ISSUE THREAD

**Issue by nzd7xW5** [MotooriKashin/Bilibili-Old#305]
如题，对于类似于
https://www.bilibili.com/video/av341787877
https://www.bilibili.com/video/av34178721
的界面，脚本可以顺利打开。但对于
https://www.bilibili.com/video/s/av341787877
https://www.bilibili.com/video/s/av34178721
界面，脚本一直没有适配。在这些界面上播放器似乎是不生效的。

**Comment by MotooriKashin** [comment]
的确，忘记SEO页面了

**Comment by nzd7xW5** [comment]
不好意思 是我上面打错了
s/video的页面应该是s在video前面，像这样
https://www.bilibili.com/s/video/av341787877
https://www.bilibili.com/s/video/av34178721
弄错了😵‍💫

**Comment by MotooriKashin** [comment]
编译推送还是留待傍晚吧🤣
