### ISSUE TITLE
[Feature Requset]现在旧版首页不能看个性推荐吗

### ISSUE THREAD

**Issue by meiruitesi** [MotooriKashin/Bilibili-Old#306]
**存在问题**
还是想看首页的个性化推荐

**目标愿景**
恢复以前的脚本的使用新版个性化推荐的功能
![QQ截图20220525082530](https://user-images.githubusercontent.com/84609642/170153122-72d4cdfd-31f5-442a-aa37-7f42a1fb56d9.png)

**Comment by MotooriKashin** [comment]
的确，升级重写机制时疏忽了。
