### ISSUE TITLE
弹幕字号太大

### ISSUE THREAD

**Issue by 3arrow** [MotooriKashin/Bilibili-Old#308]

**Comment by MotooriKashin** [comment]
你需要的莫不是这个？
![image](https://user-images.githubusercontent.com/60416767/170590178-41db4741-897c-4337-897e-c947186b2600.png)

**Comment by 3arrow** [comment]
![屏幕截图 2022-05-27 161818](https://user-images.githubusercontent.com/87346627/170660283-14d1e4f2-469c-4826-8f6e-ea429268093d.png)

**Comment by 3arrow** [comment]
还是这样
