### ISSUE TITLE
[Feature Requset]

### ISSUE THREAD

**Issue by sddddd213** [MotooriKashin/Bilibili-Old#309]
**存在问题**
动画的单集数据消失，现在展示的总的动画数据。
![QQ图片20220527000947](https://user-images.githubusercontent.com/38841494/170528674-d0800d23-4c8e-4b7a-a2c3-752f6f7673fc.png)

**目标愿景**
希望该功能能恢复。之前的版本里有对应的功能，好像就叫【分集数据】？

**参考建议**
无

**补充内容**
【toastr】的开关影响使用吗？

**Comment by MotooriKashin** [comment]
啊，的确是忘了🤣
