### ISSUE TITLE
20201109更新后失效

### ISSUE THREAD

**Issue by DarkXelNaga** [MotooriKashin/Bilibili-Old#31]
更新脚本后失效，已经尝试过重新安装脚本，不能解决

**Comment by MotooriKashin** [comment]
能不能提供一下报错数据？

**Comment by DarkXelNaga** [comment]
> 
> 
> 能不能提供一下报错数据？

F12控制台内容如下：
>content: normal start event processing for f1e80e78-8c3a-4cbd-b925-68447148c340 (1 to run) content.js:28:175
content: Start ENV normally f1e80e78-8c3a-4cbd-b925-68447148c340 content.js:12:208
env: initialized (content, id:f1e80e78-8..., https://www.bilibili.com/) eval line 1 > Function:13:251
Tampermonkey started eval line 1 > Function:74:460
env: run "Bilibili 旧播放页" ASAP -> document-start eval line 1 > Function:12:265
env: execute script Bilibili 旧播放页 @ the safe context now! eval line 1 > Function:73:163
即使其 MIME 类型（“text/plain”）不是有效的 JavaScript MIME 类型，仍已加载来自“https://www.bilibili.com/gentleman/polyfill.js?features=Promise%2CObject.assign%2CString.prototype.includes%2CNumber.isNaN”的脚本。[详细了解] www.bilibili.com
Syntax error @ "Bilibili 旧播放页"!
##########################
JSHINT output:
##########################

>F_a/T</<@eval:3:98
N@eval:2:148
E_u/<@eval:3:264
Ka@eval line 1 > Function:61:373
create@eval line 1 > Function:73:235
run@eval line 1 > Function:12:322
anonymous/</</<@eval line 1 > Function:74:502
F_a/T</<@eval:3:98
N@eval:2:148
anonymous/</<@eval line 1 > Function:74:486
anonymous/<@eval line 1 > Function:10:913
TM_back@eval line 1 > Function:3:259
anonymous@eval line 1 > Function:3:31
F_a/T</<@eval:3:98
exec_fn@eval:1:155
@eval:12:468
Aa@eval:11:177
eval line 1 > Function:62:342
SyntaxError: dynamic module import is not implemented eval:9737:79

                     //
         \\         //
          \\       //
    ##DDDDDDDDDDDDDDDDDDDDDD##
    ## DDDDDDDDDDDDDDDDDDDD ##   ________   ___   ___        ___   ________   ___   ___        ___
    ## hh                hh ##   |\   __  \ |\  \ |\  \      |\  \ |\   __  \ |\  \ |\  \      |\  \
    ## hh    //    \\    hh ##   \ \  \|\ /_\ \  \\ \  \     \ \  \\ \  \|\ /_\ \  \\ \  \     \ \  \
    ## hh   //      \\   hh ##    \ \   __  \\ \  \\ \  \     \ \  \\ \   __  \\ \  \\ \  \     \ \  \
    ## hh                hh ##     \ \  \|\  \\ \  \\ \  \____ \ \  \\ \  \|\  \\ \  \\ \  \____ \ \  \
    ## hh      wwww      hh ##      \ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\
    ## hh                hh ##       \|_______| \|__| \|_______| \|__| \|_______| \|__| \|_______| \|__|
    ## MMMMMMMMMMMMMMMMMMMM ##
    ##MMMMMMMMMMMMMMMMMMMMMM##                             Release 2.6.1. Powered by jinkela-core 2.8.3.
         \/            \/ international-home.6395933647838c973480598b9d75d2e94c363819.js:1:5156
>content: detected DOMContentLoaded f1e80e78-8c3a-4cbd-b925-68447148c340 content.js:9:266
content: normal start event processing for fd6c7458-f621-48c7-b784-56710271d386 (1 to run) content.js:28:175
content: Start ENV normally fd6c7458-f621-48c7-b784-56710271d386 content.js:12:208
env: initialized (content, id:fd6c7458-f..., https://message.bilibili.com/pages/nav/index_new_pc_sync) eval line 1 > Function:13:251
Tampermonkey started eval line 1 > Function:74:460
env: run "Bilibili 旧播放页" ASAP -> document-start eval line 1 > Function:12:265
env: execute script Bilibili 旧播放页 @ the safe context now! eval line 1 > Function:73:163
Syntax error @ "Bilibili 旧播放页"!
##########################
JSHINT output:
##########################

>F_a/T</<@eval:3:98
N@eval:2:148
E_u/<@eval:3:264
Ka@eval line 1 > Function:61:373
create@eval line 1 > Function:73:235
run@eval line 1 > Function:12:322
anonymous/</</<@eval line 1 > Function:74:502
F_a/T</<@eval:3:98
N@eval:2:148
anonymous/</<@eval line 1 > Function:74:486
anonymous/<@eval line 1 > Function:10:913
TM_back@eval line 1 > Function:3:259
anonymous@eval line 1 > Function:3:31
F_a/T</<@eval:3:98
exec_fn@eval:1:155
@eval:12:468
Aa@eval:11:177
eval line 1 > Function:62:342
SyntaxError: dynamic module import is not implemented eval:9737:79
content: detected DOMContentLoaded fd6c7458-f621-48c7-b784-56710271d386 content.js:9:266
content: detected load fd6c7458-f621-48c7-b784-56710271d386 content.js:9:412
content: detected load f1e80e78-8c3a-4cbd-b925-68447148c340 content.js:9:412
源映射错误：request failed with status 404
源 URL：https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/sentry-5.7.1.vue.min.js
源映射 URL：vue.min.js.map
源映射错误：request failed with status 404
源 URL：https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/sentry-5.7.1.min.js
源映射 URL：bundle.min.js.map

**Comment by MotooriKashin** [comment]
语法错误？不应该啊，我这边怎么没事？

**Comment by DarkXelNaga** [comment]
> 
> 
> 语法错误？不应该啊，我这边怎么没事？

……该不会是我火狐版本过低（66.0.5）的原因吧？

**Comment by MotooriKashin** [comment]
可能用了什么新特性不支持，控制台能定位具体哪句代码出错了吗？截图最好，这样复制过来一大团看不懂
我先回滚回去，反正也没什么重要更新

**Comment by DarkXelNaga** [comment]
![TIM截图20201109183904](https://user-images.githubusercontent.com/45918215/98531208-fb481a00-22ba-11eb-8219-c633df93dc30.png)

**Comment by DarkXelNaga** [comment]
上面那张是播放页的，下面这张是首页的

以及在更新浏览器后就不报错正常生效了

![TIM图片20201109184159](https://user-images.githubusercontent.com/45918215/98531813-db652600-22bb-11eb-918a-8ddf3bfaf468.png)

**Comment by MotooriKashin** [comment]
果然是`import`出的事！
我就用了两个`import`用来引入哈希算法md5和crc，这两个用的时候少，偏偏代码又老长，我是真想把它们放到单独的模块里去。
