### ISSUE TITLE
[Bug]“视频去哪了呢”的标题一闪而过

### ISSUE THREAD

**Issue by meiruitesi** [MotooriKashin/Bilibili-Old#310]
**问题详情**
如图
![image](https://user-images.githubusercontent.com/84609642/170657637-c9bcfccd-b9dc-43ca-8011-7416fe26bb1f.png)
![image](https://user-images.githubusercontent.com/84609642/170658176-ff5efefa-9e34-4366-b37a-16dc569a96cf.png)

**复现步骤**
打开任意一个视频

**相关截图**
![image](https://user-images.githubusercontent.com/84609642/170657841-6a7e80e2-43bf-4cc7-9f8a-742e49d6f6dd.png)

**运行环境**
 - 操作系统：Windows11 professional 10.0.22621.1
 - 浏览器：Microsoft Edge Beta 102.0.1245.14
 - 脚本管理器：Tampermonkey 4.16.1

**Comment by MotooriKashin** [comment]
为了加快重写速度，现在是先重写再获取视频数据，在获取之前就会显示这个。
