### ISSUE TITLE
请问一下脚本中这个API的来源？还有类似的吗

### ISSUE THREAD

**Issue by SekiBetu** [MotooriKashin/Bilibili-Old#311]
https://account.bilibili.com/api/member/getCardByMid

**Comment by MotooriKashin** [comment]
B站曾经开源过的API文档（现在应该已经删除了

**Comment by SekiBetu** [comment]
> B站曾经开源过的API文档（现在应该已经删除了

细说，有以前的链接吗，链接就行

**Comment by MotooriKashin** [comment]
> 细说，有以前的链接吗，链接就行

很抱歉我也是这两年才入的B站，所以也没经历过那个时代，因为好像不是开源到Github，而B站主站域名下的一个网址，我也不知道链接。这个接口应该是Github上某个涉及B站的远古项目里淘来的——有一段时间为了不借助第三方接口获取失效信息，疯狂在Github上阅读老项目，遇到没见过的API就记下来测试，这个接口应该就是那时找到的。原谅我并没有记下具体的项目地址（当时开源意识淡漠🤣

**Comment by MotooriKashin** [comment]
*因为是上古接口，B站自身可能都遗忘了，都没给CORS跨域标头！而且这类接口也不宜声张，不然某天突然就失效了……*
