### ISSUE TITLE
[Bug] 今天bilibili翻页评论区无法使用

### ISSUE THREAD

**Issue by xialuo928** [MotooriKashin/Bilibili-Old#312]
**问题详情**
打开视频后评论区一片空白。关闭脚本后正常显示。这个功能下线了吗。

**相关截图**
![QQ截图20220527231352](https://user-images.githubusercontent.com/106337606/170728835-3059a9e5-1cf7-4f9f-a355-5181ce66498e.png)
![QQ截图20220527231343](https://user-images.githubusercontent.com/106337606/170728936-e425ed46-5806-4f11-961d-ea1cd4654ef0.png)

**运行环境**
 - 操作系统：Windows 10 专业版
 - 浏览器：Microsoft Edge 101.0.1210.53 (正式版本) (64 位
 - 脚本管理器：Tampermonkey 4.16.1

**Comment by MotooriKashin** [comment]
由于CDN被墙，本来已经放弃维护那个脚本，这次只更新了最低限度的翻页支持，硬核会员等后续更新就不管了。

**Comment by xialuo928** [comment]
> 由于CDN被墙，本来已经放弃维护那个脚本，这次只更新了最低限度的翻页支持，硬核会员等后续更新就不管了。

非常感谢！
