### ISSUE TITLE
[Feature Requset]可以添加一个自动取消视频五秒连播功能吗

### ISSUE THREAD

**Issue by claresongs** [MotooriKashin/Bilibili-Old#316]
**存在问题**
目前存在什么问题。

**目标愿景**
希望实现的目标。

**参考建议**
可以供参考的建议。

**补充内容**
其他补充内容。

**Comment by MotooriKashin** [comment]
弹幕列表上方有个设置齿轮，或许你是在找这个
![image](https://user-images.githubusercontent.com/60416767/172730067-5d6a108b-a38a-41cf-94f9-30b00e6c46ff.png)

**Comment by claresongs** [comment]
是的 感谢大佬
