### ISSUE TITLE
找不到设置的齿轮，只看到了设置弹幕的齿轮

### ISSUE THREAD

**Issue by icer233** [MotooriKashin/Bilibili-Old#318]
**问题详情**
找不到设置的小齿轮

**复现步骤**
1. '...'
2. '...'
3. '...'

**相关截图**
可以的话，提供一下截图，最好是控制台报错截图

**运行环境**
 - 操作系统：Windows11 professional 10.0.22000.527
 - 浏览器：Edge
 - 脚本管理器：Tampermonkey 4.14.6125

**补充内容**
其他补充内容。

**Comment by icer233** [comment]
就是第一次安装脚本以后，打开bilibili有一个像弹窗一样的设置界面，找不到了，重装脚本也没有再次跳出来

**Comment by MotooriKashin** [comment]
如果没有调整过设置，齿轮会在页面页面右下角这个位置隐藏
![image](https://user-images.githubusercontent.com/60416767/172995928-50165e46-8e0d-4bbf-b25b-199ff8b6d9c7.png)
如果选择贴边隐藏，会在这里，鼠标移动到页面边缘浮现
![image](https://user-images.githubusercontent.com/60416767/172996042-3b59d693-376a-47ad-9cfb-560957c56f79.png)

如果是因为报错，请f12打开控制台，切换到console标签截图反馈报错情况  
或者切换到element标签看看有没有这个`bilibili-entry`节点（设置入口节点）
![image](https://user-images.githubusercontent.com/60416767/172996332-f03ab233-b3cc-4892-a9c2-009d74deeda2.png)

Tamepermonkey重装节点默认还要到【×】页面（相当于电脑的回收站）彻底删除，否则等于没有重装→_→
![image](https://user-images.githubusercontent.com/60416767/172996690-b82f2d27-2b58-480a-8a35-d7e49535b2a0.png)

**Comment by swxk521** [comment]
同样问题

**Comment by MotooriKashin** [comment]
如果有报错，请提供控制台截图，没有图图真的不知道如何排查。
