### ISSUE TITLE
评论区乱码

### ISSUE THREAD

**Issue by Sun0613** [MotooriKashin/Bilibili-Old#32]
<img width="751" alt="屏幕快照 2020-11-10 下午10 16 33" src="https://user-images.githubusercontent.com/46019412/98688502-e09e9f80-23a5-11eb-9084-8cec97a7f08c.png">

**Comment by wly5556** [comment]
https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5/discussions/66432
重新安装最新版本试试?

**Comment by Sun0613** [comment]
已解决
