### ISSUE TITLE
[Bug]comment.js加载失败

### ISSUE THREAD

**Issue by 3arrow** [MotooriKashin/Bilibili-Old#320]

**Comment by MotooriKashin** [comment]
![image](https://user-images.githubusercontent.com/60416767/173181139-9edf8d57-be55-4344-8b98-af05009ffddd.png)

是这个提示吗？  
如果是，评论区能够正常加载？能的话就放着吧，大概只是一时的网络问题。

**Comment by 3arrow** [comment]
是的但是加载不了弹幕也没有,要挂梯子

**Comment by MotooriKashin** [comment]
是这个链接无法访问吗？ https://fastly.jsdelivr.net/npm/protobufjs@6.11.0/dist/light/protobuf.min.js 

如果是，那就暂时关闭【托管原生脚本】和【启用新版弹幕】两个功能将就着用吧，目前没有别的办法🤣

**Comment by 3arrow** [comment]
ok了
