### ISSUE TITLE
[Bug] 反查弹幕发送者似乎失效

### ISSUE THREAD

**Issue by miss1ng** [MotooriKashin/Bilibili-Old#321]
**问题详情**
右键弹幕并不能查到弹幕发送者。只能显示 举报 屏蔽 复制三个按钮

**复现步骤**
1. '...'
2. '...'
3. '...'

**相关截图**
可以的话，提供一下截图，最好是控制台报错截图

**运行环境**
 - 操作系统：Windows11 professional 10.0.22000.527
 - 浏览器：Google Chrome 99.0.4844.74
 - 脚本管理器：Tampermonkey 4.14.6125

**补充内容**
其他补充内容。

**Comment by MotooriKashin** [comment]
似乎并没有，是不是你把设置关了？
![image](https://user-images.githubusercontent.com/60416767/174538962-ab6a17f1-6246-4f39-9921-f8f4c4b66c63.png)

**Comment by miss1ng** [comment]
> 似乎并没有，是不是你把设置关了？
> ![image](https://user-images.githubusercontent.com/60416767/174538962-ab6a17f1-6246-4f39-9921-f8f4c4b66c63.png)

打开了 但并没有生效🤔

**Comment by MotooriKashin** [comment]
那可能是关闭了【托管原生脚本】？
