### ISSUE TITLE
[Feature Requset] 移植为浏览器扩展(Manifest V3)

### ISSUE THREAD

**Issue by MotooriKashin** [MotooriKashin/Bilibili-Old#322]
随着Manifest V3标准的推行以及扩展的权限的进一步收紧，根据Manifest V3推进[时间表](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/)，6月起chrome拓展商店将不再接收旧标准的新扩展发布（已发布的旧标准扩展仍允许更新），最迟明年（2023）6月（chrome禁止运行旧标准扩展时间），现在所谓的油猴脚本（用户脚本）将在chrome浏览器上面临被封杀（参见[Tampermonkey作者的发文](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/hQeJzPbG-js)）的风险。凡事预则立，不预则废，为应对说远也不远的危机，提前将原油猴脚本移植为了符合Manifest V3标准的扩展，欢迎测试和反馈。  
Manifest V3 仍在快速更新标准，扩展使用最新标准编写，所以只能支持最新版chrome浏览器（内核版本>=102）。不保证兼容其他chrome内核浏览器，也暂时没有适配其他非chrome浏览器的计划。

---
### 注意事项
- 支持且只支持chrome浏览器（内核>=102）。
- 暂未上架扩展商店，要使用【加载已解压的扩展程序】加载解压的拓展（网上有相关教程）。
- 未添加版本检查，请自行到本页面检查跟新并使用上一条加载。
- 善用导出设置数据功能，【加载已解压的扩展程序】功能很容易导致设置数据丢失。
- 功能测试中，出现各种问题请多体谅，欢迎积极反馈！

更多详情请移步[dev](https://github.com/MotooriKashin/Bilibili-Old/tree/dev)分支或者[release](https://github.com/MotooriKashin/Bilibili-Old/releases)页面。

---
**原用户脚本将在主分支继续维护，不熟悉扩展架构也没问题，像过去一样在主分支贡献提交即可，移植工作交给我吧👌**

**Comment by yingziwu** [comment]
作者您好，我也是一名油猴脚本作者，可以交流一下将油猴脚本移植为浏览器扩展的经验吗？

将油猴脚本移植为浏览器扩展，我个人的感觉就是使用原生 API 将使用到的 GM API 重新实现一下，然后补上 ``manifest.json``，再将原有脚本作为 Content scripts 执行，或者调用 executeScript 执行。

但是看了一下 [background.js](https://github.com/MotooriKashin/Bilibili-Old/blob/dev/src/background.ts)，作者好像只实现了 ``GM_xmlhttpRequest``、``GM.cookie``，其余几个用到的权限，比如说：``GM_getResourceText``、``GM_getResourceURL``、``GM_getValue``、``GM_setValue``、``GM_deleteValue``、``GM_listValues`` 好像都没有实现。

除此而外，将油猴脚本移植为浏览器扩展，还有什么需要注意的地方吗？

**Comment by MotooriKashin** [comment]
> 将油猴脚本移植为浏览器扩展，还有什么需要注意的地方吗？

可以参看一下 https://github.com/MotooriKashin/Bilibili-Old/blob/dev/.github/contributing.md

> 我个人的感觉就是使用原生 API 将使用到的 GM API 重新实现一下

个人感觉要这么说也可以，但是指的应该是`GM.`系列而不是`GM_`系列，Manifest V3以后所有API应该都只能使用异步的，至少我没找到同步方法的实现思路。  

>  作者好像只实现了 GM_xmlhttpRequest、GM.cookie，其余几个用到的权限，比如说：GM_getResourceText、GM_getResourceURL、GM_getValue、GM_setValue、GM_deleteValue、GM_listValues 好像都没有实现。

因为我这里只有这两个需要实现，剩下的那几个其实都是基于`chrome.storage`拓展而来，我就用了目前能想到的同步方法中转，也就是使用`sessionStorage`，方便在Content scripts和userscript之间共享。因为我这个脚本是重写页面，涉及到要尽快拦截页面原生js文件执行，用`window.sendMessage`之类的方法等待异步返回可能黄花菜都凉了。`sessionStorage`是同步方法，且生命周期绑定标签页，个人以为是很方便的数据共享的替代，"GM_getResourceText、GM_getResourceURL、GM_getValue、GM_setValue、GM_deleteValue、GM_listValues"，这些本质都是要从`chrome.storage`获取数据的就都改用本方法了。  
不过原生`sessionStorage`只支持字符串数据，我在[storage.ts](https://github.com/MotooriKashin/Bilibili-Old/blob/dev/src/runtime/storage.ts)封装了一下自动格式化为其他基础数据类型。

个人也只是这两天为了移植才去看的chorme扩展文档，理解目前只有这些，欢迎一起分享经验。

**Comment by MotooriKashin** [comment]
由于`jsdelivr`被墙，就算是`fastly`好像也有部分地区无法访问。托管的`bilibiliPlayer.js`和`comment.js`还好说，可以临时禁用【托管原生脚本】解决，新版弹幕依赖的`protobuf.js`加载失败，体验就太差了。  
又因为移植未扩展的缘故，引入的前端打包工具`esbuild`，感觉可以把`protobuf.js`打包进脚本，反正也不大——唯一的问题是模块架构需要大改：从基于`namespace`的自创体系改为标准的es模块，感觉工程有点大🤣（虽然以本脚本动不动就重构的历史来看也不算什么就是了……  
还有一个问题就是`bilibiliPlayer.js`和`comment.js`这两个修改自B站的原生脚本，尤其是前者，实在是太大了！一起打包进脚本不现实，且必定超过`GreasyFork`的脚本大小限制。还是得靠CDN托管……  
不能彻底解决这些资源问题，重构的兴趣就大减了，而且由于本人已完全转向使用移植后的扩展版，更是不太想重构，所以干脆咕咕咕？！→_→

**Comment by MotooriKashin** [comment]
记一个问题：  
`sessionStorage`在同一个标签页的所有子页面中是通用的，用来同步传递脚本数据很完美，可是用来传递特定于页面的数据（如`aid`、`cid`等）就会相互覆盖导致错乱🤣，得想个稳妥的替代方案。

**Comment by MotooriKashin** [comment]
感觉MV3最大的问题就是内容脚本是个残废，而注入到`MAIN`环境中的脚本又无法与扩展其他部分直接通信，只能通过内容脚本中转🤣。听说（来源请求？）之后会支持`MAIN`脚本与扩展直接通信，但愿是真的，不然扩展编写起来实在束手束脚好没脾气ಥ_ಥ

**Comment by MotooriKashin** [comment]
从浏览器扩展反向打包回用户脚本的工作终于还是完成了，原以为需要添加大量兼容性代码，但是好像也不是太难。在chrome和Firefox上粗略测试了一下运行基本没问题，所以就大胆地推送过来了——终于不用维护两个分支两套代码了，万岁🎉🎉🎉

具体细节摘录如下：  https://github.com/MotooriKashin/Bilibili-Old/commit/9ee17074a6b6e2cf6ffcb8ab4fc3a9625916edae
1. 放弃自研的模块系统，启用es标准模块标准并使用esbuild进行打包。项目现在可以同时生成扩展和脚本，免去二者之间分裂现状。
2. 升级页面重构方案，去除原有选项，新方案基本是原“重定向”方案去重定向版本。升级了重构细节，页面出问题情况大幅减少。
3. esbuild打包工具的引入，弹幕protobuf引擎现在直接打包进了脚本，解决了原运行时因CDN问题导致弹幕无法加载问题。
4. 评论区有了新的恢复方案，新方案使用最新bbComment方案为基础，恢复了翻页功能。楼层相关则很难从瀑布流切换到翻页暂时搁置。
5. `bilibiliPlayer.js`虽然还是得托管才能维护，但现在在CDN不可用时会自动回滚回原版，至少保证了播放功能正常。
6. 扩展版本由于启动权限更高，重构页面基本不会有问题，但由于MV3只能异步获取存储数据，虽然有同步中转，部分全局功能还是得刷新才能获取设置。
7. 时间步步推进，MV3标准还是没有为用户脚本提供解决方案，个人还是期望用户脚本可以存货，当然扩展显然更香更稳定就是了。

**Comment by MotooriKashin** [comment]
重构扩展为类似了Tampermonkey那样的用户脚本启动器，以尽可能减少扩展和用户脚本的兼容性代码量便于维护。  
MV2标准停用时间已延后6个月，MV3标准也承诺着手支持脚本管理器——用户脚本到底不会彻底灭亡。  
于是，扩展似乎也没有上架的必要，毕竟由于众所周知的原因，用户脚本使用起来还是比扩展方便不少。再三思考后，本项目决定长期保留扩展和用户脚本版本，扩展只用于开发，不会正式发布，用户使用仍以用户脚本为主。
