### ISSUE TITLE
[Bug] 评论区出现手机端的搜索关键词

### ISSUE THREAD

**Issue by FrzMtrsprt** [MotooriKashin/Bilibili-Old#325]
**问题详情**
启用脚本后，评论区开始出现搜索关键词的链接，而且…全都是undefined…

**复现步骤**
1. 启用脚本
2. 观察评论区

**相关截图**
![image](https://user-images.githubusercontent.com/15852717/177026989-11901521-8096-44e9-a6b6-b0ce3843ffe7.png)

**运行环境**
 - 操作系统：Windows 11 专业版 10.0.25151.1010
 - 浏览器：Microsoft Edge 103.0.1264.44
 - 脚本管理器：Tampermonkey 4.16.1

**补充内容**
无

**Comment by MotooriKashin** [comment]
这个问题因为我没收到灰度测试，所以如何修复一时成了问题，会尽快想办法。

**Comment by nzd7xW5** [comment]
顶一下，我这里显示的倒不是undefined
<img width="585" alt="image" src="https://user-images.githubusercontent.com/69294448/177034964-0574f17b-162f-4452-ac19-c6a98ed8fb2a.png">
但还是希望作者们能直接出个选项把这玩意给屏蔽掉💀B站知乎都一群睿智天天地搞这些没用还关不掉的东西

**Comment by FrzMtrsprt** [comment]
emm…变成这样了233，有的链接有from_source追踪参数，有的只有keyword参数
![image](https://user-images.githubusercontent.com/15852717/177035807-84c77b99-da32-478f-b7e1-1afd6ae22638.png)

**Comment by MotooriKashin** [comment]
暂时禁用了，以后这种灰度中的活还是等全量以后再跟进，盲着修改只会漏洞百出🤣

**Comment by FrzMtrsprt** [comment]
感觉这样就挺好的，再去掉那个放大镜就完美了，辛苦大佬了🫠
![image](https://user-images.githubusercontent.com/15852717/177037187-0e9c36cc-73bb-4231-90f0-26a573488602.png)
这是那个放大镜的html
![image](https://user-images.githubusercontent.com/15852717/177037349-f6155c66-8563-4024-bf67-557dd08c969c.png)
放大镜图片url：https://i0.hdslb.com/bfs/reply/9f3ad0659e84c96a711b88dd33f4bc2e945045e0.png

**Comment by MotooriKashin** [comment]
嗯，已更新

**Comment by FrzMtrsprt** [comment]
感谢大佬
