### ISSUE TITLE
我是翻页评论区来的。

### ISSUE THREAD

**Issue by Towards-future** [MotooriKashin/Bilibili-Old#326]
最近你更新翻页评论区以后，依然没有效果，也是旧版。没有出现翻页评论的数字1 2 3这些。几乎就是看不到任何效果。

**Comment by MotooriKashin** [comment]
这一类问题好像的确有人出现，但我这边就是复现不了，而且也没有任何报错信息可供参考。这样，你提供一下平台信息：包括浏览器、Tampermonkey的版本，我用相同的平台测试看看。

**Comment by Towards-future** [comment]
360浏览器，tampermonkey 4.16.1，谷歌浏览器，也是tampermonkey 4.16.1。tampermonkey似乎是会自动更新的。你试试把tampermonkey更新到最新版本看看能不能用。

**Comment by Towards-future** [comment]
补充下，这两个浏览器开不开vpn都一样，没效果

**Comment by MotooriKashin** [comment]
> 补充下，这两个浏览器开不开vpn都一样，没效果

与VPN无关，翻页评论区没用用到需要CDN的资源

chrome的话，实在无法复现……

这样吧，请在任意一个有评论区的页面打开控制台，分别输入`bbComment`和`initComment`并回车，让我看看她们显示的到底都是啥可以吗？
![image](https://user-images.githubusercontent.com/60416767/177151023-b91f7225-c5b2-465e-81a1-f68436ec51fc.png)

**Comment by NightSharp** [comment]
> initComment

> > 补充下，这两个浏览器开不开vpn都一样，没效果
> 
> 与VPN无关，翻页评论区没用用到需要CDN的资源
> 
> chrome的话，实在无法复现……
> 
> 这样吧，请在任意一个有评论区的页面打开控制台，分别输入`bbComment`和`initComment`并回车，让我看看她们显示的到底都是啥可以吗？ ![image](https://user-images.githubusercontent.com/60416767/177151023-b91f7225-c5b2-465e-81a1-f68436ec51fc.png)

奇了怪了，我按照你在这里的说明调试的过程中突然就能正常显示了，迷惑ing

**Comment by MotooriKashin** [comment]
> 奇了怪了，我按照你在这里的说明调试的过程中突然就能正常显示了，迷惑ing

👌

**Comment by Towards-future** [comment]
![3J2_NZPXOX{{0L53)BSGVO0](https://user-images.githubusercontent.com/64130874/177336638-a958ef94-5c1a-4faf-ab8c-98782d2c63a5.png)

**Comment by Towards-future** [comment]
而且奇怪的是开了这个翻页评论区以后，本来正常的评论出现一堆乱七八糟的东西。这个放大镜符号。https://www.bilibili.com/video/BV16K4y1r7h2
![评论区乱码](https://user-images.githubusercontent.com/64130874/177337314-c011ef95-77dd-4c43-8350-f46e1186f5bf.png)

**Comment by NightSharp** [comment]
> > 奇了怪了，我按照你在这里的说明调试的过程中突然就能正常显示了，迷惑ing
> 
> 👌

突然又不行了，然后调试时过了一会有行了，太奇怪了，可能跟梯子把某些资源拦截了有关？

**Comment by MotooriKashin** [comment]
翻页评论区已基于新版本重置，是否还有类似问题？
