### ISSUE TITLE
[Bug]画质切换失败 FLV默认只获取1080P画质

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#327]
**问题详情**
如题 三个BUG

**复现步骤**

（使用ef2+IDM方式下载视频）
https://user-images.githubusercontent.com/77530593/178107805-73eb22b3-b7a3-4125-b4ae-85c2449576e3.mp4

PS.1080P60无法下载问题已解决

**相关截图**
控制台无报错

**运行环境**
 - 操作系统：Windows11 professional 10.0.22000.527
 - 浏览器：Google Chrome 99.0.4844.74
 - 脚本管理器：Tampermonkey 4.14.6125

**Comment by MotooriKashin** [comment]
画质切换失败那个暂时不清楚，应该是偶发的吧。

flv你可以在这是中启用开发者模式，然后在控制台输入`API.xhr.log()`并回车，我测试`qn`是会随着设置改变的：
![image](https://user-images.githubusercontent.com/60416767/178128062-f1b79862-52a9-44aa-ae04-1330c8f4b1cc.png)

但为什么只能获取到1080p，也是不太清楚，毕竟我不是大会员，最高只能1080P🤣

另外，下载面板是有缓存机制的，你打开一次下载面板之后就不会二次请求，调整设置后也请刷新页面。

**Comment by judgeou** [comment]
哔哩哔哩提供的flv格式最高就是1080p，再往上需要加 `fnval=4048` 参数，不过格式就会变成音视频分离的那种
