### ISSUE TITLE
[Bug]港澳台番剧视频加载失败

### ISSUE THREAD

**Issue by FromtoLight** [MotooriKashin/Bilibili-Old#329]
**问题详情**
在播放港澳台番剧时，视频内容加载失败，有声音有弹幕用字幕，就是没有画面。

**复现步骤**
1. '...'
2. '...'
3. '...'

**相关截图**
可以的话，提供一下截图，最好是控制台报错截图
![Uploading 截屏2022-07-12 09.49.56.png…]()

**运行环境**
 - 操作系统：macos Monterey 12.4
 - 浏览器：Google Chrome 103.0.5060.114
 - 脚本管理器：Tampermonkey 4.16.1

**补充内容**
其他补充内容。

**Comment by MotooriKashin** [comment]
截图炸了🤣

或许你不知道，GitHub支持在输入框直接粘贴截图，所以只需按一下`PrtScSysRq`键，然后在输入框里`Ctrl+V`就行

**Comment by FromtoLight** [comment]
好像好了，可能是网络问题

发自我的iPhone

在 2022年7月12日，12:54，MotooriKashin ***@***.***> 写道：

﻿

截图炸了🤣

或许你不知道，GitHub支持在输入框直接粘贴截图，所以只需按一下PrtScSysRq键，然后在输入框里Ctrl+V就行
