### ISSUE TITLE
[Bug] 无法打开设置，且无法显示小齿轮

### ISSUE THREAD

**Issue by ciallowo** [MotooriKashin/Bilibili-Old#330]
鉴于 #318 已经报告了相同的问题，此处就不再遵循 issue 模板了。

已根据 https://github.com/MotooriKashin/Bilibili-Old/issues/318#issuecomment-1151960045 进行过删除操作，仍无法调出设置按钮，且无 bilibili-entry 元素。

8.0.0 之前的版本均可打开设置，且能显示小齿轮，8.0.0 后便一直不行。

![image](https://user-images.githubusercontent.com/76084546/180261052-0f0dd686-ef7c-4a24-b860-a5093dd43de6.png)
![image](https://user-images.githubusercontent.com/76084546/180261578-9a207f68-60f0-4cbe-9cb1-1f7721541700.png)

**运行环境**
 - 操作系统：Windows 11
 - 浏览器：Edge 103.0.1264.62
 - 脚本管理器：Tampermonkey 4.16.1

**Comment by MotooriKashin** [comment]
看起来是循环调用，可我还是无法复现——总之先去掉私有属性试试🤣

**Comment by ciallowo** [comment]
@MotooriKashin 破案了，是 [Global Speed: 视频速度控制](https://chrome.google.com/webstore/detail/global-speed/jpbjcnkcffbooppibceonlgknpkniiff) 扩展与脚本有冲突，关闭该扩展后就能看到小齿轮了。
