### ISSUE TITLE
[Bug]页面反复刷新

### ISSUE THREAD

**Issue by NightSharp** [MotooriKashin/Bilibili-Old#331]
**问题详情**
在历史记录页面点击清空历史弹出探窗后页面会刷新，根本无法真正清空历史

**复现步骤**
1. 点进历史记录
2. 点击清空历史
3. 页面会刷新
4. 刷新后执行2会重复3

**相关截图**
太快了截不下来

**运行环境**
 - 操作系统：Windows10 21H2 19044.1826 专业版
 - 浏览器：Firefox 102.0.1 (64 位)
 - 脚本管理器：Violent Monkey v2.13.0

**补充内容**
其他补充内容。

**Comment by MotooriKashin** [comment]
感谢反馈！已修复！
