### ISSUE TITLE
无“下载视频”选项以及无法下载弹幕

### ISSUE THREAD

**Issue by Amezakiii** [MotooriKashin/Bilibili-Old#332]
**问题详情**
右键没有 下载视频 的选项，但是通过右下角的设置可以呼出，但无法下载弹幕

**相关截图**
![image](https://user-images.githubusercontent.com/74045211/180596356-7abce438-f24a-43ad-883a-f6e4bdbaf7da.png)
![image](https://user-images.githubusercontent.com/74045211/180596414-64f5cf5c-ea4a-4c68-aa3a-332f36103307.png)

**运行环境**
 - 操作系统：Windows10 professional
 - 浏览器：Google Chrome 103.0.5060.134
 - 脚本管理器：Tampermonkey 4.16.1

**Comment by MotooriKashin** [comment]
下载按钮移动到了播放器右侧，请在设置中启用，另外要下载弹幕请在设置中启用【其他下载】
![image](https://user-images.githubusercontent.com/60416767/180597296-dc91b3d3-a399-4fa1-8e02-999c35466f06.png)
