### ISSUE TITLE
[Feature Requset]希望跟进显示IP属地功能

### ISSUE THREAD

**Issue by Jerry19970311** [MotooriKashin/Bilibili-Old#333]
**存在问题**
没有什么问题，主要是最近B站也已经显示IP属地功能了，而旧版播放页并没有。

**目标愿景**
希望旧版播放页和个人主页也跟进实现这一功能。

**Comment by MotooriKashin** [comment]
【个人主页】并未重写为旧版，应该是B站自己网页端就没做好。    
【播放页】应该指的是评论区吧，这个网页端接口似乎也暂时没有提供位置信息。  

总之会跟进B站移动端的进度的。

**Comment by snylonue** [comment]
能不能加个开关

**Comment by MotooriKashin** [comment]
> 能不能加个开关

已添加：样式：评论IP属地。默认：`true`
