### ISSUE TITLE
[Bug?] 主页排行榜按钮无法点击

### ISSUE THREAD

**Issue by Yoho777** [MotooriKashin/Bilibili-Old#334]
**问题详情**
重构后的旧版主页，在右侧各个分区所对应的排行榜，切换「三日/一周」以及「全部/原创」的按钮无法生效。主页右侧所有的排行榜皆有此问题，包括漫画的「人气/应援/免费」选项。例如下图中绿色框出的位置。

**相关截图**
<img width="304" alt="123" src="https://user-images.githubusercontent.com/97226227/181510088-81b558b9-2951-4437-947f-f9230681a6dd.png">

**运行环境**
 - 操作系统：Windows11 professional 10.0.22000.527
 - 浏览器：Google Chrome 99.0.4844.74
 - 脚本管理器：Tampermonkey 4.14.6125

**补充说明**
猜测原因是新版主页去除了对应的选项。直播区保留的「直播排行/关注主播/为你推荐」依旧有效。
（不过我觉得这个功能大概没人用吧。特地获取一下排行榜会不会有点小题大做？）

**Comment by MotooriKashin** [comment]
因为排行榜早就不区分日期和原创，为避免误触禁用了点击事件——没有直接隐藏掉是为了尽可能保留页面当时的模样：记住原来曾经还有那些东西。

**Comment by Yoho777** [comment]
原来如此，了解了。
