### ISSUE TITLE
[Feature Requset]动态页不登录直接看评论

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#337]
### 当前问题
阿B不知道什么时候改版后，动态页未登录不能直接看评论了。但是如果点进去某条动态，还是可以看评论的。所以看上去只是一个前端限制，不像是后端强制验证。
![image](https://user-images.githubusercontent.com/20079289/181668931-f19bd2c5-60b0-4fd1-8723-f57189e6b9b5.png)
![image](https://user-images.githubusercontent.com/20079289/181668944-4e26632c-bab2-42cc-ab1a-8324561910e6.png)
![image](https://user-images.githubusercontent.com/20079289/181669165-86faceb1-c8a3-4bf0-85cb-e821ee660fdb.png)

### 目标愿景
希望可以实现在动态页不登录直接看评论。

### 参考建议
技术上我这门外汉就不装逼了……老大看看能不能实现吧。

### 补充内容
直播页面是可以直接看到所有动态和评论的……不知道动态页为啥要限制……
![image](https://user-images.githubusercontent.com/20079289/181669558-d50520ab-38a9-4338-9c31-8688d56e8207.png)

**Comment by MotooriKashin** [comment]
Mark，过几天我会研究一下。

**Comment by MotooriKashin** [comment]
研究了一下，由于原代码完全闭包，实在找不到什么注入点，想要实现不登录直接看评论，基本只有两个办法：
1. 伪造登录信息。这个简单，xhrhook或者拦截全局`UserStatus`对象即可实现，但副作用比较大，因为这个登录状态是整个页面通用的，伪造的登录状态可能导致各种功能异常，难以评估。。。
2. 像其他一样重写一下恢复旧版，旧版没有登录限制。动态页面其实没怎么变化，为这么一个功能重写整个页面有点小题大作。。。

我目前能想到的办法都有点杀鸡用牛刀的感觉，实现起来感觉都不恰当。不过这个页面是用vue写的，用webpack打包，从这两方面注入或许有更好的思路……看有没有大神有更好的思路，我好照猫画虎🤣
