### ISSUE TITLE
README 版本历史 typo

### ISSUE THREAD

**Issue by Geeyun-JY3** [MotooriKashin/Bilibili-Old#34]
如图，https://github.com/MotooriKashin/Bilibili-Old#版本历史

![image](https://user-images.githubusercontent.com/49396421/99190935-7d957a00-27a4-11eb-80a4-57dcdbbed4f2.png)

另外纯好奇，想问问评论区的小页码区是指什么？

**Comment by MotooriKashin** [comment]
![2020-11-16_065504](https://user-images.githubusercontent.com/60416767/99199291-04644a00-27d9-11eb-9d17-0ef6571cb157.jpg)
如图所示，评论区原上下各有跳转页码区域，2020年10月27日开始却去掉了右上角的，使得每次翻页必须把评论一拉到底，[有人反馈说多有不便](https://greasyfork.org/zh-CN/scripts/394296/discussions/65624)。况且新版评论并未见有何改进，干脆直接启用旧版备份。

**Comment by Geeyun-JY3** [comment]
了解了
