### ISSUE TITLE
[Bug]评论楼层消失

### ISSUE THREAD

**Issue by sddddd213** [MotooriKashin/Bilibili-Old#342]
**问题详情**
评论中不显示，点开评论楼中楼也不再显示。

**相关截图**
![QQ图片20220802135220](https://user-images.githubusercontent.com/38841494/182301792-e508542e-dad3-4aa3-95b5-f23f43df04f6.png)

**运行环境**
 - 操作系统：Windows10
 - 浏览器： Microsoft Edge 版本 103.0.1264.77 (正式版本) (64 位)
 - tampermonkey  v4.16.1

**补充内容**
以前也存在的功能，希望恢复，谢谢。

**Comment by MotooriKashin** [comment]
现有楼层接口都是基于瀑布流评论，实在很难完美符合翻页评论区恢复评论楼层的的需求。GreasyFork上有专门的恢复楼层的脚本，虽然我不敢苟同那种同时并发大量请求去获取楼层数据的方案，很容易导致被封端口甚至彻底和谐，但不得不说那也是目前最好的解决方案。

在没有更完美的方案出现之前（也许是永远），本脚本还是放弃实现类似功能了。
