### ISSUE TITLE
[Bug]不重构av页区域限制bangumi视频不会自动重定向

### ISSUE THREAD

**Issue by FromtoLight** [MotooriKashin/Bilibili-Old#343]
关闭旧版一般视频播放页面功能，开启旧版番剧播放页面功能，在从av号视频看港澳台番剧时无法定向到番剧页面

**Comment by MotooriKashin** [comment]
既然关闭了`旧版一般视频播放页面功能`，从av页到bangumi的重定向自然完全交由页面本身判定。本脚本所有附加功能都是基于旧版页面这一核心（包括但不限于基于播放器和弹幕的相关增强，下载视频等），不会另外对非旧版页面进行专门的适配，那样不仅平添了许多维护任务，也不符合脚本本身的定位（参考脚本名）。我觉得如果是不想使用旧版页面，那些附属功能其实有其他专门的脚本（比如你说的看港澳台番剧的【解除xxxx】），也就不必使用【Bilibili **旧播放页**】
