### ISSUE TITLE
[Bug]非正常打开新页面

### ISSUE THREAD

**Issue by NightSharp** [MotooriKashin/Bilibili-Old#344]
**问题详情**
在历史记录页面操作时会莫名其妙新建`历史记录`标签页

**复现步骤**
1. 在历史记录页面点击`清空历史`时会在后台新建一个历史记录标签页
2. 点击`确定清空`后还会再新建一个

**相关截图**
无

**运行环境**
 - 操作系统：Windows10 21H2 19044.1865 专业版
 - 浏览器：Firefox 103.0.1 (64 位)

**补充内容**
```
日志没有记录相关情况
```

**Comment by MotooriKashin** [comment]
已修复，感谢反馈！

**Comment by NightSharp** [comment]
> 已修复，感谢反馈！

问题又出现了，不知道为啥还是在每次点击后打开新页面
