### ISSUE TITLE
[Bug]历史记录页面有bug

### ISSUE THREAD

**Issue by nzd7xW5** [MotooriKashin/Bilibili-Old#345]
在历史记录页https://www.bilibili.com/account/history ，点击“暂停记录历史”会导致页面强制刷新（而且也并不能暂停记录）

**Comment by nzd7xW5** [comment]
另外能否添加一个默认关闭字幕（以及弹幕？）的功能？现在默认新视频都打开字幕有时候挺烦人的

**Comment by MotooriKashin** [comment]
已添加记忆关闭字幕功能，在CC字幕面板主动选择关闭即可。

**Comment by nzd7xW5** [comment]
另外发现在历史记录页面点清空历史也会触发页面强制刷新

**Comment by MotooriKashin** [comment]
> 另外发现在历史记录页面点清空历史也会触发页面强制刷新

这个问题应该早就修复了
![image](https://user-images.githubusercontent.com/60416767/184517304-732aa4f1-281c-4f36-ba90-f3e13ac74973.png)

**Comment by nzd7xW5** [comment]
哦哦确实 更新脚本就好了
看来是我太久没更新
