### ISSUE TITLE
[Bug]festival页面的定位问题

### ISSUE THREAD

**Issue by NightSharp** [MotooriKashin/Bilibili-Old#346]
**问题详情**
festival页面的后缀bvid会被转换为aid，刷新时无法正常定位到指定投稿

**复现步骤**
1. 打开链接[BV1AT411A75z](https://www.bilibili.com/video/BV1AT411A75z)
2. 关闭旧播放页时链接与定位保持正常(参见图1)`https://www.bilibili.com/festival/SummerSymphony?bvid=BV1AT411A75z`
3. 启用旧播放页时链接后缀转换为`aid`，定位出现错误(参见图2)`https://www.bilibili.com/festival/SummerSymphony?aid=471900541`

**相关截图**
![屏幕截图 2022-08-16 105000](https://user-images.githubusercontent.com/9748063/184788767-cee570ae-f56c-4b09-9c3a-bbf3749d861a.png)
![屏幕截图 2022-08-16 105029](https://user-images.githubusercontent.com/9748063/184788772-2d0738b0-a9d0-4bd0-92c2-0ac1ebf5ea21.png)
日志界面没有相关记录

**运行环境**
 - 操作系统：Windows10 21H2 19044.1889 专业版
 - 浏览器：Firefox 103.0.2 (64 位)

**补充内容**
感觉aid定位在festival中已失效，建议在festival界面不进行bvid链接转换

**Comment by MotooriKashin** [comment]
原来如此，我说怎么刷新页面视频就变了🤣

**Comment by NightSharp** [comment]
> 原来如此，我说怎么刷新页面视频就变了🤣
更新后好像是尾巴上会加上一个`&aid=471900541`
是刻意设置成这样的吗?有没有开关可以控制直接去掉

**Comment by MotooriKashin** [comment]
旧版页面（播放器）不认识bvid，所以aid是不可或缺的。而按你说的festival页面不能缺少bvid，所以只能二者都保留。

**Comment by NightSharp** [comment]
> 旧版页面（播放器）不认识bvid，所以aid是不可或缺的。而按你说的festival页面不能缺少bvid，所以只能二者都保留。

好吧，我还以为可以设置一个开关隐藏的~
