### ISSUE TITLE
[Bug]评论区排序类型刷新问题

### ISSUE THREAD

**Issue by NightSharp** [MotooriKashin/Bilibili-Old#347]
**问题详情**
点击`按时间排序`后在未知情况下会跳转回`按热度排序`，可能跟新增评论有关。

**复现步骤**
1. 打开一个评论增长比较频繁的投稿，比如[这个](https://www.bilibili.com/bangumi/play/ep604294)
2. 点击`按时间排序`，上下滚动等待一段时间
3. 评论区会跳回`按热度排序`

**相关截图**
不知道这个怎样用截图表示

**运行环境**
 - 操作系统：Windows10 21H2 19044.1889 专业版
 - 浏览器：Firefox 103.0.1 (64 位)

**补充内容**
控制台没有相关日志

**Comment by MotooriKashin** [comment]
或许是我操作方式不对，挑了个热门视频上下滚动了十分钟也未能重现类似问题。
留待后续跟进。

**Comment by NightSharp** [comment]
> 或许是我操作方式不对，挑了个热门视频上下滚动了十分钟也未能重现类似问题。 留待后续跟进。

你看看[这个](https://www.bilibili.com/bangumi/play/ep604295)链接，在评论区上下滚动一下

**Comment by NightSharp** [comment]
> 或许是我操作方式不对，挑了个热门视频上下滚动了十分钟也未能重现类似问题。 留待后续跟进。

貌似只在同时开启 `BiliBili Evolved` 跟 `BiliBili-Old` 时会出现这种情况
单开 `Old` 确实不会出现该问题
@MotooriKashin
