### ISSUE TITLE
[Bug]评论区样式重叠问题

### ISSUE THREAD

**Issue by NightSharp** [MotooriKashin/Bilibili-Old#348]
**问题详情**
评论区页面选择栏与新增的楼层数样式重叠

**复现步骤**
1. 打开[这个链接](https://t.bilibili.com/696366867607978001)
2. 查看评论区

**相关截图**
![屏幕截图 2022-08-20 141431](https://user-images.githubusercontent.com/9748063/185731844-3d4c1a4f-e283-4d50-9f57-21dc9908c53b.png)

**运行环境**
 - 操作系统：Windows10 21H2 19044.1889 专业版
 - 浏览器：Firefox 103.0.2 (64 位)

**补充内容**
无

**Comment by MotooriKashin** [comment]
未能复现，是不是其他脚本冲突了——看你好像启用了暗黑模式
![image](https://user-images.githubusercontent.com/60416767/186144834-f7e01655-4b5f-4761-9f3d-57cde35ff6f9.png)

**Comment by NightSharp** [comment]
> 未能复现，是不是其他脚本冲突了——看你好像启用了暗黑模式 ![image](https://user-images.githubusercontent.com/60416767/186144834-f7e01655-4b5f-4761-9f3d-57cde35ff6f9.png)

查了一下，确实是[另一个脚本](https://greasyfork.org/zh-CN/scripts/443543)的样式问题
如果不麻烦的话，希望可以兼容一下，麻烦的话就算了……
