### ISSUE TITLE
[Bug]高级弹幕无法被关闭

### ISSUE THREAD

**Issue by nzd7xW5** [MotooriKashin/Bilibili-Old#349]
在播放器上点击了关闭弹幕之后，高级弹幕仍然会被显示。

举例：https://www.bilibili.com/video/av338332957

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/69294448/186046365-691f09b3-ee77-4340-a380-3e95ac50b2e9.png">
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/69294448/186046391-4b81a84a-de44-4938-8991-880ea963054c.png">
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/69294448/186046408-1f7ebbf9-3e5d-4339-8a8c-a4156108d3d4.png">
右下角弹幕按钮已经被关闭。

===

另，现在有的时候，打开一个新视频页面，会在点击播放视频之前，视频附带的音频就会自动开始播放，而且无法暂停。如果音频被自动播放后，再点击播放视频，就会有两条音轨同时播放。挺奇怪的bug，而且也不太能稳定复现。有的时候反复刷新好几次，每次都出现这个bug。有的时候刷新一次页面之后这个bug就会消失。

**Comment by MotooriKashin** [comment]
高级弹幕的确是无法关闭的，旧版播放器不带这个功能。

自动播放功能请在设置里开启【重构加固】


 

-------- 原始邮件 --------
发件人：nzd7xW5 ***@***.***>
时间：2022年8月23日 09:24
收件人：MotooriKashin/Bilibili-Old ***@***.***>
抄送：Subscribed ***@***.***>
主题：[MotooriKashin/Bilibili-Old] [Bug]高级弹幕无法被关闭 (Issue #349)

**Comment by nzd7xW5** [comment]
似乎高级弹幕在15、16年就有了啊，那时候还没有新播放器啊，是后来又改了实现方式是吗

或者大佬能不能想个办法，比如出个功能手动把高级弹幕从弹幕池里删掉什么的

**Comment by MotooriKashin** [comment]
高级弹幕一直有，只是当时还是flash播放器，是一脉相承的。屏蔽功能新版播放器好像有，将来可能会移植一下，可能需要过一段时间。
