### ISSUE TITLE
求旧版评论区

### ISSUE THREAD

**Issue by Aira-Sakuranomiya** [MotooriKashin/Bilibili-Old#35]
B站之前的评论区是有几条热评在顶端，然后底下都是按照楼层来的
顶上TAB现在的按热度排序和按时间排序，原本是左边默认的全部评论，右边热门评论按照热度排序的那种
改成现在这样是在去掉楼层的那次更新同时搞的，能找回原本的那种吗

以下是找到的截图
![image](https://user-images.githubusercontent.com/45261195/99296034-1ef1fe00-2881-11eb-908d-50e5ba6aaf4f.png)

**Comment by MotooriKashin** [comment]
很久之前的事了，如果能做到，才是名副其实的旧版。

**Comment by MotooriKashin** [comment]
测试了一下，倒是可以回复先“全部评论”后“按热度排序”这种，不过我记得原来“全部评论”在时间排序之前会先陈列三条高热度评论，这点现在还原不了。这样的“全部评论”就约等于“按时间排序”，只是将两者调换了下顺序而已。即使这样，也要继续吗？

**Comment by Aira-Sakuranomiya** [comment]
啊这……还原不了吗

**Comment by MotooriKashin** [comment]
已还原，不过热评变多了而不是3条，完全的旧版评论限定3条热评，但现在肯定大于3(我测试的视频是9)，这点不知道你介意与否。  
且脚本获取的是`jsdelivr`的缓存，可能存在一天左右的延迟才能生效。  
如果想要立即查看效果可以手动将脚本第32行
```
    const COMMENT = "//cdn.jsdelivr.net/gh/MotooriKashin/Bilibili-Old/src/comment.min.js",
```
修改为
```
    const COMMENT = "//cdn.jsdelivr.net/gh/MotooriKashin/Bilibili-Old@latest/src/comment.min.js",
```
就能立即生效

**Comment by Aira-Sakuranomiya** [comment]
nb!!!!!!

**Comment by Aira-Sakuranomiya** [comment]
啊...发现bug了，如果点击按照热度排序，底下评论的内容会出现undefined
![QQ截图20201118165205](https://user-images.githubusercontent.com/45261195/99507501-692cc980-29be-11eb-9b7d-404194e43453.jpg)

**Comment by MotooriKashin** [comment]
那是新版表情吧，在旧版评论的时代还是不存在的

**Comment by MotooriKashin** [comment]
是我疏忽了，这样看起来就不能直接使用旧版评论了

**Comment by Aira-Sakuranomiya** [comment]
尝试把新旧版缝合一下？（

**Comment by MotooriKashin** [comment]
我尽力吧，经过压缩的脚本读起来有点费力

**Comment by MotooriKashin** [comment]
已在新版的基础上修改为旧版，可以试试有没有什么问题  
这次修改为`latest`没用了，请临时修改为
```
const COMMENT = "//cdn.jsdelivr.net/gh/MotooriKashin/Bilibili-Old@89b2be068c2b27eb7e09d3fa8ac355b6cf6e437c/src/comment.min.js"
```
或者等明天缓存更新了再试

**Comment by Aira-Sakuranomiya** [comment]
完美了，太强了

**Comment by Aira-Sakuranomiya** [comment]
啊对了，发现一个别的问题，就是通过顶栏点击登出账号的时候提示页面不见了，应该是旧的登出链接失效了吧

**Comment by MotooriKashin** [comment]
好的，感谢反馈，我去测试下
