### ISSUE TITLE
[Feature Requset]音频HiRes支持

### ISSUE THREAD

**Issue by iamapig120** [MotooriKashin/Bilibili-Old#350]
**存在问题**
*当前最新的官方播放器已支持 HiRes 音频轨道*

**目标愿景**
*希望在旧版播放器加入 HiRes 开关*

**参考建议**
*https://www.bilibili.com/video/av429810060 使用新版播放器可播放 HiRes 音频轨道（需大会员）*

**Comment by MotooriKashin** [comment]
直接在bilibiliPlayer.js中修修补补始终不是长久之策，那种高度压缩混淆的代码维护起来实在太痛苦🤣

最近在尝试一个大胆的工程，参考B站播放器2.0(jsc)和3.0(npd)使用TypeScript直接重构整个bilibiliPlayer.js，届时所有新版播放器已有的或即将有的功能都可以移植过来：高能进度条、视频看点、互动视频、杜比音效/杜比视界、HiRes……

所以这一段时间不会本脚本添加新功能，只进行基本的bug修复等维护工作，当然大家愿意pr更是欢迎之至。

至于时间，只是重构一下的话应该用不了太久，附一张目前进度效果图：

![image](https://user-images.githubusercontent.com/60416767/186321531-94893745-e2f7-4de1-beb6-c30eae00c07c.png)

**Comment by iamapig120** [comment]
非常感谢您的来信该邮件已成功接收至手柄的邮箱您的建议及意见会经过阅读后成为优秀的参考选项To customers:I passed the postgraduate exam! Everything will return to normal in a few days!

**Comment by wly5556** [comment]
最新版脚本（9.0.9）可以播放hires音频了，在视频窗口右下方对应增加了FLAC开关~
![image_8](https://user-images.githubusercontent.com/61644753/186475496-df4226ea-d8bc-42b2-85a3-5da90207e337.png)
