### ISSUE TITLE
[Bug]在旧播放页加载出来前新播放页会先把视频播放出来，就播放页加载出来以后就没法关掉新播放页的音频了

### ISSUE THREAD

**Issue by wcz123694578** [MotooriKashin/Bilibili-Old#351]
**问题详情**
*简洁清晰的问题描述。*

**复现步骤**
1. '...'
2. '...'
3. '...'

**相关截图**
*可以的话，提供一下截图，最好是控制台报错截图*

**运行环境**
 - 操作系统：Windows11 professional 10.0.22000.778
 - 浏览器：Google Chrome 103.0.5060.134 (正式版本) （64 位） (cohort: Stable) 

**补充内容**
*其他补充内容。*

**Comment by MotooriKashin** [comment]
新版播放器加载太快了，请尝试设置启用【重构增强】

**Comment by mxancl** [comment]
> 新版播放器加载太快了，请尝试设置启用【重构增强】

我也有这个问题，钩上了之后也没用，名字是【重构加固】
