### ISSUE TITLE
[Bug]主页重写失效

### ISSUE THREAD

**Issue by wly5556** [MotooriKashin/Bilibili-Old#352]
使用脚本版旧播放页[9.1.0-正确处理跨版本webpackJsonp]，打开B站主页只能看到主页的页脚
![image_9](https://user-images.githubusercontent.com/61644753/186827641-8f06065c-b176-498b-9c70-233bd8ed5216.png)
插件版旧播放页、脚本版旧播放页的[上一版本](https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5?version=1085471)是正常的

**Comment by MotooriKashin** [comment]
我这边是正常的，而且[9.1.0-正确处理跨版本webpackJsonp]只处理了逻辑上只处理了av页和专栏，应该不至于影响主页才对。

**Comment by MotooriKashin** [comment]
以防外一还是再处理一下吧。

webpack这个全局共用一个变量名的涉及实在是败笔，旧版脚本若读取了新版页面残留的webpackJsonp必然报错退出。扩展版是第一时间注入没有这个问题，脚本版注入时机不定，实在很难判断当前webpackJsonp到底是不是新版页面残留的以及在旧版脚本执行前新版脚本会不会突然写一个webpackJsonp到全局中。

不知道你有没有什么好的提议？

**Comment by wly5556** [comment]
更新9.1.1之后正常了😋，感谢
webpackJsonp的相关问题我去试着研究一下，不过水平有限，可能最后也找不到好的办法😖
