### ISSUE TITLE
[Feature Requset]希望能添加一个加宽(高)顶栏图片区域的功能

### ISSUE THREAD

**Issue by MSGOOHPA** [MotooriKashin/Bilibili-Old#353]
**存在问题**
*在较宽的屏幕上，旧版顶栏的图的左区域右两边会有白边，或许是因为新的顶栏图比以前的短了一些，或许是因为旧版顶栏把高度写死了。*
![屏幕截图 2022-08-26 145404](https://user-images.githubusercontent.com/40914017/186843322-ae8f4813-0341-46c1-a1c0-5d9d1f2035f6.png)

**目标愿景**
*希望能把顶栏图片区域加高一些以保证两边不留白边，就像新版主页顶栏图片那样，直接改或者做成一个可选的开关都行。*
![屏幕截图 2022-08-26 150049](https://user-images.githubusercontent.com/40914017/186843466-de3a3ef2-4409-428f-ad4e-e2e9fc34468d.png)

**Comment by MotooriKashin** [comment]
改个css不难，难的是我没有那么宽的屏幕进行测试🤣

**Comment by MSGOOHPA** [comment]
> 改个css不难，难的是我没有那么宽的屏幕进行测试🤣

直接用浏览器的缩放来测试就可以了（

**Comment by MotooriKashin** [comment]
好主意🤔

**Comment by MSGOOHPA** [comment]
还是有点问题啊
![image](https://user-images.githubusercontent.com/40914017/187909359-2dda69c6-3aaa-47b2-8fd4-d32a25a107fe.png)

![image](https://user-images.githubusercontent.com/40914017/187910293-1279a7fc-683e-4ed7-891c-a0820f94e886.png)

希望能把动态头图修一下，另外，~~希望能完整地把头图展示出来，也就是能让顶栏头图的宽度/高度跟图片的宽度/高度保持一致~~
我看了一下，新版主页头图挺宽的，默认状态下并不是展示全部，而是在点击头图之后才会展现头图的全部内容
（如果这个特性比较难移植的话，或许可以加个展示头图全部内容（让顶栏头图的宽度/高度跟图片的宽度/高度保持一致）的开关

**Comment by MotooriKashin** [comment]
动态banner是个视频而不是图片，视频的分辨率总是固定的，虽然不知道新版是怎么处理的，但是我觉得视频应该没有办法很好地适应各种分辨率——所以这就是新版取消了动态banner的原因（好久没用新版了，不太清楚，只是现在翻遍所有分区也找不到一个动态的）

你可以在设置里关闭动态banner，只是图片的话应该已经修复了，怎么缩放都不会有留白

**Comment by MSGOOHPA** [comment]
> 动态banner是个视频而不是图片，视频的分辨率总是固定的，虽然不知道新版是怎么处理的，但是我觉得视频应该没有办法很好地适应各种分辨率——所以这就是新版取消了动态banner的原因（好久没用新版了，不太清楚，只是现在翻遍所有分区也找不到一个动态的） 你可以在设置里关闭动态banner，只是图片的话应该已经修复了，怎么缩放都不会有留白

您来 Issues 页面看看？因为我上面那条改了好几版，不知道邮件有没有提示到

**Comment by MSGOOHPA** [comment]
> 动态banner是个视频而不是图片，视频的分辨率总是固定的，虽然不知道新版是怎么处理的，但是我觉得视频应该没有办法很好地适应各种分辨率——所以这就是新版取消了动态banner的原因（好久没用新版了，不太清楚，只是现在翻遍所有分区也找不到一个动态的） 你可以在设置里关闭动态banner，只是图片的话应该已经修复了，怎么缩放都不会有留白

还有，这个静态顶栏实际上是被截断了一点点，您可以仔细对比一下右下角的细节
![image](https://user-images.githubusercontent.com/40914017/187916249-acab3e9a-94c9-4be3-8e9f-ea1cb23f84fa.png)
![image](https://i0.hdslb.com/bfs/archive/956de2627e2cc1a9da53ea1d8762cea33e8ea6e5.png)

**Comment by MotooriKashin** [comment]
静态banner肯定是裁剪过的，因为分辨率不一样，既然不想留白，又不能让图片变形，裁剪是唯一的办法，这种裁剪不专门对比的话应该察觉不到，就当原图就该是那个样子过好了。
动态banner的问题我过一段时间再看吧，如果新版有很好地实现，移植起来应该不难，就是最近没有时间。

**Comment by MSGOOHPA** [comment]
> 静态banner肯定是裁剪过的，因为分辨率不一样，既然不想留白，又不能让图片变形，裁剪是唯一的办法，这种裁剪不专门对比的话应该察觉不到，就当原图就该是那个样子过好了。
> 动态banner的问题我过一段时间再看吧，如果新版有很好地实现，移植起来应该不难，就是最近没有时间。
> 
> 
>  

emmmmmmmmmmmm🤔
我是希望能把静态图片顶栏的图片区域加 高/宽（我说的 高和宽 均指窄边，也就是竖边）一点点（说的是框架，不是图片），让图片可以完全显示，这只需要修改 banner 区域的 html 代码就可以实现了。更进一步还可以先根据图片的比率把窄边的宽度算好再应用。

**Comment by MotooriKashin** [comment]
额，不是图片适应页面，而是页面适应图片的意思……是不是有点舍本逐末了……
脚本的一大原则是还原旧版页面，不会去动旧版页面的样式。旧版顶栏一脉相承这么些年，擅自更改反而会与旧版页面不和谐吧？
总之，个人以为量体裁衣可以，削足适履不大行。

**Comment by MSGOOHPA** [comment]
> 旧版顶栏一脉相承这么些年，擅自更改反而会与旧版页面不和谐吧？ 总之，个人以为量体裁衣可以，削足适履不大行。

旧版顶栏图片区的宽高比大约是 36:3，而新版头图的宽高比是 32:3，也就高/宽了那么一点，我__个人认为__修改旧版页面的顶栏图片区域的短边宽度__应该不会__有什么不和谐吧，而且也可以给这个功能加个开关嘛（
![屏幕截图 2022-09-02 204434](https://user-images.githubusercontent.com/40914017/188149933-410de739-bc40-4785-8d5d-fa1c8f28ece2.png)
![屏幕截图 2022-09-02 204635](https://user-images.githubusercontent.com/40914017/188149945-e61777e9-59f4-41d6-9447-c0a073d7bfaf.png)

**Comment by MSGOOHPA** [comment]
emmmmmmmmmmmm🤔
我是希望能把静态图片顶栏的图片区域加 高/宽（我说的 高和宽 均只窄边，也就是竖边）一点点，让图片可以完全显示，这只需要修改 banner 区域的 html 代码就可以实现了。更进一步还可以先根据图片的比率把窄边的宽度算好再应用。



在 2022年9月1日，下午9:20，MotooriKashin ***@***.***> 写道：

﻿

静态banner肯定是裁剪过的，因为分辨率不一样，既然不想留白，又不能让图片变形，裁剪是唯一的办法，这种裁剪不专门对比的话应该察觉不到，就当原图就该是那个样子过好了。
动态banner的问题我过一段时间再看吧，如果新版有很好地实现，移植起来应该不难，就是最近没有时间。

**Comment by MotooriKashin** [comment]
久等了，给了各开关设置-样式-修正banner分辨率
