### ISSUE TITLE
[Bug] 旧版顶栏和分区无法恢复

### ISSUE THREAD

**Issue by sddddd213** [MotooriKashin/Bilibili-Old#354]
**问题详情**
首先，点进视频播放页面正常。

主页可以很好实现旧版顶栏和分区的恢复
![QQ截图20220827125403](https://user-images.githubusercontent.com/38841494/187015119-ebdb1af6-0302-4c88-aeb4-c89a4c775e7f.png)

点进分区后便恢复不了
![QQ截图20220827125554](https://user-images.githubusercontent.com/38841494/187015187-1ce80816-309b-4c48-b6e9-2e9cbe0fb01f.png)

并且在该页面点击其他分区后触发其他bug，如：
![QQ截图20220827125727](https://user-images.githubusercontent.com/38841494/187015234-8ed8403e-3914-483b-9366-24a278df96d3.png)

目前经过测试，发现所有的分区都是无法恢复，并且被点击也会触发该bug。

**复现步骤**
1. '首先登陆哔哩哔哩'
2. '点击任意一个分区'
3. '再在该页面点击任意一个分区，则可以触发第二个bug。如果第一次点击没有触发，可以多点击几次，通常第二次便可以触发该bug。'

**相关截图**
控制台报错如图。
![QQ截图20220827130300](https://user-images.githubusercontent.com/38841494/187015465-1f462f10-72dc-4864-9358-fcf81b67d9e7.png)
![QQ截图20220827130323](https://user-images.githubusercontent.com/38841494/187015470-b0d95963-1514-42e5-9961-639444d752b7.png)
![QQ截图20220827130339](https://user-images.githubusercontent.com/38841494/187015474-167a78cb-8c00-4349-8060-6f3c7aa1bc5d.png)

**运行环境**
 - 操作系统：Windows10专业  21H2
 - 浏览器：Microsoft Edge 版本 104.0.1293.70 (正式版本) (64 位)

**补充内容**
后续如有其他相关发现，将在本问题下继续补充

**Comment by MotooriKashin** [comment]
B站顶栏改版过很多次，变成了多版本共存的情形，有些替换了就会导致语法报错。看来这个功能应该系统性地重新实现一下。
