### ISSUE TITLE
[Bug]问题的标题

### ISSUE THREAD

**Issue by 3arrow** [MotooriKashin/Bilibili-Old#355]
主页和搜索显示不了

**Comment by MotooriKashin** [comment]
#352 的话应该已经修好了，要不卸载重新安装试试

**Comment by 3arrow** [comment]
可以乐




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MotooriKashin/Bilibili-Old"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月28日(星期天) 晚上7:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MotooriKashin/Bilibili-Old] [Bug]问题的标题 (Issue #355)





 
#352 的话应该已经修好了，要不卸载重新安装试试
