### ISSUE TITLE
[Feature Requset]支持空降跳转的url & 允许多倍速播放

### ISSUE THREAD

**Issue by deuteros-gex** [MotooriKashin/Bilibili-Old#356]
感谢作者的脚本，旧版播放器overhead明显低得多，用在笔电上非常合适。

搜了一下应该没人提这些：

1、能否考虑处理形如：
https://www.bilibili.com/video/av985129856?t=180
这样的url，其中t=180代表打开后直接从视频的3:00开始播放
目前的版本没法识别t=180的参数，打开后只能从头开始播放

2、在1的基础上，能否考虑把这个新版播放器特有的按钮（右键呼出）backport到旧版播放器上面去？
![image](https://user-images.githubusercontent.com/67225583/188490977-c4e3e6b4-0a75-4748-be99-83ddb23548fe.png)
这个按钮还挺好用的。。。比较方便直接标记视频的位置，看教程类视频的时候经常用。
（不一定表现为添加按钮，快捷键也可以）

3、是否能够考虑允许两倍速以上的播放速度？
启用了旧版播放器后和其它支持多倍速的脚本就没法用了，因为它们基本都是针对新播放器做的。

仅做建议，是否采纳全看作者大大的判断啦。

**Comment by wly5556** [comment]
我去做第二条、第三条需求，我也一直想随意调整播放倍速来着

**Comment by deuteros-gex** [comment]
> 我去做第二条、第三条需求，我也一直想随意调整播放倍速来着

感谢大佬

**Comment by MotooriKashin** [comment]
> 我去做第二条、第三条需求，我也一直想随意调整播放倍速来着

交给你了💕

很长一段时间我都无暇顾及一些新功能请求了，重构bilibiliplayer.js时遇到的细节问题比想象中多了太多🤣
![image](https://user-images.githubusercontent.com/60416767/188541843-3dc4f29c-4c15-40b8-8162-bc862c26d462.png)

如果真的有完成那天，很多我们为旧版播放器修补的功能又要想办法移植过去——比如上图的普权弹幕换行问题

**Comment by wly5556** [comment]
![image_17](https://user-images.githubusercontent.com/61644753/188552702-118896f8-37e5-4e5b-a628-3453561b6e27.png)
提交更改了，目前是这个效果。`?t=`类型的链接以往的旧播放页是能正常跳转的，应该是近段时间产生的bug，不知道 @MotooriKashin 有时间去解决一下吗👀

**Comment by wly5556** [comment]
>很长一段时间我都无暇顾及一些新功能请求了，重构bilibiliplayer.js时遇到的细节问题比想象中多了太多🤣

难不成还要把2.x播放器的UI改成旧版播放器的？工作量好大啊
其实继续小修小补旧播放器bilibiliPlayer.js也不是不行🥶

>为旧版播放器修补的功能又要想办法移植过去

我已经记不清改了哪些功能了，只能靠翻commit记录去回忆一下😖

**Comment by MotooriKashin** [comment]
> 难不成还要把2.x播放器的UI改成旧版播放器的？工作量好大啊
> 其实继续小修小补旧播放器bilibiliPlayer.js也不是不行🥶

是的，2.x的播放相关功能完全可以直接用，就直接在其基础上还原UI了。  
习惯了typescript，形成了依赖离不开了，维护js文件容易出现各种低级错误，VSCode还不提示→_→。小修小补还好，像想要实现互动视频、全景视频……等依赖一大堆的功能。

> 我已经记不清改了哪些功能了，只能靠翻commit记录去回忆一下😖

其实也不多（大概
- bas弹幕本来就是移植的2.x代码
- 普权弹幕换行应该是新版专门去掉了
- 视频编码选择、4K缓冲时长大概2.x版dashplayer自带修复
- 其他如互动弹幕、分段进度条等与其从播放器中引出接口另做，不如直接内置，还可以参考2.x源码。

**不过重构完成也不知道要用多久就是了**

**Comment by MotooriKashin** [comment]
> ?t=类型的链接以往的旧播放页是能正常跳转的，应该是近段时间产生的bug，不知道 @MotooriKashin 有时间去解决一下吗👀

看起来只有av页不会跳转，av页播放器启动代码太简单了(aid+cid)，参数补充在`video.js`里，当时重构忘了移植这部分。

**Comment by deuteros-gex** [comment]
0.0 效率太高了，实测功能都ok！
