### ISSUE TITLE
[Bug]使用自定义服务器无法加载港澳台番剧

### ISSUE THREAD

**Issue by deuteros-gex** [MotooriKashin/Bilibili-Old#357]
用的自定义服务器是：

> 陈睿.我爱你
> 出差.xyz

页面的提示如下
![image](https://user-images.githubusercontent.com/67225583/188502042-38ba7a96-8fd3-4f9f-ba50-cf7b2698d179.png)
卡在这一步的白屏，视频内容加载不出。

同样的网络环境下如果换用内置服务器立即一切正常，不过因为内置服务器只能用flv播放器和avc编码嘛，没法流畅播放。。
所以想用自定义服务器开hevc编码，这样码率估计能小一半。

我在设置页是这么填的（只填了自定义服务器地址并做了授权，没改upos）：
![image](https://user-images.githubusercontent.com/67225583/188504229-57fb75ef-a47d-4b94-9718-0eb50018f316.png)

测试过，应该不是自定义服务器的问题。如果关掉bilibili-old脚本用新版播放器，打开“解除B站区域限制”脚本，配合上面两个自定义服务器，是能正常跨区到港澳台播放的。

**Comment by MotooriKashin** [comment]
最好还是提供一下控制台信息，加载卡住很有可能是代码报错跳出，没有报错信息很难判断。

解除限制功能个人一直在用，并未复现你说的问题。不过我有注意到你填的是**中文域名**，可以尝试填非中文域名的解析服务器试试，根据个人经验，中文路径/域名在计算机中很容易导致各种问题。

**Comment by deuteros-gex** [comment]
> 最好还是提供一下控制台信息，加载卡住很有可能是代码报错跳出，没有报错信息很难判断。
> 
> 解除限制功能个人一直在用，并未复现你说的问题。不过我有注意到你填的是**中文域名**，可以尝试填非中文域名的解析服务器试试，根据个人经验，中文路径/域名在计算机中很容易导致各种问题。

好的，控制台应该是这个界面对吧？
![image](https://user-images.githubusercontent.com/67225583/188545237-b3c3a685-6c8b-4c84-89c0-ae1872046dd5.png)

**Comment by deuteros-gex** [comment]
按照您的建议尝试换了一下纯英文的服务器，控制台显示的是：
![image](https://user-images.githubusercontent.com/67225583/188545869-acf6e3e8-76b4-4f98-a94b-8d42208d2ba1.png)
![image](https://user-images.githubusercontent.com/67225583/188545899-6d79bec6-27ef-4b79-8f77-e65de9bc564c.png)

**Comment by MotooriKashin** [comment]
403？！

> 只填了自定义服务器地址并做了授权，没改upos

图中403错误看起似乎是腾讯的upos，正常情况下港澳台返回的肯定是Akamai（如下图）而不是腾讯（或其他国内CDN）——既然没改upos那就尝试改一个能用的吧，403错误除此之外也没有其他办法。

![image](https://user-images.githubusercontent.com/60416767/188549006-01fb63d7-587e-4fcc-853d-88d39ab5678b.png)

我一般选择第一个金山CDN
![image](https://user-images.githubusercontent.com/60416767/188549231-81c5876c-70c7-47da-a7c6-16236877a9ff.png)

**Comment by deuteros-gex** [comment]
> 403？！
> 
> > 只填了自定义服务器地址并做了授权，没改upos
> 
> 图中403错误看起似乎是腾讯的upos，正常情况下港澳台返回的肯定是Akamai（如下图）而不是腾讯（或其他国内CDN）——既然没改upos那就尝试改一个能用的吧，403错误除此之外也没有其他办法。
> 
> ![image](https://user-images.githubusercontent.com/60416767/188549006-01fb63d7-587e-4fcc-853d-88d39ab5678b.png)
> 
> 我一般选择第一个金山CDN ![image](https://user-images.githubusercontent.com/60416767/188549231-81c5876c-70c7-47da-a7c6-16236877a9ff.png)

非常感谢，我再多试试看吧。
我上面提交的控制台信息中，除了403外，还会报404的错，这个也是靠反复尝试不同的自定义服务器和upos来解决，请问是这样吗？

**Comment by MotooriKashin** [comment]
404那个不用管，是脚本正常日志。

**Comment by deuteros-gex** [comment]
> 404那个不用管，是脚本正常日志。

非常感谢您的耐心指导，试了一圈找到合适的服务器和upos了
