### ISSUE TITLE
[Bug]获取用户专栏列表失败，网络错误

### ISSUE THREAD

**Issue by duoduoffff** [MotooriKashin/Bilibili-Old#358]
**问题详情**
*在自己的旧版主页当中，无法获取专栏的 API 接口。B 站似乎对其做了 403 禁止处理。*

**复现步骤**
1. 重新安装插件脚本
2. 进入自己主页，<https://space.bilibili.com>
3. 看到如标题中的错误提示，投稿 -> 专栏 中的内容无法加载

**相关截图**
*可以的话，提供一下截图，最好是控制台报错截图*

**运行环境**
 - 操作系统：`Linux SurfacePro4 5.19.6-surface #1 SMP PREEMPT_DYNAMIC Fri Sep 2 20:37:42 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux` 
 - 浏览器：`Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0` 

**补充内容**
*其他补充内容。*

**Comment by MotooriKashin** [comment]
【自己主页】根据你提供的链接`https://space.bilibili.com/`来看应该是指个人空间

> 看到如标题中的错误提示，投稿 -> 专栏 中的内容无法加载

可以的话请提供报错信息截图，是哪个接口报错。我按你说的步骤操作并没能复现类似问题——可能是因为我没有任何投稿？

另外，个人空间并不在脚本重构目标内，并不存在所谓的【旧版】，脚本只在个人空间里进行了一些修复失效视频信息、替换顶栏等操作，应该不至于导致你说的问题。

**Comment by duoduoffff** [comment]
![Screenshot from 2022-09-06 20-51-56@2x](https://user-images.githubusercontent.com/46983115/188641043-825d6a1b-47f9-41aa-8bf0-6e207c875b6d.png)

似乎是下面这两个请求被 ban 导致的，也不一定是本人的投稿，mid 可以换成任何一个人的，都报 403 的错误。我这边再换个浏览器看是不是浏览器设置导致的

https://api.bilibili.com/x/space/article?mid=<mid>&pn=1&ps=12&sort=publish_time&jsonp=jsonp&callback=__jp4
https://api.bilibili.com/x/article/up/lists?mid=<mid>&sort=0&jsonp=jsonp&callback=__jp5
