### ISSUE TITLE
[Bug]开启嵌入式播放器替换时，无法正确加载专题页面的视频

### ISSUE THREAD

**Issue by PMisRIGHT** [MotooriKashin/Bilibili-Old#359]
**问题详情**
使用浏览器扩展，开启嵌入式播放器替换时，无法正确加载[此专题页面](https://www.bilibili.com/blackboard/activity-LnJEkfPb9v.html)的视频，已排除其他扩展和脚本影响，关闭嵌入式播放器替换时可正常加载视频

**相关截图**
下图为嵌入式播放器替换关闭时，可正确加载
![嵌入替换关闭](https://user-images.githubusercontent.com/45200086/190668787-2b023d93-135f-4fcb-9455-c109027c43e4.PNG)

下图为嵌入式播放器替换开启时，不可正确加载
![嵌入替换开启](https://user-images.githubusercontent.com/45200086/190668800-d04867e3-8375-4bad-aaa6-cad579d68696.PNG)

**运行环境**
 - 操作系统：Windows 10 1903
 - 浏览器：Google Chrome 105.0.5195.126

**Comment by MotooriKashin** [comment]
这个问题其实已经修复了，只是扩展很久没更新了🤣  
当前扩展版还存在技术难题无法攻克（设置数据的同步获取问题），一直在等待Manifest V3标准更新，所以没什么动力更新release。最关键的是扩展居然有人在用？！   
总之，目前的重心还是用户脚本，扩展则一直是开发版一样的半成品，更新速度肯定是指望不上的，还请多多担待。

PS: 截止时间只剩下3个多月了，MV3标准委员会真的有在好好考虑用户脚本的生存问题吗？完全没有任何动静的样子。

**Comment by PMisRIGHT** [comment]
更新后已正常使用嵌入式播放器，谢谢更新。
Tampermonkey的设备间同步稍微有些混乱，并且感觉扩展相对简洁一些，相对还是喜欢扩展啦。
我一个白嫖用户能用上这么好的东西就很开心了，以后再有问题我会对比扩展和脚本，如脚本无问题就不提issue打扰了。
——————
委员会：看看网友怎么说，咦，在催啊，别催了别催了，文件夹已经建好了捏~
