### ISSUE TITLE
评论区只有“按热度排行”的选项

### ISSUE THREAD

**Issue by redapple0204** [MotooriKashin/Bilibili-Old#36]
RT 
![image](https://user-images.githubusercontent.com/16254644/99797927-16dcdb80-2b6b-11eb-986f-bc5e021ecee2.png)
正常情况应该是这样，现在缺少了“按时间排序”的选项
![image](https://user-images.githubusercontent.com/16254644/99797956-23613400-2b6b-11eb-9875-aecc7e53f18e.png)

**Comment by redapple0204** [comment]
看了一下，这大概是#35 的feature？
不过建议添加一个选项来关闭这种模式

**Comment by MotooriKashin** [comment]
的确，还是有人喜欢新版的，那就加入设置中吧
