### ISSUE TITLE
[Bug]访问受限UP主空间功能无效

### ISSUE THREAD

**Issue by Nevidebla** [MotooriKashin/Bilibili-Old#360]
被拉黑的用户主页并不能访问

**Comment by MotooriKashin** [comment]
是指出差这种吗？实测被没有问题。——又或者你是指B站有什么别人拉黑你就看不到别人主页之类的功能？
![image](https://user-images.githubusercontent.com/60416767/192136243-568fa9c0-2c68-4f5e-b545-accdf50c4b26.png)

**Comment by Nevidebla** [comment]
> 

B站如果被某个用户拉黑之后就看不了他的主页了。我以为你脚本的这个功能是用来解锁这个拉黑屏蔽限制的。

**Comment by MotooriKashin** [comment]
啊，还真有这功能？那不登录不就是了？  
脚本那个功能是为解除区域限制服务的，很抱歉让你误会😂
