### ISSUE TITLE
[Feature Requset]搜索页-回到旧版

### ISSUE THREAD

**Issue by Yoho777** [MotooriKashin/Bilibili-Old#361]
**存在问题**
*bilibili默认采用新版搜索页面，虽然提供了「回到旧版」按钮，在不保存cookie设定时每次都要点一下。另外刷新的时候能复现[#354](https://github.com/MotooriKashin/Bilibili-Old/issues/354#issue-1352945177)的问题，顺便返回一个空搜索结果。回到旧版后脚本完美运行。*
<img width="1024" alt="截屏1" src="https://user-images.githubusercontent.com/97226227/193306505-5075990e-c7f4-4304-a4ef-8566532fb0d5.png">

**目标愿景**
*免去这一步操作，直接定向到旧版网页。*

**参考建议**
*模拟cookie返回一个参数？*

**Comment by Yoho777** [comment]
顺带一提，今天发现「回到旧版」的选项消失。不过切换到无痕模式就回来了。估计是灰度测试吧。
<img width="1024" alt="10 02" src="https://user-images.githubusercontent.com/97226227/193471795-8e820854-e80c-4c02-8cb4-22fd013e33d7.png">

**Comment by MotooriKashin** [comment]
搜索页面其实有重构的，我也一直在用，目前没发现什么问题，所以你大概没启用？
![image](https://user-images.githubusercontent.com/60416767/194734232-b6ea8099-1ae2-4464-a13b-0bae9ed06e48.png)

**Comment by Yoho777** [comment]
破案了，是某个广告过滤器的锅。直接导致新旧版页面同时崩坏。关掉就没有问题了。
