### ISSUE TITLE
[Bug]纪录片页面无法加载

### ISSUE THREAD

**Issue by nzd7xW5** [MotooriKashin/Bilibili-Old#362]
https://www.bilibili.com/bangumi/play/ep675689

这个界面，既不能加载视频，也不能加载评论。关掉脚本后均可正常加载

**Comment by nzd7xW5** [comment]
顺便feature request一下，B站有一堆这种强行把video/av界面重定向到bangumi/play/ep的操作。能不能在脚本这边做一个，强行在video/av界面播放的功能呢

**Comment by MotooriKashin** [comment]
第一个问题查询信息时ep列表竟然返回为空，原因不明，正在寻求解决办法...
![image](https://user-images.githubusercontent.com/60416767/194461812-a0f953d4-1cf3-4ee0-8268-112eb89762d9.png)

第二个问题：重定向是请求html页面时写在http返回头里的，那时别说用户脚本了，就连浏览器自身的一些基础脚本都未运行，所以根本没有拦截重定向请求的可能。要实现的话只能反过来在bangumi页面重定向回av页，这就会有两次重定向了，感觉也不符合你的需求。再者av页是不支持显示bangumi的分p的，重定向回去得不偿失。

**Comment by MotooriKashin** [comment]
看来bangumi接口没有该纪录片的ep数据，不知道是个例还是以后的常态，已使用其他接口进行修补。

按：因为新旧接口属性名差异太大，bangumi关键数据仍沿用bangumi主机接口。该接口20年也出现过一次同样缺少episode数组的情况，而且那次情况更为普遍，所有season都一样丢失，那时曾一度被迫全面启用新版接口。新版接口有一个问题，就是有区域限制，比如大陆ip获取不到港澳台season数据，如果不是万不得已还是继续沿用bangumi主机接口。

**Comment by nzd7xW5** [comment]
谢谢大佬
