### ISSUE TITLE
补充RSS的B站视频高清晰度

### ISSUE THREAD

**Issue by Babooers** [MotooriKashin/Bilibili-Old#363]
大佬这个项目能做吗？
https://github.com/DIYgod/RSSHub/issues/11042

**Comment by MotooriKashin** [comment]
这个【RSSHub】我没用过，暂时也没时间去研究怎么用，所以没办法测试你说的问题，非常抱歉。如果是与本脚本相关的问题，请提供相关问题截图，让我知道问题详情，或许我能大概知道怎么处理。
