### ISSUE TITLE
[Bug]带时间跳转的视频页面存在问题

### ISSUE THREAD

**Issue by nzd7xW5** [MotooriKashin/Bilibili-Old#365]
类似于这样的视频：
https://www.bilibili.com/video/av257079891_t=23s
不能够加载评论。而去掉了t=23s之后就可以：
https://www.bilibili.com/video/av257079891

另外记得早期的时候，似乎是在av号后面加上?t=70s就可以在播放视频的时候自动跳转到70秒然后开始播放，这个功能是被取消了吗？之前在历史记录页面点视频都是跳转到指定时间继续播放的，现在没有了

**Comment by MotooriKashin** [comment]
> https://www.bilibili.com/video/av257079891_t=23s

这并不是有效的参数形式（就是个错误网页），你下面说的`?t=70s`那种带问号的才是。

> 另外记得早期的时候，似乎是在av号后面加上?t=70s就可以在播放视频的时候自动跳转到70秒然后开始播放，这个功能是被取消了吗？之前在历史记录页面点视频都是跳转到指定时间继续播放的，现在没有了

近期会修复的。

**Comment by nzd7xW5** [comment]
> 这并不是有效的参数形式（就是个错误网页），你下面说的`?t=70s`那种带问号的才是。

好吧，当时报这个bug的时候输?t=10s的参数会直接跳转到_t=10s的页面，不过现在好像修复了

**Comment by MotooriKashin** [comment]
10.x 完全重构了播放器，应该已经恢复了参数识别。
