### ISSUE TITLE
[Bug]为什么有的视频会加载出一个巨大的弹幕池啊

### ISSUE THREAD

**Issue by nzd7xW5** [MotooriKashin/Bilibili-Old#366]
https://www.bilibili.com/video/av503126002/
这个视频会直接加载出10万条弹幕，然后对弹幕排序就会卡死。一般来说不是一个视频只会显示最近的两千或者三千条弹幕吗？这是bug还是这一个视频特殊啊

**Comment by wly5556** [comment]
4个小时的视频，持续满屏的弹幕量，确实会有这么多条
然后弹幕排序卡死具体是怎么触发的？我试了弹幕列表的三种排序方式，都能在一两秒内完成

**Comment by nzd7xW5** [comment]
哦哦又试了一下是假死。网页冻结三四秒之后就排序完成了。

但是按弹幕内容排序的速度是的确比其他两个慢很多
