### ISSUE TITLE
[Bug]部分视频下不显示置顶评论

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#367]
很奇怪，就是经过大量测试发现，只有一部分视频在旧版主页下不显示置顶评论，而另外一部分视频是可以显示置顶评论的。

https://www.bilibili.com/video/av293293834
![image](https://user-images.githubusercontent.com/20079289/198574108-6a767938-1937-4e8c-afe6-fe8030e4ed52.png)
![image](https://user-images.githubusercontent.com/20079289/198574170-1a794a7d-e739-463f-b367-75c5d1cf93ff.png)

**Comment by MotooriKashin** [comment]
的确，应该是翻页评论接口已不提供置顶评论数据了吧。

**Comment by MotooriKashin** [comment]
没有啊，错觉吧
