### ISSUE TITLE
请问设置-播放-播放本地文件功能是否已经失效？

### ISSUE THREAD

**Issue by y9918995** [MotooriKashin/Bilibili-Old#368]
起初我是想给站内和谐版本的视频换源观看弹幕，但是并不能够播放
然后我查询了这里的说明，并尝试在已失效的视频界面打开该功能
但是并没有什么反应
能否修复一下该功能呢？还是说由于原作者早就不更新了，该功能目前暂时失效呢？

![图片](https://user-images.githubusercontent.com/57078593/199017745-8172854f-0153-4f17-8751-d27ca88a83fa.png)

这大概是一个无效av号~
本页面使用缓存数据生成，并无法播放！
部分上古视频还存在评论区哦~

**Comment by MotooriKashin** [comment]
感谢反馈，已修复！
