### ISSUE TITLE
建议提供选项开启“评论区BV号显示标题”功能

### ISSUE THREAD

**Issue by redapple0204** [MotooriKashin/Bilibili-Old#37]
RT，这功能似乎是前几天加的，现在在新版评论里BV号会直接显示标题
![image](https://user-images.githubusercontent.com/16254644/99880603-6b598700-2c4f-11eb-9d88-f48b1fba9b92.png)
（其实我觉得这玩意加上之后会变得很冗长，不过感觉可能之后类似周刊之类的地方抄榜都不写标题了....这样只看BV号就比较不方便）

**Comment by MotooriKashin** [comment]
已更新，不过由于`jsdelivr`缓存的原因可能延时才会生效  
另外，我就直接转化为av号了，省得二次转化

**Comment by redapple0204** [comment]
@MotooriKashin 感谢！
