### ISSUE TITLE
[Feature Requset]合并dash下载

### ISSUE THREAD

**Issue by URenko** [MotooriKashin/Bilibili-Old#370]
**存在问题**
目前是分开下载，然后要手动合并

**目标愿景**
可以选择先合并然后下载

**参考建议**
往mp4添加audio track估计只要解析数据位置然后提取插入？不知道[MP4Box.js](https://gpac.github.io/mp4box.js)是否有帮助
或许干脆ffmpeg.wasm?

**Comment by MotooriKashin** [comment]
其实脚本根本没实现下载功能，脚本只是提供了下载链接，然后下载功能是交给浏览器或者IDM等工具。你说的功能如果想要实现则必须由脚本来把文件下载下来然后合并，我觉得在浏览器中实现下载功能实在不是优雅的做法，性能开销太大了。目前脚本领域大概只有[bilibili merged flv+mp4+ass+enhance](https://github.com/Xmader/bilitwin)有类似实现，而且只提供了flv到MKV封装而不是mp4。目前除了下载这种专业的功能还是交给专业的工具去做吧，下载完成使用ffmpeg合并也不是很难。

我就喜欢使用IDM，那速度感觉不是浏览器能实现的。

**Comment by URenko** [comment]
那好吧，我自己做一个

另外是否能考虑屏蔽mcdn，看着像是某种个人CDN/P2P，连接质量很差

**Comment by MotooriKashin** [comment]
设置里有个替换UPOS服务器的更能，能强制指定【下载】使用的cdn

**Comment by URenko** [comment]
我不知道它返回的CDN是对于某个清晰度&编码是单一固定的吗？如果不是可以考虑多次获取来选取非mcdn的?
因为这样可能速度最佳？虽然感觉差异不大
另外我指的不只是下载使用的CDN，也指播放的，虽然看起来是一致的

**Comment by MotooriKashin** [comment]
四个选项都有，不只是下载。  
多次获取没必要，你自己测试哪个合适用哪个就行。
