### ISSUE TITLE
请问非会员账号，解析1080P60 4K的功能，是本项目原创还是整合？有单独插件吗？

### ISSUE THREAD

**Issue by Nevidebla** [MotooriKashin/Bilibili-Old#372]
请问非会员账号，解析1080P60 4K的功能，是本项目原创还是整合？有单独插件吗？

**Comment by MotooriKashin** [comment]
本项目应该没有类似功能

**Comment by Nevidebla** [comment]
> 本项目应该没有类似功能

是我记错了吗？我记得之前好像简介里面有写这个功能。
而且目前本项目的最新版本，用非会员账号访问高清视频的时候，下面的切换清晰度栏目里面也可以成功切换成1080p60 或者4k。
截图是刚刚截的。
![image](https://user-images.githubusercontent.com/54260027/203570716-9c2de6b7-2e38-4a0e-8e83-963915be87e2.png)
![image](https://user-images.githubusercontent.com/54260027/203571241-c2558d39-c4ff-43f7-afac-89859fafa582.png)

**Comment by MotooriKashin** [comment]
图中的是B站推广4K画质的特权视频，是特例，不能等同于其他视频。B站每一次新技术推广都有这种特权视频存在，包括4K、HDR、8K、杜比视界和Hires无损音频等，详见对应的活动页面。

**Comment by Nevidebla** [comment]
> 图中的是B站推广4K画质的特权视频，是特例，不能等同于其他视频。B站每一次新技术推广都有这种特权视频存在，包括4K、HDR、8K、杜比视界和Hires无损音频等，详见对应的活动页面。

不是的呀。我截图的这个视频如果不用本项目插件，是会提示要开通会员才能切换的。
而且我也试过其他生活区、游戏区的那些视频，也都是靠本插件可以解锁高画质切换。
![image](https://user-images.githubusercontent.com/54260027/203741663-b888d99e-1b92-4e97-9e3f-644a52b6d9b5.png)

**Comment by MotooriKashin** [comment]
那些是本脚本去除了相关弹窗而已，实际上没有会员是切换不过去的，你可以邮件查看视频信息验证。
