### ISSUE TITLE
请求恢复下载字幕、弹幕、封面功能

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#373]
RT

**Comment by followmypeach** [comment]
> RT

现在我降级回了9.1.8版本了 没有弹幕字幕封面下载真的蛋疼（（（

另外提出个问题 能不能把新重构的播放器做到跟老版本一模一样（（（ 看着真的不习惯（（（（（（

**Comment by MotooriKashin** [comment]
下载功能会考虑移到播放器里。
一模一样是指？界面上唯一的不同应该就是多了个字幕按钮吧。

**Comment by followmypeach** [comment]
> 下载功能会考虑移到播放器里。 一模一样是指？界面上唯一的不同应该就是多了个字幕按钮吧。

暂停时播放按钮 播放器右上角三个按钮等

**Comment by followmypeach** [comment]
> 下载功能会考虑移到播放器里。 一模一样是指？界面上唯一的不同应该就是多了个字幕按钮吧。

附图
新版：

![_C3I4QE(3G~V3Y(X%XYVXRG](https://user-images.githubusercontent.com/77530593/206709785-d5f54740-ff00-4e88-9dfc-6192d95a3a5f.png)

旧版：

![image](https://user-images.githubusercontent.com/77530593/206710108-4270b64b-c7cd-4c56-97f1-882779b2dab0.png)

**Comment by followmypeach** [comment]
这里是一些废话
说实话我真的不是很喜欢这次的大改版
因为这次大版本直接把原版旧版播放器改的残废
重制版旧版播放器又做不到100%的复刻
在这个版本中如果我只想要原汁原味的版本就会失去新版弹幕和画质选项
挺让人糟心的
你至少也得在完全搞定新版播放器后才放弃维护原版啊
现在新版还没做好你还不维护旧版干什么（（（（（（
哎......伤心了

**Comment by MotooriKashin** [comment]
> 重制版旧版播放器又做不到100%的复刻

可以做到的，有人提出来就行，上面说的那些点都会尝试还原，同时欢迎你提出更多需要改进的地方。   
同时为原生播放器提供新版弹幕和画质选项也可以，有人提出来就行了。  
重构是一个很大的工程，而我眼力也不大好，有些地方的区别我一个人也看不出来，所以就需要大家多多提修改意见。

> 旧版

如果是说原生的旧版，那关闭【重构播放器】就是了。如果说的是那个魔改版本的【旧版】，那维护起来太痛苦了，那经过压缩混淆后的代码，就是噩梦。维护已然如此，添加新功能就更不必想。就像Bilibili开始灰度的DRM功能，如果有一天全量了，那对于旧版播放器而言就是绝路。从零开始重构为可以长期可持续维护的版本，才是我认为合理的方案。不完善的地方那就修改到满意就行了。

**Comment by followmypeach** [comment]
> > 重制版旧版播放器又做不到100%的复刻
> 
> 可以做到的，有人提出来就行，上面说的那些点都会尝试还原，同时欢迎你提出更多需要改进的地方。 同时为原生播放器提供新版弹幕和画质选项也可以，有人提出来就行了。 重构是一个很大的工程，而我眼力也不大好，有些地方的区别我一个人也看不出来，所以就需要大家多多提修改意见。
> 
> > 旧版
> 
> 如果是说原生的旧版，那关闭【重构播放器】就是了。如果说的是那个魔改版本的【旧版】，那维护起来太痛苦了，那经过压缩混淆后的代码，就是噩梦。维护已然如此，添加新功能就更不必想。就像Bilibili开始灰度的DRM功能，如果有一天全量了，那对于旧版播放器而言就是绝路。从零开始重构为可以长期可持续维护的版本，才是我认为合理的方案。不完善的地方那就修改到满意就行了。

我的建议是 在10.x.x版本内把魔改的原版保留 然后你自己写的播放器写好之前先别移除魔改原版播放器

**Comment by MotooriKashin** [comment]
下载功能已完全恢复，不会在播放器上外挂任何破坏旧版播放器样式的入口，请统一使用设置 -> 下载来下载视频、弹幕和封面。  
字幕则cc字幕控件里提供了下载按钮，切换到哪个就下哪个，设置里就不重复了。当然指的是重构后的播放器，原生播放器从来就不支持cc字幕，所以也就无从谈起。
