### ISSUE TITLE
重构版播放器的一些BUG（此issue将处于长期open状态）

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#374]
原版播放器的加载：
https://user-images.githubusercontent.com/77530593/206888449-909a1b1d-2d2b-4ebd-ac23-8dbe72c59b1f.mp4

重构版播放器的加载：
https://user-images.githubusercontent.com/77530593/206888455-b4a27247-d2f8-4da8-9154-e7fbf5777f43.mp4

图示
![GD }6ATZC40Q}GF_RQ37D7T](https://user-images.githubusercontent.com/77530593/206888517-151fe166-e63a-4d0b-b13e-d52e65611dba.png)
![image](https://user-images.githubusercontent.com/77530593/206888576-b9d4947b-5f52-490b-a88f-c6abf9018947.png)
![image](https://user-images.githubusercontent.com/77530593/206888635-7704c117-a006-48c0-914e-92b8c76c4e66.png)
![image](https://user-images.githubusercontent.com/77530593/206888664-7c9d67fd-df34-4ecc-ba70-66d1685f23ec.png)
![1WX@EPTM4JYHYFCVTL`4}G2](https://user-images.githubusercontent.com/77530593/206888759-db4b965c-3e10-4c64-a343-aded13a14e3e.png)

**Comment by MotooriKashin** [comment]
除了那个登录渐变我没看出来，其他应该已经修复了。

**Comment by followmypeach** [comment]
> 除了那个登录渐变我没看出来，其他应该已经修复了。

可以慢放对比 我的就是对比出来的

**Comment by MotooriKashin** [comment]
渐变就是css动效，都是transition那0.2秒，我是实在看不出来有区别。

![image](https://user-images.githubusercontent.com/60416767/207771289-f935e7c7-4f62-4b20-ba4f-e4c9c8f43d29.png)
![image](https://user-images.githubusercontent.com/60416767/207771305-f2dcaa3a-d2a2-41fe-afcc-c5d5d8b2d12c.png)

**Comment by followmypeach** [comment]
> 渐变就是css动效，都是transition那0.2秒，我是实在看不出来有区别。 新版video.css ![image](https://user-images.githubusercontent.com/60416767/207771289-f935e7c7-4f62-4b20-ba4f-e4c9c8f43d29.png) 旧版 ![image](https://user-images.githubusercontent.com/60416767/207771305-f2dcaa3a-d2a2-41fe-afcc-c5d5d8b2d12c.png)

估计是你电脑有点卡吧 这个css我觉得还是增加好

**Comment by followmypeach** [comment]
新增问题：
反查弹幕视觉不和谐 应该把它合并到弹幕右键列表中

**Comment by MotooriKashin** [comment]
0.2一直存在啊，所以我不明白为什么你能看出区别……

**Comment by MotooriKashin** [comment]
如果你指的是弹窗，你是页面自带的，与播放器无关。确切的说是评论区组件自带的，所以才会那么眼熟。你打开一个有播放器但无评论区的页面就可以验证。

发送者信息写入但右键里，你不觉得太长更不和谐吗？像旧版那样另起一行，遇到多条弹幕时也不像话，所以根本就没做。只标记了uid信息，如果被其他组件（比如评论区）检测到，就由对方负责提示，否则就没有任何效果。当然右侧弹幕列表除外，那个可以完美插入新行。

**Comment by MotooriKashin** [comment]
高赞弹幕可以在播放器设置里与所有互动弹幕一并关闭，而且默认就是关闭的。
![image](https://user-images.githubusercontent.com/60416767/208239930-8cd890db-7d43-4a35-a7bb-895b3648a1c8.png)

**Comment by MotooriKashin** [comment]
很抱歉之前只看到了反查弹幕的……剩下的容我再排查一下。

ps：编辑后的评论并不会邮件通知，所以不妨不要编辑而是另外追加一条评论。

**Comment by followmypeach** [comment]
新反馈：
画质选择似乎有bug（默认自动画质 手动选择画质后仍显示自动画质 第二次选择画质才会正常显示 且无法记忆之前所选择的画质）

**Comment by followmypeach** [comment]
追加视频

https://user-images.githubusercontent.com/77530593/208602630-4afe7439-3404-4350-b67d-32d94e2322da.mp4

**Comment by followmypeach** [comment]
追加：播放器样式有误（弹幕列表）
原版
![image](https://user-images.githubusercontent.com/77530593/209249999-5c771de7-01c2-45c6-8747-0c77d6c3b892.png)
重构版
![77GO)7XV3H C1K8}~9 B${Q](https://user-images.githubusercontent.com/77530593/209250123-aa295971-2aea-4645-8b9f-ea8aa00c0943.png)

这是在up主状态下的弹幕列表
可以看到 原版有四个up主操作弹幕的按钮 而重构版没有

**Comment by followmypeach** [comment]
同理 弹幕选项样式也有问题
重构版
![image](https://user-images.githubusercontent.com/77530593/209250718-222a37aa-9228-4397-821f-855867a830cd.png)
原版
![image](https://user-images.githubusercontent.com/77530593/209250781-70211961-e964-4336-bb4d-7560ccaae1df.png)


样式问题太多了......
我还是先建议搬个魔改版上去和重构版并存（‘

**Comment by MotooriKashin** [comment]
- CC字幕测试200毫秒淡出正常，该功能直接调用的`jQuery.fadeOut`并确认正常返回，应该不存在问题。
- 已添加播放器顶栏通知。
- 已修复画质选择记忆。
- 已修复右侧面板用户状态获取（影响到up本人判定导致弹幕操作面板无法调出）。
- 已修正弹幕样式选择面板对准样式。

感谢反馈，如有后续，欢迎继续反馈。

**Comment by followmypeach** [comment]
> * 已修正弹幕样式选择面板对准样式。
修正了 但未完全修正

原版
![image](https://user-images.githubusercontent.com/77530593/209536394-a4a74258-e9d8-465b-82a7-9df6b475f062.png)

重构版
![image](https://user-images.githubusercontent.com/77530593/209536415-8d000923-5a3b-4b8f-a72a-ff9b643831c3.png)

**Comment by followmypeach** [comment]
补充：行间距问题 是谁也能看得出

**Comment by followmypeach** [comment]
追加：（这个问题不知道如何描述）
重构版：
https://user-images.githubusercontent.com/77530593/209537078-cbd6c34b-92bf-4800-ae8c-cc7ec713dde4.mp4

原版：
https://user-images.githubusercontent.com/77530593/209537135-561560ec-420f-457b-8cc5-6d69d74e8b55.mp4

**Comment by MotooriKashin** [comment]
抱歉，我之前真没看出来，可能我没有特殊权限吧。

**Comment by MotooriKashin** [comment]
![image](https://user-images.githubusercontent.com/60416767/209537986-408dbad6-9edd-46f2-9a5d-70d725138bbe.png)

**Comment by followmypeach** [comment]
up主可以发字幕弹幕

**Comment by MotooriKashin** [comment]
Soga，之后再说吧，最近人不太舒服。等好一点再……抱歉……

**Comment by followmypeach** [comment]
> Soga，之后再说吧，最近人不太舒服。等好一点再……抱歉……

草 真就大多数人都阳了。。。

**Comment by followmypeach** [comment]
追加bug
重构版:
![image](https://user-images.githubusercontent.com/77530593/210136440-85a0cbce-d02d-478d-bb38-5bd3b41252d5.png)
原版：
![image](https://user-images.githubusercontent.com/77530593/210136452-ece58caf-1e6a-4138-bc4b-adecd96429e9.png)

**Comment by MotooriKashin** [comment]
1. 字幕选择样式问题未能复现
![image](https://user-images.githubusercontent.com/60416767/210933891-f5bb83c0-dd63-4efe-8f3e-d6d2d983c251.png)
2. loading样式是专门改成带测速的版本的，难道不是更实用吗？

**Comment by followmypeach** [comment]
> 2. loading样式是专门改成带测速的版本的，难道不是更实用吗？

不是实用的问题
是背景没了啊啊啊啊啊

**Comment by followmypeach** [comment]
追加个新bug
新版播放器通病了

色号为#000000的弹幕（普通弹幕 高级弹幕）都会以#FFFFFF显示

**Comment by MotooriKashin** [comment]
> 追加个新bug 新版播放器通病了
> 
> 色号为#000000的弹幕（普通弹幕 高级弹幕）都会以#FFFFFF显示

应该是protobuf弹幕的通病吧，弹幕直接用数值表示，而`0`在js语言中很容易被识别为`null`或`undefined`。我会修改一下默认值判定，麻烦稍后测试一下，或者提供一个弹幕链接给我。

ps: 以后播放器问题还是转去[bilibiliplayer](https://github.com/MotooriKashin/bilibiliplayer)仓库的issue，更方便跟踪。同时也欢迎参与维护。最后两个问题稍后修复，这个问题就先关闭了。

**Comment by MotooriKashin** [comment]
> 是背景没了啊啊啊啊啊

背景本来可以有，只是添加了网速显示后怎么看怎么别扭：  
1. 不包含文字
![image](https://user-images.githubusercontent.com/60416767/211259944-3cd041df-c3fe-4dd6-8878-3dc89ce83132.png)

2. 包含文字
![image](https://user-images.githubusercontent.com/60416767/211259991-9e780123-5ce1-4977-a486-169c8bb830f0.png)

3. 都不如不要背景，或者干脆填满整个视频？
![image](https://user-images.githubusercontent.com/60416767/211260769-e694bf30-de55-4aa0-8767-f97a91ae4a34.png)

感觉都不如不要背景，毕竟新版播放器就是这么处理的。
