### ISSUE TITLE
[Bug] 对专栏复制限制的修改失效 #171

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#375]
**问题详情**
对专栏复制限制的修改失效，无法选中问题重新出现
#171

**复现步骤**
对专栏进行选中，无法选中

**运行环境**
 - 操作系统：Windows 10 Professional 10.0.19045.2251
 - 浏览器：Mozilla Firefox 107.0.1（64 位）

**Comment by MotooriKashin** [comment]
感谢反馈，已修复
