### ISSUE TITLE
[Bug]播放器后台播放BUG

### ISSUE THREAD

**Issue by Levin-7** [MotooriKashin/Bilibili-Old#376]
**问题详情**
向前或向后加速（按下左右箭头）时会额外出现后台播放且后台播放无法暂停（但可以加速）

**复现步骤**
1.打开一个视频
2.加速

**相关截图**

https://user-images.githubusercontent.com/101990094/207416598-172d6b9f-79cd-469f-a477-1a9a0f9041af.mp4

**运行环境**
Google Chrome | 108.0.5359.99 (正式版本) （64 位） (cohort: Stable)
操作系统 | Windows 10 Version 21H2 (Build 19044.2251)
JavaScript | V8 10.8.168.21

**补充内容**
科学上网时这种现象消失（至少我没测试到）
无其他插件影响

**Comment by MotooriKashin** [comment]
已尝试对新版播放器进行精准爆破，可以测试一下是否解决。
![image](https://user-images.githubusercontent.com/60416767/207587831-6547035a-a40c-4efa-93ce-f1bade264427.png)

相同问题，全部链接到本issue #377

**Comment by chinen95** [comment]
> 已尝试对新版播放器进行精准爆破，可以测试一下是否解决。 ![image](https://user-images.githubusercontent.com/60416767/207587831-6547035a-a40c-4efa-93ce-f1bade264427.png)
> 
> 相同问题，全部链接到本issue #377

解决了！
