### ISSUE TITLE
[Bug]键盘控制异常

### ISSUE THREAD

**Issue by chinen95** [MotooriKashin/Bilibili-Old#377]
**问题详情**
*简洁清晰的问题描述。*

这两天自动更新了新版本
播放时按空格键暂停 会有从头开始播放的声音 应该是原本的播放器没屏蔽感觉 响应了键盘操作开始播放了
另外利用方向键快进/快退也会触发这个问题

**复现步骤**
1. 播放任意视频
2. 中途按下空格键暂停
3. 画面暂停住，但是会有从头播放的声音

**相关截图**
*可以的话，提供一下截图，最好是控制台报错截图*

**运行环境**
 - 操作系统：Windows11 professional 10.0.22000.778
 - 浏览器：Google Chrome 103.0.5060.134 (正式版本) （64 位） (cohort: Stable) 

**补充内容**
*其他补充内容。*

**Comment by MotooriKashin** [comment]
重复问题链接到 #376
