### ISSUE TITLE
[Bug]番剧区的播放控件问题

### ISSUE THREAD

**Issue by NightSharp** [MotooriKashin/Bilibili-Old#379]
**问题详情**
*番剧区的播放控件显示不正常，没有加载，只能点击后播放暂停*

**复现步骤**
1. 打开任意一个番剧，比如[这个](https://www.bilibili.com/bangumi/play/ss39722)
2. 播放控件没有正常加载

**相关截图**
![屏幕截图 2022-12-16 193349](https://user-images.githubusercontent.com/9748063/208092625-91f82ee9-d604-4081-9bb5-887e46d1182e.png)
下面这个是标准视频的播放控件
![屏幕截图 2022-12-16 193422](https://user-images.githubusercontent.com/9748063/208092680-2f6e9ec4-5b0f-4e24-9f35-ad1974841df8.png)

**运行环境**
 - 操作系统：Windows10 专业版22H2
 - 浏览器：Firefox 108.0 (64 位)

**补充内容**
*其他补充内容。*

**Comment by MotooriKashin** [comment]
爆破新版播放器时不小心引入的错误，感谢反馈，已尝试修复，请测试一下。

**Comment by NightSharp** [comment]
> 爆破新版播放器时不小心引入的错误，感谢反馈，已尝试修复，请测试一下。

没问题了
