### ISSUE TITLE
评论区头像框存在错位问题

### ISSUE THREAD

**Issue by redapple0204** [MotooriKashin/Bilibili-Old#38]
RT，
![image](https://user-images.githubusercontent.com/16254644/100499200-8e7dbc80-31a2-11eb-8f1e-5093cf927dac.png)

**Comment by MotooriKashin** [comment]
好吧，B站修复了评论区样式问题，所以旧版样式成了累赘，已删除相应样式。  
感谢反馈。

**Comment by redapple0204** [comment]
@MotooriKashin 感谢！

**Comment by followmypeach** [comment]
。。。。

**Comment by MotooriKashin** [comment]
脚本是最新版吗？还是说评论今天改版了？
