### ISSUE TITLE
[Feature Requset] 分集数据和弹幕投票

### ISSUE THREAD

**Issue by sddddd213** [MotooriKashin/Bilibili-Old#380]
**存在问题**
分集数据在这次更新之后就没了，可以重新加上吗？
弹幕投票好像没有一个开关来控制，可以设置一个开关了控制吗？有些弹幕投票直接出现在视频的正中央，不想投票而且还挺烦恼的。

**目标愿景**
希望出一个控制弹幕投票的生效与否的开关。
希望出一个控制分集数据的生效与否的开关。

**参考建议**
这两个功能都是之前又实现过的功能，只是在这次更新中消失的。

**补充内容**
如果可以的话，能不能把评论中楼层的功能恢复了啊？现在的那个脚本，作者放弃了。

**Comment by MotooriKashin** [comment]
投票弹幕与所有互动弹幕一并在播放器设置齿轮里关闭

**Comment by sddddd213** [comment]
![QQ截图20221219174511](https://user-images.githubusercontent.com/38841494/208396460-58f23a8c-f791-49be-a4b0-148db37ee6ed.png)
是像这样不选吗？但问题是，设置也还是会有啊。

**Comment by sddddd213** [comment]
目前重新设置后，没有弹幕投票。

**Comment by sddddd213** [comment]
分集数据，恢复了吗？我这边没有接受到新版本的推送欸。

**Comment by sddddd213** [comment]
最新情况：在播放器设置中把互动弹幕关了也依旧会有投票弹幕的框框出现，在播放器中设置好像不太行。建议回到设置面板中，之前在设置面板中时，设置一次就不用再设置了。

bangumi的分集数据什么时候能恢复呢？

**Comment by MotooriKashin** [comment]
> 在播放器设置中把互动弹幕关了也依旧会有投票弹幕的框框出现

给个视频链接？顺便提供一下时间轴。

**Comment by sddddd213** [comment]
> 

https://www.bilibili.com/video/av221419595/  
2:25以及之后4:42都有，并且我之后打开的只要有弹幕投票的视频，都有。并没有像之前的一次设置永远生效。

每次播放都要单独调整。

**Comment by MotooriKashin** [comment]
已恢复分集数据功能 设置 -> 样式 -> 分集数据  
已正确关闭投票弹幕
