### ISSUE TITLE
[Bug]番剧播放页面评论区刷新的问题

### ISSUE THREAD

**Issue by NightSharp** [MotooriKashin/Bilibili-Old#381]
**问题详情**
在打开迷你小窗时，每次在小窗消失时评论区都会强制刷新，比较不方便
标准播放页中没有问题

**复现步骤**
1. 打开任意番剧
2. 开启迷你小窗
3. 上下滚动页面让小窗出现后消失

**相关截图**
情况跟 #347 类似，就不提供截图了

**运行环境**
 - 操作系统：Windows10 专业版22H2
 - 浏览器：Firefox 108.0.1 (64 位)

**补充内容**
可能是因为番剧页面默认采用了新版样式？

**Comment by MotooriKashin** [comment]
这是不是跟你 #347 一个问题，我反复尝试页无法复现。

**Comment by NightSharp** [comment]
> 这是不是跟你 #347 一个问题，我反复尝试页无法复现。

要开启那个迷你小窗的，在每次小窗消失时评论区就会刷新
![屏幕截图 2022-12-26 095541](https://user-images.githubusercontent.com/9748063/209489644-f1442c22-6f66-49ad-9162-3efec9697f9b.png)

#347 那个是普通播放页`3.25.5-e3a5739f`，已经是正常的了。
这次这个是番剧播放页`3.25.8-d037a5fc`，仍然存在问题。

**Comment by MotooriKashin** [comment]
是不是也是其他脚本的问题，我这边真的无法复现。
![image](https://user-images.githubusercontent.com/60416767/209492684-f1ce9efb-08c0-4449-8333-c202d7a8b910.png)

**Comment by NightSharp** [comment]
> 是不是也是其他脚本的问题，我这边真的无法复现。 ![image](https://user-images.githubusercontent.com/60416767/209492684-f1ce9efb-08c0-4449-8333-c202d7a8b910.png)

好吧，貌似真的是其它脚本的问题……我先问问

**Comment by NightSharp** [comment]
> 是不是也是其他脚本的问题，我这边真的无法复现。 ![image](https://user-images.githubusercontent.com/60416767/209492684-f1ce9efb-08c0-4449-8333-c202d7a8b910.png)

是另一个脚本中的一个功能出了问题，需要关闭那个脚本中的默认宽屏功能

这边脚本中的`宽屏模式`貌似没有效果啊

**Comment by MotooriKashin** [comment]
脚本是围绕旧版播放器工作的，不会专门去适配新版播放器，设置中所有功能如果能在新版播放器生效那是碰巧，不能的话也没办法，只能说声抱歉。

**Comment by NightSharp** [comment]
> 脚本是围绕旧版播放器工作的，不会专门去适配新版播放器，设置中所有功能如果能在新版播放器生效那是碰巧，不能的话也没办法，只能说声抱歉。

好吧，那大佬有没有跟宽屏有关的脚本推荐一下，关掉那个默认宽屏后有点不太适应

**Comment by MotooriKashin** [comment]
不好说，我没用过新版，你可以自己去greasyfork找找看。

**Comment by NightSharp** [comment]
> 是不是也是其他脚本的问题，我这边真的无法复现。 ![image](https://user-images.githubusercontent.com/60416767/209492684-f1ce9efb-08c0-4449-8333-c202d7a8b910.png)

大佬，要不要再看看BE的`默认播放器模式`和BO的`翻页评论区`之间的问题
