### ISSUE TITLE
[Bug]快捷键失效（ctrl+f，alt+d）& 加回#356中的已经做好的两个feature

### ISSUE THREAD

**Issue by deuteros-gex** [MotooriKashin/Bilibili-Old#382]
不太清楚作者近期是否还会有频繁更新。。仅以目前的最新版本为准（没有任何催更的意思）

1、页面重构后，alt+d快捷键失效，实际只相当于单按d，然后弹幕就关了

2、页面重构后，ctrl+f经常识别为单按f，原本想在评论区内搜东西结果就变成视频全屏了

3、随着最近脚本的重构，原本#356 中做好的复制空降地址和多倍速播放的功能又没了，请问还能再加回来吗？

**Comment by followmypeach** [comment]
> 不太清楚作者近期是否还会有频繁更新。。仅以目前的最新版本为准（没有任何催更的意思）
> 
> 1、页面重构后，alt+d快捷键失效，实际只相当于单按d，然后弹幕就关了
> 
> 2、页面重构后，ctrl+f经常识别为单按f，原本想在评论区内搜东西结果就变成视频全屏了
> 
> 3、随着最近脚本的重构，原本#356 中做好的复制空降地址和多倍速播放的功能又没了，请问还能再加回来吗？

作者已经好几天没上github了 要不先降级回9.1.8版用着先？

**Comment by deuteros-gex** [comment]
> > 不太清楚作者近期是否还会有频繁更新。。仅以目前的最新版本为准（没有任何催更的意思）
> > 1、页面重构后，alt+d快捷键失效，实际只相当于单按d，然后弹幕就关了
> > 2、页面重构后，ctrl+f经常识别为单按f，原本想在评论区内搜东西结果就变成视频全屏了
> > 3、随着最近脚本的重构，原本#356 中做好的复制空降地址和多倍速播放的功能又没了，请问还能再加回来吗？
> 
> 作者已经好几天没上github了 要不先降级回9.1.8版用着先？

目前就是这么用的

**Comment by sddddd213** [comment]
> > 不太清楚作者近期是否还会有频繁更新。。仅以目前的最新版本为准（没有任何催更的意思）
> > 1、页面重构后，alt+d快捷键失效，实际只相当于单按d，然后弹幕就关了
> > 2、页面重构后，ctrl+f经常识别为单按f，原本想在评论区内搜东西结果就变成视频全屏了
> > 3、随着最近脚本的重构，原本#356 中做好的复制空降地址和多倍速播放的功能又没了，请问还能再加回来吗？
> 
> 作者已经好几天没上github了 要不先降级回9.1.8版用着先？

如何降级？

**Comment by MotooriKashin** [comment]
1. 已忽略组合键
2. 复制跳转地址已加回
3. 自定义播放速率请移步（在右键菜单上实现有点不和谐）
![image](https://user-images.githubusercontent.com/60416767/209467595-2ac4cf14-5688-4929-adf9-87616ec6e791.png)
