### ISSUE TITLE
[Bug]部分15年左右的搜索框下方彩蛋对应链接失效

### ISSUE THREAD

**Issue by meiruitesi** [MotooriKashin/Bilibili-Old#383]
**问题详情**
有一些彩蛋对应的超链接是http://www.bilibili.com/search?keyword=
而不是https://search.bilibili.com/all?keyword=
单击后没有返回彩蛋对应的搜索结果

**复现步骤**
随机刷出以前的彩蛋，然后单击

**相关截图**

https://user-images.githubusercontent.com/84609642/209337531-60f26f44-871d-411d-8d1a-9f67f97e1e25.mp4

https://user-images.githubusercontent.com/84609642/209338357-e77f21e6-79e9-441e-af34-9a8bfaffdff7.mp4

**运行环境**
 - 操作系统：Windows11 企业版 10.0.22621.963
 - 浏览器：Microsoft Edge 108.0.1462.54 (正式版本) （64 位）

**补充内容**
根据网页标题，貌似b站本身有自动跳转到现在的搜索结果页，但是脚本没有正确识别匹配

**Comment by meiruitesi** [comment]
控制台截图：

https://user-images.githubusercontent.com/84609642/209338706-bda54f0e-a494-4a92-abff-73a7288d85a4.mp4

**Comment by MotooriKashin** [comment]
已修复，感谢反馈！
