### ISSUE TITLE
[Bug]两个问题：没有下载按钮和如何调出设置窗口

### ISSUE THREAD

**Issue by Cloudy2022123** [MotooriKashin/Bilibili-Old#384]
我的环境：
Windows 10 企业版 LTSC
Microsoft Edge 版本 108.0.1462.54 (正式版本) (64 位)
Tampermonkey BETA 4.19.6175
Bilibili 旧播放页 10.1.1-4e3d69e61f7bae0d355804cbbda8f598579f6c92
网页链接：https://www.bilibili.com/video/av520976044/

问题1：
没有下载按钮
![22](https://user-images.githubusercontent.com/121393502/209473891-13dcaeb6-b30d-4f02-81c7-15e99713f9ef.png)

问题2：
如何调出设置窗口？
这个网址里图片的设置窗口
https://github.com/MotooriKashin/Bilibili-Old/issues/368
![33](https://user-images.githubusercontent.com/121393502/209473967-a2f78a3b-1710-4b28-8a4a-63bd1a64f40a.png)

**Comment by MotooriKashin** [comment]
其实是一个问题，如果你没用过设置，那设置入口应该就在页面右下角，鼠标移动到对应位置就会显现，而且每次页面加载完成都会滚动几下彰显存在感后才会消失。下载入口移动到了设置里，因为播放器原本是什么样式就是什么样，不想添加东西就去破坏。
![image](https://user-images.githubusercontent.com/60416767/209485841-5ba46d53-0ad9-4071-b12b-60fa34292ff7.png)

**Comment by MotooriKashin** [comment]
其实是一个问题，如果你没用过设置，那设置入口应该就在页面右下角，鼠标移动到对应位置就会显现，而且每次页面加载完成都会滚动几下彰显存在感后才会消失。下载入口移动到了设置里，因为播放器原本是什么样式就是什么样，不想添加东西就去破坏。
![image](https://user-images.githubusercontent.com/60416767/209485928-27a57c74-8b63-4d9a-a6ba-82d3e3334624.png)

**Comment by Cloudy2022123** [comment]
> 口移动到了设置里，因为播放器原本是什么样式就是什么样，不想添加东西就去破坏

看到了！闪现几秒消失了，之前从没注意到，非常谢谢！
