### ISSUE TITLE
[Bug]还是互动弹幕

### ISSUE THREAD

**Issue by sddddd213** [MotooriKashin/Bilibili-Old#385]
**问题详情**
互动弹幕目前并未得到正确关闭。

**复现步骤**
1. 找到一个带有互动弹幕的视频。
2. 跳到对应的时间节点
3. 出现互动弹幕

**相关截图**
目前找不到了，之前的带互动弹幕的视频经常出现。

**运行环境**
 - 操作系统：Windows10 2021H2
 - 浏览器：Microsoft Edge 版本 108.0.1462.76 (正式版本) (64 位)

**补充内容**
后续找到符合条件的视频后，将截图补充。

**Comment by MotooriKashin** [comment]
欢迎后续补充

**Comment by sddddd213** [comment]
建议长期该issue，以便后续用户反馈该方面的问题。

**Comment by MotooriKashin** [comment]
抱歉，我没听懂，长期是什么意思？是一直开着的意思吗？

**Comment by sddddd213** [comment]
> 抱歉，我没听懂，长期是什么意思？是一直开着的意思吗？

对。如果不便管理的话也可以关掉。

**Comment by meiruitesi** [comment]
所以互动弹幕是被砍了吗
![QQ截图20230130224247](https://user-images.githubusercontent.com/84609642/215508869-e9e152f3-527d-4208-8874-2f78b7493f85.png)
![QQ截图20230130224320](https://user-images.githubusercontent.com/84609642/215508898-507521f7-7c0b-44f9-9016-cbc1429dfcc7.png)

**Comment by meiruitesi** [comment]
如果没砍的话，问一下在哪里开，翻了半天设置没找到。。。。。

**Comment by sddddd213** [comment]
> 如果没砍的话，问一下在哪里开，翻了半天设置没找到。。。。。

没有被砍，只是之前互动弹幕设置有点问题。
要打开互动弹幕的话，可以播放器右边的齿轮里进行设置。
