### ISSUE TITLE
[Bug]文章界面乱码

### ISSUE THREAD

**Issue by nzd7xW5** [MotooriKashin/Bilibili-Old#387]
https://www.bilibili.com/read/cv20884203
<img width="685" alt="image" src="https://user-images.githubusercontent.com/69294448/211225094-b48ab248-d6de-410c-a70c-ecc7d079d587.png">

**Comment by MotooriKashin** [comment]
该问题前几天修复了，更新一下试试。

ps: 不过这篇文章的图片显示有点问题——这乱码中的`https://i0.hdslb.com/bfs/article/022df336cb0296d183f751d2e2ed2a3728e21807.jpg@progressive.jpg`是什么鬼？正常难道不应该是`https://i0.hdslb.com/bfs/article/022df336cb0296d183f751d2e2ed2a3728e21807.jpg@progressive.webp`吗？我会针对性修复一下看看。
