### ISSUE TITLE
“标签修改记录”顶栏问题、其他功能请求、评论区异常

### ISSUE THREAD

**Issue by redapple0204** [MotooriKashin/Bilibili-Old#39]
RT，在“标签修改记录”这个页面的顶栏和其他页面的顶栏对比似乎还是不是同一风格，而且依旧有莫名的N条动态提醒
![image](https://user-images.githubusercontent.com/16254644/100534505-95600a00-324a-11eb-9cdb-4212bcfd3b99.png)
![image](https://user-images.githubusercontent.com/16254644/100534509-9a24be00-324a-11eb-9c74-bd6c284e6818.png)
另外针对前几周B站开启的“BV号转标题"功能，想提一个小小的功能请求，就是在设置里可选地把这个功能关闭（但是不回退到上古的评论曲样式），这个功能感觉在某些情况下显示下来还是有点太累赘了

**Comment by redapple0204** [comment]
另外还有一个问题，通过回复界面打开视频播放链接（例如[这个](https://www.bilibili.com/video/BV1ns411D7W1#reply3759711057)）则会出现评论区加载异常的情况，不单止无法跳转到对应的评论，而且评论区整个都会变得很诡异：没有回复条数显示，无法切换页面等

**Comment by MotooriKashin** [comment]
感谢反馈。
1.评论跳转问题已解决，请稍待jsdelivr刷新缓存
2.关闭bv转标题这个不太好做，那是原生脚本实现的，如何与本脚本沟通设置数据是个问题。
3.“标签修改记录”大概是个被B站遗忘的页面，在新版页面也没有入口，那里读取历史记录的接口可能早就该版了，所以动态历史一直是过时的，我去看看能不能主动生成旧版记录吧
