### ISSUE TITLE
[Feature Requset]自动关闭生成的字幕

### ISSUE THREAD

**Issue by KazeShukufuku** [MotooriKashin/Bilibili-Old#390]
**存在问题**
*视频无字幕时总是显示自动生成的字幕（常在港澳台区看番，需要打开繁体字幕，可进入其他无字幕视频就会出现中文（自动生成））*

**目标愿景**
*视频本身无字幕时默认关闭，有字幕时再行开启*

**参考建议**
*有什么可以供参考的建议：思路或者示例等都可以。*

**补充内容**
*其他补充内容。*

**Comment by MotooriKashin** [comment]
字幕并不是播放器生成的，与一般字幕本身并无区别。感觉你的诉求是该开字幕是自动开启，改关闭时自动关闭。但这几乎不可能实现。因为有些up主根本不做字幕就依赖自动生成。

其实关字幕这个操作是很便捷的，点一下进度条的cc字幕图标就行，无需到面板中切换字幕语言的地方选择关闭。
