### ISSUE TITLE
[Bug]个别页面脚本未支持

### ISSUE THREAD

**Issue by nzd7xW5** [MotooriKashin/Bilibili-Old#392]
https://www.bilibili.com/festival/blhx2023?bvid=BV1iG4y1w7Bo&=&aid=820479022

这个页面似乎加载不出来旧版播放器

**Comment by MotooriKashin** [comment]
测试应该能正常加载，是不是设置中关了？
![image](https://user-images.githubusercontent.com/60416767/213662436-19c52a31-83a2-4c43-bf80-a3dff487349a.png)

**Comment by nzd7xW5** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/69294448/213753850-4efd7122-6db1-42c9-8073-d8d190a8ff33.png">
没关啊

**Comment by MotooriKashin** [comment]
看看一下控制台信息

**Comment by nzd7xW5** [comment]
pakku ajax: injecting hook
activity-video.7ccf61330ff2435db6f0b29b258550163267da13.js:1                      //         \\         //          \\       //    ##DDDDDDDDDDDDDDDDDDDDDD##    ## DDDDDDDDDDDDDDDDDDDD ##   ________   ___   ___        ___   ________   ___   ___        ___    ## hh                hh ##   |\   __  \ |\  \ |\  \      |\  \ |\   __  \ |\  \ |\  \      |\  \    ## hh    //    \\    hh ##   \ \  \|\ /_\ \  \\ \  \     \ \  \\ \  \|\ /_\ \  \\ \  \     \ \  \    ## hh   //      \\   hh ##    \ \   __  \\ \  \\ \  \     \ \  \\ \   __  \\ \  \\ \  \     \ \  \    ## hh                hh ##     \ \  \|\  \\ \  \\ \  \____ \ \  \\ \  \|\  \\ \  \\ \  \____ \ \  \    ## hh      wwww      hh ##      \ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\    ## hh                hh ##       \|_______| \|__| \|_______| \|__| \|_______| \|__| \|_______| \|__|    ## MMMMMMMMMMMMMMMMMMMM ##    ##MMMMMMMMMMMMMMMMMMMMMM##                                          Release undefined@no release yet         \/            \/                                       Powered by @bilibili/jinkela-core@2.8.11
xhr_hook.js:2 pakku ajax: hook set
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/activity-video/css/activity-video.0.7ccf61330ff2435db6f0b29b258550163267da13.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/activity-video/css/activity-video.1.7ccf61330ff2435db6f0b29b258550163267da13.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/activity-video/css/activity-video.11.7ccf61330ff2435db6f0b29b258550163267da13.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/activity-video/css/activity-video.10.7ccf61330ff2435db6f0b29b258550163267da13.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/activity-video/11.activity-video.7ccf61330ff2435db6f0b29b258550163267da13.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/activity-video/8.activity-video.7ccf61330ff2435db6f0b29b258550163267da13.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/vue.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/activity-video/activity-video.7ccf61330ff2435db6f0b29b258550163267da13.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/activity-video/10.activity-video.7ccf61330ff2435db6f0b29b258550163267da13.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/activity-video/css/activity-video.8.7ccf61330ff2435db6f0b29b258550163267da13.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/activity-video/1.activity-video.7ccf61330ff2435db6f0b29b258550163267da13.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
script_injector.js:2 pakku ajax: injecting hook
xhr_hook.js:2 pakku ajax: hook set
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/seed/jinkela/header-v2/international-header-088954d6af65fc8e90626a3503732878e59ac211-header.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
VM2966:17236 The key "target-densitydpi" is not supported.
palyerPage @ VM2966:17236
eval @ VM2966:27028
eval @ VM2966:27046
(anonymous) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=1c421df1-6031-493d-8d1b-515e891680c0:27093
(anonymous) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=1c421df1-6031-493d-8d1b-515e891680c0:27103
(anonymous) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=1c421df1-6031-493d-8d1b-515e891680c0:27104
St @ VM2956:9
(anonymous) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=1c421df1-6031-493d-8d1b-515e891680c0:1
window.__f__lddyejz4.ix8 @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=1c421df1-6031-493d-8d1b-515e891680c0:1
St @ VM2956:9
n @ VM2956:71
(anonymous) @ VM2956:72
set @ VM2956:80
(anonymous) @ userscript.html?name=Bilibili%2520%25E6%2597%25A7%25E6%2592%25AD%25E6%2594%25BE%25E9%25A1%25B5.user.js&id=1c421df1-6031-493d-8d1b-515e891680c0:1
ho @ content.js:21
O @ content.js:39
(anonymous) @ content.js:40
Mt @ content.js:8
t @ content.js:9
Io @ content.js:36
Vo @ content.js:51
(anonymous) @ content.js:51
(anonymous) @ content.js:15
Mt @ content.js:8
t @ content.js:9
(anonymous) @ content.js:15
(anonymous) @ content.js:48
1.activity-video.7ccf61330ff2435db6f0b29b258550163267da13.js:38 res {code: 0, message: '0', ttl: 1, data: {…}}
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/activity-video/12.activity-video.7ccf61330ff2435db6f0b29b258550163267da13.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
script_injector.js:2 pakku ajax: injecting hook
script_injector.js:2 pakku ajax: injecting hook
xhr_hook.js:2 pakku ajax: hook set
xhr_hook.js:2 pakku ajax: hook set
xhr_hook.js:2 pakku ajax: worker send 968607603 https://api.bilibili.com/x/v2/dm/web/view?type=1&oid=968607603&pid=820479022
xhr_hook.js:2 pakku ajax: worker finished for 968607603
xhr_hook.js:2 pakku ajax: worker send 968607603 https://api.bilibili.com/x/v2/dm/web/seg.so?type=1&oid=968607603&pid=820479022&segment_index=1
xhr_hook.js:2 pakku ajax: worker finished for 968607603

**Comment by MotooriKashin** [comment]
还是截图吧，原谅我看不懂这些未排版的数据——只能看到是有报错，但无法定位。    

建议关闭同时运行的其他脚本和扩展测试，因为上图报错有几个关键词`target-densitydpi``palyerPage`等明显不是来自本脚本，怀疑是其他脚本或扩展代码出错而牵连出的问题。

**Comment by nzd7xW5** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/69294448/215027174-b837f258-bade-4a4a-9e0b-08961e562ddf.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/69294448/215027224-452dd8cf-c137-43b0-b3ab-d50b0f3ff3b3.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/69294448/215027249-305a3061-530a-49c1-b0ce-d30e7d7e0665.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/69294448/215027287-0ab83bb7-f27a-493c-b339-beddb9f8adc2.png">

**Comment by nzd7xW5** [comment]
除了pakku我应该没有其他在运行的相关插件了啊

**Comment by nzd7xW5** [comment]
以及不好意思 以为github的粘贴可以把控制台的字号颜色缩进啥的一并粘过来

**Comment by MotooriKashin** [comment]
抱歉，从截图中没发现任何与本脚本相关的错误。能不能临时把pakku关了测试，另外请将`The key "target-densitydpi" is not supported.`那行警告前的三角展开。

**Comment by nzd7xW5** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/69294448/215155937-37855052-58a0-4814-bb90-71b513e56a4d.png">
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/69294448/215155982-c7ef1966-e22c-48b9-984b-30a7e1e0ed99.png">
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/69294448/215156057-125779c0-3bba-48de-9ab3-935285de4c7d.png">
关掉了除了monkey之外的所有插件了
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/69294448/215156193-4cb58b49-5236-49fd-9905-a8f420889059.png">
症状还是，会出现一个白页面

**Comment by MotooriKashin** [comment]
奇了怪了，没有任何报错，唯一一个警告的关键词也不属于本脚本。你干脆把本脚本也禁用看看，我觉得可能依然是一个白页面。

**Comment by MotooriKashin** [comment]
对于这种嵌入播放器的页面，脚本做的唯一的事情就是拦截并替换掉播放器，而不是对页面本身做任何修改。拦截时至少该有下面这样的日志。你这种情况根本时新版播放器都未载入，很难说与本脚本有关。

![image](https://user-images.githubusercontent.com/60416767/215254379-ef2e7877-df2a-44da-81f9-d62c02a19dff.png)

**Comment by nzd7xW5** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/69294448/215267961-2b62a2a7-2c5b-42e5-ab29-3914155b84f8.png">
关了脚本就有播放器了啊

关了脚本后的控制台：
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/69294448/215268006-b5f3ac50-eca7-46f3-b179-d3d91a41499a.png">
开了脚本的控制台：
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/69294448/215268029-b26a1623-ff1f-4dae-8bd6-55e4b23ad5aa.png">
额这次不太一样，这次开了脚本之后是出了肥肠抱歉的16秒视频

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/69294448/215268058-ba72402d-b20e-40de-847e-0703d7849db6.png">
又刷新了一次，这次又白屏了

**Comment by nzd7xW5** [comment]
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/69294448/215287017-1d09d157-ab73-4e6a-aeb6-47d6bca135b0.png">
另外，我只要打开脚本，monkey这里都显示的是有4个脚本在运行？不知道这个是不是问题的原因？

**Comment by nzd7xW5** [comment]
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/69294448/215287065-39b95bda-0231-4b2e-a46f-54975e4ea9d2.png">
其他视频里monkey都显示是两个脚本运行

**Comment by MotooriKashin** [comment]
突然想到你可以在设置里关闭 重写 -> 播放器 试试，在此页面禁用旧版播放器。

**Comment by nzd7xW5** [comment]
<img width="137" alt="image" src="https://user-images.githubusercontent.com/69294448/216571924-8b42a9c8-7cb6-4644-9951-e317ad74ecb7.png">
哪个栏目啊

**Comment by nzd7xW5** [comment]
av/BV
旧版一般视频播放页面
bangumi
旧版Bangumi页面
稍后再看
旧版稍后再看页面
嵌入
旧版嵌入式播放器
主页
旧版主页
排行榜
旧版全站排行榜
专栏
旧版专栏页面
medialist
旧版播单相关页面
合集
以分P形式呈现
搜索
旧版搜索页面

哪一个是播放器啊，第一个吗

**Comment by MotooriKashin** [comment]
嵌入

**Comment by MotooriKashin** [comment]
你这应该不是最新版脚本吧？设置界面都不一样。

**Comment by nzd7xW5** [comment]
更新了脚本就可以打开了 == 不知道之前是什么bug
谢谢了
