### ISSUE TITLE
[弹幕]本人搜集还原的一些弹幕

### ISSUE THREAD

**Issue by Deadline233233** [MotooriKashin/Bilibili-Old#394]
链接: https://pan.baidu.com/s/1wL_CnFI4dTMzm93fJkqFPA?pwd=5u8c 提取码: 5u8c 

网站本体来自https://github.com/MikuFan039/DMFNew

把三回蓝白弹幕大赛全部备份了一遍，零零散散把自己看到的觉得好的都抓了一遍，大部分来自b站，一部分来自danmaku.site:90(网站已经没了)
M7，M8都可以正常运行，弹幕游戏也可以正常玩。之前一直被一个protobuf转xml的工具坑了，有些字符不认导致弹幕没法正常放，自己重写了一遍转换工具从b站爬下来的基本都行了。写了个爬虫，输入视频地址自动爬取并转换成xml，https://github.com/Deadline233233/bilibili_danmaku_protobuf2xml
转换的xml格式是DMF里的弹幕格式，而不是b站xml弹幕的格式

**Comment by MotooriKashin** [comment]
抱歉，来晚了，链接已失效。建议直接添加到danmaku文件夹，命名为`${cid}.xml`就行，非常感谢。

**Comment by Deadline233233** [comment]
> 抱歉，来晚了，链接已失效。建议直接添加到danmaku文件夹，命名为`${cid}.xml`就行，非常感谢。

傻X百度，竟然说我文件违规，天翼云盘应该可以：https://cloud.189.cn/web/share?code=6VfIVnuqyQnq（访问码：6khc）
弹幕文件在html\uploads\Bilibili下，并不是按cid来命名的

**Comment by followmypeach** [comment]
> > 抱歉，来晚了，链接已失效。建议直接添加到danmaku文件夹，命名为`${cid}.xml`就行，非常感谢。
> 
> 傻X百度，竟然说我文件违规，天翼云盘应该可以：[https://cloud.189.cn/web/share?code=6VfIVnuqyQnq（访问码：6khc）](https://cloud.189.cn/web/share?code=6VfIVnuqyQnq%EF%BC%88%E8%AE%BF%E9%97%AE%E7%A0%81%EF%BC%9A6khc%EF%BC%89) 弹幕文件在html\uploads\Bilibili下，并不是按cid来命名的

打扰下 这里是DMF网站管理员之一
DMF网址已经更改为danmaku.top

**Comment by MotooriKashin** [comment]
经过验证，确实存在弹幕丢失的以及视频没有失效的已添加到目录中。感谢提供资源！
