### ISSUE TITLE
[Bug]竖向弹幕

### ISSUE THREAD

**Issue by sddddd213** [MotooriKashin/Bilibili-Old#396]
**问题详情**
播放器的右边会有一块白色区域，看其功能应该是显示竖向的弹幕。
**复现步骤**
1. 打开 https://www.bilibili.com/video/av983933215/

2. 
![image](https://user-images.githubusercontent.com/38841494/216215408-f6715065-6997-45a8-9a45-2c427034bc42.png)

**相关截图**
![image](https://user-images.githubusercontent.com/38841494/216215648-146cc9ca-4051-4c3d-9598-b1f88824f2f3.png)

**运行环境**
 - 操作系统：Windows10 21H2
 - 浏览器：Microsoft Edge 版本 109.0.1518.70 (正式版本) (64 位)

**补充内容**
上一个互动弹幕的issue可以关闭了，麻烦开发者了，谢谢。

**Comment by MotooriKashin** [comment]
应该已经支持了，你是不是没更新脚本？
