### ISSUE TITLE
[Feature Requset]希望重新加入设置-播放-优先载入的视频编码类型（avc，hevc, av1）选项

### ISSUE THREAD

**Issue by ichitodake** [MotooriKashin/Bilibili-Old#397]
**存在问题**
*目前存在什么问题：设置-播放-优先载入视频的编码的选项，一段时间没有用，发现貌似从去年的某个版本开始就不见了，无法选择优先载入的视频编码*

**目标愿景**
*希望实现的目标：希望重新加入设置-播放-优先载入的视频编码类型（avc，hevc, av1）*

**补充内容**
*通过查找issue,发现在 https://github.com/MotooriKashin/Bilibili-Old/issues/224 应该是最初这个功能的请求，不知道从哪个版本开始这个功能又不见了。*

**Comment by MotooriKashin** [comment]
已内置于播放器中，请在右侧齿轮中调整。
![image](https://user-images.githubusercontent.com/60416767/216758331-013f9afa-deb3-474c-b5e2-b366cd468dbe.png)
