### ISSUE TITLE
[Feature Requset]能否关闭弹幕自动遮挡&进度条热力图

### ISSUE THREAD

**Issue by nzd7xW5** [MotooriKashin/Bilibili-Old#398]
1. 可以关闭AI自动识别的自动让人像遮挡弹幕功能吗？有的时候人在视频里动来动去的，AI识别的不准确，遮挡了弹幕全都是花的。没找到在哪里可以关闭这个AI功能
2. 可以关闭进度条的热力图吗？就是进度条 上面一点的蓝色的那个热力图（好像叫高能进度条）。

另外就是提一个小小的建议，很多人用这个脚本应该都是因为不太喜欢新播放器的花里胡哨的功能吧。像AI识别使弹幕避开人像，和进度条热力图这种属于新播放器的新功能，能不能设计一个总的开关，来控制这些功能的启动与否啊？就设计一个总开关，开了之后就让播放器不支持任何新播放器的花哨功能，做成纯净版的那种感觉。不知道技术上方不方便实现，谢谢了

**Comment by MotooriKashin** [comment]
只能防档弹幕和高能进度条
![image](https://user-images.githubusercontent.com/60416767/216805448-43c4e30e-8bd5-41fa-948b-b99d46df6577.png)
