### ISSUE TITLE
[功能请求] 允许进入播放页不预载入视频

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#40]
如题
有时候使用脚本的下载功能，由于在按流量计费的网络中并不希望自动预载。

**Comment by MotooriKashin** [comment]
这个要求还真是很奇怪哈！我可以试试看

**Comment by MotooriKashin** [comment]
已在设置中添加相关功能，拦截视频链接，功能过于暴力，不用时请关闭并刷新页面

**Comment by MyBlueHorizon** [comment]
话说可以通过 video 标签的preload和autoplay来解决吗

**Comment by MotooriKashin** [comment]
B站为了加快视频载入速度，请求视频数据似乎是由播放器脚本代劳而不是由video标签调用浏览器自带实现，DASH视频尤其如此。从video标签入手应该无法阻止视频自动载入，只等强行让播放器获取错误的地址。
