### ISSUE TITLE
[Bug]免登录看1080p失效，还有办法吗

### ISSUE THREAD

**Issue by yilksd** [MotooriKashin/Bilibili-Old#408]
**问题详情**
*简洁清晰的问题描述。*
b站未登录，有切换到1080p的选项，但是点击切换后没效果，实际画质无提升。

**运行环境**
 - 操作系统：ubuntu20.04
 - 浏览器：firefox 104

**补充内容**
*其他补充内容。*
现在b站不登录只给360p了，  搜索发现 ：https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5/discussions/70799 ，我看到这个讨论发现之前本脚本是有b站免登录看1080p的功能的，故有此疑问。

**Comment by MotooriKashin** [comment]
有在设置里启用相关选项吗？

**Comment by yilksd** [comment]
> 有在设置里启用相关选项吗？

哦哦，刚看了下设置，不登录看高画质需要账户授权，那这还是算了。还是谢谢作者
