### ISSUE TITLE
有些视频看不了啦

### ISSUE THREAD

**Issue by sannanaama** [MotooriKashin/Bilibili-Old#409]
**问题详情**有些视频看不了啦
*简洁清晰的问题描述。*
播放部分视频黑屏
**复现步骤**
1. '...'
2. '...'
3. '...'

**相关截图**
![2023-03-01](https://user-images.githubusercontent.com/118704590/222146360-d80c9e64-cc64-4e19-8289-fab10d4733f4.png)

*可以的话，提供一下截图，最好是控制台报错截图*
运行环境
 -操作系统：Windows 10 专业版 22H2
  浏览器：Cent Browser 版本 5.0.1002.295（正式版本） （64 位） (Chromium 102.0.5005.167)

**补充内容**
*其他补充内容。*

**Comment by MotooriKashin** [comment]
你把清晰度切换为自动并刷新试试，该视频似乎有点特殊，部分清晰度只有hev编码，Windows+chrome102显然无法解析。

**Comment by sannanaama** [comment]
> 你把清澈度切换为自动并刷新试试，该视频似乎有点特殊，部分清澈度只有hev编码，Windows+chrome102显然无法解析。
好了，看来确实是hevc的问题，选择avc就能放了,谢啦
