### ISSUE TITLE
[Bug]在使用插件时，会遇到cpu占用过高的问题

### ISSUE THREAD

**Issue by javilak** [MotooriKashin/Bilibili-Old#410]
**问题详情**
在使用插件时，不知道为什么会让浏览器占用大量cpu资源

**运行环境**
 - 操作系统：Windows11 professional 
 - 浏览器：Google Chrome  110.0.5481.177 (正式版本) （64 位）

**Comment by MotooriKashin** [comment]
不太明白你的意思，内存占用还好理解，CPU占用是什么意思，能不能提供一些性能数据参考？与不使用本脚本情况对比什么的。
1. 比如chrome自带的资源监视器
![image](https://user-images.githubusercontent.com/60416767/222620317-ce0265f1-f6c2-45a7-8820-bfaedb4738f0.png)
2. 比如chorme devtool性能快照
![image](https://user-images.githubusercontent.com/60416767/222620885-0f2a00d1-4e2d-4d57-8028-25130c9f0096.png)

ps: 性能快照可以分享出来供分析，步骤如下图
![image](https://user-images.githubusercontent.com/60416767/222621187-775b0e62-7dc6-4258-8b94-dd8059e83073.png)


我是不太明白为什么会担心CPU占用什么的，下图是关闭脚本情况下的B站首页性能监视情况，CPU占用一直都是一个跳动的数值，大体上与开启脚本时没有区别，也可能是我的设备太烂的缘故？  
我觉得你的意思应该是哪里卡顿？那与其关心CPU占用，还是按上文分析性能快照中的其他因素更有效一些。
![image](https://user-images.githubusercontent.com/60416767/222621659-653d566c-b81f-486a-b933-5b85309a0505.png)

**Comment by MotooriKashin** [comment]
如果在Bangumi页面遇到，会不会是 #411 的原因？

**Comment by javilak** [comment]
在我当晚更新扩展之后好像就没出现了。但是之前的话在我开了上百个页面之后，打开新的b站页面如bilibili搜索页面时，浏览器任务管理器里的实用程序: Storage Service，会和其余的b站页面cpu占用变高。

**Comment by MotooriKashin** [comment]
上百个🤣  
没复现就好，我这破设备也没办法复现过程，只打开一个B站页面的话，实用程序: Storage Service根本不动的。  
此问题先关闭了，以后复现了再看情况重新打开吧。

**Comment by javilak** [comment]
https://1drv.ms/u/s!AoR4ljDVv-H3swIaaIdR-qhGVCqi?e=qTeT9a
昨晚好像遇到情况了，我导出了一份，🤣不过这玩意预料外的大

**Comment by MotooriKashin** [comment]
> 不过这玩意预料外的大

纯文本文件，可以用压缩软件压缩一下，然后就可以直接在这里发送。OneDrive我打不开🤣

**Comment by javilak** [comment]
[Profile-20230305T115722.zip](https://github.com/MotooriKashin/Bilibili-Old/files/10890958/Profile-20230305T115722.zip)

**Comment by javilak** [comment]
说实话能察觉这种情况就是因为太夸张了，任务管理器一看chrome把我12核cpu占用干到100%🤣
![Snipaste_2023-03-05_15-16-03](https://user-images.githubusercontent.com/47470153/222947319-3a840bf1-17e0-4566-8ff9-0e8b7e52b8c3.png)

**Comment by MotooriKashin** [comment]
![image](https://user-images.githubusercontent.com/60416767/222951481-bab25be8-d864-49c4-973c-efe609490909.png)

分析了一下你提供的性能快照：
首先，根据标记3可知，的确在页面加载完成后那一段有持续的js执行（黄色）在占用cpu资源，而且隐隐有持续上升的趋势。——这应该就是问题的核心。  
然后根据标记1可知这是在`search.bilibili.com`（搜索页面），然而矛盾出现了，随便点击此时的任务队列，发现有脚本一直在反复定时器（消耗cpu资源），执行的脚本来自`s1.hdslb.com/bfs/static/jinkela/home/1.home.4eadf4209b1762230047120e0a9945a9f3b56fd1.js`（标记2）——这个脚本本不该出现在搜索页面，这是B站主页脚本！  

所以主页的脚本为什么会出现在搜索页面？如下图，我这里测试搜索页面无论如何都不会请求上面那个脚本。
![image](https://user-images.githubusercontent.com/60416767/222951951-6075c56b-acf7-40bc-9270-8f6d0b3aa8c7.png)

现在原因已经锁定了，就是那个不该出现的脚本不停在使用定时器。我想知道这个问题是只发生在搜索页面吗？是百分百发生的吗？以及如果可以的话提供一下发现问题时"网络"面板（如图2）的情况，重点关注"js"和”文档“两项，我想知道为什么会请求那个脚本。

ps: 网络面板只会记录打开控制台以后的数据，所以可能要刷新页面。请确认刷新以后问题仍然存在，这样记录的数据才有意义。另外网络面板虽然也能保存快照，但各种请求可能会包含你的身份信息，请不要公开分享出来，截图就行。

**Comment by javilak** [comment]
![image](https://user-images.githubusercontent.com/47470153/222956059-6afd80ae-61ed-4659-ae7f-0d5d1a5b4094.png)
![image](https://user-images.githubusercontent.com/47470153/222956100-9fa25ac7-0e1c-4670-b7e7-5f30e49202e9.png)
并不是百分百发生的，只能说摸不着头脑，上两月试过开一个页面都有高占用的情况

**Comment by MotooriKashin** [comment]
> ![image](https://user-images.githubusercontent.com/47470153/222956059-6afd80ae-61ed-4659-ae7f-0d5d1a5b4094.png) ![image](https://user-images.githubusercontent.com/47470153/222956100-9fa25ac7-0e1c-4670-b7e7-5f30e49202e9.png) 并不是百分百发生的，只能说摸不着头脑，上两月试过开一个页面都有高占用的情况

确定时异常时的截图吗？好像也没有`s1.hdslb.com/bfs/static/jinkela/home/1.home.4eadf4209b1762230047120e0a9945a9f3b56fd1.js`的身影。。。

**Comment by javilak** [comment]
是，那页面我还留着

**Comment by javilak** [comment]
[Profile-20230306T175805.zip](https://github.com/MotooriKashin/Bilibili-Old/files/10896924/Profile-20230306T175805.zip)
这是另一个页面的，播放页。
我推测触发这种情况需要10+的已打开b站页面，并静置一段时间？几小时-一晚上？然后打开新的b站页面

**Comment by javilak** [comment]
[Profile-20230306T184224.zip](https://github.com/MotooriKashin/Bilibili-Old/files/10897241/Profile-20230306T184224.zip)
这个是打开首页的性能分析，有两份，下面因为太大做了分卷处理
[Profile-20230306T184149.zip](https://github.com/MotooriKashin/Bilibili-Old/files/10897277/Profile-20230306T184149.zip)
下面这个是分卷，后缀名需要改回z01
[Profile-20230306T184149.zip](https://github.com/MotooriKashin/Bilibili-Old/files/10897287/Profile-20230306T184149.zip)
希望有助于定位到问题根源所在

**Comment by MotooriKashin** [comment]
> 我推测触发这种情况需要10+的已打开b站页面，并静置一段时间？几小时-一晚上？然后打开新的b站页面

如果时这样，那可能不是脚本的问题。或许是浏览器的问题，猜测可能和标签页自动休眠机制有关。

**Comment by javilak** [comment]
现在chrome有了内存节省程序就没问题了，推测是有个主页开太久不知道怎么被其他页面调用导致的，因为经过测试只要把在主页的标签全关掉占用就瞬间下来了，现在内存节省程序自动把页面回收后这个问题就以一种奇怪的方式解决了

**Comment by MotooriKashin** [comment]
Soga！
