### ISSUE TITLE
重构播放器时失败

### ISSUE THREAD

**Issue by Ourworldmediagroup** [MotooriKashin/Bilibili-Old#415]
获取播放器组件出错！1/2
{ "finalUrl": "https://fastly.jsdelivr.net/gh/MotooriKashin/Bilibili-Old@d414ddff0d7fd83097694b3542d19a559b95e242/chrome/player/video.js", "readyState": 4, "status": 0, "statusText": "", "lengthComputable": false, "loaded": 0, "total": 0, "response": "", "responseHeaders": "", "responseText": "", "responseXML": { "location": null } }

**Comment by MotooriKashin** [comment]
网络（墙）问题吧，如果多次出现临时请关闭重构播放器更新。
