### ISSUE TITLE
[Bug]: 稍后再看右侧列表的x不能删除视频，会直接跳转到该视频

### ISSUE THREAD

**Issue by 562860579** [MotooriKashin/Bilibili-Old#416]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

RT，想删除稍后再看里的视频只能在https://www.bilibili.com/watchlater/#/list这个页面里删除，已经这样好久了，更新了好几次插件也没好

### 操作系统

Windows 10

### 浏览器名称及版本

chrome 111.0.55563.65/edge 111.0.1661.44

### 脚本版本

10.3.9-d414ddff0d7fd83097694b3542d19a559b95e242

**Comment by MotooriKashin** [comment]
感谢反馈，已修复
