### ISSUE TITLE
主页无法实现旧版界面

### ISSUE THREAD

**Issue by redapple0204** [MotooriKashin/Bilibili-Old#42]
RT，不过播放也正常，console中错误如下
![image](https://user-images.githubusercontent.com/16254644/103734335-b88a9000-5026-11eb-889c-267ea06e683b.png)

**Comment by MotooriKashin** [comment]
感谢反馈！
已重构主页数据。

**Comment by redapple0204** [comment]
@MotooriKashin 感谢！不过貌似现在新版本还是有这个问题诶...

**Comment by MotooriKashin** [comment]
不会吧，试试卸载脚本重新安装，可能是模块没更新。

**Comment by redapple0204** [comment]
@MotooriKashin 感谢，现在测试一番已经正常了
