### ISSUE TITLE
[Feature Requset]: 网页版能否出一个「取消重定向到404页面」的功能

### ISSUE THREAD

**Issue by nzd7xW5** [MotooriKashin/Bilibili-Old#420]
### 存在问题

现在加载一个视频页面时间太长的时候（比如说，假如我网速很慢），加载一两分钟页面会自动重定向到 https://www.bilibili.com/404 然后浏览器的历史记录也没有重定向前的网页地址，按“回退”键也找不回自己一开始输入的到底是什么地址，就等于是/404 这个网址直接把我之前想浏览的所有信息都覆盖掉了。有的时候单纯网速慢，结果等个几分钟一看页面，全变404了，都找不到之前的av号

### 目标愿景

能不能拦截这个自动重定向到404页面的功能，就比如加载时间过长就直接让浏览器报错说检测到你网速不好建议你重联网再刷新，类似于chrome自己的报错页面那种，起码让我的地址栏仍然看得到我之前输入的视频号

不方便的话能不能在404页面里加一行信息，展示一下我是从哪个视频跳转到这个404页来的

**Comment by MotooriKashin** [comment]
404是原生超时自动重定向，使用的方法是
```
location.herf = '/404'
```
据我所知这没法拦截，因为`location`是个不能覆写的对象，无法进行hook。

只是想知道是从哪个页面重定向来的话可以在控制台输入
```
document.referrer
```
并回车，会返回重定向前的链接。
