### ISSUE TITLE
[Bug]: 无法使用idm下载视频

### ISSUE THREAD

**Issue by chatseeon** [MotooriKashin/Bilibili-Old#421]
### 问题是发生在那种形态的？

Chrome扩展

### 问题详情

很久没有下视频了，刚刚想下个视频，发现下载链接一直显示不出来，于是我就更新了一下脚本，然后下载链接就可以显示了。我像以前一样复制链接到idm下载，却发现无法使用idm下载视频，并且用potplayer测试了一下链接（以前用potplayer播放过视频链接），同样也是无法播放。

### 复现步骤

1.复制链接到idm下载
![屏幕截图 2023-03-25 153449](https://user-images.githubusercontent.com/107085673/227704522-6f58574e-7997-435a-90f6-834da07b3966.jpg)

2.出现如下错误
![屏幕截图 2023-03-25 153517](https://user-images.githubusercontent.com/107085673/227704545-7f8c45cd-893d-40bb-99e4-39b758481fe4.jpg)

3.复制链接到potplayer尝试播放
![屏幕截图 2023-03-25 153551](https://user-images.githubusercontent.com/107085673/227704624-86d207f5-c488-4a86-aa29-1886591a621f.jpg)

4.出现如下错误
![屏幕截图 2023-03-25 153843](https://user-images.githubusercontent.com/107085673/227704633-b0d10bf8-575b-4ecb-bc75-2f7c482f3060.jpg)

### 操作系统

Windows 10

### 浏览器名称及版本

Google Chrome 64位 111.0.5563.65 

### 脚本版本

v10.4.1-91f6f5f11c47f13fb7f79ab811124cda994f77f7

**Comment by chatseeon** [comment]
目标视频地址：https://www.bilibili.com/video/av310805926/
脚本获取地址：https://xy42x81x247x173xy.mcdn.bilivideo.cn:4483/upgcxcode/60/48/1053304860/1053304860-1-208.mp4?e=ig8euxZM2rNcNbhBhzdVhwdlhzUzhwdVhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1679736230&gen=playurlv2&os=mcdn&oi=604372963&trid=00006c6e83c2fec043d1a14eed719a84dde0u&mid=332723291&platform=pc&upsig=e110992a2aa4b9122354b07ea2beced9&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&mcdnid=11000356&bvc=vod&nettype=0&orderid=0,3&buvid=FE1717F6-FF26-46FE-8561-773AB736279A167620infoc&build=0&agrr=1&bw=353715&logo=A0000400

**Comment by MotooriKashin** [comment]
之前获取mp4的借口和谐了，现在mp4和其他格式一样需要配置User-Agent和referer，除非是Bangumi。

下载复制链接同理，建议设置里更换下载方式。
