### ISSUE TITLE
[Feature Requset]: 其他脚本使用 __INITIAL_STATE__ ，导致失效。

### ISSUE THREAD

**Issue by hdchieh** [MotooriKashin/Bilibili-Old#424]
### 存在问题

其他脚本使用 __INITIAL_STATE__ ，导致失效。

https://greasyfork.org/en/scripts/431519-bilibili%E8%A7%86%E9%A2%91%E8%A7%82%E7%9C%8B%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95/code

请教，我应该如何修改。十分感谢。

**Comment by hdchieh** [comment]
> 能详细描述一下问题吗？
> 
> 1. 出现问题的视频连接
> 2. 问题相关的截图（包括控制台截图）
> 
> 我尝试了几个av和bangumi页面未能复现问题。

对不起，应该是我没有叙述清楚。原本的页面有__INITIAL_STATE__。但是重构后的旧版页面貌似这个属性就被删除，导致其他的脚本失效。如果我还想使用其他脚本，应该如何修改本tempermonkey代码呢？

**Comment by MotooriKashin** [comment]
要说明一点，新旧页面的__INITIAL_STATE__格式是不同的，新版页面的__INITIAL_STATE__的存在如果被旧版页面读取到，旧版页面原生脚本就会报错崩溃，导致旧版页面重构失败。所以本脚本要重构旧版页面，必须将__INITIAL_STATE__重构或者删除。

至于你说的兼容问题，应该说对方就没有去兼容旧版页面的__INITIAL_STATE__，就算我不删除__INITIAL_STATE__，只是重构为旧版的__INITIAL_STATE__，对方一样用不了。所以应该是对方主动去适配旧版页面，或者寻找其他不使用__INITIAL_STATE__的方法。

**Comment by hdchieh** [comment]
> 要说明一点，新旧页面的__INITIAL_STATE__格式是不同的，新版页面的__INITIAL_STATE__的存在如果被旧版页面读取到，旧版页面原生脚本就会报错崩溃，导致旧版页面重构失败。所以本脚本要重构旧版页面，必须将__INITIAL_STATE__重构或者删除。 至于你说的兼容问题，应该说对方就没有去兼容旧版页面的__INITIAL_STATE__，就算我不删除__INITIAL_STATE__，只是重构为旧版的__INITIAL_STATE__，对方一样用不了。所以应该是对方主动去适配旧版页面，或者寻找其他不使用__INITIAL_STATE__的方法。

明白了谢谢，只能改别人的代码了。
