### ISSUE TITLE
[Feature Requset]: 以后还会支持本地视频播放功能吗？

### ISSUE THREAD

**Issue by ciriue** [MotooriKashin/Bilibili-Old#426]
### 目标愿景

之前还可以把被和谐的番剧替换掉来看，现在看番已经没法在b站看了，别的播放器又不习惯。好难受。

 ╯ 　乀
ヘ　 へ
　′
　﹀
不也挺好吗.jpg

**Comment by MotooriKashin** [comment]
原先的办法太暴力了，既然已经重构了播放器脚本，就想使用更完美的办法。只是一直没时间尝试，既然你提了需求，会尽快提上日程，请多担待一段时间。

**Comment by ciriue** [comment]
给大佬递茶
![~Y %$HT`41MCUGK~37(R_B](https://user-images.githubusercontent.com/84818059/228523122-8188289b-00e3-4333-854d-e79940a3776b.jpg)

**Comment by MotooriKashin** [comment]
已支持播放本地视频，入口：设置 -> 弹幕 -> 本地视频。和本地弹幕放在一处，方便一起使用。
