### ISSUE TITLE
新版弹幕接口疑似失效(bug)

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#43]
关闭“新版弹幕”后可以正常接收弹幕
但开启后弹幕数量为0

[高级弹幕测试_哔哩哔哩 (゜-゜)つロ 干杯~-bilibili - 360极速浏览器 12.0 2021-01-16 18-04-48.zip](https://github.com/MotooriKashin/Bilibili-Old/files/5824164/_.-.-bilibili.-.360.12.0.2021-01-16.18-04-48.zip)

**Comment by MotooriKashin** [comment]
测试相同视频下新版弹幕是正常的，猜想可能是网络问题？  
控制台有没有什么报错？

**Comment by followmypeach** [comment]
![Uploading QQ截图20210116182701.png…]()

**Comment by followmypeach** [comment]
有

**Comment by MotooriKashin** [comment]
新版弹幕其实就是新版播放器载入的弹幕，这边测试关掉脚本情况下新版播放器获取的弹幕链接完全相同。   
你可以试试关闭脚本看看新版播放器能不能载入弹幕

**Comment by followmypeach** [comment]
能

**Comment by MotooriKashin** [comment]
那发控制台截图给我看看(方才好像有截图一闪而过，刷新不见了...)

**Comment by wly5556** [comment]
在安卓上的kiwi浏览器也能复现相同的问题，不过在手机上没有控制台，所以一直没办法排查原因。如果能把控制台截图发上来就太好了

**Comment by followmypeach** [comment]
![QQ截图20210116182701](https://user-images.githubusercontent.com/77530593/104809559-33bf2380-5829-11eb-9fd1-fd7c38d2be81.png)

**Comment by MotooriKashin** [comment]
> 在安卓上的kiwi浏览器也能复现相同的问题，不过在手机上没有控制台，所以一直没办法排查原因。如果能把控制台截图发上来就太好了

这脚本居然手机上也能用，我试过x浏览器完全不行？

**Comment by wly5556** [comment]
原来是replaceall的兼容性 kiwi是77内核，要85+才能使用replaceall，360浏览器也是这样

**Comment by followmypeach** [comment]
> > 在安卓上的kiwi浏览器也能复现相同的问题，不过在手机上没有控制台，所以一直没办法排查原因。如果能把控制台截图发上来就太好了
> 
> 这脚本居然手机上也能用，我试过x浏览器完全不行？

。。。啥时候回复我

**Comment by wly5556** [comment]
> > > 在安卓上的kiwi浏览器也能复现相同的问题，不过在手机上没有控制台，所以一直没办法排查原因。如果能把控制台截图发上来就太好了
> > 
> > 
> > 这脚本居然手机上也能用，我试过x浏览器完全不行？
> 
> 。。。啥时候回复我

抱歉，问题已经找到了，很快修复

**Comment by MotooriKashin** [comment]
> 。。。啥时候回复我

这位聊天的是另一位作者，弹幕方面他更懂。

**Comment by followmypeach** [comment]
> 原来是replaceall的兼容性 kiwi是77内核，要85+才能使用replaceall，360浏览器也是这样

额我去下载最新内核的看看（

**Comment by wly5556** [comment]
已经更新啦，写成replaceAll有点偷懒的成分，用原装的正则做替换了

**Comment by followmypeach** [comment]
这个问题我先搁着，到时候懒得写内啥了

**Comment by MotooriKashin** [comment]
85+的确是有点太新了，毕竟最新才87

**Comment by wly5556** [comment]
> 这个问题我先搁着，到时候懒得写内啥了

手动更新[最新版](https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5?version=891517)就可以了

**Comment by followmypeach** [comment]
> > 这个问题我先搁着，到时候懒得写内啥了
> 
> 手动更新[最新版](https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5?version=891517)就可以了

免了，升级最新浏览器版本了（

**Comment by followmypeach** [comment]
下次写代码别偷懒了（

**Comment by followmypeach** [comment]
对了还有一个问题

**Comment by wly5556** [comment]
> 下次写代码别偷懒了（

抱歉，我立正挨打

**Comment by followmypeach** [comment]
![QQ截图20210116185756](https://user-images.githubusercontent.com/77530593/104810005-ce6d3180-582c-11eb-9d86-d013860508d2.png)

**Comment by MotooriKashin** [comment]
这是哪个视频？

**Comment by followmypeach** [comment]
> > 下次写代码别偷懒了（
> 
> 抱歉，我立正挨打![](https://camo.githubusercontent.com/66865cba51876693facf88bef02e1e2f24a1e9021ceb9a3b18cab75473d98757/68747470733a2f2f7374617469632e7361726162613173742e636f6d2f696d6167652f736d696c65792f66616365323031372f3035312e706e67)



> 这是哪个视频？

av20567123?p=2，今天才发完弹幕

**Comment by followmypeach** [comment]
刷新前一切正常，刷新后就成这样了

**Comment by followmypeach** [comment]
时间：4：07

**Comment by wly5556** [comment]
请再次更新脚本
这个是因为播放器原厂代码将换行符替换成\r，导致我写的鲁棒性为零的代码不起作用了，已经修了

**Comment by MotooriKashin** [comment]
> 请再次更新脚本
> 这个是因为播放器原厂代码将换行符替换成\r，导致我写的鲁棒性为零的代码不起作用了，已经修了

第一感觉也是这个

**Comment by MotooriKashin** [comment]
![2021-01-16_190941](https://user-images.githubusercontent.com/60416767/104810299-7fc09700-582e-11eb-9c39-b849aae37062.png)

居然是个弹幕君，失敬！

**Comment by followmypeach** [comment]
不是啊，flash播放器就没有这个问题

**Comment by MotooriKashin** [comment]
> 不是啊，flash播放器就没有这个问题

flash播放器脚本无权接管，所以获取的依旧是旧版弹幕

**Comment by wly5556** [comment]
> 不是啊，flash播放器就没有这个问题

是这样的，刚才我把原版html播放器的代码直接拿来用了，没看到他们替换的是”\r“不是”\n“，于是我后续有关”\n“的代码执行不了。错在我

**Comment by followmypeach** [comment]
我寻思着我没有换行符啊

**Comment by followmypeach** [comment]
不过先别改了，我喜欢

**Comment by MotooriKashin** [comment]
你更新最新脚本应该就没问题了。  
方才那是不小心引入的错误。

**Comment by followmypeach** [comment]
> 你更新最新脚本应该就没问题了。
> 方才那是不小心引入的错误。

但这错误我喜欢

**Comment by MotooriKashin** [comment]
> 但这错误我喜欢

错误到底是错误，处理其他弹幕会出问题的。

**Comment by followmypeach** [comment]
哦哦

**Comment by followmypeach** [comment]
仍然是这样

**Comment by wly5556** [comment]
> 不过先别改了，我喜欢

![A0~ S5XAMDBD~DO0VFGUEZ3](https://user-images.githubusercontent.com/61644753/104810765-d27a5e80-57ee-11eb-9493-d1bc56572092.png)
那部分代码是为了提供这样文字和方块■重叠的弹幕效果，之前那个错误会导致无论什么字幕弹幕都会叠在一起

>仍然是这样

在[主页面](https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5)再安装试试?

**Comment by followmypeach** [comment]
嗯

**Comment by MotooriKashin** [comment]
![2021-01-16_194014](https://user-images.githubusercontent.com/60416767/104810889-bbf5f680-5832-11eb-9052-602497fc9ab4.png)
我这里测试正常

**Comment by MotooriKashin** [comment]
哇！居然有bas弹幕权限！太强了！  
![2021-01-16_194553](https://user-images.githubusercontent.com/60416767/104811012-99b0a880-5833-11eb-8815-ee29ea58e875.png)

**Comment by followmypeach** [comment]
。。。bas公测 新版播放器才有

**Comment by followmypeach** [comment]
> ![2021-01-16_194014](https://user-images.githubusercontent.com/60416767/104810889-bbf5f680-5832-11eb-9052-602497fc9ab4.png)
> 我这里测试正常

啊你是不是没有上传，还是那个鸟样..

**Comment by followmypeach** [comment]
干脆直接把js发我算了..我直接安装

**Comment by wly5556** [comment]
> 干脆直接把js发我算了..我直接安装

greasyfork上面的”重新安装“按钮试过了吗？如果还不行可以去检查代码第33行，是不是
``// @resource     xhrhook https://cdn.jsdelivr.net/gh/MotooriKashin/BilibiliOld@0f5ccdfaa4549ab2c6c4c019f364778e9f5ffc1e/src/xhrhook.js``

**Comment by wly5556** [comment]
> 85+的确是有点太新了，毕竟最新才87

replaceAll这个名字太亲切了，还以为很早就存在这个方法，没想到是去年8月新加入的![](https://camo.githubusercontent.com/66865cba51876693facf88bef02e1e2f24a1e9021ceb9a3b18cab75473d98757/68747470733a2f2f7374617469632e7361726162613173742e636f6d2f696d6167652f736d696c65792f66616365323031372f3035312e706e67)

>这脚本居然手机上也能用，我试过x浏览器完全不行？

当初专门为了测试搜索到的kiwi浏览器，脚本能用。不过手机上操作太折磨了，不能打开脚本的设置界面

**Comment by MotooriKashin** [comment]
我觉得可能是没有更新版本号的原因，他也没有去greasyfork重新安装，而是直接tampermonkey里检查更新。  
要不可以试试先卸载本脚本再重新安装？

**Comment by followmypeach** [comment]
> 我觉得可能是没有更新版本号的原因，他也没有去greasyfork重新安装，而是直接tampermonkey里检查更新。 要不可以试试先卸载本脚本再重新安装？

额卸载重装也是一个鸟样

**Comment by followmypeach** [comment]
[Uploading 视频太大放压缩包里了.zip…]()

**Comment by followmypeach** [comment]
没关梯子所以网有点卡

**Comment by followmypeach** [comment]
=）

**Comment by followmypeach** [comment]
> > 干脆直接把js发我算了..我直接安装
> 
> greasyfork上面的”重新安装“按钮试过了吗？如果还不行可以去管理面板里检查已安装的脚本的代码第33行，是不是
> `// @resource xhrhook https://cdn.jsdelivr.net/gh/MotooriKashin/BilibiliOld@0f5ccdfaa4549ab2c6c4c019f364778e9f5ffc1e/src/xhrhook.js`

没错，但是还是这样

**Comment by wly5556** [comment]
> 没错，但是还是这样

我自己安装了360极速浏览器12和13两个版本去测试，都是正常的
如果你已经更新到版本13的360极速浏览器，可以试看回退到[这个版本](https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5?version=890028)（记得手动安装[最新](https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5)版本，保证后续能收到更新）

**Comment by followmypeach** [comment]
> > 没错，但是还是这样
> 
> 我自己安装了360极速浏览器12和13两个版本去测试，都是正常的
> 如果你已经更新到版本13的360极速浏览器，可以试看回退到[这个版本](https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5?version=890028)看效果如何（结束后记得手动安装[最新](https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5)版本，保证后续能收到更新）

回退后行了，谢谢！
