### ISSUE TITLE
[Feature Requset]: 恢复旧版外链播放器(player.bilibili.com/player.html)

### ISSUE THREAD

**Issue by Minteea** [MotooriKashin/Bilibili-Old#431]
### 存在问题

B站这个月更换了新的外链播放器（player.bilibili.com/player.html），不仅砍掉了一些功能（例如不能全屏和洗脑循环），操作逻辑也变得稀烂，点击视频画面、试图更改播放倍速都会直接跳转到视频页。
以下是旧版外链播放器和新版的区别：

↓旧版外链播放器↓
![](https://user-images.githubusercontent.com/83207760/229034123-8c2a5d9b-4922-4068-9a4d-feb7119da869.png)

↓新版外链播放器↓
![](https://user-images.githubusercontent.com/83207760/229034130-02100f12-3d21-4b19-b40d-86b34e181d9f.png)

### 目标愿景

希望脚本能实现恢复旧版外链播放器 (https://player.bilibili.com/player.html) 的功能

注：**不是**嵌入式播放器 (https://www.bilibili.com/blackboard/newplayer.html)

### 参考建议

网页时光机有旧版播放器相关存档，最后一个存档如下，不过没有请求参数显示不了啥内容=。=
(https://web.archive.org/web/20220726055716/https://player.bilibili.com/player.html) 

旧版播放器核心代码似乎与这个有关：
https://player.bilibili.com/main/html5/outer/liteplayer.min.js

**Comment by Minteea** [comment]
啊，顺便说一下，打开bilibili-old之后外链播放器还会出现视频内容无法播放的问题
![bilibili-old-issue-3](https://user-images.githubusercontent.com/83207760/229040341-9fba41e5-6cda-4c26-a008-1c073394922e.png)

**Comment by MotooriKashin** [comment]
直接替换为嵌入式播放器可以吗？

**Comment by Minteea** [comment]
虽然外链播放器和嵌入式播放器外观还是有点区别的
但是先用旧版嵌入式播放器代替一下也没啥问题（

**Comment by MotooriKashin** [comment]
ok
