### ISSUE TITLE
旧播放页面异常

### ISSUE THREAD

**Issue by NoAyase** [MotooriKashin/Bilibili-Old#44]
在旧页面当中，header重复出现。 新版界面header并未废除，同时下方再次出现旧版页面hedaer

**Comment by MotooriKashin** [comment]
可能是我将`getElementsByClass`替换为`querySelector`时出现错误。我应该再仔细检查一下的😓

**Comment by MotooriKashin** [comment]
暂时可以回滚上个版本解决，这边可能要明天才能修复。
