### ISSUE TITLE
[Bug]: m.bilibili.com错误重写

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#444]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

在切换浏览器UA后，访问移动端页面，脚本依旧会重写页面

### 操作系统

Windows 10

### 浏览器名称及版本

Mozilla Firefox 112.0.2 (64 位)

**Comment by MotooriKashin** [comment]
已忽略移动端页面
