### ISSUE TITLE
[Bug]: 媒体屏蔽插件无法屏蔽视频载入

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#445]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

使用媒体屏蔽插件，无法屏蔽重写页面媒体资源载入
https://addons.mozilla.org/zh-CN/firefox/addon/image-video-block/

### 操作系统

Windows 10

### 浏览器名称及版本

Mozilla Firefox 112.0.2 (64 位)

**Comment by MotooriKashin** [comment]
兼容适配问题一般只能由对方主动适配，虽然说要对方去适配已经不存在的页面可能性不大

**Comment by MyBlueHorizon** [comment]
> 兼容适配问题一般只能由对方主动适配，虽然说要对方去适配已经不存在的页面可能性不大

之前的屏蔽视频载入选项找不到了，这个插件是通过浏览器屏蔽所有页面的媒体请求的，但不知道为什么对本脚本重写的页面不生效
