### ISSUE TITLE
[Bug]: 首页港澳台新番时间表无法跳转到最新话

### ISSUE THREAD

**Issue by KaYukiW** [MotooriKashin/Bilibili-Old#448]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

开启修复->港澳台新番时间表后，首页新番时间表的港澳台新番最新话地址为https://www.bilibili.com/bangumi/play/epundefined， 无法跳转到最新话页面

### 参考数据

![image](https://github.com/MotooriKashin/Bilibili-Old/assets/80619139/49a0f2e6-a18a-466c-889d-f9dd85954fb9)

### 操作系统

Windows 10

### 浏览器名称及版本

Chrome 113.0.5672.127

### 脚本版本

10.5.5-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by MotooriKashin** [comment]
感谢反馈，已修复
