### ISSUE TITLE
评论区av号存在bug

### ISSUE THREAD

**Issue by WolfgangWu** [MotooriKashin/Bilibili-Old#45]
在 https://www.bilibili.com/video/av79896242 里，评论区第59楼（在按热度排序的第一页第8位），点开二级评论可见两个视频地址。其一是第2个二级评论

> 冰山边的浩太回复 @敲可爱地莉莉丝 :【Fate/GO 2.5】队长你是不是玩不起？！R金时4T击破队长4管血后他居然开宝具逃跑了！

其二是第5个二级评论

> 阿木尼亚回复 @敲可爱地莉莉丝 :回复 @敲可爱地莉莉丝 :嗯......刚刚手滑删了【FGO】骑狗蛋强杀四管血条队长，队长你怎么玩不起啊

两个二级评论的视频地址，在打开了bili-old之后，均变为 https://www.bilibili.com/video/undefined 。而关闭bili-old脚本后，两个评论的视频地址均可指向正确的视频。

**Comment by MotooriKashin** [comment]
感谢反馈！  

B站今天修复了`comment.js`处理评论跳转链接时不匹配大写av号的问题，奇怪的是不是直接修改而是重新创建了个脚本并移动到了`s1.hdslb.com`服务器（原来的还留在`static.hdslb.com`）——莫非以为着评论脚本以后要经常改动？  
已更近修复。  
这次改动由于涉及了基础的页面框架，需要改动的模块太多，若是更新脚本仍未能解决，请尝试卸载本脚本重装。

**Comment by WolfgangWu** [comment]
不太了解web脚本哈哈，但是要不要考虑不跟进B站的“自动把av号转化出视频名称功能”？毕竟旧版的B站是直接把av号飘蓝、加链接的，个人也觉得新版强行给av号打出名字显得有些凌乱

**Comment by MotooriKashin** [comment]
评论区基本还是调用原生脚本生成的，所以B站有什么改动都是同步的，只是这次直接更换了脚本导致没能跟进出现bug.  
我不太想直接修改原生脚本来开关某个功能，毕竟原生脚本经过压缩混淆以后维护起来难度太大（比如忘记当时是怎么修改的）。所以要实现类似功能只能由本脚本重新改回av号，我明天试试吧。

**Comment by WolfgangWu** [comment]
感谢大佬 orz

**Comment by MotooriKashin** [comment]
已添加相关功能，请在设置里自行启用。  
另外链接前面那个视频图标我没有去掉，感觉应该不影响观感吧？

**Comment by WolfgangWu** [comment]
太感谢了
