### ISSUE TITLE
[Feature Requset]: 在网页播放器中添加“播放速度”按钮

### ISSUE THREAD

**Issue by y2-Whyto** [MotooriKashin/Bilibili-Old#450]
### 存在问题

目前脚本在设置中实现了播放速度的控制，但是好像并没有提供在播放器中显示调速按钮的选项。需要进行调速时不够方便。

### 目标愿景

希望脚本能够将该调速功能集成到网页播放器内，可以考虑将其设计为与脚本设置中一样的无级滑条，效果类似于播放器中的音量条。

**Comment by MotooriKashin** [comment]
播放器右键那几个应该够了吧

**Comment by y2-Whyto** [comment]
哦，谢谢！之前没有观察过右键菜单。不过添加到播放器下方的设计依然可以考虑，毕竟和新版的交互逻辑不太一样，猛地切换过来之后可能难以发现。在 2023年5月28日，19:22，MotooriKashin ***@***.***> 写道：﻿
播放器右键那几个应该够了吧
