### ISSUE TITLE
[Bug]: 火狐浏览器下视频全屏时闪烁

### ISSUE THREAD

**Issue by Latomoyocarl** [MotooriKashin/Bilibili-Old#451]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

用火狐看B站视频时，全屏状态下时不时触发闪烁，黑-内容-黑-内容这样，有时候半秒一下，有时候疯狂闪烁，不确定持续多久，暂时的解决方法是退出全屏然后重新进入。问过使用chrome旧版的朋友他说并没有出现这个问题。此外声音没影响。

另外，火狐上看B站视频时无论是否使用旧版，只要是观看单个视频，核显(Intel UHD)占用就会达到100%附近。此时，弹幕会出现明显的卡顿以及延迟甚至消失，调整音量的显示也是如此。我试过只有b站+firefox 有这种爆核显的问题，b+chrome、油管+chrome/firefox 都没有，除非后台疯狂开新标签页，我试过将浏览器的显卡选项优先N卡但无济于事。因为我不确定上述闪屏是否是因此导致的，所以在此一并描述出来。

### 复现步骤

火狐上通过旧版，点开视频，全屏播放，等待……。最好选择长视频，当然如果运去足够“好”能碰上全屏没过几秒就疯狂闪烁的情况

### 操作系统

Windows 11

### 浏览器名称及版本

Firefox 113.0.2 (64bit)

### 脚本版本

10.5.9-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by MotooriKashin** [comment]
右键视频统计信息看看是不是视频编码的问题

**Comment by Latomoyocarl** [comment]
> 右键视频统计信息看看是不是视频编码的问题

![无标题](https://github.com/MotooriKashin/Bilibili-Old/assets/58652186/96b30faa-0d2f-425d-8da7-e35878151e22)
播放中突然出现闪烁时点开的

**Comment by MotooriKashin** [comment]
硬解avc爆显存这种事情不该发生在现代的设备上，尤其是视频分辨率也不高，实测我这里3代i5里用该版本firefox也没有出现问题。
新版播放器默认使用av1编码，你可以试试在新版播放器里选择avc，看看是不是也有类似问题。

**Comment by MotooriKashin** [comment]
撤回上条，你说新版也有问题的话，这锅要么是Firefox有问题，要么是核显驱动有问题。

排除方法也很简单，使用其他浏览器测试，如果其他浏览器没问题，那么就是Firefox有问题，或者说Firefox对某些Intel核显适配有问题（毕竟我的3代i5实测是没问题）。反正大概是Intel核显驱动的锅——大概是内存泄漏？

要缓解的话：
1. 调整播放策略，从AVC改为AV1或者HEVC
2. 关闭浏览器设置里的硬件加速

两种方法都是改用软解，代价是CPU占用将变更，以及电量消耗……

当然如果其他浏览器没问题的话，试试改用其他浏览器吧——虽然在坚守Firefox的人肯定都有自己的执着

**Comment by MotooriKashin** [comment]
更改播放策略在弹幕列表上面齿轮里面
