### ISSUE TITLE
[Bug]: 视频界面展现不全

### ISSUE THREAD

**Issue by CloudyEagle** [MotooriKashin/Bilibili-Old#452]
### 问题是发生在那种形态的？

Chrome扩展

### 问题详情

![QQ图片20230531103916](https://github.com/MotooriKashin/Bilibili-Old/assets/58777085/1be586d0-e5c9-4ab8-9637-c3aff5a87ea0)
任意视频的右侧有部分无法展示，使用的最新版，且关闭其他的扩展与脚本；也有可能是自己哪里设置出错。
在同一台电脑上的Edge Version 114.0.1823.30 (Official build) beta (64-bit)和
Edge Version 113.0.1774.57 (Official build) (64-bit)没有这个问题，甚至开启其他的脚本与拓展。
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/58777085/54be4133-9ce0-40ef-840a-7594348e463a)

### 参考数据

![Snip_2023_05_31-10_40_57](https://github.com/MotooriKashin/Bilibili-Old/assets/58777085/659d1af3-e040-4f7a-a261-54cdd205da7f)
不知道这个报错是否有用

### 操作系统

Windows 10

### 浏览器名称及版本

Edge Version 115.0.1866.1 (Official build) dev (64-bit)

### 脚本版本

10.5.9

**Comment by MotooriKashin** [comment]
edge115有问题，114，113没问题？

请试试在任意视频上右键**两次**，点击【检查】，会直接在控制台定位到video元素，截图看看样式有没有什么问题（如下图
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/60416767/517ea4fa-7060-4b04-ae9a-e6e123f52cb0)

**Comment by CloudyEagle** [comment]
### 有问题的截图
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/58777085/46002895-0870-418d-98df-ac8dbafd5d20)


### 没问题的截图
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/58777085/85a7b3d0-31e2-427e-af31-8fbedf1e04e5)

**Comment by MotooriKashin** [comment]
额，这样隔空实在诊断不出来，等以后115成为正式版时再说吧，也许是金丝雀版本引入了什么bug吧。

**Comment by MotooriKashin** [comment]
额，这样隔空实在诊断不出来，等以后115成为正式版时再说吧，也许是金丝雀版本引入了什么bug吧。

**Comment by zerozzc** [comment]
我也是同样的，右边没了一块，edgedev115版本，主窗口和往下看评论时候的自动弹出的视频小窗右边少了一截。另外如果视频比例是21：9的话全屏也是右边少了一截。
![QQ截图20230531165625](https://github.com/MotooriKashin/Bilibili-Old/assets/42660990/0d109e2c-5ae3-4e64-9b4a-54e8a51e38c3)
![QQ截图20230531165652](https://github.com/MotooriKashin/Bilibili-Old/assets/42660990/534e4f95-96ab-4aa9-bbfd-1de7690e6758)
![QQ截图20230531165748](https://github.com/MotooriKashin/Bilibili-Old/assets/42660990/885079f7-3fcb-4b55-9ffc-bd0eb32bc904)
![QQ截图20230531165808](https://github.com/MotooriKashin/Bilibili-Old/assets/42660990/b19a4c64-6930-4559-a478-7f1a58f72142)
从上到下依次是主窗口视频，小窗口视频，开脚本后的21：9全屏和不开脚本默认的21：9的视频全屏
