### ISSUE TITLE
[Bug]: 火狐浏览器没有评论区

### ISSUE THREAD

**Issue by DarkXelNaga** [MotooriKashin/Bilibili-Old#454]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

最近半个月火狐火狐88.0.1无评论区，包括动态页面和视频页面
动态页面点击评论图标打开评论区时，本应展开评论区的位置仅增加几个像素的高度

### 参考数据

![图片](https://github.com/MotooriKashin/Bilibili-Old/assets/45918215/2ad4c8dd-887c-4bfc-9596-927886b8c70b)
未开启评论区，高度373px

![图片](https://github.com/MotooriKashin/Bilibili-Old/assets/45918215/d0d96060-47ce-4149-86fc-c446488d6253)
未开启评论区，高度375px

![图片](https://github.com/MotooriKashin/Bilibili-Old/assets/45918215/00405546-8b4c-49ae-acd6-4c2cb19ff436)
视频页面无评论区

### 操作系统

Windows 10

### 浏览器名称及版本

火狐88.0.1

### 脚本版本

最新

**Comment by DarkXelNaga** [comment]
打开控制台后点击动态页面内的评论区按钮报错：

**Comment by MotooriKashin** [comment]
是不是也被广告拦截插件误伤了？

**Comment by DarkXelNaga** [comment]
> 是不是也被广告拦截插件误伤了？

确实被误伤了
