### ISSUE TITLE
[Bug]: 旧版搜索页面呈现大面积白屏

### ISSUE THREAD

**Issue by iahwiidwa** [MotooriKashin/Bilibili-Old#456]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

旧版搜索页面呈现大面积白屏无法使用

### 复现步骤

1.于搜索框输入任意字符
2.回车

### 参考数据

![图片](https://github.com/MotooriKashin/Bilibili-Old/assets/135593295/1e9e6966-a3bc-4d53-a4f1-4b2526d713e4)

### 操作系统

Windows 11

### 浏览器名称及版本

火狐浏览器  107.0.1（64位）

### 脚本版本

10.6.1-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by MotooriKashin** [comment]
感谢反馈，已修复
