### ISSUE TITLE
[Bug]:部分番剧信息获取错误 

### ISSUE THREAD

**Issue by beiyuan-tongzhi** [MotooriKashin/Bilibili-Old#458]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

在观看番剧名侦探柯南(ss33378)时出现，故障现象为打开此番剧页面时不显示番剧信息且显示为“即将开播！敬请期待”，经排查初步认定为是请求https://bangumi.bilibili.com/view/web_api/season?season_id=33378 接口时504错误导致。我认为是该请求发出后响应时间超出2s导致504错误。（b站服务器超时设置的这么短吗？）

 找到错误后使用手机5g网络测试可以复现504错误，排除网络因素。经测试其他番剧不会出现此现象，怀疑是名侦探柯南集数过多导致返回数据过大导致（无504错误时成功返回数据高达89841行）。

经查新版页面season接口返回只需要800ms左右，或许可以采用https://api.bilibili.com/pgc/view/web/season?season_id=33378 （但这个接口只能返回5w行左右数据，不清楚是否会缺少必要的数据？）

### 复现步骤

复现方法：打开名侦探柯南番剧(ss33378)立即复现。

### 参考数据

![image](https://github.com/MotooriKashin/Bilibili-Old/assets/77305532/b4da5d8f-e707-4fac-aeee-476cb5da2e21)
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/77305532/a48c4150-a217-475f-8348-82a4e7e23e86)

### 操作系统

Windows 10

### 浏览器名称及版本

Microsoft Edge 版本 114.0.1823.37 (正式版本) (64 位)

### 脚本版本

10.6.3

**Comment by MotooriKashin** [comment]
已启用备用接口
