### ISSUE TITLE
bas弹幕异常

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#46]
https://www.bilibili.com/video/av288866972/?p=2
这个视频（不是我做的）的弹幕在新版正常，在旧版就有点异常(有一段全黑）

**Comment by wly5556** [comment]
用旧页面载入这个视频时，bas渲染器向控制台报了很多错，不知道是不是和[bas](https://github.com/Bilibili/bas)在弃用旧版页面之后进行的更新有关
``
Error in BAS parser:  Error: Parse Error:}@row:33col:0
``

**Comment by MotooriKashin** [comment]
哇，这样掰新版代码那就太痛苦了吧

**Comment by followmypeach** [comment]
那么什么时候更新啊QAQ

**Comment by wly5556** [comment]
https://github.com/MotooriKashin/Bilibili-Old/commit/c1ef90f3477379de95e323b643f98d63a81b4df2 修修补补之后，看起来是那么个回事了，不过把新版代码整进来的改动太巨大了，新版本晚点再发

**Comment by wly5556** [comment]
>哇，这样掰新版代码那就太痛苦了吧

哪里报错修哪里，不少错误只需要改一改变量名，还挺解压![](https://static.saraba1st.com/image/smiley/face2017/057.png)

**Comment by wly5556** [comment]
> 那么什么时候更新啊QAQ

https://github.com/MotooriKashin/Bilibili-Old/raw/preview/main.user.js
这里有个**测试版**，请随意使用，如果发现bas、普通弹幕出了问题或者其他的什么bug，那太好不过了![](https://static.saraba1st.com/image/smiley/face2017/057.png)，把问题发到这就行
过阵子合并到主版本之后，记得更新主版本，到时候测试版会相应失效

**Comment by followmypeach** [comment]
额打不开啊

**Comment by followmypeach** [comment]
地址无效

**Comment by followmypeach** [comment]
额挂了梯子才成功了
话说你们直接把新版弹幕的渲染方式直接照搬过来吧
这样可以少点错误吧
（控制台疯狂报错

**Comment by followmypeach** [comment]
额有时候会音画不同步

**Comment by wly5556** [comment]
> （控制台疯狂报错

可以看看截图吗?
>额有时候会音画不同步

就是说，新播放器里面更流畅?

**Comment by followmypeach** [comment]
> > （控制台疯狂报错
> 
> 可以看看截图吗?
> 
> > 额有时候会音画不同步
> 
> 就是说，新播放器里面更流畅?

嗯嗯

**Comment by followmypeach** [comment]
![QQ截图20210124100319](https://user-images.githubusercontent.com/77530593/105619237-72f20380-5e2b-11eb-88dc-cecc473c5ceb.png)

**Comment by followmypeach** [comment]
正常吗

**Comment by MotooriKashin** [comment]
太强了！四种模式同屏与p1对比，旧版播放器Canvas模式下基本没有区别，CSS3下不仔细对比也没区别。反倒是新版播放器两种模式下都有点拉跨是怎么回事？不是从新版播放器获取的代码吗？竟然做出了青出于蓝的效果！

**Comment by followmypeach** [comment]
> 太强了！四种模式同屏与p1对比，旧版播放器Canvas模式下基本没有区别，CSS3下不仔细对比也没区别。反倒是新版播放器两种模式下都有点拉跨是怎么回事？不是从新版播放器获取的代码吗？竟然做出了青出于蓝的效果！

对了我建议在新增一种功能

**Comment by followmypeach** [comment]
类似新版的“隐藏黑边”功能

**Comment by followmypeach** [comment]
额现在玩这种bas弹幕游戏，但是那些按钮无法正常点击

**Comment by followmypeach** [comment]
要回去新版才能

**Comment by followmypeach** [comment]
正常点击

**Comment by wly5556** [comment]
>额有时候会音画不同步

昨天发的版本缺失了一个同步播放进度的函数``timeSyncFunc``，已经加回来了，应该不会再有错位

>>就是说，新播放器里面更流畅?

>嗯嗯

这个原因就不好找了，按理说他们运行的都是同一套代码

>![image](https://user-images.githubusercontent.com/61644753/105620787-58526700-5df8-11eb-9085-793072cc5776.png)

看起来是bas弹幕中含有语法错误，新播放器中一样会提示，具体错因要请教这条bas弹幕的作者了

>太强了！四种模式同屏与p1对比，旧版播放器Canvas模式下基本没有区别，CSS3下不仔细对比也没区别。反倒是新版播放器两种模式下都有点拉跨是怎么回事？不是从新版播放器获取的代码吗？竟然做出了青出于蓝的效果！

bas弹幕的代码独立性相当强，只包含一个渲染管理器和对应的bas弹幕对象，播放器给参数初始化之后，渲染管理器能就独立工作，所以替换这两部分代码就能用了（本来做好了准备要面对高耦合！）
而且前端给各种null的情况都做了准备，所以上个版本其实缺失了``timeSyncFunc`` ``blockJudge`` ``pauseFunc`` ``seekFunc``，却也没报错

至于渲染效果，能这么好，太开心了![](https://static.saraba1st.com/image/smiley/face2017/066.png)

>额现在玩这种bas弹幕游戏，但是那些按钮无法正常点击

->[新版本](https://github.com/MotooriKashin/Bilibili-Old/raw/preview/main.user.js) 修了

（如果是那个【弹幕游戏】互动钢琴，按钮与背景会有轻微错位。这问题无解，根源在新、旧播放器的视频区默认的大小比例不同）
又比如“第四回蓝白弹幕合作祭”06:39，bas弹幕创作者把“の”放大10倍，让字符超出窗口大小，触发机制让字符消失。在旧播放器中就会由于播放器大小比例不同，字符没有消失，就影响到后面的显示效果 （初步感受下来，bas的限制太多了，特别是元素的定位，貌似不少创作者是按照新播放器默认大小(760x516)制作的bas弹幕，全屏观看就乱套了）

**Comment by followmypeach** [comment]
> > 额有时候会音画不同步
> 
> 昨天发的版本缺失了一个同步播放进度的函数`timeSyncFunc`，已经加回来了，应该不会再有错位
> 
> > > 就是说，新播放器里面更流畅?
> 
> > 嗯嗯
> 
> 这个原因就不好找了，按理说他们运行的都是同一套代码
> 
> > ![image](https://user-images.githubusercontent.com/61644753/105620787-58526700-5df8-11eb-9085-793072cc5776.png)
> 
> 看起来是bas弹幕中含有语法错误，新播放器中一样会提示，具体错因要请教这条bas弹幕的作者了
> 
> > 太强了！四种模式同屏与p1对比，旧版播放器Canvas模式下基本没有区别，CSS3下不仔细对比也没区别。反倒是新版播放器两种模式下都有点拉跨是怎么回事？不是从新版播放器获取的代码吗？竟然做出了青出于蓝的效果！
> 
> bas弹幕的代码独立性相当强，只包含一个渲染管理器和对应的bas弹幕对象，播放器给参数初始化之后，渲染管理器能就独立工作，所以替换这两部分代码就能用了（本来做好了准备要面对高耦合！）
> 而且前端给各种null的情况都做了准备，所以上个版本其实缺失了`timeSyncFunc` `blockJudge` `pauseFunc` `seekFunc`，却也没报错
> 
> 至于渲染效果，能这么好，太开心了![](https://camo.githubusercontent.com/f94bf7721bb6a4e251074e98a120bcbdb8ca311f8cf28bfb332579105144ebf2/68747470733a2f2f7374617469632e7361726162613173742e636f6d2f696d6167652f736d696c65792f66616365323031372f3036362e706e67)
> 
> > 额现在玩这种bas弹幕游戏，但是那些按钮无法正常点击
> 
> ->[新版本](https://github.com/MotooriKashin/Bilibili-Old/raw/preview/main.user.js) 修了
> 
> （如果是那个【弹幕游戏】互动钢琴，按钮与背景会有轻微错位。这问题无解，根源在新、旧播放器的视频区默认的大小比例不同）
> 又比如“第四回蓝白弹幕合作祭”06:39，bas弹幕创作者把“の”放大10倍，让字符超出窗口大小，触发机制让字符消失。在旧播放器中就会由于播放器大小比例不同，字符没有消失，就影响到后面的显示效果 （初步感受下来，bas的限制太多了，特别是元素的定位，貌似不少创作者是按照新播放器默认大小(760x516)制作的bas弹幕，全屏观看就乱套了）

不，新版bas弹幕是会按比例缩放的，就是全屏也不会错位

**Comment by followmypeach** [comment]
为什么我知道，因为我试过

**Comment by followmypeach** [comment]
> > 额有时候会音画不同步
> 
> 昨天发的版本缺失了一个同步播放进度的函数`timeSyncFunc`，已经加回来了，应该不会再有错位
> 
> > > 就是说，新播放器里面更流畅?
> 
> > 嗯嗯
> 
> 这个原因就不好找了，按理说他们运行的都是同一套代码
> 
> > ![image](https://user-images.githubusercontent.com/61644753/105620787-58526700-5df8-11eb-9085-793072cc5776.png)
> 
> 看起来是bas弹幕中含有语法错误，新播放器中一样会提示，具体错因要请教这条bas弹幕的作者了
> 
> > 太强了！四种模式同屏与p1对比，旧版播放器Canvas模式下基本没有区别，CSS3下不仔细对比也没区别。反倒是新版播放器两种模式下都有点拉跨是怎么回事？不是从新版播放器获取的代码吗？竟然做出了青出于蓝的效果！
> 
> bas弹幕的代码独立性相当强，只包含一个渲染管理器和对应的bas弹幕对象，播放器给参数初始化之后，渲染管理器能就独立工作，所以替换这两部分代码就能用了（本来做好了准备要面对高耦合！）
> 而且前端给各种null的情况都做了准备，所以上个版本其实缺失了`timeSyncFunc` `blockJudge` `pauseFunc` `seekFunc`，却也没报错
> 
> 至于渲染效果，能这么好，太开心了![](https://camo.githubusercontent.com/f94bf7721bb6a4e251074e98a120bcbdb8ca311f8cf28bfb332579105144ebf2/68747470733a2f2f7374617469632e7361726162613173742e636f6d2f696d6167652f736d696c65792f66616365323031372f3036362e706e67)
> 
> > 额现在玩这种bas弹幕游戏，但是那些按钮无法正常点击
> 
> ->[新版本](https://github.com/MotooriKashin/Bilibili-Old/raw/preview/main.user.js) 修了
> 
> （如果是那个【弹幕游戏】互动钢琴，按钮与背景会有轻微错位。这问题无解，根源在新、旧播放器的视频区默认的大小比例不同）
> 又比如“第四回蓝白弹幕合作祭”06:39，bas弹幕创作者把“の”放大10倍，让字符超出窗口大小，触发机制让字符消失。在旧播放器中就会由于播放器大小比例不同，字符没有消失，就影响到后面的显示效果 （初步感受下来，bas的限制太多了，特别是元素的定位，貌似不少创作者是按照新播放器默认大小(760x516)制作的bas弹幕，全屏观看就乱套了）

本当に？

**Comment by followmypeach** [comment]
> > （如果是那个【弹幕游戏】互动钢琴，按钮与背景会有轻微错位。这问题无解，根源在新、旧播放器的视频区默认的大小比例不同）
> > 又比如“第四回蓝白弹幕合作祭”06:39，bas弹幕创作者把“の”放大10倍，让字符超出窗口大小，触发机制让字符消失。在旧播放器中就会由于播放器大小比例不同，字符没有消失，就影响到后面的显示效果 （初步感受下来，bas的限制太多了，特别是元素的定位，貌似不少创作者是按照新播放器默认大小(760x516)制作的bas弹幕，全屏观看就乱套了）
> 
> 本当に？

我就是全屏观看也不会有弹幕错位的现象

**Comment by followmypeach** [comment]
![image](https://user-images.githubusercontent.com/77530593/105622471-0556cf00-5e4d-11eb-892e-c801660d2aa6.png)

**Comment by wly5556** [comment]
>我就是全屏观看也不会有弹幕错位的现象

![](https://static.saraba1st.com/image/smiley/face2017/067.png) 感谢纠正
这么说吧，“乱套”说的是中途全屏的情况，从头到尾用全屏看是正常的。锅算在前端头上，跟创作者无关

**Comment by followmypeach** [comment]
> > 我就是全屏观看也不会有弹幕错位的现象
> 
> ![](https://camo.githubusercontent.com/abcfa09a053ff606924fd4ef489134f0c4a118ec8778431d2f25cb93304182a6/68747470733a2f2f7374617469632e7361726162613173742e636f6d2f696d6167652f736d696c65792f66616365323031372f3036372e706e67) 感谢纠正
> 这么说吧，“乱套”说的是中途全屏的情况，从头到尾用全屏看是正常的。锅算在前端头上，跟创作者无关

嗯呐，啥时候修复。。

**Comment by followmypeach** [comment]
。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by followmypeach** [comment]
1天没回复是不是当鸽子去了

**Comment by MotooriKashin** [comment]
BAS弹幕还是尽量不要全屏/窗口随时切换吧，相关问题可能新版播放器自己都没能解决好。

**Comment by followmypeach** [comment]
嗯嗯

**Comment by followmypeach** [comment]
可以出正式版了把..

**Comment by followmypeach** [comment]
好了，，，
现在获取不了bas弹幕了
难道只有我这一种情况吗

**Comment by wly5556** [comment]
可以发一下控制台截图吗？
(身边只有手机，在kiwi浏览器里同样获取不到bas弹幕，是普遍问题了)

**Comment by MotooriKashin** [comment]
BAS专包有请求，没有任何报错，但就是没有解析出BAS弹幕

**Comment by MotooriKashin** [comment]
![2021-02-13_082844](https://user-images.githubusercontent.com/60416767/107835777-a0e8b900-6dd5-11eb-93fe-11f21c56cf80.png)
二进制内容不像普通弹幕那样完全乱码，难道是修改了protobuf定义？

**Comment by MotooriKashin** [comment]
好吧，我知道问题出在哪里了...
![2021-02-13_084330](https://user-images.githubusercontent.com/60416767/107836379-e6a68100-6dd7-11eb-9d86-10ed3211c03d.png)
BAS弹幕包索引不是整数，应该是上回修改+1时引入的错误。不是整数以为着BAS弹幕包被存进了对象而不是数组（一切皆对象），导致后面数组方法调用时读取不到。  
我觉得有点奇怪为什么当时填充数组时用这种别扭的索引方法而不是直接`push()`？好像当时是为了弹幕包排序？  
想来也是一个历史遗留问题，毕竟后面已经添加了“按id升序”，请求弹幕包的顺序好像不重要了。

**Comment by wly5556** [comment]
![](https://static.saraba1st.com/image/smiley/face2017/112.png) 是了，之前避免请求100个分段的时候，分段总数`total`用除法重新算了，这里没有相应改
填充数组的办法能改成push，确实是历史遗留了

**Comment by followmypeach** [comment]
> 好吧，我知道问题出在哪里了...
> ![2021-02-13_084330](https://user-images.githubusercontent.com/60416767/107836379-e6a68100-6dd7-11eb-9d86-10ed3211c03d.png)
> BAS弹幕包索引不是整数，应该是上回修改+1时引入的错误。不是整数以为着BAS弹幕包被存进了对象而不是数组（一切皆对象），导致后面数组方法调用时读取不到。
> 我觉得有点奇怪为什么当时填充数组时用这种别扭的索引方法而不是直接`push()`？好像当时是为了弹幕包排序？
> 想来也是一个历史遗留问题，毕竟后面已经添加了“按id升序”，请求弹幕包的顺序好像不重要了。

按id升序是什么意思，是用户的id吗

**Comment by MotooriKashin** [comment]
就是弹幕发送时间顺序，也是正常的弹幕排序，BAS/代码弹幕排版依赖这个顺序

**Comment by followmypeach** [comment]
哦哦
