### ISSUE TITLE
[Bug]: 右侧播单/弹幕列表会遮挡播放器画面

### ISSUE THREAD

**Issue by xueweidiqiu** [MotooriKashin/Bilibili-Old#462]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

右侧列表会遮挡播放器画面。

不太懂前端，搜了一下发现可能是flex父元素不约束子元素宽度的原因，找到一个 [解决方法](https://www.cnblogs.com/ygyy/p/13328310.html) 但是感觉不太优雅。

直接在devtools里改了一下发现正常了，可以确定确实是这个问题。

### 参考数据
原始状态：
![启用脚本时](https://github.com/MotooriKashin/Bilibili-Old/assets/34111694/7fb50fb2-0aa0-4909-b609-0da3bf1dc9de)
给```<video>```的父元素添加width: 0;之后：
![给<video>的父元素添加width: 0;之后](https://github.com/MotooriKashin/Bilibili-Old/assets/34111694/3210d0b0-ba11-483c-af3d-4a09ea8db1e2)
b站默认效果：
![不启用脚本时b站默认效果](https://github.com/MotooriKashin/Bilibili-Old/assets/34111694/5b3fbbbb-40a7-4764-8319-8572366879aa)

### 操作系统

Windows 10

### 浏览器名称及版本

Google Chrome 版本 116.0.5837.0（正式版本）canary （64 位）

### 脚本版本

10.6.3-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by MotooriKashin** [comment]
一直道chrome117正式版都未能复现，暂时关闭
