### ISSUE TITLE
[Feature Requset]: 恢复新版？页面

### ISSUE THREAD

**Issue by InoriKugimiya** [MotooriKashin/Bilibili-Old#469]
### 目标愿景

希望大佬能够把最老版本和最新版本之间隔的，也就是可以用回到旧版按钮回去的那个主页给作为一个可选功能加进脚本中。如果能够实现的话非常感谢。

### 参考建议

今日是2023年7月4日下午
感觉有一部分人是喜欢最老版本和最新版本之间的那个网页端主页（比如我）

最老版的主页对于现在动不动2k或者4k的分辨率有点太小了
最新版的又太大了

**Comment by MotooriKashin** [comment]
脚本就是因为不喜欢那个页面才会诞生——当然最新版这个也不喜欢。  
所以很抱歉并没有动力取实现该需求。

——很久维护本项目了，过了这么久才回复十分抱歉
