### ISSUE TITLE
为啥番剧默认防挡字幕开启啊，麻烦赶紧修复

### ISSUE THREAD

**Issue by jeff6471** [MotooriKashin/Bilibili-Old#47]
为啥番剧默认防挡字幕开启啊，麻烦赶紧修复

**Comment by MotooriKashin** [comment]
这不是bug，对于番剧，服务器返回的数据就是默认防挡字幕。我没注意过新版播放器是不是这样，因为从来不用。  
不过我也挺烦这个的，可以考虑拦截一下。

**Comment by jeff6471** [comment]
新版的flash是，h5就没有

**Comment by jeff6471** [comment]
旧版的就一定是，好烦

**Comment by jeff6471** [comment]
> 我没注意过新版播放器是不是这样，因为从来不用。不过我也挺烦这个的，可以考虑拦截一下。

油猴那边更新了吗？

**Comment by MotooriKashin** [comment]
更新了，但我忘了加版本号，检查更新无效，所以可能需要手动安装。
