### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by L00124** [MotooriKashin/Bilibili-Old#470]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

没有高清画质了

### 操作系统

Windows 10

### 浏览器名称及版本

edge

**Comment by L00124** [comment]
是用了地区限制没有高清画质了

**Comment by MotooriKashin** [comment]
请自定义服务器。
内置服务器只能获取flv格式，然而去年11后B站已经不提供flv封装了，返回的是360P的mp4。想要高清只能自定义服务器。
