### ISSUE TITLE
[Bug]: 最新版本10.6.4-1272ee50230293555dec1d2e23fc5c74215b4c86在2023.7.7又失效了

### ISSUE THREAD

**Issue by reserveword** [MotooriKashin/Bilibili-Old#471]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

打开b站动态首页，发现变成了新版页面

### 操作系统

Windows 10

### 浏览器名称及版本

Firefox 114.0.2 (64 位)

### 脚本版本

10.6.4-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by MotooriKashin** [comment]
脚本并未适配过动态首页，设置里也没有相应选项
