### ISSUE TITLE
[Bug]: 评论区翻页功能失效

### ISSUE THREAD

**Issue by YongChingShieh** [MotooriKashin/Bilibili-Old#472]
### 问题是发生在那种形态的？

Chrome扩展

### 问题详情

若评论有1页以上 那么翻页到第二页时  第二页的内容就是第一页内容

### 参考数据

![Annotation 2023-07-15 191421](https://github.com/MotooriKashin/Bilibili-Old/assets/24885976/9a7a57db-2b3f-46b8-b3a9-3e89905424f8)
![Annotation 2023-07-15 1914210](https://github.com/MotooriKashin/Bilibili-Old/assets/24885976/6f7fc9e1-5c2b-4956-9c34-ad29abe59881)

### 操作系统

Windows 10

### 浏览器名称及版本

Google Chrome 114.0.5735.199 (Official Build) (64-bit)

### 脚本版本

10.6.4-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by MotooriKashin** [comment]
应该是没登录，B站现在不登录看不了更多评论，强制的，没有办法
