### ISSUE TITLE
[Bug]: 无法显示评论区

### ISSUE THREAD

**Issue by HertCZ** [MotooriKashin/Bilibili-Old#473]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

开启脚本后，评论区会显示为如下，无法查看评论。点击“查看删除日志”则会显示页面404。

### 参考数据

![image](https://github.com/MotooriKashin/Bilibili-Old/assets/69506776/b24bac20-eb5b-4215-85e9-9483d93b6a73)

### 操作系统

Windows 10

### 浏览器名称及版本

Firefox

### 脚本版本

10.6.4-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by MotooriKashin** [comment]
偶发可能是网络问题，经常出现请提供控制台报错截图

**Comment by Taebost** [comment]
> 偶发可能是网络问题，经常出现请提供控制台报错截图

并非偶发，本人也是，在火狐上本脚本经常出现该问题。
![图片](https://github.com/MotooriKashin/Bilibili-Old/assets/64080472/797f4067-0c8a-4fa5-bc65-7cd941e5ad0e)

**Comment by MotooriKashin** [comment]
抱歉，并没有在火狐上复现该问题，而且报错中也没有任何有效信息。
