### ISSUE TITLE
[Bug]: 扩展打不开设置

### ISSUE THREAD

**Issue by KMINGJAY** [MotooriKashin/Bilibili-Old#476]
### 问题是发生在那种形态的？

Chrome扩展

### 问题详情

扩展打不开设置，点击扩展图标什么也没有发生

### 操作系统

Windows 7

### 浏览器名称及版本

Edge109

### 脚本版本

最新版本

**Comment by MotooriKashin** [comment]
你说的是不是这个设置？
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/60416767/ffc36c75-62c2-4569-b70d-89a929193d1c)
不妨试试页面右下角这个
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/60416767/586170ce-d455-4b94-a7c1-a79e66ed745c)
