### ISSUE TITLE
[Bug]: 在关闭稍后再看页面的重写时会导致点击任意视频跳转也只从第一个播放

### ISSUE THREAD

**Issue by imtipi** [MotooriKashin/Bilibili-Old#478]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

关闭稍后再看页面的重写时，正常情况应该是稍后再看列表点击哪个视频就会播放哪个视频，但是实际上会变成只会跳转到列表的第一个视频，而且在稍后再看播放页面点击删除视频如果删除超过一个会有删除其他视频的情况

### 复现步骤

关闭重写中的稍后再看（也就是不恢复）

### 操作系统

Windows 11

### 浏览器名称及版本

chrome 115.0.5790.110

### 脚本版本

10.6.4-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by MotooriKashin** [comment]
脚本默认启用了BV转av，旧版关闭了旧版页面也一样。但问题出在B站自己身上，如下图
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/60416767/2fc673eb-322a-4349-9399-8910f6ecd453)

没有这样的BV号，所以默认从第一个开始播放。  
BV转av是脚本运行的基础，因为旧版时代不存在BV号，这是一定不能关闭的。  
本脚本是为旧版页面服务的，如果误伤了新版页面，也只能多担待了，虽然只是多点一下的事情。
