### ISSUE TITLE
[Bug]: 无法后退到上一个视频

### ISSUE THREAD

**Issue by COSMIC-TAMAGO** [MotooriKashin/Bilibili-Old#479]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

无法后退到上一个视频

### 复现步骤

1播放完视频后点击右侧关联的视频
2在同一个标签页转到新视频
3此时后退栏是空的，无法后退到上一个视频

### 参考数据

重写选项中
   恢复旧版av页
   恢复旧版bangumi页
   恢复旧版稍后再看
这三项未开启，其他均开启

### 操作系统

Windows 11

### 浏览器名称及版本

Chrome   115.0.5790.110（正式版本） （64 位）

### 脚本版本

10.6.4-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by MotooriKashin** [comment]
已修复
