### ISSUE TITLE
4k视频卡顿

### ISSUE THREAD

**Issue by jeff6471** [MotooriKashin/Bilibili-Old#48]
在观4k的时候会有像是网络跟不上的问题，但关闭插件就没问题，预览的条就是卡着不动或要加载很久

**Comment by MotooriKashin** [comment]
那可能是新版播放器有专门的优化？  
我这边硬件综合条件跟不上，4K对我而言那就不是一点点卡了！——所以我可能暂时无法优化了……  

@wly5556 有没有什么看法？

**Comment by wly5556** [comment]
可以提供几个视频链接吗？我只有1080p屏，不过解码4k应该还吃得消，我会试着找找原因

**Comment by MotooriKashin** [comment]
av969628065 如何？这个甚至是HDR的

**Comment by wly5556** [comment]
> av969628065 如何？这个甚至是HDR的

我的设备也挺老了，120fps丢了快一半的帧，60fps还勉强
其实看描述像是dash加载出了问题，所以想知道这个问题会不会只在特定的视频出现

**Comment by jeff6471** [comment]
有些时候会，刷新后可能没了，可能还有，但关插件一定行。进度条不加载，就是缓存不了问题，会不会跟缓存的地方有关系
