### ISSUE TITLE
[Bug]: 视频播放数和弹幕数不显示

### ISSUE THREAD

**Issue by sddddd213** [MotooriKashin/Bilibili-Old#483]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

![image](https://github.com/MotooriKashin/Bilibili-Old/assets/38841494/bae30f88-5d55-4b1a-b24e-d431de397dea)

### 参考数据

![image](https://github.com/MotooriKashin/Bilibili-Old/assets/38841494/70245891-2d6a-4d1f-8a4d-4e2aa05871c6)

### 操作系统

Windows 11

### 浏览器名称及版本

Microsoft Edge 版本 115.0.1901.203 

### 脚本版本

10.6.5-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by sddddd213** [comment]
且同时还有其他分区的首页无法回到旧版页面的问题。
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/38841494/e5c0b5e7-5b24-4442-80a5-b8707abe9cc6)
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/38841494/f4c1ea94-4c5c-4898-984b-f68755747471)
包括但不限于以上也分区，目前经过观察发现，貌似所有访问地址为  /v/xxxx 分区都无法回到旧版页面。

**Comment by sddddd213** [comment]
同时，想问一下那个可以通过特定api访问楼层数的插件或者脚本叫什么？可以给个名字吗？我去搜搜看。

**Comment by sddddd213** [comment]
目前进入视频播放页不显示播放数和弹幕数的情况再次出现，简单分析，之前的已解决可能是播放了视频较长时间导致的。因为后续在其他的刚点开的视频里，该问题依旧存在。
其中关于这些数据在代码上的展示。 ![image](https://github.com/MotooriKashin/Bilibili-Old/assets/38841494/ae07fcdc-3669-48d1-874d-a1e4f3282845)

**Comment by MotooriKashin** [comment]
感谢反馈，已修复
