### ISSUE TITLE
[Bug]: 视频页面相似数据无法显示

### ISSUE THREAD

**Issue by Larliers** [MotooriKashin/Bilibili-Old#487]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

旧版页面下点赞、硬币、收藏、播放、弹幕量无法显示

### 复现步骤

直接用插件打开

### 操作系统

Windows 10

### 浏览器名称及版本

谷歌新版

**Comment by MotooriKashin** [comment]
可能时是登录？

**Comment by MotooriKashin** [comment]
感谢反馈，已修复
