### ISSUE TITLE
[Bug]: 无法退出登录

### ISSUE THREAD

**Issue by h5mcbox** [MotooriKashin/Bilibili-Old#488]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

无法退出登录

### 复现步骤

1、点击顶栏上的个人资料卡的退出按钮
2、页面跳转到https://passport.bilibili.com/login?act=exit
3、然后就404了

### 参考数据

可按照[这份文档](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/login/exit.md)实现一下退出登录？

### 操作系统

Windows 11

### 浏览器名称及版本

Chrome 114

### 脚本版本

10.6.7-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by MotooriKashin** [comment]
已手动实现退出登录功能
