### ISSUE TITLE
[Bug]: 翻页评论区，会有多余的空白页

### ISSUE THREAD

**Issue by u2shana** [MotooriKashin/Bilibili-Old#489]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

![image](https://github.com/MotooriKashin/Bilibili-Old/assets/14146754/97dba91e-84e3-4bb0-85d3-5f936c7fb27a)
后面的页都是空白内容了，这个问题其实很久了

### 操作系统

Windows 11

### 浏览器名称及版本

chrome116

**Comment by MotooriKashin** [comment]
的确很久了，而且以前也有人提过。  
因为评论接口已不返回正确的页数，脚本也不可能遍历所有评论取计算页数。  
此问题将永远无法解决，除非B站重新提供正确的页数，或者总评论数（不包含楼中楼）。
