### ISSUE TITLE
Firefox 无法另存为视频

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#49]
如题
右键从链接另存为除MP4，FLV的文件得到了大小150B的m4s文件

**Comment by MotooriKashin** [comment]
Firefox还是兼容问题不断哈，记得上一个Firefox问题也是你提的。  
150B是什么内容，我记得网页端DASH的SegmentBase都不只这么点。  
等我安装火狐试试看。  

ps：建议安装IDM，习惯了以后用浏览器自带下载简直浑身难受→_→

**Comment by MotooriKashin** [comment]
打开那个150B文件确认为403重定向网页，可能与https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5/discussions/72590 是同一个问题，也就是部分CDN有故障（如果IDM对同一个链接也无法下载的话那就是）  

吐槽一下别的浏览器403错误是直接报下载出错，Firefox直接把错误重定向页面下载下来是搞哪样？！
