### ISSUE TITLE
[Bug]: 播放页面有两个播放器，网页全屏无法播放，全屏可以

### ISSUE THREAD

**Issue by zhouxianren** [MotooriKashin/Bilibili-Old#490]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

播放页面有两个播放器，网页全屏无法播放，全屏可以。
还有感觉播放器有点小，和上面的标题没有对齐。

### 参考数据

![QQ截图20230828105748](https://github.com/MotooriKashin/Bilibili-Old/assets/47177890/878a2297-caad-4a04-a021-dab45765ec09)
![QQ截图20230828105804](https://github.com/MotooriKashin/Bilibili-Old/assets/47177890/bb42cf99-7e2e-459d-b350-f0d1dbbd4e21)

### 操作系统

Windows 11

### 浏览器名称及版本

Microsoft Edge 版本 116.0.1938.62 (正式版本) (64 位)

**Comment by MotooriKashin** [comment]
这种问题一般是由于重写后的旧版页面被原新版页面残留脚本破坏所致，因为新版脚本一旦执行，也会访问的重写后的页面，且没有任何办法能够阻止它们。  
只能尝试刷新，无法彻底根除。

**Comment by zhouxianren** [comment]
好吧，谢谢了
