### ISSUE TITLE
[Bug]: 点赞缺失

### ISSUE THREAD

**Issue by Larliers** [MotooriKashin/Bilibili-Old#493]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

旧版页面缺失了点赞

### 复现步骤

直接开着脚本点开视频即可

### 操作系统

Windows 10

### 浏览器名称及版本

谷歌新版

**Comment by MotooriKashin** [comment]
请确认是否开启了 设置 -> 样式 -> 添加点赞功能
