### ISSUE TITLE
[Bug]:  哔哩哔哩番剧出差 打开报400

### ISSUE THREAD

**Issue by sddddd213** [MotooriKashin/Bilibili-Old#494]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

正常打开哔哩哔哩番剧出差 会报400错误，开全局之后可以正常打开。

### 复现步骤

无

### 参考数据

![image](https://github.com/MotooriKashin/Bilibili-Old/assets/38841494/894344fe-6641-486d-8472-6cfe4658bdf5)
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/38841494/fc6d6f6f-fb0f-4cb7-908e-321968118038)
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/38841494/fd7af181-fa57-4802-b49f-3a243395d65d)
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/38841494/1595cbf5-3cd8-495d-b9b7-b59529f69a57)

### 操作系统

Windows 11

### 浏览器名称及版本

Microsoft Edge 版本 116.0.1938.62 (正式版本) (64 位)

### 脚本版本

10.6.8-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by MotooriKashin** [comment]
感谢反馈，已修复！

---
ps: 该请求从`XMLHttpRequest`转向了`fetch`，花了一点时间实现了一下对`fetch`的`hook`。如果B站打算大面积换用`fetch`，其他一些功能应该也要重新实现了——值得庆幸的是旧版页面永远不会有这个问题。
