### ISSUE TITLE
[Bug]: 火狐更新到117版本加载出错

### ISSUE THREAD

**Issue by YuririQwQ** [MotooriKashin/Bilibili-Old#496]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

![QQ截图20230903151933](https://github.com/MotooriKashin/Bilibili-Old/assets/43914246/48e7e5a3-6ab3-449e-bbe6-d33284b17d1a)
火狐更新到117版本后打开视频页就会变成这样，什么都加载不出来

### 参考数据

![图片](https://github.com/MotooriKashin/Bilibili-Old/assets/43914246/d32f1358-13f0-40b1-87a9-f93ec48a12c5)
![图片](https://github.com/MotooriKashin/Bilibili-Old/assets/43914246/2a4004d7-e5a2-4b12-abaf-8ccc35b96f7f)

### 操作系统

Windows 11

### 浏览器名称及版本

火狐 117版本

### 脚本版本

10.6.9-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by MotooriKashin** [comment]
未能复现，请检查一下是不是与其他脚本或扩展冲突了
