### ISSUE TITLE
[Bug]: dark reader拓展兼容问题

### ISSUE THREAD

**Issue by ExusiaK** [MotooriKashin/Bilibili-Old#497]
### 问题是发生在那种形态的？

Chrome扩展

### 问题详情

使用dark rader显示硬币数量和收藏数目的时候覆盖区域深浅不一？ 并且专栏在使用dark reader这个拓展的时候暗色覆盖错误？

### 复现步骤

1.视频页面
2.专栏页面

### 操作系统

Windows 11

### 浏览器名称及版本

版本 116.0.5845.141（正式版本） （64 位）

**Comment by MotooriKashin** [comment]
dark reader这种都是对方手动适配的，当然要对方主动适配已不存在的页面可能也是强人所难，但也没办法。
