### ISSUE TITLE
[Bug]: 投币数缺失

### ISSUE THREAD

**Issue by sddddd213** [MotooriKashin/Bilibili-Old#498]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

投币之后，会依旧显示当然投币数为0。

### 复现步骤

首先点开一个视频，进行投币，投两个硬币后会显示当前稿件的投币已达上限。
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/38841494/1ad7b903-0a40-4adb-ab2c-dae836934a89)

然后又打开一个视频，点击投币时会发现“投币+经验”处本该显示为20/50的，但是显示为0/50。
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/38841494/30dc4c7c-5479-4c16-a5b0-44d89f3477a8)

### 参考数据

![image](https://github.com/MotooriKashin/Bilibili-Old/assets/38841494/bf624ba4-e1a4-443c-9cf5-fdeae062f40f)

### 操作系统

Windows 10

### 浏览器名称及版本

Microsoft Edge 版本 116.0.1938.76 (正式版本) (64 位)

### 脚本版本

10.6.9-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by sddddd213** [comment]
目前已对bug做进一步补充说明。

**Comment by MotooriKashin** [comment]
感谢反馈，已修复
