### ISSUE TITLE
[Bug]: 推荐视频为空

### ISSUE THREAD

**Issue by l4326769** [MotooriKashin/Bilibili-Old#499]
### 问题是发生在那种形态的？

Chrome扩展

### 问题详情

播放页面右侧推荐视频为空

### 操作系统

Windows 10

### 浏览器名称及版本

Chrome

**Comment by wcz123694578** [comment]
我也是

**Comment by MotooriKashin** [comment]
最近404的接口有点多了，有空看看怎么替代吧
