### ISSUE TITLE
收藏夹的播放全部中，界面还是新版的

### ISSUE THREAD

**Issue by Yan-Zero** [MotooriKashin/Bilibili-Old#5]
![图片](https://user-images.githubusercontent.com/32036413/78010703-45f0d380-7375-11ea-879a-73f02e4de64d.png)

如图

**Comment by MotooriKashin** [comment]
感谢反馈，这个页面没用过，还真没适配

**Comment by MotooriKashin** [comment]
@Yan-Zero 研究旧版播放器源代码后发现这个页面旧版播放器原生并不支持，也就是说这是收藏改版后专为新版播放器定制的页面，并无旧版可以参考，这也解释了为什么Wayback Machine没有相关的旧版页面备份。
目前的实现是直接跳转对应的av页面，并使用旧版播放器的稍后再看列表功能恢复了收藏列表，这样就可以实现选择播放，并附带稍后再看列表固有的“随机播放”按钮等功能
这个功能默认不启用，需自行在设置里开启，因为还未完全实现，切换视频后播放器之外的其他信息，如视频标题、简介，评论等不会随之更新，需要后续优化，目前只做到了地址栏的av号会更新
