### ISSUE TITLE
报个神奇的bug

### ISSUE THREAD

**Issue by WolfgangWu** [MotooriKashin/Bilibili-Old#50]
我的浏览器是Chrome 86.0.4240.198（正式版本） (x86_64)，系统是Mac OS 10.15.7

在上这个页面 https://www.bilibili.com/video/av202706041 的时候，我的键盘快捷键一直会咬不上播放器，就按空格键是施加到浏览器页面的效果（比如说在浏览文字页面的时候，按空格就是往下翻一页，按shift+空格是往上翻一页）而不会暂停视频，按上下方向键也是会把页面往上下方向微移而不是调整音量的大小。即使我使用鼠标单击视频画面将视频暂停，键盘也仍然不会识别播放器，键盘控制的始终是大的浏览器页面，单击空格仍然会向下翻页而不是暂停视频。

这个bug目前好像只存在在这个界面，刷新无法解决，重启浏览器无法解决。关闭脚本后，使用新版视频播放器不会出现这个问题；开启脚本，打开别的视频页也暂时没有这个问题。

为了确认我还专门拿了另外一台 Chrome 86.0.4240.198 + Mac OS 10.15.7 的电脑尝试，情况是一模一样的，不是电脑本地的问题。此外，Safari 13.1.3 (15609.4.1) + Mac OS 10.15.7 也会出现这个情况。不知道别的系统环境和浏览器能不能复现这个bug。

**Comment by MotooriKashin** [comment]
还真是...唯一能找到的不同点就是这个视频是flv格式的，但测试另一个flv视频却没有问题

**Comment by wly5556** [comment]
发现播放器实际上先载入了dash，下一瞬间黑屏弹回flv，很反常
一顿顺藤摸瓜找到了关键部分，替换其中一行代码为新版的，之后就恢复正常了。

（下面都是用av202706041举例）
![TQBBWKTSKNGGG}_P(11GE7P](https://user-images.githubusercontent.com/61644753/106235054-d2685e80-61f1-11eb-9744-1769980802d6.png)
↑↑↑新版播放器载入时的调试输出
↓↓↓旧版
![%IM9EQIXRL1D~$EIJ$HH)R9](https://user-images.githubusercontent.com/61644753/106235059-d3998b80-61f1-11eb-8063-b2366507a3ab.png)
新版中，播放器的参数``defaultQuality``一分为二，变为``defaultAudioQuality``和``defaultVideoQuality``，默认载入quality = 1的音频流 _(控制台输出[13])_
而旧版没有这个设定，所以先载入的quality = 0音频流 _([859])_，随后尝试载入quality = 2的音频 _([1630][3817][4503])_
这两份音频数据有部分不同，会在下面的代码中抛错，于是播放器刷新，载入flv流

### video.js：
```javascript
// 每次获得分段数据后被调用，共三次
// 1  audio(30216)
// 2  video
// ----------> 播放器尝试提高quality
// 3  audio(30232) <---与第一次数据不同
function R(l) {
    try {
        l && l.mediaType && function () {
            var e = l.mediaType,
                n = se[e], // se[e]:先前载入的分段，用于比较
                r = l.segments,
                t = l.representation && l.representation.index,
                i = !0,
                a = [],
                o = {};
            // 切换清晰度时，比较新旧数据
            n.total && (n.segments.forEach(function (e, t) {
                // e.duration !== r[t].duration && t < n.total - 1 && a.push(t)
                // 下为新版判定代码，上为旧版
                e.duration && e.duration !== r[t].duration && t < n.total - 1 && Math.ceil(1e3 * Math.abs(e.duration / e.timescale - r[t].duration / r[t].timescale)) > 100 && a.push(t)
                // 其中r[t].timescale === e.timescale === 44100
                // 少部分e.duration不等于r[t].duration
            }), a.length && (i = !1, o = {
                old: n.qualityIndex,
                new: t
            }));
            // 比较的结果会不同
            // 旧代码中： a === [0, 1, 8, 9, 11, 12, 14, 15]
            // 新代码中： a === []
// ...
            i || (u.notEqualIndexList = a, u.notEqualQualityIndex = o),
                se[l.mediaType] = u, 
                "function" == typeof ue && ue(e, u)// 有差异时触发-> onInitSegmentsLoaded(8359行)
        }
            ()
    } catch (e) {
        throw new Error("Parse segment loaded error, " + e)
    }
}
```
![{T$_@AH2`YANW9Q08_IU4WN](https://user-images.githubusercontent.com/61644753/106236586-1f016900-61f5-11eb-9ff8-adeaa0c2f2ea.png)
_(判定为不相等之后，旧播放器内部产生的错误消息)_

看起来许多duration不同的分段被新代码中``Math.ceil(1e3 * Math.abs(e.duration / e.timescale - r[t].duration / r[t].timescale)) > 100``判定为相等，只要添加进旧版就不会触发重载播放器的机制（怎么有点掩耳盗铃）

音视频流这部分我实在不熟，新版的那个判定看得云里雾里，请教一下@MotooriKashin 
，它们被判定为相等的理由是什么，这样改真的没问题么

**Comment by MotooriKashin** [comment]
播放器内部逻辑我从来没早就过……  
感觉照抄新版播放器应该不会有问题吧

**Comment by MotooriKashin** [comment]
哇，这段代码有点眼熟！  
这两天把移动端DASH流重构为网页端DASH流时我就遇到过同样位置报错，也是强行把我重构好的DASH抛弃另外请求flv。那个视频记得好像是视频48段，音频却有49段，在新版播放器右键播放信息取的也是49段。我当时没办法，只能强行丢弃有问题的音频流。新版播放器这个强行相等感觉也是个办法（既然官方采用这种办法的话）

**Comment by wly5556** [comment]
>感觉照抄新版播放器应该不会有问题吧

![](https://static.saraba1st.com/image/smiley/face2017/068.png)稍微有点担心其他什么地方给这些奇怪的分段擦了屁股，这里才能认为它们相等



> 哇，这段代码有点眼熟！ 这两天把移动端DASH流重构为网页端DASH流时我就遇到过同样位置报错，也是强行把我重构好的DASH抛弃另外请求flv。那个视频记得好像是视频48段，音频却有49段，在新版播放器右键播放信息取的也是49段。我当时没办法，只能强行丢弃有问题的音频流。新版播放器这个强行相等感觉也是个办法（既然官方采用这种办法的话）

说起来这个视频也是音频分段比视频分段多一个
——
另外刚偶然发现av75432在我这会卡在最后一帧，附控制台
![)EP`OPKEBB~AXE`4B4P%X$I](https://user-images.githubusercontent.com/61644753/106247296-3f3a2380-6207-11eb-82b2-33dafc5770bd.png)

**Comment by MotooriKashin** [comment]
我看小圆那个视频也会卡在最后一秒，旧版播放器可能使用的是向上取整

**Comment by wly5556** [comment]
> 我看小圆那个视频也会卡在最后一秒，旧版播放器可能使用的是向上取整

![](https://static.saraba1st.com/image/smiley/face2017/077.png)那可以排除网络问题了
有点好奇这1秒的差别是不是原因，我去翻翻播放器代码

**Comment by MotooriKashin** [comment]
对比了下旧版播放器下方提供的那个嵌入式旧版播放器（player.bilibili.com），那个跟新版一样不会+1s。那个调用的不是Bilibiliplayer.min.js，而是liteplayer.min.js，字面上理解大概是前者的精简版，而且版本更新是2020-04-27，大概是旧版播放器弃用后还更新过，其中或许有可以借鉴的代码。

**Comment by wly5556** [comment]
> 对比了下旧版播放器下方提供的那个嵌入式旧版播放器（player.bilibili.com），那个跟新版一样不会+1s。那个调用的不是Bilibiliplayer.min.js，而是liteplayer.min.js，字面上理解大概是前者的精简版，而且版本更新是2020-04-27，大概是旧版播放器弃用后还更新过，其中或许有可以借鉴的代码。

嵌入播放器右键显示Player Type：NativePlayer，直接载入的mp4，那个问题应该是dash player独占
dash这部分代码好复杂，一片浆糊了 ![](https://static.saraba1st.com/image/smiley/face2017/122.png)

**Comment by wly5556** [comment]
554feda863975ce3db3e5f9dbdad87b9cede7032 改动应该生效了，@WolfgangWu 现在还会出现咬不上播放器的问题吗？

**Comment by MotooriKashin** [comment]
我这边该视频按键控制正常，也没有转到flv了

**Comment by WolfgangWu** [comment]
额不行啊，最新版是4.2.3吗？4.2.3我用着还是有这个问题啊

**Comment by WolfgangWu** [comment]
你们说的控制台是开发者工具里的console吗？我的console里有很长的报错和警告信息
[www.bilibili.com-1612007122405.log](https://github.com/MotooriKashin/Bilibili-Old/files/5897872/www.bilibili.com-1612007122405.log)
![image](https://user-images.githubusercontent.com/69294448/106355629-3bf08600-6334-11eb-9faa-69d01753ce23.png)
![image](https://user-images.githubusercontent.com/69294448/106355633-490d7500-6334-11eb-98c1-fdadd44c74da.png)

**Comment by MotooriKashin** [comment]
那个错误很常见，应该不是原因。  

另外该视频右键在火狐中bilibiliplayer有报错

**Comment by wly5556** [comment]
> 我这边该视频按键控制正常，也没有转到flv了

我这里测试也是正常的

>额不行啊，最新版是4.2.3吗？4.2.3我用着还是有这个问题啊

这个小补丁是在服务器端生效的，应该跟版本号没有关系，或者你可以试试command＋shift＋r强制刷新页面（没用过mac，度娘说快捷键是这个）

>你们说的控制台是开发者工具里的console吗？我的console里有很长的报错和警告信息

看了一遍，这些错误信息都是普遍出现的，可以无视

**Comment by WolfgangWu** [comment]
哦哦太感谢了，command＋shift＋r就解决掉了

**Comment by WolfgangWu** [comment]
https://www.bilibili.com/video/av7172520 这个视频我的chrome又出现咬不上的问题了，而且视频的加载时间非常非常的长，感觉和之前这个bug情况差不多？而且视频加载出来会强制切换到720p的清晰度（清晰度上会出现一个小红点），手动切换回其他清晰度之后（又需要非常非常长的加载时间）键盘倒是回重新咬上播放器

**Comment by WolfgangWu** [comment]
播放器加载的时候也确实有[Dash] [加载失败]之类的提示

**Comment by WolfgangWu** [comment]
https://www.bilibili.com/video/av798498998 这一页的症状差不多，加载时间长，键盘咬不上，加载时有报错

**Comment by MotooriKashin** [comment]
这边测试没问题呢

**Comment by WolfgangWu** [comment]
![image](https://user-images.githubusercontent.com/69294448/106871948-c27ade00-670d-11eb-8aaa-39919563eca5.png)
![image](https://user-images.githubusercontent.com/69294448/106872002-d0c8fa00-670d-11eb-8549-8152a5c06e2e.png)

**Comment by WolfgangWu** [comment]
![image](https://user-images.githubusercontent.com/69294448/106872063-df171600-670d-11eb-9ceb-9a468531477a.png)
加载后清晰度处出现小红点

**Comment by WolfgangWu** [comment]
Chrome版本 86.0.4240.198（正式版本） (x86_64)

**Comment by WolfgangWu** [comment]
另外，在我这边，旧播放器加载完成后的清晰度是包括1080p的
![image](https://user-images.githubusercontent.com/69294448/106873139-1c2fd800-670f-11eb-9b5b-ff57fa249284.png)而新播放器加载这个视频则显示视频最高只有720p的清晰度

**Comment by WolfgangWu** [comment]
我试了试safari倒确实不能复现。但是另一个电脑上的Chrome86是有同样的这个问题的

**Comment by wly5556** [comment]
在控制台手动阻止访问upos-sz-mirrorhw.bilivideo.com之后，确实能重现这个问题了
前面说“加载时间非常非常的长”，没想到加载了超过一分钟，真挑战耐心啊
长时间访问失败之后播放器就自动切换成flv player模式，就出现了清晰度上面的小红点
>我试了试safari倒确实不能复现。但是另一个电脑上的Chrome86是有同样的这个问题的

从这个描述看又不是单纯的网络问题![](https://static.saraba1st.com/image/smiley/face2017/068.png)， @MotooriKashin 有什么想法

**Comment by WolfgangWu** [comment]
> 从这个描述看又不是单纯的网络问题
也许确实是单纯的网络问题？我chrome挂了梯子之后好像就不会稳定出现这个问题了，多次刷新会随机出现这个问题。不挂梯子这个问题就更加频繁的出现

**Comment by wly5556** [comment]
>而新播放器加载这个视频则显示视频最高只有720p的清晰度

新播放器一切正常吗？

**Comment by WolfgangWu** [comment]
> 新播放器一切正常吗？

正常，秒打开，也很流畅

**Comment by WolfgangWu** [comment]
另外我发现我调成新播放器打开一切正常，再切回旧播放器的头几分钟旧播放器也是正常的。但是过个十分钟一刻钟再打开旧播放器，又开始出现这个问题。也许是本地缓存之类的问题？

**Comment by WolfgangWu** [comment]
另外补充一下，旧播放器出现问题之后，点击切换清晰度到1080p时，会报错说无法连接到服务器，然后显示正在重新连接。重新连接之后播放的仍然是720p的视频，但是所有弹幕都变成了两份（重新加载了一套弹幕？），这时候再点击暂停视频，只有一套弹幕会随之暂停，另一套弹幕会独立于视频一直往后滚动播放

**Comment by MotooriKashin** [comment]
测试下是不是网络问题吧，先打开控制台切换到network，然后刷新页面，若出现同样问题，那看看是不是有哪个链接是不是一直卡在pending...

**Comment by WolfgangWu** [comment]
![image](https://user-images.githubusercontent.com/69294448/106918063-d5100a00-6743-11eb-950b-bb8776354f79.png)
前两个都是pending转cancelled/failed。两个的地址是一样的，都是 https://upos-sz-mirrorhw.bilivideo.com/upgcxcode/89/06/11700689/11700689_da3-1-30216.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1612460983&gen=playurl&os=hwbv&oi=2101823837&trid=3018ac5cbe0d47728f5fe8a250da9e4fu&platform=pc&upsig=bdfda3b382ca4c4da13c09f75d03d570&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=40857217&orderid=0,3&agrr=1&logo=80000000

**Comment by WolfgangWu** [comment]
failed那一行的报错是 net::ERR_NAME_NOT_RESOLVED。情况是播放器加载时会出两个上面说的地址的进程，然后一个在几秒后被calcel，另一个pending很久最后failed。刷新试了几次，有的时候会有三四组这个进程，都是一般cancel一半fail，报错都一样

**Comment by MotooriKashin** [comment]
pending很久的话应该就是网络问题？DASH流是分片请求的，最大也不过1-2MB一片，不大可能下载失败吧...  
30216是音频流，[30280,30216,30232]，中16是码率最低的那条，就算不分片也不大  
所以我觉得可能就是该条音轨有问题，而依据上面

> ![%IM9EQIXRL1D~$EIJ$HH)R9](https://user-images.githubusercontent.com/61644753/106235059-d3998b80-61f1-11eb-8063-b2366507a3ab.png)
> 新版中，播放器的参数`defaultQuality`一分为二，变为`defaultAudioQuality`和`defaultVideoQuality`，默认载入quality = 1的音频流 _(控制台输出[13])_
> 而旧版没有这个设定，所以先载入的quality = 0音频流 _([859])_，随后尝试载入quality = 2的音频 _([1630][3817][4503])_

旧版播放器先载入的就是30216，这个pending很久播放器也就卡了很久，最后failed报错开始获取flv。  
新版播放器直接获取的30280，所以没有问题。  

@wly5556 这是我的看法，要不修改一下旧版播放器的音频加载逻辑，也直接加载30280，反正音频文件也不大（相比于视频），这样至少可以与新版播放器共进退？

**Comment by MotooriKashin** [comment]
> 在控制台手动阻止访问upos-sz-mirrorhw.bilivideo.com之后，确实能重现这个问题了
> 前面说“加载时间非常非常的长”，没想到加载了超过一分钟，真挑战耐心啊
> 长时间访问失败之后播放器就自动切换成flv player模式，就出现了清晰度上面的小红点
> 
> > 我试了试safari倒确实不能复现。但是另一个电脑上的Chrome86是有同样的这个问题的
> 
> 从这个描述看又不是单纯的网络问题![](https://camo.githubusercontent.com/3778a82de96016ae8246e3efee9b6823ab9b93236bc3a3957c63f82eede23a4e/68747470733a2f2f7374617469632e7361726162613173742e636f6d2f696d6167652f736d696c65792f66616365323031372f3036382e706e67)， @MotooriKashin 有什么想法

“超过1分钟”大概是[这个反馈](https://greasyfork.org/zh-CN/scripts/394296-bilibili-%E6%97%A7%E6%92%AD%E6%94%BE%E9%A1%B5/discussions/78569#comment-191065)同样的问题：B站服务器返回的更差的两条音轨并非直链，而是一个-302重定向(不明白B站为什么要这么做)，我猜播放器获取到该重定向网页以为是网络卡顿没接受完(字节数不对)，于是一直等一直等……  
所以处理该问题的思路大概有两条：
   1.  像之前提出的想办法直接让旧版播放器载入30280而不是从最低的音质开始慢慢升高，与新版播放器同风险共进退。
   2.  看看有没有什么办法在js中判断这是-302重定向？大概不行，因为我一直想尝试判断-404错误也找不到途径。

**Comment by followmypeach** [comment]
> 长时间访问失败之后播放器就自动切换成flv player模式，就出现了清晰度上面的小红点
> 
强加载应该可以试试用这个方法（）
