### ISSUE TITLE
[Bug]: 相簿页关注按钮失效

### ISSUE THREAD

**Issue by sddddd213** [MotooriKashin/Bilibili-Old#501]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

![image](https://github.com/MotooriKashin/Bilibili-Old/assets/38841494/649d0a23-1a1c-4c77-a529-3cea149e8621)

### 参考数据

![image](https://github.com/MotooriKashin/Bilibili-Old/assets/38841494/6d4710db-fd5d-46c3-b9ac-8874c0bc4459)
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/38841494/228eb796-9b8b-4988-9c41-5fd3434a4cc3)

### 操作系统

Windows 10

### 浏览器名称及版本

Microsoft Edge 版本 116.0.1938.76 (正式版本) (64 位)

### 脚本版本

 10.6.9-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by MotooriKashin** [comment]
点击头像进入空间关注吧。

相簿基本所有api都面临404，基本无法抢救
