### ISSUE TITLE
[Bug]: 视频画面

### ISSUE THREAD

**Issue by wcz123694578** [MotooriKashin/Bilibili-Old#503]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

旧播放页某些视频会变蓝

### 参考数据

![Screenshot 2023-09-19 211458](https://github.com/MotooriKashin/Bilibili-Old/assets/83484741/614eba28-4848-4a5e-867a-d5363c853c6b)
![Screenshot 2023-09-19 211435](https://github.com/MotooriKashin/Bilibili-Old/assets/83484741/ed3d937f-67fb-451b-8a35-45324541b480)

### 操作系统

Windows 11

### 浏览器名称及版本

Edge

**Comment by MotooriKashin** [comment]
有点诡异，你关闭浏览器硬件加速试试

**Comment by wcz123694578** [comment]
> 有点诡异，你关闭浏览器硬件加速试试

试过了，没用，现在用下来基本上是网页放久了以后刷新就会变成紫色。还有就是不知道和edge自己有没有关系，视频变紫以后edge黑屏刷新的概率感觉会变大

**Comment by MotooriKashin** [comment]
视频播放肯定不会是js端负责的，原因要么在浏览器，要么在显卡。  
你可以试试将新版播放器播放策略调整为avc，看看新版播放器能不能复现类似问题。

**Comment by ExusiaK** [comment]
目前我没出现过这种问题，应该是你电脑的原因

**Comment by MotooriKashin** [comment]
可能是个人设备原因，暂且关闭
