### ISSUE TITLE
[Bug]: 首页为旧版时, 从google搜索页打开b站视频只会跳转到B站首页.

### ISSUE THREAD

**Issue by luminous030** [MotooriKashin/Bilibili-Old#508]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

似乎现在是会在新版首页内打开一个视频的小窗口, 然后要再点击视频下方的"进入详情页", 才能跳转到对应的视频. 而旧版首页没有这个视频窗口, 就只能跳转到首页不动.
举例:
google搜索页的视频链接: https://www.bilibili.com/video/BV1Qw41197kx/
点击后跳转: https://www.bilibili.com/?bvid=BV1Qw41197kx&spm_id_from=333.788.seo.out
然后跳转到: https://www.bilibili.com/?bvid=BV1Qw41197kx&aid=334336368(在这个时候, 页面是在主页的, 但是会跳出一个视频窗口)
点击进入视频后, 正常播放.

### 参考数据

![image](https://github.com/MotooriKashin/Bilibili-Old/assets/36995907/7c3dad6e-c728-43e0-8100-aed70c862b99)
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/36995907/f4dfa8a2-8808-4734-a3ac-93dcf1dbc2ca)

### 操作系统

Windows 10

### 浏览器名称及版本

Chrome 版本 116.0.5845.180（正式版本） （64 位）

### 脚本版本

10.7.2-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by MotooriKashin** [comment]
已重定向往av页
