### ISSUE TITLE
[Bug]: 在自动换p设置为自动的情况下连续播放分p视频时跳转异常

### ISSUE THREAD

**Issue by AmateurMUL** [MotooriKashin/Bilibili-Old#509]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

在勾选“自动换p”之后，连续播放带有分p的视频时，切换分p的行为会变得难以预测，例如：连续跳转2p以上、功能窗口的同时视频在后台播放、分p向后跳转等。网址里的"?p="也一直在跳动。问题发生的同时，视频加载会变慢、CPU、内存和网络占用也会出现骤增。

#### 设置界面显示异常
![设置界面显示异常](https://github.com/MotooriKashin/Bilibili-Old/assets/92992777/5e94e383-edd2-42ab-9b92-fbdc455f9f78)

### 复现步骤

1. 将“自动换p”选项设置为视频结束后立刻换p（打钩）
2. 打开有大量分p的视频，跳转到任意分p（例如[av31781480](https://www.bilibili.com/video/av31781480/)）
3. 播放或拖动到视频末尾，进行自动换p

#### 其他扩展：

- HTTPS Everywhere
- Gooreplacer
- User-Agent Switcher and Manager
- Plasma Integration
- uBlock Origin
- Privacy Badger
- LocalCDN
- Ruffle - Flash Emulator

#### 脚本管理器：
- Violentmonkey 2.15.0

#### 其他B站相关脚本：
- Bilibili Evolved (Preview Offline) 1246.26

#### 控制台输出：
[console-export-2023-10-11_1-55-37.txt](https://github.com/MotooriKashin/Bilibili-Old/files/12860380/console-export-2023-10-11_1-55-37.txt)

#### 脚本设置：
[Bilibili-Old-2023-10-11-01-41-31.json](https://github.com/MotooriKashin/Bilibili-Old/files/12860282/Bilibili-Old-2023-10-11-01-41-31.json)

### 操作系统

Linux

### 浏览器名称及版本

Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0

### 脚本版本

10.7.3-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by MotooriKashin** [comment]
虽然那个视频分P数有点夸张，但我测试了下没能复现问题。虽然展开分P列表时的确有点卡顿，但那个列表是不由播放器负责，理论上也干扰不到播放器。  
可能是我测试的平台不对。Linux + Firefox 的环境对我而言不太现实，有条件的你可以实时Windows + chrome是不是也有类似问题？

**Comment by AmateurMUL** [comment]
又新建了一个Firefox配置文件用于测试，仅安装了uBlock Origin和Violentmonkey脚本管理器，全部为出厂设置。并从greasyfork安装了本脚本。
打开[av31781480](https://www.bilibili.com/video/av31781480/)，将“自动换p”打钩，播放结束时会出现充电鸣谢界面，分p跳转正常。
在脚本设置中将充电鸣谢界面关闭，依然正常。
在原Firefox配置文件下将Bilibili Evolved禁用后，播放结束时会出现充电鸣谢界面，分p跳转正常。
在脚本设置中将充电鸣谢界面关闭，依然正常。
现在个人怀疑是脚本冲突，Bilibili Evolved在分p结束后可能尝试在播放器没被回收时构造新的播放器实例，导致问题发生。
将Bilibili Evolved重新启用后，依然没能复现。可能和网络环境有关。但注意到了拖动进度条时缓冲时间明显变长，当前分p播放结束时也会卡一秒钟左右。

顺便提一下：我的Bilibili Evolved上一次更新是在21年末左右的预览版。
