### ISSUE TITLE
嵌入播放器 肥肠抱歉

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#51]
![image](https://user-images.githubusercontent.com/77530593/106348282-1b0e3d80-6300-11eb-9948-99543a94bd9d.png)

**Comment by followmypeach** [comment]
有人吗

**Comment by MotooriKashin** [comment]
给个链接

**Comment by followmypeach** [comment]
https://www.bilibili.com/BPU2020

**Comment by followmypeach** [comment]
别说这个了，差不多其他页面的也是这样

**Comment by MotooriKashin** [comment]
所给链接我这边测试正常，控制台有没有什么报错？

**Comment by followmypeach** [comment]
啊没有，可能...啊算了

**Comment by followmypeach** [comment]
抱歉打扰了你的宝贵的时间..

**Comment by MotooriKashin** [comment]
算了？

**Comment by followmypeach** [comment]
草又要打扰你一次

**Comment by followmypeach** [comment]
![image](https://user-images.githubusercontent.com/77530593/106832726-2b8e3180-66cd-11eb-9c04-6a98d166fef8.png)

**Comment by followmypeach** [comment]
emmm

**Comment by MotooriKashin** [comment]
给个链接？

**Comment by followmypeach** [comment]
https://www.bilibili.com/festival/2021bnj?bvid=BV1jt4y1678G&=

**Comment by MotooriKashin** [comment]
这个不是嵌入式页面，也不是av页，而是单独做了个页面，我看看能不能适配吧。

**Comment by followmypeach** [comment]
到时候修改一下颜色，txk QW

**Comment by followmypeach** [comment]
在？适配完了没有

**Comment by followmypeach** [comment]
![image](https://user-images.githubusercontent.com/77530593/107839913-f0d17b00-6de9-11eb-8e81-98703ac77390.png)
。。。。。。

**Comment by followmypeach** [comment]
![image](https://user-images.githubusercontent.com/77530593/107839988-3ee67e80-6dea-11eb-81e2-d6a1ff8fb3f6.png)

**Comment by MotooriKashin** [comment]
这里的BV号去掉了开头的“BV”，已修复。

**Comment by followmypeach** [comment]
并没有，其他页面呢

**Comment by followmypeach** [comment]
![image](https://user-images.githubusercontent.com/77530593/107844256-dc52aa00-6e0c-11eb-9204-6b7e3bc7bfb2.png)

**Comment by WolfgangWu** [comment]
现在这个拜年祭的页面咋样了？前几天开拜年祭页面是自动用新版播放器，今天好像旧版可以用了，是上新功能了吗？没看明白上面具体做了哪些修改，就借这个楼报一下有关拜年祭页面的bug

现在点开今年拜年祭的单品视频会自动跳到拜年祭的特殊背景页里，然后地址大概是这样的 https://www.bilibili.com/festival/2021bnj?bvid=BV1wv411s7x7&=

但是这个状态进去，播放器会闪现一下要加载的视频的第一帧，然后迅速变成肥肠抱歉的16秒视频。但是手动去掉那个&=之后，
https://www.bilibili.com/festival/2021bnj?bvid=BV1wv411s7x7 就可以正常加载视频了，我体感觉得所有功能都是可以用的，只是不能加载弹幕出来。

但是也有的视频即使删掉后面的&=也会闪现视频的第一帧后变成肥肠抱歉，比如https://www.bilibili.com/festival/2021bnj?bvid=BV1sv4y1f7Q2 和 https://www.bilibili.com/festival/2021bnj?bvid=BV1LT4y1P7re
