### ISSUE TITLE
[Bug]: 整个网页大小自适应有问题

### ISSUE THREAD

**Issue by Yangtzi** [MotooriKashin/Bilibili-Old#510]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

整个网页的自适应有问题，大小只有平时网页的一半。包括，主页、播放页都是这样。
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/29507063/39f6c13f-8762-4200-b738-11e10ed0b1a8)
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/29507063/72b30729-f880-452f-a5ce-7d6d23219ac6)

### 参考数据

![image](https://github.com/MotooriKashin/Bilibili-Old/assets/29507063/39f6c13f-8762-4200-b738-11e10ed0b1a8)
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/29507063/72b30729-f880-452f-a5ce-7d6d23219ac6)

### 操作系统

Windows 11

### 浏览器名称及版本

Chrome 117.0.5938.152

### 脚本版本

10.7.4-1272ee50230293555dec1d2e23fc5c74215b4c8610.7.4-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by MotooriKashin** [comment]
旧版页面没适配高分屏，我页不会去擅自改动
