### ISSUE TITLE
[Bug]: 简繁转换出错

### ISSUE THREAD

**Issue by CloudyEagle** [MotooriKashin/Bilibili-Old#513]
### 问题是发生在那种形态的？

插件和脚本都有吧

### 问题详情

比如说”著“，大部分情况下是替换成“着”，但是存在”著名“这个词语，就变成”着名“。
前几次没反应过来，后来才发觉，不知道应该怎么替换。

### 复现步骤

有“著名”词的单集外挂字幕，具体忘了

### 操作系统 浏览器名称及版本

应该不涉及吧

### 脚本版本

当前的10.7.4未知，大概率有吧

**Comment by MotooriKashin** [comment]
只能说暴力替换大概就这个水平了吧，考虑到两个字的使用情况，只能忍忍了。而且还有很多字大概也是这种情况。
