### ISSUE TITLE
[Bug]: 启用翻页评论区后无法查看评论区

### ISSUE THREAD

**Issue by AndyStrom** [MotooriKashin/Bilibili-Old#514]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

启用翻页评论区后无法查看评论区

### 参考数据

![图片](https://github.com/MotooriKashin/Bilibili-Old/assets/72268762/6aa4fc48-6f4c-4a1d-ba60-3a7d402d2498)

### 操作系统

Windows 11

### 浏览器名称及版本

FireFox 118.0.2 64bit

**Comment by MotooriKashin** [comment]
这个问题最近似乎很多人有，但是我就是没碰到。可以的话请提供控制台截图帮助诊断——请在控制台开启的情况下刷新页面，不然有些数据不会记录到控制台

**Comment by AndyStrom** [comment]
[console-export-2023-10-29_4-16-11.txt](https://github.com/MotooriKashin/Bilibili-Old/files/13196643/console-export-2023-10-29_4-16-11.txt)
