### ISSUE TITLE
[Feature Requset]: 建议恢复除国创和番剧以外的旧版分区页面 

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#518]
### 存在问题

此脚本目前并不能完全恢复旧版分区页面 只恢复了国创以及番剧分区

### 目标愿景

建议恢复除国创和番剧以外的旧版分区页面  如果不能适配 则加一个分区切换栏
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/77530593/006e1cfc-91f0-438d-9e35-78f516e37881)

### 参考建议

旧版分区页面可在web,archive.org找到

**Comment by MotooriKashin** [comment]
曾经有尝试过，放弃了，主要是二级、三级分区太多了，没有上百也有几十
