### ISSUE TITLE
[Feature Requset]: 恢复16年11月19日之前的旧专题页面

### ISSUE THREAD

**Issue by AmateurMUL** [MotooriKashin/Bilibili-Old#519]
### 存在问题

B站不知道在什么时候403了16年11月19日之前的数字编号的旧专题页面，例如11月18日的[topic/1622](https://www.bilibili.com/topic/1622.html)，对我这种考古党不太友好。
16年11月19日之后的专题页面链接被改成了类似BV号的格式的blackboard页面，例如[blackboard/activity-HyXV7ea-g](https://www.bilibili.com/blackboard/activity-HyXV7ea-g.html)，可以正常访问。

### 目标愿景

恢复对旧专题页面的访问。

### 参考建议

大概可以从archive.org里获取备份。
也许这些旧专题页面有对应的的blackboard/activity-AbCDef0-g格式也说不定？
恢复之后，最好把里面的bilibili.tv链接换成bilibili.com链接。

**Comment by MotooriKashin** [comment]
专题页面没有固定框架模板，不可能把所有界面全部集成到脚本中
