### ISSUE TITLE
在bilibili游戏中心页面的播放器是未登录状态

### ISSUE THREAD

**Issue by WolfgangWu** [MotooriKashin/Bilibili-Old#52]
哈哈又是我
https://www.biligame.com/detail/?id=106588 在这个界面，虽然页面本身是已登陆状态，但播放器是未登陆状态，需要手动输入账号密码后才能播放1080p以上清晰度的视频

**Comment by MotooriKashin** [comment]
暂时先关闭“嵌入式播放器”试试

**Comment by MotooriKashin** [comment]
经测试嵌入第三方网页的播放器就算是新版播放器也是未登录的，这大概受限于安全机制，无法解决。
