### ISSUE TITLE
[Bug]: BV转AV号逻辑失效

### ISSUE THREAD

**Issue by Levin-7** [MotooriKashin/Bilibili-Old#525]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

无法打开视频
已确定至少于1月29日22点14分之后的视频BV号逻辑被修改，采用现有AV转换逻辑会变乱码
早于此时间的不会访问失效
视频例子：https://www.bilibili.com/video/BV12U421o7x5

### 参考数据

原网页：https://www.bilibili.com/video/BV12U421o7x5
转换结果：https://www.bilibili.com/video/av-647469841（这个AV号无法访问，哪怕是删了横杠）

### 操作系统

Windows 10

### 浏览器名称及版本

 Google Chrome: 120.0.6099.227

### 脚本版本

10.7.9

**Comment by AmateurMUL** [comment]
经个人研究，发现将转换之后错误的av号转换成无符号整数之后，再以0x7fffffff相或即可得到正确的av号。
例如：BV12U421o7x5 -> av-647469841 -> 0xd96864ef -> 0x596864ef -> [av1500013807](https://www.bilibili.com/video/av1500013807/)

**Comment by MotooriKashin** [comment]
已重写BV/av互转算法，该BV号测试已没问题
