### ISSUE TITLE
[Bug]: 部分视频跳转异常,疑似bv号解析错误

### ISSUE THREAD

**Issue by leifeng-su** [MotooriKashin/Bilibili-Old#527]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

在动态页部分视频点击后跳转最后出现404错误.
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/42539886/5d9c3a5e-bed4-439e-9e06-374a889f6825)

### 参考数据

![image](https://github.com/MotooriKashin/Bilibili-Old/assets/42539886/87fb8cca-f61b-4cf8-9c0a-0b36a9d4b016)
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/42539886/6f41dc62-e9a6-44a6-9fa1-711c7b1f8544)

### 操作系统

Windows 11

### 浏览器名称及版本

chrome

**Comment by MotooriKashin** [comment]
[原来"迅猛龙"也可以这么脏！](https://www.bilibili.com/video/BV14A4m1L7gq)

你可以更新脚本试试，今天上午修复了该问题。
