### ISSUE TITLE
[Bug]: 【已解决——更新版本即可】部分新视频页无法正常打开，网址解析为负的av号

### ISSUE THREAD

**Issue by forfun13799** [MotooriKashin/Bilibili-Old#528]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

部分视频页无法正常打开，会解析为负的av号，然后跳转至b站404。如BV1rt421W7oM。（怀疑是av号占满溢出，或更改了命名规则？）
即使关闭了重写中的“恢复旧版av页”，可以以b站新版界面打开视频了，此时网页地址栏仍显示为av-xxxxx（如av-347377699），无法正常复制网址分享。``

### 复现步骤

1.启用油猴中的旧播放页脚本；
2.设置中启用“重写”里的“av/BV 恢复旧版av页”
3.打开某一时间点后的视频，如www.bilibili.com/video/BV1rt421W7oM
4.404
5.设置中关闭“重写”里的“av/BV 恢复旧版av页”
6.打开某一时间点后的视频，如www.bilibili.com/video/BV1rt421W7oM
7,可以打开，但界面为新版，且网址解析为-avxxxx（xxx为数字），如www.bilibili.com/video/av-347377699

### 操作系统

Windows 10

### 浏览器名称及版本

火狐 102.0(64bit)

### 脚本版本

10.7.9-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by jeremy-lyoko** [comment]
同样情况。如果关闭bv转av，则播放页会变成新版页面。
