### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Parisyl** [MotooriKashin/Bilibili-Old#529]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

macOS 12.7.2 Safari 17.2.1 下视频播放页无法正常加载。

### 参考数据

<img width="1792" alt="image" src="https://github.com/MotooriKashin/Bilibili-Old/assets/75690764/35cc7e64-c546-419c-b103-3c79e0dba1fd">

### 操作系统

Mac (x86)

### 浏览器名称及版本

Safari 17.2.1

### 脚本版本

v10.8.1

**Comment by MotooriKashin** [comment]
抱歉，Safari本人实在无条件测试。从截图中也看不出任何有效信息

**Comment by peiong** [comment]
<img width="892" alt="image" src="https://github.com/MotooriKashin/Bilibili-Old/assets/75690764/0e87e1a2-51ca-4203-ac06-35bfdab65128">
@MotooriKashin

**Comment by MotooriKashin** [comment]
截图最好切到`console`，其他标签无用
![image](https://github.com/MotooriKashin/Bilibili-Old/assets/60416767/bdb590d9-3fae-479d-ac2e-799635784f48)

**Comment by peiong** [comment]
<img width="892" alt="image" src="https://github.com/MotooriKashin/Bilibili-Old/assets/75690764/4ea13d22-89fa-49ce-a094-dcf9c55657e8">

<img width="891" alt="image" src="https://github.com/MotooriKashin/Bilibili-Old/assets/75690764/826e9c95-29ad-4873-8a25-15755aeb0f6f">

谢谢大大！
@MotooriKashin
