### ISSUE TITLE
[Feature Requset]: 翻页评论区可以重新恢复使用

### ISSUE THREAD

**Issue by zzzzzz9125** [MotooriKashin/Bilibili-Old#536]
### 存在问题

我使用的是单独的翻页评论区脚本，自上周以来，我这边确实发现，使用脚本后，评论区的“按时间排序”功能已经损坏，无法使用。几天前的更新，也已经将翻页评论区的功能砍掉了，不过我选择了回退到翻页评论区脚本 2.2.5 版继续使用。今天发现“按时间排序”功能已经重新恢复正常，能够正确获取评论，所以我认为可以考虑将该功能重新加上。

### 目标愿景

重新恢复“翻页评论区”功能的使用。

**Comment by MotooriKashin** [comment]
好像还真是，再观察两天吧，想用的可以先用旧版

**Comment by fredomne** [comment]
我升级到砍了翻页的新版之后几乎开任何一个视频页都会导致cpu高占用率，降级之后似乎就缓解了，不过我本来开的插件就有点多，很难说具体是跟哪个的冲突😂，还得再看看。之前就过有css乱套的毛病要强制刷新才行。
最后我觉得翻页如果还能活下来挺好的，我是可以接受页数不准的，不影响实际使用。

**Comment by sddddd213** [comment]
评论翻页脚本是单独的？还是这个的前面几期？

**Comment by xxxqq55** [comment]
为啥都说都说翻页失效了？要不是被动升级，把翻页功能砍了，都不知道。使用时我好像没发现有什么问题

**Comment by MotooriKashin** [comment]
已恢复评论翻页功能
