### ISSUE TITLE
[Bug]: 视频页加载错误

### ISSUE THREAD

**Issue by KazeShukufuku** [MotooriKashin/Bilibili-Old#539]
### 问题是发生在那种形态的？

Chrome扩展

### 问题详情

随机点进一个视频，发现页面加载错误，关闭其他b站相关油猴脚本无济于事

### 复现步骤

1. 打开视频
2. 出现错误

### 参考数据

![image](https://github.com/user-attachments/assets/cedf807e-8594-432e-a5f7-0fe9a446b2b1)

### 操作系统

Windows 10

### 浏览器名称及版本

Chrome 128.0.6613.119

### 脚本版本

10.8.3-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by MotooriKashin** [comment]
此问题跟上无法解决，只能刷新缓解

**Comment by KazeShukufuku** [comment]
可我一直刷新，就没有正常过……刷新有用也就不反馈了

**Comment by MotooriKashin** [comment]
那请提供控制台截图看看有什么报错
