### ISSUE TITLE
关于番剧界面捉几个虫

### ISSUE THREAD

**Issue by WolfgangWu** [MotooriKashin/Bilibili-Old#54]
一个是现有的脚本在番剧详情界面似乎点不开长评的链接。比如说 https://www.bilibili.com/bangumi/media/md1598/#long#long ，点开长评栏目，再点击每个长评的标题并不能跳转到长评所在的网页。而关闭脚本之后，每个长评的标题是带有超链接并可点击的

另一个是电影页面，如 https://www.bilibili.com/bangumi/play/ss28281/ ，关闭脚本之后可见这个视频是有多个分P的 
![image](https://user-images.githubusercontent.com/69294448/106776838-65d0e200-667f-11eb-9557-4bc934952739.png) ，但打开脚本之后没有切换分P的按钮

大佬们辛苦 _(:_」∠)_

**Comment by MotooriKashin** [comment]
> 现有的脚本在番剧详情界面似乎点不开长评的链接

#53 似乎已在上个 版本修复

> 有切换分P的按钮

曾经处理过，原因在这类电影有特殊背景，旧版播放器识别到会隐藏分P列表(为了沉浸式体验？)，只能去掉背景解决。

**Comment by WolfgangWu** [comment]
那设置里现在有关闭背景的选项吗

**Comment by MotooriKashin** [comment]
已直接去掉了

**Comment by WolfgangWu** [comment]
太强了，谢谢
