### ISSUE TITLE
[Bug]: 翻页评论区失效

### ISSUE THREAD

**Issue by GhostArtyom** [MotooriKashin/Bilibili-Old#540]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

Bilibili 翻页评论区失效，被退回原版的评论区了，请求修复

### 操作系统

Windows 11

### 浏览器名称及版本

Microsoft Edge 128.0.2739.67

### 脚本版本

Bilibili 翻页评论区 v2.2.7

**Comment by hexadecimal233** [comment]
评论区灰度貌似结束了，可以看看https://github.com/the1812/Bilibili-Evolved/discussions/4804

**Comment by MotooriKashin** [comment]
已修复
