### ISSUE TITLE
[Bug]: 注册日期无法显示

### ISSUE THREAD

**Issue by Octobersama** [MotooriKashin/Bilibili-Old#546]
### 问题是发生在那种形态的？

Tampermonkey脚本

### 问题详情

注册日期无法正常显示了 是和谐掉了吗 记得之前能正常显示来着

### 复现步骤

随便找个人主页打开 注册日期一般都是1970

### 参考数据

![image](https://github.com/user-attachments/assets/d9f09ad5-46c3-43c6-a125-46e659efcc8f)

### 操作系统

Windows 11

### 浏览器名称及版本

Microsoft Edge 130.0.2849.46 (正式版本) (64 位)

### 脚本版本

10.8.5-1272ee50230293555dec1d2e23fc5c74215b4c86

**Comment by MotooriKashin** [comment]
接口已失效，勿念
