### ISSUE TITLE
无法显示旧版历史页面（？）

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#55]
![image](https://user-images.githubusercontent.com/77530593/106997193-6e2f3700-67bd-11eb-8873-a8289f286050.png)

**Comment by MotooriKashin** [comment]
历史页面哪有什么旧版

**Comment by followmypeach** [comment]
（？）那个js报404

**Comment by MotooriKashin** [comment]
可能是因为顶栏没有替换成旧版所以...  
重新实现了一下替换顶栏的功能，大概可以解决这个问题，至于旧版历史记录是真没有这个实现。
