### ISSUE TITLE
提个比较魔鬼的建议哈哈哈

### ISSUE THREAD

**Issue by WolfgangWu** [MotooriKashin/Bilibili-Old#56]
能不能加个功能，把所有网页内容里所有文本格式的“拜年纪”都改成“拜年祭” 😂

**Comment by MotooriKashin** [comment]
的确有点暴力，难道要遍历整个document文档？会不会性能开销太大？

**Comment by WolfgangWu** [comment]
我的想法是对加载新script的时候遍历一遍里面的中文内容，如果有百年纪就改成拜年祭

我之前写过B站评论区的爬虫，直觉上「每当页面加载新script时对这个新script进行扫描和修改」不会很消耗性能？确实不太了解web编程，还是你们看觉得可不可行

**Comment by MotooriKashin** [comment]
额，据我所知至少在chrome上没有监听其他script运行的办法，否则这个脚本重写页面也不必暴力地使用`document.write()`方法阻断原生脚本运行并刷新整个页面。  
其次，大部分数据其实是通过Ajax在线获取的，网页文件基本只是通用网页框架。虽然本脚本也用了`XMLHttpRequest`hook，但要过滤所有Ajax的`response`也不是小的消耗，尤其是有些走的还是jQuery的`jsonp`。  
感觉不如单写一个脚本，但同时使用`Ajax hook`和`jsonp hook`来实现有点用牛刀杀鸡的感觉...

深入考虑了一下，在重写页面时`__INITIAL_STATE__`因为本来就要重构，但似乎也没什么意义，因为除了该视频本身可能会部分基于`__INITIAL_STATE__`，页面其他部分如顶栏、评论及切P后的数据刷新都走的是`Ajax`或`jsonp`，而这些才是需要过滤的大头。  

综上，抱歉，暂时不会考虑实现类似功能。

**Comment by WolfgangWu** [comment]
啊这么复杂啊，受教了

之前用过 https://github.com/Arnie97/katakana-terminator 这个脚本，感觉像是监听页面里所有文本，然后自动把舶来语识别出来并翻译成英文，你觉得他这个脚本的原理有可用性吗

![image](https://user-images.githubusercontent.com/69294448/107112537-5c1fc800-6893-11eb-8d2e-123cfca469dc.png)
![image](https://user-images.githubusercontent.com/69294448/107112566-8ec9c080-6893-11eb-8048-6ca3f47af348.png)

这个脚本的原版是故意exclude掉B站视频页的，但是似乎只是为了排版考虑？不过看起来这个技术也是有一些问题的样子…

**Comment by MotooriKashin** [comment]
看了下那个脚本的实现就是层层遍历body下的所有节点

**Comment by WolfgangWu** [comment]
好吧😢
