### ISSUE TITLE
给个建议

### ISSUE THREAD

**Issue by jeff6471** [MotooriKashin/Bilibili-Old#57]
给个建议，吧原本的1024的宽度改高点，只是原生1280吧，地下的精度条和弹幕也是有距离的，注意一下，如果有4k屏想要原生1080p的。而且能不能直接定位到视频播放器那里，不用每次在往下拉了。打扰了，谢谢了。

**Comment by jeff6471** [comment]
以前的好像是适配4:3的，现在的能不能适配一下16:9的，稍微把东西拉宽点

**Comment by MotooriKashin** [comment]
已将1080P屏幕下播放器尺寸提升为720P，4K屏下提升为1080P，切换宽屏模式即可以16：9显示。

因为硬件条件限制未能测试4K下的表现，4K下的CSS样式写的如果有问题请继续反馈

**Comment by jeff6471** [comment]
你的小播放器好像不太对劲啊，在番剧的时候好像也变成了720p了。其他的还好

**Comment by jeff6471** [comment]
能不能直接定位到视频播放器那里，不用每次在往下拉了。谢谢了

**Comment by jeff6471** [comment]
还有联合投稿也希望以后能适配，谢谢了

**Comment by MotooriKashin** [comment]
番剧，为什么番剧就不用？  

设置里那个“播放居中”是太往下了吗？

**Comment by MotooriKashin** [comment]
联合投稿功能如果指的是显示其他合作UP主信息请开启设置中的“创作团队”选项

**Comment by MotooriKashin** [comment]
改功能已放入设置中请自行按需启用

**Comment by jeff6471** [comment]
番剧的小窗口有问题，一开始太大了，再次更新后，没有画面了

**Comment by MotooriKashin** [comment]
那看来番剧播放器大小还是不能随便乱动，直接牵扯到了mini播放器

**Comment by jeff6471** [comment]
> 已将1080P屏幕下播放器尺寸提升为720P，4K屏下提升为1080P，切换宽屏模式即可以16：9显示。
> 
> 因为硬件条件限制限制测试4K下的表现，4K下的CSS样式写的如果有问题请继续反馈
> 
> 附一张1080P下的截图
> ![2021-02-06_154421](https://user-images.githubusercontent.com/60416767/107112427-8de45f00-6892-11eb-9cbc-89de493511be.png)

<img width="1920" alt="捕获" src="https://user-images.githubusercontent.com/67215390/107143406-c3d62180-692c-11eb-9fe6-972f2081651f.PNG">

**Comment by jeff6471** [comment]
现在好像防挡字幕出了问题

**Comment by MotooriKashin** [comment]
你那张图我加载了半天...所以是出了什么问题？

**Comment by jeff6471** [comment]
貌似还是太小了啊

**Comment by MotooriKashin** [comment]
1080P不够的话不如全屏，视频源也没有到4K之间的档位
