### ISSUE TITLE
proto弹幕解析出错

### ISSUE THREAD

**Issue by MotooriKashin** [MotooriKashin/Bilibili-Old#58]
虽然不知道是不是我一个人的问题  
![2021-02-06_112917](https://user-images.githubusercontent.com/60416767/107107861-c6724180-686e-11eb-9070-781158930560.png)
检查发现是从弹幕二进制数据=>json那一步出现问题，所以是不是B站修改了protobuf表？

**Comment by wly5556** [comment]
具体是哪个视频？看了一下protobuf表是没变化的

**Comment by MotooriKashin** [comment]
方才我这边打开任何视频都是这样，现在突然又好了！  
可能是虚惊一场？

**Comment by wly5556** [comment]
这也太神秘了![](https://static.saraba1st.com/image/smiley/face2017/117.png)

**Comment by wly5556** [comment]
我也碰上这个状况了

**Comment by wly5556** [comment]
一模一样的错误3+99>61，现在又正常了...

**Comment by MotooriKashin** [comment]
会不会是服务器返回的二进制文件有问题，或者直接临时被封ip了，导致获取的二进制文件有误？  
我注意到有时一个视频会请示上百个弹幕片段，显然不太科学，但没对比过新版页面会不会这样。

**Comment by wly5556** [comment]
是bug了，马上就找到了一个会请求100个片段的视频，看来发作率挺高![](https://static.saraba1st.com/image/smiley/face2017/112.png)

**Comment by wly5556** [comment]
原来是把``{"code":-412,"message":"请求被拦截","ttl":1,"data":null}``喂给解释器了，所以报错

**Comment by MotooriKashin** [comment]
果然！  
那请求100个片段是bug吗？还是说新版也那样？

**Comment by wly5556** [comment]
新版直接无视dmSeg.total，自己重新算了一个....![](https://static.saraba1st.com/image/smiley/face2017/112.png)
旧播放器的player.getDuration()获得的时长还比新版播放器的+1s，神秘啊
```javascript
let pageSize = config.dmSge.pageSize ? config.dmSge.pageSize / 1000 : 360;
let total = player.getDuration() / pageSize + 1;
```

**Comment by MotooriKashin** [comment]
又是+1，难道可以和之前的+1是同一个？

**Comment by wly5556** [comment]
应该是同一个，新版里有这样一行``r.url && r.url.duration && (r.url.duration = r.url.duration - 1)``
弄进旧版之后，依然没有解决卡在最后一秒的问题，最后不了了之
不过getDuration()确实减了一秒

**Comment by MotooriKashin** [comment]
好像不止要修改`duration`，那下面还有一行`timelength`，应该也要修改。  
另外好像av页视频可能是直接由`video.js`请求并解析而不等`bilibiliPlayer.js`，所以大概也要同步修改。

**Comment by wly5556** [comment]
![](https://static.saraba1st.com/image/smiley/face2017/145.png)果真是到处牵连啊
还好需要复制进来的代码量不大，把几个新、旧版混淆后的单字母变量名对应起来已经够折磨了
不知道”只能循环一遍“是不是跟这个问题根源相同

**Comment by MotooriKashin** [comment]
好耶！我看小圆那个视频终于不卡在最后一秒了！  
“只能循环一遍”只有等明天CDN更新了再问能稳定复现的人了，我是从来没遇到过。  
#41

**Comment by MotooriKashin** [comment]
感觉还是判断一下弹幕是不是有效二进制文件再交给proto处理，毕竟只要一个弹幕包返回出错（http状态码400+或500+）。  
因为报错时某个弹幕包返回的是报错json/html，代码中又没有容错处理，导致整个新版弹幕加载流程中断。  
或者可以考虑`try {} catch(e){}`？或略报错的弹幕包而不中止处理，把错误抛给`toast.error`

**Comment by wly5556** [comment]
想了下，验证数据合规、忽略错误分段有点不利于后续排除故障，要我选还是选catch方案，弄个toast提示用户刷新页面就可以了，网络问题、被锁ip过阵子就自动解决
而如果是数据格式改了，或者什么未知问题，直接toast错误也方便用户上来反馈，到时候再对应改代码

**Comment by wly5556** [comment]
不过我前天从老家回去之后，现在去了另一边的老家，要上电脑修改还得过一两天
