### ISSUE TITLE
部分评论消失：按下“点击查看”按钮后没有评论出现

### ISSUE THREAD

**Issue by wly5556** [MotooriKashin/Bilibili-Old#60]
![2021-02-08 22-09-06 1](https://user-images.githubusercontent.com/61644753/107231570-5bfd0500-6a18-11eb-8b0a-c5ad26d21e28.gif)
-----

检查发现评论服务器返回的回复数量为1，但本应有回复内容的replies为null：
![Z@W D4O4U(5(~98@C1$A3`5](https://user-images.githubusercontent.com/61644753/107231945-c9109a80-6a18-11eb-8537-218a5980f58f.png)
导致**新、旧版都出现**虚空回复的现象

-----
移动端仍可以看到回复的内容
![$Z529OD$(614}BAUCE%FPNH](https://user-images.githubusercontent.com/61644753/107232730-a8951000-6a19-11eb-8e00-1be3fbfe80a7.png)
照这个不负责任地猜测，后端实装了屏蔽词系统![](https://static.saraba1st.com/image/smiley/face2017/066.png)

**Comment by MotooriKashin** [comment]
有可能，网页端和安卓端请求评论走的是不同API，所以大概网页端有更严格的过滤吧。  
其实当初实现恢复楼层功能时有考虑过重定向到安卓端API，毕竟安卓端自带楼层数据。但二者间参数无法完全对应，网页端是靠页码对应评论，安卓端靠的是最后一条评论的楼层号（安卓端也没办法跳页）。而且安卓端API不响应jsonp（网页端评论至今还是jsonp也是醉了）。  
所以这个问题大概无法解决？  

顺便请教一下jsonp的hook问题，因为`$`不是是jQuery挂在window下的，脚本想要hook时机很成问题，目前是使用`setTimeout`判断`$`存在再hook，但似乎又会错过一些东西，导致一些链接hook不到。也尝试使用过`Object.defineProperties`失败，不知道有没有什么更可靠的办法。  
（相关代码在xhrhook.js最底部）

**Comment by wly5556** [comment]
不太了解，如果要保证第一时间执行hook，也许可以把钩子直接放在jq的script标签下面

**Comment by MotooriKashin** [comment]
没用的，又不是所有页面都要重写。尤其是评论可以说无处不在。

**Comment by wly5556** [comment]
受教了

**Comment by MotooriKashin** [comment]
如今新版评论照搬了移动端接口，而且仍旧是`jsonp`方式——也就是说后端给移动端接口添加了`jsonp`支持，这个问题大概有希望解决了。  
参考 https://greasyfork.org/zh-CN/scripts/403348-bilibili-%E7%BF%BB%E9%A1%B5%E8%AF%84%E8%AE%BA%E5%8C%BA/discussions/85087 也有这种只有移动端才看得到的弹幕，不过目前只发现了这个av号

**Comment by MotooriKashin** [comment]
使用移动端接口必须放弃翻页，此问题无解。
