### ISSUE TITLE
历史弹幕已升级为protobuf格式

### ISSUE THREAD

**Issue by wly5556** [MotooriKashin/Bilibili-Old#61]
![)5$S 8 9FXJH0`26O5T@@SN](https://user-images.githubusercontent.com/61644753/107489268-56223380-6b80-11eb-9036-9e7d8b2c15b4.png)

旧的历史弹幕服务器也同一时间关闭了
![{BDHAE_RAQ_2QEKV}_N@9`D](https://user-images.githubusercontent.com/61644753/107489575-b0bb8f80-6b80-11eb-857e-18713fd7e991.png)

正在给脚本做重定向

**Comment by wly5556** [comment]
5bf2eabc9f8b065745ad4f0515c8fc6b79291162 弄完了。事发突然，看biliplus那边说停止维护全弹幕下载，大概也是因为这个原因

**Comment by MotooriKashin** [comment]
哇！辛苦！

**Comment by wly5556** [comment]
这次升级把代码弹幕从历史弹幕里抹掉了，卧槽！心痛

**Comment by MotooriKashin** [comment]
proto弹幕本来就把BAS弹幕独立出来了，要不直接把BAS弹幕包临时保存下来，每次请求历史弹幕时合并到历史弹幕中？  
除非BAS弹幕包也有上限请求不全？

**Comment by wly5556** [comment]
看了其他的视频，专包里有代码弹幕，还好
就是像av2739681的代码弹幕，几个月之前就不能从实时弹幕池获取了，list.so还是代码弹幕包里都没有，只有xml格式的历史弹幕里还有保留。现在它升级换代之后也合理地消失了，还是有点可惜
