### ISSUE TITLE
拜年祭页面又来个问题

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#62]
[1613054067203.zip](https://github.com/MotooriKashin/Bilibili-Old/files/5966127/1613054067203.zip)

**Comment by followmypeach** [comment]
麻烦了大佬赶快修复了qw

**Comment by MotooriKashin** [comment]
你点名字别点图片

**Comment by followmypeach** [comment]
哦哦哦，那么新版我看看啊

**Comment by followmypeach** [comment]
新版的可以，该不是什么bug啊

**Comment by followmypeach** [comment]
还是无解

**Comment by MotooriKashin** [comment]
因为我只监听了文字，以遍识别视频信息。就是图片右边的视频标题。我这边试了完全没问题，右上角还有切P弹窗。  
拜年祭是专门做的页面，不存在所谓的旧版，我一个人也不可能短时间写一个旧版页面出来，所以是直接炸了新版播放器嵌入了个旧版播放器进去。切P由脚本负责监听标题。

**Comment by followmypeach** [comment]
哦哦哦哦哦没事了
打扰了qw

**Comment by followmypeach** [comment]
草实时弹幕好像又炸了

**Comment by followmypeach** [comment]
刚开始1280，过5分钟后还是1280，一刷新1287
