### ISSUE TITLE
播放器尺寸异常

### ISSUE THREAD

**Issue by WolfgangWu** [MotooriKashin/Bilibili-Old#63]
![image](https://user-images.githubusercontent.com/69294448/107686449-34d85900-6ce0-11eb-928d-d3d1cb8d0899.png)

播放器突然出这个问题，右边的列表有多长左边播放器底下就拉多长。另外竖版视频会自动把宽度填充成播放器宽度，然后把高度按比例拉得更长

**Comment by MotooriKashin** [comment]
这是播放器css掉了，如果刷新依然异常，请提供av号我去测试一下

**Comment by WolfgangWu** [comment]
我现在所有页面都是这个问题，清除浏览器缓存+强制刷新页面也一直这样。应该还是我本地的问题🤦‍♂️，我另一个电脑就没有这毛病

**Comment by MotooriKashin** [comment]
那卸载脚本重装试试

**Comment by WolfgangWu** [comment]
重装就解决了，谢谢哈。另外借楼问一下，我这个电脑用旧版播放器时，历史记录一直不会进行任何记录，这是bug还是feature呢

**Comment by MotooriKashin** [comment]
开启脚本设置中的“视频心跳”功能试试。  
曾有类似问题是因为被广告拦截插件误伤了视频心跳，启用该功能将启用备用心跳接口。

**Comment by WolfgangWu** [comment]
解决了，太感谢了
