### ISSUE TITLE
非大会员无法锁定默认1080p+画质

### ISSUE THREAD

**Issue by redapple0204** [MotooriKashin/Bilibili-Old#64]
RT，虽然不是大会员，然而我发现其实选中1080p+还是可以正常播放的，然而却无法一直钦点1080p+，再刷新网页之后依旧默认1080p

**Comment by MotooriKashin** [comment]
因为那是假的1080P+，播放器发现切换不到所需画质会继续播放之前的画质，但显示不会切换回1080P，这一点切换到HDR也是一样的

**Comment by redapple0204** [comment]
@MotooriKashin 明白了，感谢！
