### ISSUE TITLE
如下图，无法获取弹幕

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#65]
![image](https://user-images.githubusercontent.com/77530593/107910552-a0971c00-6f95-11eb-869e-07324e17ad60.png)
控制台报错↑
该不会只有我才有这个问题吧

**Comment by wly5556** [comment]
我这里也是一样的问题。如果是4.3.5版本，可以先回退到上个版本，还能正常使用

**Comment by followmypeach** [comment]
草

**Comment by followmypeach** [comment]
有分p的点p2再返回p1就没事了

**Comment by MotooriKashin** [comment]
我的锅...  
今天安装了个会修改window.cid的脚本，导致新版弹幕获取出错，获取到其他视频的弹幕。想着改变一下cid的监听方法……不过不知为什么我这边测试完全没问题。
