### ISSUE TITLE
设置内容名称不准确

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#66]
如题
例如p2p，如果单看可能会理解为是开启p2p功能，但查看描述是禁用该功能。

**Comment by MotooriKashin** [comment]
的确。所以你是想启用p2p咯？那个B站直播间默认开启的。

**Comment by MyBlueHorizon** [comment]
是想关闭
然后看到这个脚本设置
一般来说看到功能名后面的开关会认为选中是开启这个功能。
但是看到描述之后就疑惑打开开关是开启还是禁用了。

**Comment by MotooriKashin** [comment]
其实我写的设置名称大都意义不明，后面那些大都是禁用也都没写明。或许改考虑一下优化一下设置面板，做成其他脚本那种可以打钩，可以输入内容的弹窗。可以CSS捉急，需要找一个样本借鉴一下...
　 ﾍ^ヽ､　 /⌒､　　_,_
　 |　　￣7　 (⌒r⌒7/
　 レ　　　＼_/￣＼_｣
＿/　　　　　　　　 {
_ﾌ　●　　　　　　　ゝ
_人　　　ο　　●　 ナ
　 `ト､＿　　　　　メ
　　　 /　 ￣ ーィﾞ
　　 〈ﾟ･｡｡｡･ﾟ 　丶

**Comment by wly5556** [comment]
无聊数了一下，现在有46个开关了，或许可以顺便在UI上把它们分类...？

**Comment by MotooriKashin** [comment]
> 无聊数了一下，现在有46个开关了，或许可以顺便在UI上把它们分类...？
HTML + css方面你会不会更顺手一点（暗示.jpg），我只会抄π_π
设置相关都在`ui.js`里

**Comment by wly5556** [comment]
我的css只是初学者水平啊！![](https://static.saraba1st.com/image/smiley/face2017/105.png)
ui拿现成的去用确实舒服![](https://static.saraba1st.com/image/smiley/face2017/057.png)，话说回来我对这个控制面板的设计有点模糊的想法，待会去做个demo，顺便熟悉熟悉css
