### ISSUE TITLE
下载的新版弹幕换行符缺失以及播放器不显示弹幕（如图）

### ISSUE THREAD

**Issue by Akari-R** [MotooriKashin/Bilibili-Old#67]

**Comment by Akari-R** [comment]
下载的新版弹幕换行符缺失
![Uploading IMG_20210217_214119.jpg…]()
![Uploading IMG_20210217_214231.jpg…]()

**Comment by Akari-R** [comment]
播放器不显示弹幕
![Snipaste_2021-02-17_21-07-49](https://user-images.githubusercontent.com/75869519/108213880-72b70080-716a-11eb-8e58-928710dd948f.png)

**Comment by Akari-R** [comment]
下载的新版弹幕换行符缺失
![IMG_20210217_214231](https://user-images.githubusercontent.com/75869519/108214657-5ff0fb80-716b-11eb-935d-71992b4e815b.jpg)
![IMG_20210217_214119](https://user-images.githubusercontent.com/75869519/108214447-28824f00-716b-11eb-87cb-006075a5f8d5.jpg)

**Comment by MotooriKashin** [comment]
下载那边可能是忘了处理换行？  
播放器载入弹幕失败如果刷新无效就卸载脚本重装试试。如果仍不能解决请提供一下控制台报错截图。

**Comment by wly5556** [comment]
换行符看起来消失了，是因为脚本里前边把/n替换成了\n，后边用修改过的弹幕数据生成xml，所以与直接下载来的xml不同。这个之前没考虑到，我去把它改过来

**Comment by wly5556** [comment]
我很少用本地播放器看弹幕，不过还是很好奇有什么好用的播放器？![](https://static.saraba1st.com/image/smiley/face2017/026.png)
只用过弹弹play、acdown、bililocal

**Comment by MotooriKashin** [comment]
> 我很少用本地播放器看弹幕，不过还是很好奇有什么好用的播放器？![](https://camo.githubusercontent.com/82ea30e0731f3c2728667da003a848caf7762f747634628456512bc4cfbd4a6b/68747470733a2f2f7374617469632e7361726162613173742e636f6d2f696d6167652f736d696c65792f66616365323031372f3032362e706e67)
> 只用过弹弹play、acdown、bililocal  

我是使用旧版播放器搭配[Bilibili 修车插件](https://greasyfork.org/scripts/374449)直接载入本地弹幕，原汁原味。  
该插件也是我曾经一直坚守旧版播放器的理由之一，还能载入本地视频源配合在线弹幕观看，对于很多失效的视频，使用其他视频源配合biliplus(曾经)保存的历史弹幕也相当于还原了。

**Comment by Akari-R** [comment]
> 我很少用本地播放器看弹幕，不过还是很好奇有什么好用的播放器？ 只用过弹弹播放，acdown，bililocal![](https://camo.githubusercontent.com/82ea30e0731f3c2728667da003a848caf7762f747634628456512bc4cfbd4a6b/68747470733a2f2f7374617469632e7361726162613173742e636f6d2f696d6167652f736d696c65792f66616365323031372f3032362e706e67)
本地弹幕播放，我一般代码弹幕用acdown搭配waybackmachine找到的播放器，普权弹幕以及老的高级弹幕用mukioplayer
![Snipaste_2021-02-18_09-03-04](https://user-images.githubusercontent.com/75869519/108288788-30bca780-71c8-11eb-972f-c256eda9c8d4.png)

**Comment by wly5556** [comment]
感谢推荐！
mukioplayer用上了，不过修车插件似乎不能启动

**Comment by MotooriKashin** [comment]
虽然我也很久没用了，不过不至于吧。要不添加`run-at document-start `试试

**Comment by wly5556** [comment]
@Akari-R _“下载的新版弹幕换行符缺失”_ 在新版本(4.3.6+)里已经修复了，_“播放器不显示弹幕”_ 还是会一直出现吗？

**Comment by Akari-R** [comment]
> @ Akari-R _“下载的新版弹幕换行符缺失”_在新版本（4.3.6+）里已经修复了，_“播放器不显示弹幕”_还是会一直出现吗？

感谢修复！播放器有时候会出问题，不过出现的次数不多
![Snipaste_2021-02-18_16-31-49](https://user-images.githubusercontent.com/75869519/108327978-04744b80-7207-11eb-9c91-259e4cc56cb6.png)

**Comment by MotooriKashin** [comment]
> mukioplayer用上了，不过修车插件似乎不能启动

![2021-02-18_183016](https://user-images.githubusercontent.com/60416767/108343962-853b4380-7217-11eb-81e6-b9d9eaceb1f3.png)
似乎是我们代理并修改了原生脚本，导致修车插件hook播放器出错。在`reset.js`里注释掉替换`video.min.js`的那行就可以正常了。

**Comment by wly5556** [comment]
>播放器有时候会出问题，不过出现的次数不多

图上旧页面的框架里却出现了新播放器的各种元件，神奇的错误，实在看不出什么头绪

>似乎是我们代理并修改了原生脚本，导致修车插件hook播放器出错。在reset.js里注释掉替换video.min.js的那行就可以正常了。
可以试试看，在线播放的感觉还是很棒的。
那个插件实现方法也挺有意思，是通过hook整个播放器实例来直接替换播放器内部变量，从而达到替换弹幕的目的。话说本脚本已经代理了弹幕功能，所以若想实现个类似的载入本地弹幕的功能似乎就不必那么大费周章了。不过那个脚本另一部分播放本地视频的功能确实可以借鉴一下。

原来是这样吗![](https://static.saraba1st.com/image/smiley/face2017/108.png)
这么说来载入本地弹幕功能或许可以内置一个，这样就能用上修改过的脚本去考古

**Comment by MotooriKashin** [comment]
> > 播放器有时候会出问题，不过出现的次数不多
> 
> 图上旧页面的框架里却出现了新播放器的各种元件，神奇的错误，实在看不出什么头绪
> 

这种错误多发生在浏览器打开了太多标签页的时候。
个人怀疑是新版页面原生脚本残留的破坏，毕竟JavaScript脚本一旦进入解析就无法阻止。所以本脚本才会用`document.write`这种暴力方法直接阻止所有未解析的新版原生脚本的解析，但受限于用户脚本载入速度，就算是`run-at document-start`也有可能会慢于部分原生脚本的解析，尤其是`video.js`直接在新版页面最前面。  
以上只是个人的猜测，万幸这种情况很少出现，而且一般刷新就能解决，建议还是随时关闭一些没用的标签页。
