### ISSUE TITLE
更新之后，启用了插件但并没有作用

### ISSUE THREAD

**Issue by hzyluffy** [MotooriKashin/Bilibili-Old#68]
右下的设置无法调用，播放页也是新版，都发生在更新之后，请问这是什么造成的呢
![QQ图片20210220002816](https://user-images.githubusercontent.com/79327265/108533692-3b845300-7314-11eb-8939-560328a315f3.png)

**Comment by MotooriKashin** [comment]
抱歉，我模块哈希值填错了，请临时到greasyfork更新一下

**Comment by hzyluffy** [comment]
> 抱歉，我模块哈希值填错了，请临时到greasyfork更新一下

谢谢，已解决
