### ISSUE TITLE
无法使用新版主页

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#69]
由于某种原因，一直以来我是使用新版主页，然后其他页面用旧版。因此，我一般是关闭“主页”和“顶栏底栏”这两项就可以了。不过现在不行了，应该是某次更新引起的，但版本跨度比较大，不好定位了。

试问，目前这种情况，是我操作不当导致的，还是脚本在更新后没有考虑到我这种情况呢？

当前版本：4.4.0
浏览器：Chrome、Firefox、Microsoft Edge

**Comment by MotooriKashin** [comment]
感谢反馈！已修复。

**Comment by byyxx128** [comment]
够速度的啊！我就下了个面条hhh……真香。
亲测有效。
