### ISSUE TITLE
在动态页面的几个问题

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#7]
1.返回顶部按钮把设置遮挡。
2.动态中的视频链接为bv

**Comment by MotooriKashin** [comment]
嗯，脚本并未对动态页面作任何处理(大概)，所以在动态页面的任何设置都是无效的
因为动态页面主机"t.bilibili.com"与一般主机"www.bilibili.com"不同，设置在不同主机间不共享，所以似乎也没有在动态页面进行设置的必要

那个返回按钮的层级实在太高了，我会试着把设置页面的层级再提高一点以处理被遮挡问题

至于bv链接问题，是这样的，脚本不会直接把页面中的bv改为av，只是在跳转的bv页面后再转化为av，也就是说点进去就跳转到av页了，这一点包括收藏等页面都是一样的。而主页问什么都是av而不是bv呢，因为重写主页用的框架是bv号推出之前的版本，所以重写过的主页大部分是不显示为bv号的。

个人以为是bv的地方就让它显示为bv吧，想知道对应的av号点进去对应的页面就知道了，直接替换页面中所有bv号对性能消耗太大，目前暂时没有考虑实现将页面中所有bv直接替换为av的功能
