### ISSUE TITLE
[功能请求] 添加流量/低带宽模式

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#70]
如题。
原先的视频拦截功能在更新后消失。
另外在网络连接质量较差的环境下页面加载速度也不是很理想。
不知道能否优化在这些情境下的体验。

**Comment by MotooriKashin** [comment]
应该不是消失，而是忘了，会更新进下载菜单

**Comment by MotooriKashin** [comment]
我在考虑直接在设置界面的下载面板里直接添加个功能输入av号或者ss/ep号直接获取下载链接并呼出下载面板会不会更好，这样在任意B站页面都可以下载视频而不必进入对应页面

**Comment by MyBlueHorizon** [comment]
其实有时候会有点进页面翻翻评论或简介的情景

**Comment by MotooriKashin** [comment]
已在设置中添加回改功能并添加了自定义下载
