### ISSUE TITLE
[功能请求] 解析多个CDN的视频地址

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#71]
#49 

这个问题又出现了好几次，希望可以解析时同时解析备用地址。

**Comment by MotooriKashin** [comment]
会考虑添加个按钮以便在首选链接无效时使用备用链接

**Comment by MotooriKashin** [comment]
目前的视线是从给的三个链接中随机选取一条，因为我发现备用地址也不一定有效，所以碰到无效链接时还是使用刷新吧。或者在设置里自定义下载填入当前链接，然后回车或者”下载“，那个提交一次都会重新获取链接，等于是不刷新页面的情况下刷新了（单纯的重新请求下载链接，应该用不了多少流量）。

**Comment by MotooriKashin** [comment]
关于下载-404报错我一直以为是B站CDN抽风，但问题也太频繁了，有些视频现在我无论怎么尝试都报403错误。  
但现在我发现问题可能并不是之前的以为的那样。  
当打开脚本最近更新的“ef2辅助IDM下载”功能后，同一条-403的链接居然就可以正常下载了。所以可能右键下载与主动调用IDM之间存在某种差别吧。  
总之传统的右键下载问题可能是无法解决了，不过“ef2辅助IDM下载”倒是从来没有出过错，如果不嫌配置麻烦的话可以尝试——当然前提是使用IDM。
