### ISSUE TITLE
【严重问题】新设置页面无法正常设置

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#72]
版本：4.4.3
浏览器：全体（和浏览器无关）

最近听说更新了新设置界面。于是闲来测试一下，就发现了这个问题。这里举个例子，比如说“下载”中“其他下载”，这一项默认没有选择，如图——
![image](https://user-images.githubusercontent.com/20079289/108805287-ba121680-75da-11eb-93d8-356cf1899da4.png)
如果我点击勾选，那么右上角会是这样——
![image](https://user-images.githubusercontent.com/20079289/108805331-ce561380-75da-11eb-92be-d9cf69131210.png)
然后我再取消勾选，右上角会这样——
![image](https://user-images.githubusercontent.com/20079289/108805350-de6df300-75da-11eb-85aa-33c7e4003478.png)
如果我不停地勾选、取消，反正右上角通知就乱了……通知乱了不要紧，实测是，我的选择并没有被保存。就如同通知中的一样，选上后立即被取消了……

**受影响的不止“其他下载”这一个**，而是多个设置，所以应该不是这一个设置的逻辑出现问题了。烦劳老大排查一下什么情况。

哎对了，测试过程中发现，打开页面，首次打开设置，首次勾选或取消，这时候是对的，再次勾选或取消，通知就会这样报两次，同时设置项目也保存不上了。（我估计不是保存不上，而是某个地方出现问题，导致出现了如同“双击”的效果）

**Comment by byyxx128** [comment]
补充一下，刚刚测试了一下，把鼠标放在选项右侧没字的地方单击，可以单次开或关，但是对勾没有变化，只能在刷新网页后可以看到。可能还是这个新设置界面的问题。
![image](https://user-images.githubusercontent.com/20079289/108806385-82a46980-75dc-11eb-8f92-c14741e69b8d.png)

**Comment by MotooriKashin** [comment]
的确，犯了个很常见的错误：把<input>标签放在<label>标签监控后者，将导致点击文字时`click`事件触发两次，待我把这次更新的问题一并解决后就推送上来。

**Comment by MotooriKashin** [comment]
目前，直接点击打钩的那个框框是正常的

**Comment by MotooriKashin** [comment]
已推送修复，应该没问题了

**Comment by byyxx128** [comment]
神速！
好使！
