### ISSUE TITLE
视频播放时出现报错

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#73]
右上角弹出
播放通知 TypeError: msg[1] is undefined
的错误

**Comment by MotooriKashin** [comment]
该问题已知，将同设置问题一并修复

**Comment by MotooriKashin** [comment]
已修复

**Comment by byyxx128** [comment]
确认修复了？4.4.4 怎么还有……⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄

**Comment by MotooriKashin** [comment]
好吧，某个模块更新没有推送上去，暂时就先关闭设置>修复>填充播放器上方信息吧？  
该模块稍后推送

**Comment by byyxx128** [comment]
没事没事，不是啥大事，就顺便提一下……其实要是没这个issue，我都懒得反馈这种小毛病了。

**Comment by MotooriKashin** [comment]
这次大概是真的修复了
