### ISSUE TITLE
旧版顶栏的“退出”按钮失效

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#74]
随着时间推移，越来越多旧版上的功能失效是在所难免的，发现一个修一个呗。

目前发现的是，旧版上指向头像后弹出的一个小栏下面，点击“退出”，这个网址失效了——
![image](https://user-images.githubusercontent.com/20079289/108818225-074eb200-75f4-11eb-8387-a678efdd8a3e.png)
链接的是 [https://account.bilibili.com/login?act=exit](https://account.bilibili.com/login?act=exit)，目前看来，现在退出登录不是这样了。

嗯，还发现了一个问题，如果关闭![image](https://user-images.githubusercontent.com/20079289/108818537-7e844600-75f4-11eb-8bc0-7dcd10bb759e.png)，这会导致鼠标指向头像时候不弹出那个新版的菜单，就这个东西——
![image](https://user-images.githubusercontent.com/20079289/108818731-c5723b80-75f4-11eb-870e-536f57e0ebbf.png)
不知道这是有个开关决定的呢，还是不小心给把这个拦截了。

**Comment by MotooriKashin** [comment]
退出又失效了吗？我记得修复过一次  
头像菜单难道不会弹出旧版的吗？还是说有新版顶栏残留？

**Comment by MotooriKashin** [comment]
已通过主动post退出命令修复，虽然依旧会跳转404页面。  
部分退出按钮是由js跳转的，无法替换链接，只能由本脚本后台代为退出，成功退出将返回之前的页面

**Comment by byyxx128** [comment]
旧版的“退出”失效了，因为之前还是用[链接](https://account.bilibili.com/login?act=exit)退出，现在应该不是了。

顶栏的问题，我深度测试了下，只在 Firefox 上可以重现。具体是，在关闭替换顶栏的情况下，鼠标指向头像，不会弹出来任何内容了，类似这样——
![image](https://user-images.githubusercontent.com/20079289/108827492-a4afe300-7600-11eb-9e98-f2da046dbdf5.png)
正常应该弹出来这些东西——
![image](https://user-images.githubusercontent.com/20079289/108827447-9661c700-7600-11eb-9e76-bc9a11135423.png)

**Comment by byyxx128** [comment]
没错现在是js退出了……看看能移植不，不好弄的话先这样也行。反正我倒不用旧版顶栏……
不过那个链接就别留着了呗，不然还得跳转下404有点别扭。
https://github.com/MotooriKashin/Bilibili-Old/commit/96b79d4bc764abd4dd0a6ca83d25d34ae5fb8dfc

**Comment by MotooriKashin** [comment]
已移除跳转链接，不过那个链接只有鼠标放上去才出现，所以现在退出可能要单击两次

**Comment by byyxx128** [comment]
哈哈，先暂时这样吧，看来是不好弄。反正我也用不着……等以后再慢慢弄就行。

**Comment by byyxx128** [comment]
抛砖引玉一下吧——
https://s1.hdslb.com/bfs/seed/jinkela/header-v2/header.js

闲着没事就稍微瞅了一眼，新版顶栏是怎么退出的。
![image](https://user-images.githubusercontent.com/20079289/108863444-2ec17100-762c-11eb-8bf6-9263777166a2.png)
反正我是看不懂了……不妨先放着，慢慢研究。

**Comment by byyxx128** [comment]
不错不错，整挺好。
