### ISSUE TITLE
新版主页与 Firefox 的兼容性问题

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#76]
标题可能取得不太合适……但是这个问题因为只在 Firefox 上可以重现，就先这么起了。

版本：4.4.5
Firefox：v86

在关闭“主页”和“替换一般页面顶栏底栏”后，就可以使用新版主页和顶栏了。这是个前提。
初次进入小破站主页，目前新版主页会有个这个东西——
![image](https://user-images.githubusercontent.com/20079289/108849585-45140080-761d-11eb-8814-bbde9eeecac0.png)
初次进入，或者鼠标指上去，都应该弹出来。

在登录状态下，鼠标指向顶栏头像，也应该会弹出这么个东西——
![image](https://user-images.githubusercontent.com/20079289/108850033-d3888200-761d-11eb-8433-928394dcb6bc.png)

不过这些东西在 Firefox 下统统没有。另外，在未登录状态下刷新主页，会有个闪现——
![image](https://user-images.githubusercontent.com/20079289/108850165-ff0b6c80-761d-11eb-8ad7-267ff91211f2.png)
就看上去是加载出来了，但又给屏蔽了……但是我也想不出这是怎么屏蔽了，就来反馈了。

不是很严重的问题，有空时候看看吧。

**Comment by MotooriKashin** [comment]
应该已经修复了……大概

**Comment by byyxx128** [comment]
好使……另外，b站好像又把没登录状态的新版顶栏恢复了？邪了门了，三天两头改……
![image](https://user-images.githubusercontent.com/20079289/108945660-f8214000-7697-11eb-929e-534df8c4df84.png)
