### ISSUE TITLE
BV⇒av 功能改进探索

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#77]
这个算是个 Feature Request 了。
此前我一直用这个脚本来转换BV——
https://greasyfork.org/scripts/398535/code
因为这个脚本算比较早的（目前已知最早的吧），而且是本地转换，代码简洁，也没有误伤和漏网。

然后发现老大的这个脚本也具有 BV⇒av 的功能，而且**可以去除掉无关参数**（强迫癌的福音），这个很好。

但实测发现，可能受某些限制，[本脚本](https://github.com/MotooriKashin/Bilibili-Old)本身的 BV⇒av 暂时有一些先天不足——
1. 在很多页面，比如主页，能够肉眼看到这个转换过程，就是可以看到页面里的超链接本来都是 BV，然后过一会儿（得有个好几秒）才慢慢变成 av。
2. 新版主页整个页面没有被转换。
3. 旧版主页“推广”一行没有被转换。
4. 其他……

不知道能否改善一下。要是不好弄的话，我就继续先用着两个脚本……可以的话我就用一个了。

**Comment by MotooriKashin** [comment]
已改进对于a标签的监听，可以试试效果

**Comment by byyxx128** [comment]
应该好使……观察看看。
