### ISSUE TITLE
视频播放页面出现报错

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#78]
![图片](https://user-images.githubusercontent.com/20754543/109080110-f8bee280-773a-11eb-8589-2d28d80df65a.png)
如图

**Comment by MotooriKashin** [comment]
弹幕问题吗？看下控制台报错是不是-412或者其他HTTP码？顺便提供一下视频链接方便测试。

**Comment by MyBlueHorizon** [comment]
emm 这个问题似乎没法复现了

**Comment by MotooriKashin** [comment]
那可能就是-412临时问题，刷新即可
