### ISSUE TITLE
非大会员误更改画质为大会员画质后画质选项无法点击

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#79]
如题

**Comment by MotooriKashin** [comment]
刷新能复现吗？提供个视频我试试

**Comment by MyBlueHorizon** [comment]
emm 问题大约是因为播放器认为切换没有完成所以锁死了按钮，当播放器认为切换完成后就正常了。但是在低速网络上就表现为按钮无法点击

**Comment by MotooriKashin** [comment]
有道理

**Comment by MyBlueHorizon** [comment]
不知道这个有没有办法解决下emm

**Comment by MotooriKashin** [comment]
当时播放器左下角由弹出切换成功吗？

**Comment by MyBlueHorizon** [comment]
是的，弹出成功后按钮才恢复正常

**Comment by MotooriKashin** [comment]
按理说这个切换过程应该很快啊，尤其是切换到不支持的画质（如HDR）什么的，我这里是秒切（内容并没有实际切换过去）。  
既然是在切换过程中，脚本也没办法从外部干预。不过为什么要切换到不支持的画质去呢？这个操作应该不常见吧。  
虽然画质什么的也不一定是会员专享，av969628065 这个视频画质都可以播放，不需要会员。
