### ISSUE TITLE
为旧版播放器上方的通知区添加信息

### ISSUE THREAD

**Issue by MyBlueHorizon** [MotooriKashin/Bilibili-Old#8]
留空感觉效果不是很好，能否进行些处理

**Comment by MotooriKashin** [comment]
@MyBlueHorizon 我有点没弄明白你指的是哪一块区域，可否详细说明或者截图示意一下？
顺便问一下想要添加什么样的信息，我会试着弄一下，但可能不会默认开启，需要在设置里自己打开，毕竟使用这个脚本的人中有一些强迫症人士，不能容忍与原生旧版页面哪怕有一丁点的不同

**Comment by MyBlueHorizon** [comment]
![QQ截图20200511150742](https://user-images.githubusercontent.com/20754543/81533713-3e234680-9399-11ea-8dc6-0af7f81e0886.png)
就是这一个区域。
![QQ截图20200511150900](https://user-images.githubusercontent.com/20754543/81533781-60b55f80-9399-11ea-939b-f18b26d90228.png)
虽然开启了这些但还是空的，看起来有点...

**Comment by MotooriKashin** [comment]
那块其实就是个广告位，由于旧版播放器已经失去维护，所以后台相关的广告接口也失效了。
其实这样也挺好的，毕竟当初还是旧版播放器的时代的去处广告插件还要多些动作去除这里的广告，如今这样，你不说我还真没觉得有什么不妥。
如果要真要写些东西的话，一时还真不知道写些什么，当前视频标题？可再上方已经有标题了不免重复，或者你有什么好建议？

**Comment by MyBlueHorizon** [comment]
如果不能利用的话可不可以添加一个功能将其折叠，或者用其他的将其替代，如果可以利用的话就更好了。
个人感觉可以作为一个快捷区或者显示一些b站知名的梗或者视频的一些详细信息或者显示与这个脚本相关的内容之类的

**Comment by MotooriKashin** [comment]
尝试了好久，发现修改完还是会被播放器置空，那地方属于播放器控制区域，除非能找到旧版节点的详细结构，否则我的意思是还是最好别动，就那样维持原样挺好的。

**Comment by MyBlueHorizon** [comment]
折叠也无法实现吗

**Comment by MotooriKashin** [comment]
已在新版设置中提供隐藏选项，但个人还是不建议开启，隐藏节点会改变播放器布局，原本播放器正好贴合视频画面，隐藏后上下黑边会变宽，当然宽屏、网页全屏和全屏不受影响
