### ISSUE TITLE
非字母弹幕还有换行符问题

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#80]
![image](https://user-images.githubusercontent.com/77530593/109284613-04092f80-785b-11eb-9c38-b28d51e3725b.png)

**Comment by followmypeach** [comment]
46发错图了

**Comment by MotooriKashin** [comment]
为什么你们提问都不提供测试链接……
　　　 ＿＿＿
　　 ／　　　▲
／￣　 ヽ　■■
●　　　　　■■
ヽ＿＿＿　　■■
　　　　）＝｜
　　　／　｜｜
　∩∩＿＿とﾉ
　しし———┘

**Comment by followmypeach** [comment]
> 为什么你们提问都不提供测试链接…… 　　　 ＿＿＿ 　　 ／　　　▲ ／￣　 ヽ　■■ ●　　　　　■■ ヽ＿＿＿　　■■ 　　　　）＝｜ 　　　／　｜｜ 　∩∩＿＿とﾉ 　しし———┘

。。。。。。为什么要给测试链接。。。
通病
m7没添加字幕弹幕时就这样了

**Comment by followmypeach** [comment]
现在又有个新问题
![image](https://user-images.githubusercontent.com/77530593/109297213-9ebe3a00-786c-11eb-9f7f-60efb83d37a0.png)

**Comment by followmypeach** [comment]
不知道是否正常

**Comment by followmypeach** [comment]
![Uploading image.png…]()

**Comment by wly5556** [comment]
> 现在又有个新问题
> ![image](https://user-images.githubusercontent.com/77530593/109297213-9ebe3a00-786c-11eb-9f7f-60efb83d37a0.png)

这个bug下次更新就能修复

关于剩下的问题，即使是通病也给几个链接啊，不能要求我也同样遇到过这个通病啊![](https://static.saraba1st.com/image/smiley/face2017/145.png)
