### ISSUE TITLE
关于历史弹幕

### ISSUE THREAD

**Issue by sharenfan22** [MotooriKashin/Bilibili-Old#81]
无法查看2020年2月以前的历史弹幕
切到2020年2月这个按钮就按不动了
![屏幕截图 2021-02-26 230627](https://user-images.githubusercontent.com/53631838/109317452-b1923800-7887-11eb-989b-45ffb657b8f8.png)

**Comment by wly5556** [comment]
旧播放器限制了只能查看1年内的历史弹幕，看了一眼新版播放器没有这个限制
已经在代码里移除了限制，不过由于cdn每天才刷新一次，可能要等到明天中午才能“解锁”这个向前按钮

**Comment by MotooriKashin** [comment]
稍后再看页面历史弹幕处理的可能有点问题：
![2021-02-28_105646](https://user-images.githubusercontent.com/60416767/109406439-15b21a80-79b4-11eb-939c-c13c5122a318.png)
` __INITIAL_STATE__`的话，稍后再看页面是没有的，` videoData`貌似Bangumi页面也没有，获取视频上传日期应该有更妥善的办法，感觉播放器内部肯定有调用到这个数据，获取由脚本代为妥善地获取这个数据挂载到`BLOD`上也可以。

**Comment by wly5556** [comment]
要去找内部的变量要费力得多，还是由脚本获取吧，麻烦你了![](https://static.saraba1st.com/image/smiley/face2017/057.png)

**Comment by MotooriKashin** [comment]
尝试了下由脚本获取也费劲。。。几种播放页面几种获取办法  
尝试分析了下该数据的用处似乎是用来判断“向前”的按钮是否可以点击，对比新版播放器代码：
![2021-02-28_161729](https://user-images.githubusercontent.com/60416767/109412093-fd0c2980-79e0-11eb-8488-3b6b8694430b.png)
发现新版好像直接就不判定向前的按钮（前不封顶？）  
所以是否有不需要该数据直接像新版那样处理的办法？

**Comment by wly5556** [comment]
限制到投稿时间确实是按我自己想加上去的
之前在新版页面摆弄这个按钮的时候，不知触发了什么，日期不断往前跳，一直跳到上个世纪.....还因为查询历史弹幕的请求太多被412了一段时间，所以就想要弄成这样来着
其实我还挺惊讶新版没有任何限制，限制到投稿时间应该是符合直觉的想法

**Comment by MotooriKashin** [comment]
好久不见。关于 #84 你知道是怎么回事吗？我对比了一下好像就是历史弹幕那边复制过来的，为什么历史弹幕密度不失效而添加的本地弹幕会，我是实在不知道如何下手。

**Comment by wly5556** [comment]
卧槽，内部用的是dm.gb而不是dm.class
原生代码用web worker载入弹幕的流程里，直接把整个数组了扫一遍，去生成这个gb属性....
```javascript
for (var e = +new Date, k = [], h = void 0, q = 0, m = b.danmakuArray.length; q < m; q++) h = b.danmakuArray[q], h.gb = b.danmakuArray[q]["class"], k[k.length] = h;
```
