### ISSUE TITLE
专栏评论页面头像框存在偏移

### ISSUE THREAD

**Issue by Undefined-User** [MotooriKashin/Bilibili-Old#82]
好像没啥可描述的，100%触发，示意如下
随便找了个评论比较多的专栏 [链接](https://www.bilibili.com/read/cv9669080)
![image](https://user-images.githubusercontent.com/11058656/109376835-24d89000-7902-11eb-8393-8885b574db12.png)

**Comment by MotooriKashin** [comment]
应该又是什么CSS样式冲突了

**Comment by MotooriKashin** [comment]
已修复
