### ISSUE TITLE
[功能请求]支持上传本地弹幕以及Bilibili 修车插件导致的问题

### ISSUE THREAD

**Issue by auto-bot-ty** [MotooriKashin/Bilibili-Old#83]
按照 #67 提到的方法注释video.min.js的那行，会导致请求两次，同时播放两个视频，一个视频的声音不受控制
<img width="278" alt="2021-2-27 23-33-55" src="https://user-images.githubusercontent.com/75887908/109391930-7e69aa80-7954-11eb-930b-418318a02020.png">
[测试连接](https://www.bilibili.com/bangumi/play/ep380621)
希望能够内置上传本地弹幕的功能，进而避免出现上述问题

**Comment by MotooriKashin** [comment]
因为那个脚本要hook播放器，必须要二次初始化播放器。不过音画不同步可能只是偶发问题，或者与解除区域限制有关，毕竟我还真没在区域限制视频中使用过该脚本。  
内置一个上传弹幕的功能也是一直就有的想法，只是目前仍有个问题没解决。弹幕方面 @wly5556 可能比较熟悉：所以我想请教一下播放器有没有提供什么调用来清空当前弹幕，若是要载入本地弹幕，肯定会涉及移除播放器已获取的在线弹幕的问题。而目前脚本代理新版弹幕的办法，投喂弹幕给播放器按我的理解是以新弹幕事件传递给播放器的，这样好像无法处理播放器已载入的弹幕。当然也可以直接拦截在线弹幕，可是载入本地弹幕是一个不能未卜先知的事件，我觉得不能期望于用户之后需要载入本地弹幕而提前拦截在线弹幕，在设置里提供相关选项然后刷新页面或者播放器来在需要时拦截也太僵硬了。  
个人以为播放器在切换历史弹幕时肯定有类似调用，只不过可能没有暴露给页面上下文只是作为内部调用存在？只要这个问题解决了，相信实现类似功能也不难。

**Comment by auto-bot-ty** [comment]
> 因为那个脚本要hook播放器，必须要二次初始化播放器。不过音画不同步可能只是偶发问题，或者与解除区域限制有关，毕竟我还真没在区域限制视频中使用过该脚本。 内置一个上传弹幕的功能也是一直就有的想法，只是目前仍有个问题没解决。弹幕方面 @wly5556 可能比较熟悉：所以我想请教一下播放器有没有提供什么调用来清空当前弹幕，若是要载入本地弹幕，肯定会涉及移除播放器已获取的在线弹幕的问题。而目前脚本代理新版弹幕的办法，投喂弹幕给播放器按我的理解是以新弹幕事件传递给播放器的，这样好像无法处理播放器已载入的弹幕。当然也可以直接拦截在线弹幕，可是载入本地弹幕是一个不能未卜先知的事件，我觉得不能期望于用户之后需要载入本地弹幕而提前拦截在线弹幕，在设置里提供相关选项然后刷新页面或者播放器来在需要时拦截也太僵硬了。 个人以为播放器在切换历史弹幕时肯定有类似调用，只不过可能没有暴露给页面上下文只是作为内部调用存在？只要这个问题解决了，相信实现类似功能也不难。

我的需求是增加弹幕而不是替换弹幕，不需要清空当前弹幕
[bili_danmaku_replace](https://github.com/lyineee/bili_danmaku_replace/blob/master/script.user.jsl)
这个是用于新版的，能够增加弹幕，不过现已失效，不知道 能否借鉴

**Comment by MotooriKashin** [comment]
脚本肯定要考虑到普适需求啊，毕竟载入的弹幕如果与原弹幕有重叠的话会导致同一条弹幕显示两遍，这种情况是要避免的。  
当然合并弹幕也是个需求，这个也肯定会考虑的

**Comment by wly5556** [comment]
8c128d18cd18bfe5b4157fe0398e6062ea924e15 按照历史弹幕切换的处理过程，弄了了一个设置弹幕池的函数
应该足够直接，没有再去拦截什么的，而且能完全操纵弹幕池，可玩性挺高
载入弹幕的ui就靠 @MotooriKashin 来做了，像偏移弹幕出现时间这类的功能我再去弄弄

**Comment by MotooriKashin** [comment]
哇！好快！

**Comment by MotooriKashin** [comment]
已绘制相关UI并在设置中添加相关选项：启用本地弹幕、是否合并当前弹幕。
![2021-02-28_145417](https://user-images.githubusercontent.com/60416767/109410386-35a60600-79d5-11eb-8202-ad42366d06c0.png)  

CDN那边还未更，推送的事看来只能明天再说了。

**Comment by auto-bot-ty** [comment]
> 已绘制相关UI并在设置中添加相关选项：启用本地弹幕、是否合并当前弹幕。
> ![2021-02-28_145417](https://user-images.githubusercontent.com/60416767/109410386-35a60600-79d5-11eb-8202-ad42366d06c0.png)
> 
> CDN那边还未更，推送的事看来只能明天再说了。

按照[README](https://github.com/MotooriKashin/Bilibili-Old/blob/7be372f80bec4f9df90491cecbbe6a3d45f6c7f8/src/README.md#%E6%A8%A1%E5%9D%97%E9%97%AE%E9%A2%98)提到的方法更改了4个源，没有出现上面的ui，是哪里出了问题？
<img width="891" alt="2021-2-28 16-47-3" src="https://user-images.githubusercontent.com/75887908/109412876-7c036100-79e5-11eb-845a-4e085b1690e8.png">

**Comment by MotooriKashin** [comment]
cdn未更新要等明天，控制台应该有“本地弹幕功能载入失败”的提示。

**Comment by MotooriKashin** [comment]
我这边看CDN已经更新了，居然不用明天。  
可以测试下效果如何

**Comment by auto-bot-ty** [comment]
> 我这边看CDN已经更新了，居然不用明天。
> 可以测试下效果如何

试了一下还是没有,红色是我修改的部分,这样对吗?
<img width="883" alt="2021-2-28 21-23-14" src="https://user-images.githubusercontent.com/75887908/109420103-b122aa00-7a0b-11eb-9f16-5ecafad41d4c.png">
用的都是最新的commit

**Comment by MotooriKashin** [comment]
我刚才看这边是已经更新了，也许cdn节点不同？还是明天我再推送吧。

**Comment by auto-bot-ty** [comment]
> 我刚才看这边是已经更新了，也许cdn节点不同？还是明天我再推送吧。

今天更新后可以了,使用中发现一些小问题 ,需要切换集数或刷新一次才能出现本地弹幕UI,弹幕设置--同屏弹幕密度调了也没有生效,仍然满屏弹幕,导入本地弹幕需要关闭[pakku 哔哩哔哩弹幕过滤器](https://s.xmcp.ml/pakkujs/?src=wext_homepage)

**Comment by MotooriKashin** [comment]
1. 需要刷新才会生效这点我想问下“自动活动到播放器”这个功能是否也是这样，以及控制台有没有“无法启动本地弹幕功能”的消息。  
2. 同屏功能可能是修改原生脚本忽略了什么，留待优化。
3. paku就有点奇怪了，有没有什么报错？它连播放器内部都管？

**Comment by auto-bot-ty** [comment]
> 1. 需要刷新才会生效这点我想问下“自动活动到播放器”这个功能是否也是这样，以及控制台有没有“无法启动本地弹幕功能”的消息。 2. 同屏功能可能是修改原生脚本忽略了什么，留待优化。 3. paku就有点奇怪了，有没有什么报错？它连播放器内部都管？

1.“自动活动到播放器”这个功能正常,控制台有“无法启动本地弹幕功能”的消息
 刷新不是每次都显示,切换集数是可以稳定显示UI
2.弹幕密度的问题是否单独提个issue?
3.可能描述的不够清楚,具体是导入本地弹幕后,弹幕列表没有变化
附控制台截图
<img width="679" alt="2021-3-1 11-54-2" src="https://user-images.githubusercontent.com/75887908/109450416-cc320000-7a85-11eb-8088-9e3270c1943e.png">

<img width="684" alt="2021-3-1 11-55-42" src="https://user-images.githubusercontent.com/75887908/109450604-4498c100-7a86-11eb-838f-3bc394979112.png">

**Comment by MotooriKashin** [comment]
1. 已经有头绪了，稍后更新。2、3容我找找原因，可能需要点时间。

**Comment by MotooriKashin** [comment]
已尝试修复1和3并推送，这边测试没问题了（推送测试没加版本号，直接从greasyfork更新可能仍是旧版，可以的话直接在github下载更新）  

2检查了下原生代码似乎与播放器切换历史弹幕逻辑并没有区别，实在摸不清为什么历史弹幕不会出现相同问题，这方面可能只能拜托对弹幕方面更了解的 @wly5556 了。

**Comment by auto-bot-ty** [comment]
> 已尝试修复1和3并推送，这边测试没问题了（推送测试没加版本号，直接从greasyfork更新可能仍是旧版，可以的话直接在github下载更新）
> 
> 2检查了下原生代码似乎与播放器切换历史弹幕逻辑并没有区别，实在摸不清为什么历史弹幕不会出现相同问题，这方面可能只能拜托对弹幕方面更了解的 @wly5556 了。

更新后可以正常显示UI,也可以直接导入弹幕了,历史弹幕我这里无法点击
<img width="663" alt="2021-3-1 15-26-45" src="https://user-images.githubusercontent.com/75887908/109465277-e62e0b80-7aa2-11eb-92b2-0b8699f5c423.png">

**Comment by MotooriKashin** [comment]
你是没登录吗？

**Comment by auto-bot-ty** [comment]
> 你是没登录吗？

为了排查问题,就在新浏览器测试,忘记了登录.
登录后,点击切换月份的按钮没有反应
<img width="214" alt="2021-3-1 16-11-17" src="https://user-images.githubusercontent.com/75887908/109470152-feedef80-7aa9-11eb-8694-195ab8c30485.png">

**Comment by MotooriKashin** [comment]
我觉得目前av页是没问题的，稍后再看和Bangumi要等明天

**Comment by auto-bot-ty** [comment]
> 我觉得目前av页是没问题的，稍后再看和Bangumi要等明天

好奇的问一下,为什么原生脚本不能通过添加commit哈希值来更新,它的地址不能改变吗?

**Comment by MotooriKashin** [comment]
因为调用那个脚本的是另一个原生脚本，把哈希值直接写进原生代码里反而不方便。
