### ISSUE TITLE
同屏弹幕密度失效

### ISSUE THREAD

**Issue by auto-bot-ty** [MotooriKashin/Bilibili-Old#84]
在导入本地弹幕后,同屏弹幕密度调成5,仍然满屏弹幕

<img width="738" alt="2021-3-1 17-26-50" src="https://user-images.githubusercontent.com/75887908/109477786-68bec700-7ab3-11eb-84e9-209d3202d2fb.png">

[测试链接](https://www.bilibili.com/bangumi/play/ep380620)

[弹幕文件](https://comment.bilibili.com/299762908.xml)

**Comment by wly5556** [comment]
”同屏弹幕密度“在4.5.1版本里修好了
如果cdn更新了，本地弹幕的载入速度也会有提升，特别是对于上万条的大型弹幕文件

**Comment by auto-bot-ty** [comment]
完美,非常感谢!
