### ISSUE TITLE
主站首页直播相关功能的问题

### ISSUE THREAD

**Issue by Undefined-User** [MotooriKashin/Bilibili-Old#85]
主站首页直播分区侧栏功能（直播排行、为你推荐）的数据接口已经过期，还是2020年5月份的数据，如果没有维护打算可以考虑删除
![image](https://user-images.githubusercontent.com/11058656/109641296-83b13a00-7b8c-11eb-9009-c5dc2d83fe22.png)
![image](https://user-images.githubusercontent.com/11058656/109642003-6a5cbd80-7b8d-11eb-9e87-d66fe175e61a.png)

PS：奇怪，架梯子刷新了一下又好了，但是不架前会提示JsonParseError，我先关掉issue吧

**Comment by MotooriKashin** [comment]
这个提示偶尔在网络不好时出现，页面就会请求备用的json数据。我一直想定位这个错误，可是每当打开控制台刷新又触发不了……太难复现了！
