### ISSUE TITLE
无法播放番剧

### ISSUE THREAD

**Issue by acerlb** [MotooriKashin/Bilibili-Old#86]
我的浏览器是 Chrome 89.0.4389.72（正式版本）beta （64 位），使用旧播放页打开番剧会无法播放，关闭此脚本之后恢复正常
![_KF0@7(BN2OIB5 ZY0%9 UJ](https://user-images.githubusercontent.com/78630437/110072880-6f05b980-7db9-11eb-86d9-95a45e9f6d84.png)

**Comment by MotooriKashin** [comment]
这种情况刷新不能解决的话请f12打开控制台截图看看红色的报错。
