### ISSUE TITLE
禁用p2p上传天选会有bug

### ISSUE THREAD

**Issue by HYY-zh** [MotooriKashin/Bilibili-Old#88]
禁用了p2p上传之后天选时刻的内容会加载不出来（如果是刷新进去的话有概率会加载出来，但重新点击之后就无法加载了）
![image](https://user-images.githubusercontent.com/61227595/111025588-0a350980-8420-11eb-8a4b-353a522e1c3c.png)

**Comment by MotooriKashin** [comment]
控制台有报错吗？人在外地可能要过几天才能测试

**Comment by HYY-zh** [comment]
![image](https://user-images.githubusercontent.com/61227595/111026965-43717780-8428-11eb-978b-dc54f730fa57.png)
我刚发现还会出现一圈黑框，关闭不了天选
![image](https://user-images.githubusercontent.com/61227595/111026994-67cd5400-8428-11eb-9118-a028604e98cc.png)
只有在油猴关闭脚本运行后才才能关闭

**Comment by MotooriKashin** [comment]
经确认是前两天处理子页面跨域问题误伤了直播间子页面的跨域，现已修复。  
黑框应该是清理了有效参数导致的，更新后测试没问题

**Comment by HYY-zh** [comment]
试了一下，没问题了(°∀°)ﾉ
