### ISSUE TITLE
哈希值又出错（弹幕反查）

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#89]
![image](https://user-images.githubusercontent.com/77530593/111028249-6b64d900-8430-11eb-8479-1bb0aad924da.png)
测试视频[https://www.bilibili.com/video/av13930169](url)

**Comment by MotooriKashin** [comment]
哈希是肯定存在碰撞的，所以说仅供参考

**Comment by followmypeach** [comment]
“仅供参考”是没错

**Comment by followmypeach** [comment]
这也出错的太离谱了把

**Comment by followmypeach** [comment]
之前的版本就没（很少）有这样的现象

**Comment by wly5556** [comment]
我的锅，之前的某次改动，把弹幕又排序了一遍，现在对不上号了

**Comment by followmypeach** [comment]
https://user-images.githubusercontent.com/77530593/111028601-951eff80-8432-11eb-8ad8-71189c21b8c2.mp4

**Comment by followmypeach** [comment]
全人类感谢你（）

**Comment by followmypeach** [comment]
还有一个问题，就是旧版播放器无法实时渲染弹幕

**Comment by wly5556** [comment]
@MotooriKashin 现在托管了原生脚本，或许可以在生成节点的时候再添加一个更可靠的标记，不再使用dmmo？
@followmypeach 可以详细说说吗？

**Comment by followmypeach** [comment]
额，我在用个弹幕姬发送弹幕（高级弹幕），旧播放器能够实时接收到弹幕但是不能实时渲染。

**Comment by MotooriKashin** [comment]
我是有想过把相关功能直接写进原生脚本，这样什么可以试试查询活动弹幕，只是一直没有付诸实现。

**Comment by followmypeach** [comment]
尽  快  实  现

**Comment by wly5556** [comment]
>额，我在用个弹幕姬发送弹幕（高级弹幕），旧播放器能够实时接收到弹幕但是不能实时渲染。

如果能发一下这个工具的下载链接，让我在这边重现这个问题，或许能找到原因去修复，感谢

>我是有想过把相关功能直接写进原生脚本，这样什么可以试试查询活动弹幕，只是一直没有付诸实现。

期待，一直很想要能够在按时间排序的弹幕上面反查

**Comment by followmypeach** [comment]
> > 额，我在用个弹幕姬发送弹幕（高级弹幕），旧播放器能够实时接收到弹幕但是不能实时渲染。
> 
> 如果能发一下这个工具的下载链接，让我在这边重现这个问题，或许能找到原因去修复，感谢
> 
> > 我是有想过把相关功能直接写进原生脚本，这样什么可以试试查询活动弹幕，只是一直没有付诸实现。
> 
> 期待，一直很想要能够在按时间排序的弹幕上面反查

弹幕发射场地址：http://47.115.4.57:8060/index[弹幕发射场](url)

**Comment by followmypeach** [comment]
> > 额，我在用个弹幕姬发送弹幕（高级弹幕），旧播放器能够实时接收到弹幕但是不能实时渲染。
> 
> 如果能发一下这个工具的下载链接，让我在这边重现这个问题，或许能找到原因去修复，感谢
> 
> > 我是有想过把相关功能直接写进原生脚本，这样什么可以试试查询活动弹幕，只是一直没有付诸实现。
> 
> 期待，一直很想要能够在按时间排序的弹幕上面反查

弹幕发射场地址[http://47.115.4.57:8060/index](url)

**Comment by followmypeach** [comment]
> > 额，我在用个弹幕姬发送弹幕（高级弹幕），旧播放器能够实时接收到弹幕但是不能实时渲染。
> 
> 如果能发一下这个工具的下载链接，让我在这边重现这个问题，或许能找到原因去修复，感谢
> 
> > 我是有想过把相关功能直接写进原生脚本，这样什么可以试试查询活动弹幕，只是一直没有付诸实现。
> 
> 期待，一直很想要能够在按时间排序的弹幕上面反查

### http://47.115.4.57:8060/index

**Comment by followmypeach** [comment]
自己研究（）

**Comment by MotooriKashin** [comment]
已重构了弹幕列表那边的反查功能，不再依赖弹幕排序。  
活动弹幕那部分未能实现，因为暂时没考虑好如果同时选中多条弹幕该怎么处理。。。

ps：涉及原生脚本修改，可能要等明天CDN更新，今天直接更新脚本可能导致该功能暂时失效。

**Comment by MotooriKashin** [comment]
已支持活动弹幕，包括选中多条弹幕的情况  
![2021-03-16_123110](https://user-images.githubusercontent.com/60416767/111257416-11455d00-8656-11eb-9520-94f94ff89def.png)

**Comment by followmypeach** [comment]
？？？为什么脚本旧版404了？？？

**Comment by MotooriKashin** [comment]
> ？？？为什么脚本旧版404了？？？

什么404？greasyfork？

**Comment by followmypeach** [comment]
> > ？？？为什么脚本旧版404了？？？
> 
> 什么404？greasyfork？

没错

**Comment by MotooriKashin** [comment]
好像是greasyfork的历史版本下载出问题了，只能通过复制下面的代码粘贴进脚本了。  
选择历史版本后，下面的代码其实就是历史版本的。  
不过对于本脚本而言，降级应该没什么用，反而可能模块不匹配各种用不了。  
如果是遇到什么问题，还是提issue吧。
