### ISSUE TITLE
跟 bilibili evolved的快捷键扩展的开关弹幕功能不兼容

### ISSUE THREAD

**Issue by CCCAUCHY** [MotooriKashin/Bilibili-Old#9]
bilibili evolved的弹幕开关快捷键“d”不兼容，跟其他插件也不兼容，总之就是不能用快捷键开关弹幕

**Comment by MotooriKashin** [comment]
经测试部分其他快捷键如网页全屏(w)宽屏(t)静音(m)都没问题，所以应该不是兼容问题，而是Bilibili Evolved本身没有后者已经放弃支持旧版播放器。
本脚本只负责启用旧版网页框架，其他脚本不主动适配或已经放弃支持旧版网页的话这边也无法解决

兼容性条目其实有测试了其他一些脚本，如果原生就是支持旧版页面的脚本，兼容性上一般不会有问题
   比如[Bilibili - Whose Bullets](https://greasyfork.org/zh-CN/scripts/40341)这个脚本，失去维护多年，似乎并不支持新版页面，反而在旧版页面兼容良好

Bilibili Evolved的话我一直有在用，但作者似乎已经在一些功能上已经放弃了支持旧版，不知道去那边反馈有没有用。

总之其他快捷键没有一起失灵的话，只能是作者就没有适配旧版页面，其他插件的话应该也是同理。
