### ISSUE TITLE
关闭所有功能仅使用旧版主页功能时，Bilibili Evolved的自动展开弹幕列表功能会失效

### ISSUE THREAD

**Issue by Celles** [MotooriKashin/Bilibili-Old#90]

**Comment by MotooriKashin** [comment]
视频页面没有使用旧版的话，我想不到可能产生冲突的缘由，能不能提供控制台截图看看是否有报错？

**Comment by Celles** [comment]
![image](https://user-images.githubusercontent.com/3955937/111057581-a131ae00-8480-11eb-8bd4-f0464dec4937.png)
感觉像是这边删除了某个东西导致Bilibili Evolved失效了？这张图是关闭所有浏览器插件只保留这两个脚本的结果，如果把本脚本关闭只留Bilibili Evolved是没问题

**Comment by MotooriKashin** [comment]
哦，原来我们都使用了Object.defineProperty来捕获视频的cid，此方法应该无法使用两次，此脚本先执行导致后执行的Evolved报错，伤及了其他代码。  
aid、cid这类数据对我们脚本来说非常重要，我想想看有没有别的方法来监听这类等数据的变化，尽量规避吧。

**Comment by MotooriKashin** [comment]
已尝试处理cid监听问题，可以试试有没有恢复你说的功能

**Comment by Celles** [comment]
> 已尝试处理cid监听问题，可以试试有没有恢复你说的功能

神速，谢谢，已经解决了
