### ISSUE TITLE
没法播放firefox

### ISSUE THREAD

**Issue by Zonnne** [MotooriKashin/Bilibili-Old#91]
![图片](https://user-images.githubusercontent.com/23009013/111062768-fb188f00-84e5-11eb-8fa2-3df19e3a8ddd.png)
点不了

**Comment by Zonnne** [comment]
原来不支持ff

**Comment by followmypeach** [comment]
ff是啥

**Comment by MotooriKashin** [comment]
> ff是啥

Firefox 缩写
