### ISSUE TITLE
[Feature] 自定义载入在线弹幕

### ISSUE THREAD

**Issue by MotooriKashin** [MotooriKashin/Bilibili-Old#92]
参考[Bilibili 修车插件](https://greasyfork.org/scripts/374449)实现载入本地弹幕后，我想实现一个自定义载入在线弹幕的功能，这样比起把下载好的弹幕再以本地的方式载入会更简便一些。  
考虑的应用场景：
   - 比如某些下架的番剧如[无职转生～到了异世界就拿出真本事～](https://www.bilibili.com/bangumi/play/ss36168)，在港澳台有对应[無職轉生～到了異世界就拿出真本事～（僅限港澳台地區）](https://www.bilibili.com/bangumi/play/ss37762)。番剧下架并没有清空弹幕，正好可以填补港澳台稀薄的弹幕列表。  
   - 又比如某些上古就失效的视频如[魔法少女小圆03【新番】【治愈】](https://www.bilibili.com/video/av51568)，现在已经有了对应的[番剧页面](https://www.bilibili.com/bangumi/play/ss29076/)，可以试试载入上古弹幕体验一下当时追“新番”的感觉。
   - 又比如只是想下载某个失效视频的弹幕，由于页面已不存在，很难实现，通过biliplus的话还是用的旧版接口，有点不太理想。
   - 甚至还可以实现类似`BiliLocal`的“全弹幕装填”功能，弹幕爆炸卡得飞起，想想就(ಡωಡ)hiahiahia～  
 
我看了下`xhrhook.js`中正好有可以用来获取弹幕的`getSegDanmaku`函数，以及转化为xml弹幕的`toXml`函数。  
```
     /**
     * 请求该视频所有的分段弹幕
     * @param  {Function} onload 得到所有弹幕之后触发的回调函数
     */
    const getSegDanmaku = (onload) => {
        let request = (url) => BLOD.xhr.true(url, "arraybuffer", {}, false);
        let DmWebViewReply = "https://api.bilibili.com/x/v2/dm/web/view?type=1&oid=" + BLOD.cid + "&pid=" + BLOD.aid
        request(DmWebViewReply).then(getAllSeg).catch((e) => {
            toast.error("载入弹幕失败", "请尝试刷新页面");
            toast.error(e);
        });
        // 获得所有分段
        function getAllSeg(config) {
            config = protoView.decode(new Uint8Array(config));
            // dmSge.total代表的分片总数，有时错误地为100
            // 故需要按照 视频时长/分片时长(一般是360秒) 把分片总数计算出来
            let pageSize = config.dmSge.pageSize ? config.dmSge.pageSize / 1000 : 360;
            let total = window.player.getDuration() / pageSize + 1;
            let allrequset = [];
            let reqUrl = "https://api.bilibili.com/x/v2/dm/web/seg.so?type=1&oid=" + BLOD.cid + "&pid=" + BLOD.aid;
            for (let index = 1; index <= total; index++) {
                allrequset.push(request(reqUrl + "&segment_index=" + index));
            }
            // BAS弹幕
            if (config.specialDms.length > 0) {
                for (let index = 0; index < config.specialDms.length; index++) {
                    // 下发的是http链接，但会被chrome的安全措施拦掉，于是替换成https
                    allrequset.push(request(config.specialDms[index].replace("http", "https")));
                }
            }
            // 完成所有的网络请求大概要300ms
            return Promise.all(allrequset).then((segments) => {
                onload(segments);
            });
        }
    }
```
但有两个问题
   1.  `getSegDanmaku`使用的是挂载在`BLOD`上的`aid`和`cid`，而我需要能主动配置这两个参数来获取任意视频的弹幕。
   2.  `getSegDanmaku`用的是回调函数，说实话我不太适应那种写法。   
 
所以 @wly5556 我想修改一下`getSegDanmaku`函数：
   1.  添加两个可选参数`aid`、`cid`，不存在时再从`BLOD`上获取。
   2.  改写成`async/await`的形式。

可是`getSegDanmaku`函数在`xhrhook.js`有两次调用，其中第二次是在`async`函数中好说，第一次
```
Worker.prototype.postMessage = function (aMessage, transferList) {
    // ...
   getSegDanmaku(function (protoSegments) {/**...*/});
   // ...
}
```
`Worker.prototype.postMessage`这个复写方法感觉应该不能修改为`async`函数，那就只能`Promise.then()`？  
说实话回调函数虽然用得少，但有些系统API必须这么用也是没办法，而`Promise.then()`我是真完全没用过，就怕改错了╮（╯＿╰）╭  。  
总之我先救这样改改试试……

**Comment by MotooriKashin** [comment]
目前效果图  
![2021-03-19_163726](https://user-images.githubusercontent.com/60416767/111753413-cdf72280-88d1-11eb-8cba-a1b0068d4003.png)

**Comment by MotooriKashin** [comment]
全弹幕装填功能已上线，测试[av28448139](https://www.bilibili.com/video/av28448139)的第一 p 的确有点炸，尤其是上里大帝出场的时候。  
没敢测试弹幕池更大的视频，怕请求太频繁被封端口→_→

**Comment by MotooriKashin** [comment]
另外也许有人会需要无职转生的下架的前四集分别是av288554260、av628641980、av928803013和av416423565，使用载入在线弹幕的功能即可在港澳台区载入对应弹幕，可以勾选“以合并方式载入”。  
删剪的几秒时间对不上可以手动调整弹幕偏移，不过删减不多不是强迫症的话应该没有必要调整。  
2月7日下架之后的就没办法了→_→  
哦对了，也许有人不知道，无职的三个番剧页面分别是  
  1.  https://www.bilibili.com/bangumi/play/ss36168 (已下架的大陆版本)
  2.  https://www.bilibili.com/bangumi/play/ss37762 (港澳台版本)
  3.  https://www.bilibili.com/bangumi/play/ss36690 (泰国版本)  

想要用同样的方式就着弹幕看的话选择版本 2 就行，泰国梯子太难找而且清晰度也不高实在没必要。

**Comment by wly5556** [comment]
嘿嘿，我一直不熟悉async await，所以都是按回调格式来写的...辛苦你去重构了

**Comment by wly5556** [comment]
手滑close issue了

**Comment by MotooriKashin** [comment]
async await用起来还是很舒服的，就跟写同步函数一样，就是调用时容易漏写`await`导致返回值是`undefined`。熟悉了以后感觉阅读起来舒爽极了，不像回调函数嵌套多了太难理清“传参”是什么，因为回调函数本身就是传递过去的参数。


话说[读取本地弹幕超过17000+时读取不完全](https://github.com/MotooriKashin/Bilibili-Old/commit/abe270bed419dbd02bce0cf8b9b79869e1504837)那个你有什么头绪吗？会不会是`DOMParser`有大小限制？

**Comment by wly5556** [comment]
学习了( ﾟ∀ﾟ)
载入的问题我没什么想法，回想起之前一直用2020拜年祭做测试视频，干掉worker之后原生代码里记得是通过主线程里的dom parser载入弹幕，也能完整获取到20000条弹幕
后来测试载入本地弹幕的时候，多次载入了同一个40000条弹幕的文件，记得弹幕数量也是正常增加的
不过有可能是xml文件有点小问题，像那次没有转义特殊符号，就只能获取到部分弹幕

**Comment by MotooriKashin** [comment]
那可能真是转义符号的问题

**Comment by wly5556** [comment]
欸 是toxml那里又忘了转义哪个符号吗
