### ISSUE TITLE
【Issue Report】禁止挂机检测弹出了不该出现的东西

### ISSUE THREAD

**Issue by byyxx128** [MotooriKashin/Bilibili-Old#93]
## 看图——
![image](https://user-images.githubusercontent.com/20079289/111856152-cda76780-8963-11eb-8459-bd3e8fabeebe.png)
## 看了下，估计和这里有关系——
https://github.com/MotooriKashin/Bilibili-Old/blob/a2ee4e1a3f9dcec4793ddeab6fe5f34dc26c8b72/src/reset.js#L953-L957

**Comment by MotooriKashin** [comment]
那个就是被拦截的挂机检测调用，看到它才能安心真的拦截成功了。后面的300000表示原本挂机5分钟就会触发。  
如果觉得影响美观我可以去掉转而打印到控制台。

**Comment by byyxx128** [comment]
哈哈不是美观不美观，我以为那个300000是不小心显示出来的……😂
没事解释清楚就行了。其实留着挺好看的。这个提示还是要要的，不能全去掉。只不过后面冒出来代码下午一跳😂

**Comment by byyxx128** [comment]
## 哈哈不是美观不美观，我以为那个300000是不小心显示出来的……😂
## 没事解释清楚就行了。其实留着挺好看的。这个提示肯定还是要的，不能全去掉。只不过后面冒出来代码吓我一跳😂
## 另外强迫癌晚期发现个小问题，就你上面的commit
![image](https://user-images.githubusercontent.com/20079289/111858513-a9a05200-8974-11eb-8bf7-f3c25fd45fa6.png)
## 框中文字是不是写错了？是不是想说“正在尝试……”？“正常尝试”什么鬼……😂

**Comment by MotooriKashin** [comment]
错别字哈，感谢指正  
　　　 ＿＿＿
　　 ／　　　▲
／￣　 ヽ　■■
●　　　　　■■
ヽ＿＿＿　　■■
　　　　）＝｜
　　　／　｜｜
　∩∩＿＿とﾉ
　しし———┘

**Comment by byyxx128** [comment]
# 作者也太可爱了……不会是个妹子吧？🤔😏
