### ISSUE TITLE
使用此脚本加载视频时偶尔会不显示视频（）

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#94]
这种情况硬刷新也解决不了
控制台没报错

**Comment by followmypeach** [comment]
https://user-images.githubusercontent.com/77530593/111892612-f862f000-8a37-11eb-9a76-6b5b1e8550e0.mp4

**Comment by MotooriKashin** [comment]
第一次见。。。暂时不知道问题在哪。

**Comment by followmypeach** [comment]
可能是某个覆盖层问题？

**Comment by MotooriKashin** [comment]
我试了打开该av号没法重现

**Comment by followmypeach** [comment]
我这有（偶尔性）.png

**Comment by followmypeach** [comment]
差不多是看所有视频都有这个问题

**Comment by duoduoffff** [comment]
同样问题， macOS Safari，版本 14.0.3 (15610.4.3.1.7, 15610)，Catalina，几乎每次都复现这问题。我还有一个火狐，88.0b2 (64 位) aurora，上面装的脚本管理器也是 Tampermonkey，就没有这问题。

**Comment by followmypeach** [comment]
> 同样问题， macOS Safari，版本 14.0.3 (15610.4.3.1.7, 15610)，Catalina，几乎每次都复现这问题。我还有一个火狐，88.0b2 (64 位) aurora，上面装的脚本管理器也是 Tampermonkey，就没有这问题。

也是查不出原因吗？

**Comment by MotooriKashin** [comment]
Safari 的话，难道是hevc的原因，可以右键查看“播放信息”看看，可以的话保存一份播放器日志也好。  
不过Safari真的没条件测试，只能猜想了。

**Comment by followmypeach** [comment]
> Safari 的话，难道是hevc的原因，可以右键查看“播放信息”看看，可以的话保存一份播放器日志也好。 不过Safari真的没条件测试，只能猜想了。

找到原因了 和CC字幕助手冲突

**Comment by followmypeach** [comment]
关掉了就没事

**Comment by followmypeach** [comment]
控制台的报错我真的是分辨不出来就没截图

**Comment by followmypeach** [comment]
![image](https://user-images.githubusercontent.com/77530593/112715083-4a64b380-8f19-11eb-9634-1ca1158202ae.png)
不知道这个报错有没有联系

**Comment by followmypeach** [comment]
![image](https://user-images.githubusercontent.com/77530593/112715100-6c5e3600-8f19-11eb-96da-9d0d2dafa69c.png)
能载入视频时

**Comment by MotooriKashin** [comment]
竟是CC字幕工具的原因吗？说起来那个插件好像经常能伪装成原生脚本报错不知道是怎么办到的，我也不知道如何区分。

**Comment by followmypeach** [comment]
我关了那个插件，黑屏几率少多了（但还是有25%的几率）

**Comment by followmypeach** [comment]
对了，我在那个状态下看了那个统计信息
![image](https://user-images.githubusercontent.com/77530593/113477041-ec544500-94b1-11eb-9d51-034025df3ca9.png)

**Comment by followmypeach** [comment]
你可以改改代码直接获取带音频的视频吗（）

**Comment by MotooriKashin** [comment]
所以这真的是h.265的问题吗？无法解码所以视频轨是`undefined`。  
可以考虑设计一个强制使用flv的选项，flv的话音视频是在一起的，而且只有h.264编码，提供给出现类似问题时临时开启吧。  
flv相比dash有一下不同望周知：flv载入稍慢，且不支持HDR分辨率。  
至于修改代码处理...由于没有调试的条件，实在难以修改。

**Comment by followmypeach** [comment]
![image](https://user-images.githubusercontent.com/77530593/117085803-5ac04780-ad7d-11eb-993a-05a6f32b4738.png)
视频确实能载入，但是部分按钮不能点击
