### ISSUE TITLE
双版头

### ISSUE THREAD

**Issue by Sun0613** [MotooriKashin/Bilibili-Old#95]
<img width="1270" alt="屏幕快照 2021-03-21 下午4 59 50" src="https://user-images.githubusercontent.com/46019412/111899341-04b27180-8a67-11eb-8096-4e05cf194053.png">

仅在av页出现

**Comment by MotooriKashin** [comment]
脚本是最新版吗？还是控制台有报错？

**Comment by Sun0613** [comment]
<img width="1272" alt="屏幕快照 2021-03-21 下午9 33 59" src="https://user-images.githubusercontent.com/46019412/111906801-6554a500-8a8d-11eb-8237-f32d0cce195c.png">

最新的4.5.9

**Comment by MotooriKashin** [comment]
又是bigint问题吗？等我明天做下兼容处理。  
另外这个界面感觉不像chrome系浏览器。

**Comment by MotooriKashin** [comment]
已对新添加的代码做了BigInt兼容处理，不知道能否解决问题

**Comment by Sun0613** [comment]
我的是Safari 11.1.2 （好老的了）

**Comment by MotooriKashin** [comment]
我再想想办法，因为B站弹幕编号已经超过了正常JS数字所能精确表达的范围，不得已引入了新特性BigInt型数据来处理，旧版浏览器应该不兼容。我再想想办法吧。

**Comment by MotooriKashin** [comment]
已彻底弃用BigInt，自己重写了个大整数比较算法。  
再看看好了没有吧，兼容问题实现不好处理，也麻烦你反复测试了。

**Comment by Sun0613** [comment]
大部分功能已经恢复，不过在bangumi页面下打开设置界面没有前面的勾。其他页面打开设置正常

<img width="516" alt="屏幕快照 2021-03-23 下午3 25 30" src="https://user-images.githubusercontent.com/46019412/112110656-2157c200-8bab-11eb-823e-53d4e29c6c62.png">

**Comment by MotooriKashin** [comment]
难道是模块未更新？你可以试试点击编辑脚本-外部，把所有的外部资源删除一次看看，如图

**Comment by Sun0613** [comment]
试了，仍然没有前面的勾

**Comment by MotooriKashin** [comment]
这是什么疑难杂症？设置界面理论上来说应该是对所有页面通用的……

**Comment by MotooriKashin** [comment]
如果可以的话，可以试试如下操作（虽然不知道Safari是不是类似）：
  1. 右键“检查”任意一个菜单比如图中的av/BV
  2. 展开"label"选中“input”，也就是那个不知为何消失的那个复选框
  3. 然后截图看看有没有类似“style”的东西，我怀疑是样式被覆盖了

实在麻烦你了，附图如下  
![2021-03-23_163418](https://user-images.githubusercontent.com/60416767/112117589-78cf4f80-8bf6-11eb-90b7-9844230c6dd2.png)  
![2021-03-23_163523](https://user-images.githubusercontent.com/60416767/112117612-7e2c9a00-8bf6-11eb-9b1f-a3c90e77fe52.png)

**Comment by Sun0613** [comment]
<img width="1269" alt="屏幕快照 2021-03-23 下午4 52 58" src="https://user-images.githubusercontent.com/46019412/112119344-333e6280-8bb5-11eb-993f-d7675f89cc7c.png">

**Comment by MotooriKashin** [comment]
看起来是浏览器不支持那个`appearance`属性，我知道怎么办了。不过今天暂时碰不到电脑，明天解决。

**Comment by MotooriKashin** [comment]
已添加替代样式，想来应该没问题了

**Comment by Sun0613** [comment]
没有好转

<img width="303" alt="屏幕快照 2021-03-24 下午1 37 10" src="https://user-images.githubusercontent.com/46019412/112262204-2e38ec00-8c65-11eb-8c27-3ad29e4c4ab1.png">

同时，在Firefox 78.9.0 esr 等旧版本中也出现相同问题，下附截图。不过84版本正常

<img width="1276" alt="屏幕快照 2021-03-24 下午1 58 04" src="https://user-images.githubusercontent.com/46019412/112262697-f2eaed00-8c65-11eb-84b9-40e22eb4e2ef.png">

**Comment by MotooriKashin** [comment]
额，居然连auto都不识别  
　　　 ＿＿＿
　　 ／　　　▲
／￣　 ヽ　■■
●　　　　　■■
ヽ＿＿＿　　■■
　　　　）＝｜
　　　／　｜｜
　∩∩＿＿とﾉ
　しし———┘  
已改为指定checkbox，如果这样都无效，那我真不知道该怎么做。毕竟bangumi页面强制指定的none被识别了——它不会只识别这一个值吧……

**Comment by Sun0613** [comment]
这次恢复了，没问题了
