### ISSUE TITLE
.

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#96]
如果有就指下路怎么下载谢谢qw

**Comment by MotooriKashin** [comment]
在任意播放页面打开设置面板-〉弹幕，将失效视频的链接填入“载入其他视频弹幕”的输入框，点击“”载入“，获取成功的话设置界面会弹出相应提示，右键另存为即可。  
设置里启用其他下载的话也可以载入成功后打开右键呼出下载面板，此时面板上提供的弹幕下载已同步替换为所输入的失效视频的弹幕。
![2021-04-02_182221](https://user-images.githubusercontent.com/60416767/113408211-826c6a80-93e1-11eb-8420-6d6e53237fb4.png)  
~~嗯，全弹幕装填暂不支持直接保存，因为失效视频不会弹出下载面板（或许可以调整一下？），临时解决方案是载入完全弹幕后在控制台`console`中输入`BLOD.xml`，复制结果保存到一个文件中即可。~~

额，我还是调整一下下载面板设置吧，如果开启了其他下载就算失效视频也能从面板上下载其他的。

**Comment by MotooriKashin** [comment]
已提供失效视频呼出下载面板功能，可以用来下载全弹幕（设置里启用失效视频并且页面成功重写）  
![2021-04-02_191404](https://user-images.githubusercontent.com/60416767/113411485-759f4500-93e8-11eb-8c77-1bbfc8d0b4ba.png)

**Comment by followmypeach** [comment]
之后有问题我直接在这提了
