### ISSUE TITLE
站外播放器肥肠抱歉

### ISSUE THREAD

**Issue by Hibanaw** [MotooriKashin/Bilibili-Old#98]
如http://cloud.hibanaw.icu/av314.html

（话说刚发现隐藏播放量的视频外链播放不了，我们叔叔真是太厉害了
（比如av1336146 av12310533

**Comment by MotooriKashin** [comment]
那些是曾经“只有会员知道的世界”，不是站在播放不了，而是非会员（也就是游客）播放不了。

**Comment by Hibanaw** [comment]
> 那些是曾经“只有会员知道的世界”，不是站在播放不了，而是非会员（也就是游客）播放不了。

只是没想到av1336146 会在“只有会员才知道的世界”里🤔
而且这个issue重点在前半部分啊kora
所有的视频站外播放器都会肥肠抱歉

**Comment by MotooriKashin** [comment]
前半部分？好吧，我去看看

**Comment by MotooriKashin** [comment]
已修复

**Comment by Hibanaw** [comment]
感谢！
