### ISSUE TITLE
canvas弹幕渲染机制错误（字幕弹幕）

### ISSUE THREAD

**Issue by followmypeach** [MotooriKashin/Bilibili-Old#99]
https://user-images.githubusercontent.com/77530593/113502670-55929180-9560-11eb-811a-9fac680b349b.mp4

**Comment by wly5556** [comment]
其实我一直没有关注过canvas的显示效果，我去找找原因

**Comment by wly5556** [comment]
现在去看那个视频有恢复正常吗？如果没效果可能需要shift+f5强行刷新一两次
